### PR TITLE
"Set uv color" and "find UV coord on surface" nodes

### PR DESCRIPTION
**Pull request by Kosvor2**
Inspired by this: https://blender.stackexchange.com/questions/79236/access-color-of-a-point-given-the-3d-position-on-the-surface-of-a-polygon

thus works only on triangulated mesh.

uv_coords234234

### CODE REVIEW

**Comment by Durman** [comment]
Can you give an example of using? I receive error.
[untitled_2018_03_26_09_01.zip](https://github.com/nortikin/sverchok/files/1847108/untitled_2018_03_26_09_01.zip)

**Comment by Kosvor2** [comment]
I will look now

**Comment by Kosvor2** [comment]
commited fix in master: https://github.com/nortikin/sverchok/commit/430cd391dc0b5d2552cc3c1e21637238199a8bd0

You can try again.

**Comment by Kosvor2** [comment]
Use case:

find_on_uv_234324

**Comment by Kosvor2** [comment]
Turns out it can work with quads too, but only if these quads are flat, like quads of the cube object.

**Comment by Durman** [comment]
Interesting )
[project point from UV to object_2018_03_26_10_56.zip](https://github.com/nortikin/sverchok/files/1847507/project.point.from.UV.to.object_2018_03_26_10_56.zip)

**Comment by Kosvor2** [comment]
UVMap sockets nestiness also fixed in master.

**Comment by Kosvor2** [comment]
Also, points for colorUV node not forced to liyng exactly on surface. They will be magnetized to closest location on object by bvh.find_nearest().

**Comment by Durman** [comment]
[painting_2018_03_26_13_42.zip](https://github.com/nortikin/sverchok/files/1848031/painting_2018_03_26_13_42.zip)
painting

**Comment by nortikin** [comment]
object socket input please

**Pull request merged**
