### PR TITLE
Selection grabber lite

### PR DESCRIPTION
**Pull request by zeffii**
Lite version, why so complicated.

### CODE REVIEW

**Comment by enzyme69** [comment]
Zeffii is this how you propose to use this node? Every single time there is a masking needed?

Screen Shot 2020-04-01 at 1 19 26 pm

**Comment by Durman** [comment]
I do not see purpose of having of bool properties in current implementation.

**Comment by zeffii** [comment]
exactly right @enzyme69 . When you want to mix "purely procedural" with some elements of "manual" work, then this is a solution that works right now. 

@Durman , but then an index_to_mask node is needed... if if someone wants the indices, they can use mask_to_index..

**Comment by zeffii** [comment]
@enzyme69   but I recomment swithing the `Live` of the `BMV Alpha` node .  off.

**Comment by Durman** [comment]
I meant `include_vertex`, `include_edges`, `include_faces` properties.

**Comment by zeffii** [comment]
ok.. it could be an `enum`, and that node could have one socket output..  but how much does it really matter..

**Comment by Durman** [comment]
I think the node can be without any properties at all. Now those properties do not have any sense. The simpler UI the better.

**Comment by zeffii** [comment]
@Durman   like this?  https://github.com/nortikin/sverchok/pull/3024

**Comment by Durman** [comment]
Yes, that what I meant.

**Comment by zeffii** [comment]
i might add a button to store the current set in `self.node_dict[hash(self)] = ...`

**Comment by enzyme69** [comment]
After some exploration, @zeffii this might be quite something, because it's somewhat SEMI working with UI and normally it tooks me quite a long time to make this, but using Viewer, and baking "intermediate mesh" (with selection still on) allow me to make this

Screen Shot 2020-04-01 at 10 21 28 pm

**Comment by enzyme69** [comment]
I just realized that if I make changes to 1st selection, then 2nd, 3rd etc will change :) which means some kind of special care needed for this "dynamic masking".

**Comment by enzyme69** [comment]
Screen Shot 2020-04-01 at 11 12 47 pm

I will make video about this, it's going to be a weird one. 

The previous "intermediate mesh" that stores the masking will grow and it keeps history, however, there is no correlation between them however, so if I make changes to any selection, it will suddenly change others.

Especially obvious if I select all of those intermediate, hit Edit, and select all or deselect all ...

**Comment by zeffii** [comment]
you will always find sverchok lacking when it comes to selections based on manual interaction, bmesh face/edge index instability (as a direct result of using bmesh and bmesh.ops from Blender) plays a role in this. You might not always notice "weird indexing" but you will encounter it, and if you look at the code of the node involved you'll see it relies on bmesh for something.

**Comment by enzyme69** [comment]
@zeffii Thanks for that extra info Zeffi. I know this is probably not perfect but I think what you add here can open up ideas. It's a bit like building a giant tower using cards, I supposed. We can't go back but at least this visualize and letting user grab edit the component while figuring out where to go next :)

**Comment by zeffii** [comment]
also..   if you are just picking one index... use indexviewer and then feed it manually.
image

**Comment by Durman** [comment]
> i might add a button to store the current set in `self.node_dict[hash(self)] = ...`

Can you explain what difference will be between this node and this #2465 after that?

**Comment by Durman** [comment]
> you will always find sverchok lacking when it comes to selections based on manual interaction, bmesh face/edge index instability (as a direct result of using bmesh and bmesh.ops from Blender) plays a role in this. You might not always notice "weird indexing" but you will encounter it, and if you look at the code of the node involved you'll see it relies on bmesh for something.

There is no trouble with indexing of bmesh data there is trouble with understanding of such data structure.

**Comment by zeffii** [comment]
@Durman i haven't noticed unstable indices lately either. so maybe.   but I would not count on it..

as howardt put it here:  https://devtalk.blender.org/t/bmesh-adding-new-verts/11108/3

>  I don’t regard this as a bug since there was never any guarantee about what happens to vertex indices as you do operations. 

for us, unfortunately as scripters, stability is super important..

**Comment by enzyme69** [comment]
I wonder how "Sorcar" addon does it... It might be more like Macro of procedures within a Loop.

Let say we start with a grid of 3x3 polygon face.

We select a center face to start with. Extruding it and make a tree somewhat.

Then I suddenly want to have 2 or 3 more face selected from the original 3x3 grid. But the tree does not automatically traverse through for reason that the node dependant on the index.

**Comment by enzyme69** [comment]
Maybe "propagate" is something that I was looking for. So selection can be propagated based on topology... 
https://docs.blender.org/manual/uk/dev/modeling/meshes/editing/vertex/propagate_shapes.html

**Comment by Durman** [comment]
@zeffii Vertices, edges and faces can keep custom attributes. It is possible to create such attribute for indexes and when work with bmesh is finish to rebuild list of indexes of elements. This is the way how `mesh filter` node work for example.

**Comment by zeffii** [comment]
> Can you explain what difference will be between this node and this #2465 after that?

yeah, the Lite version is coded to be as simple as possible.

**Pull request merged**
