### PR TITLE
points inside solid

### PR DESCRIPTION
**Pull request by vicdoval**
Points inside solid node
Also solid viewer accepts alpha values :D 
points_inside_solid_blender_sverchok_example

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by zeffii** [comment]
slightly offtopic, but maybe it's time to do a not-so-realtime renderer, with beauty-passes for AA with oversampling and render to disk.

**Comment by vicdoval** [comment]
@zeffii i could be cool, but I'm not sure it would be better than eevee 😄 other idea would be a  SVG exporter which would be awesome to generate blueprints from sverchok  (i have a couple of scripts for the SNL for that task but nothing too elaborated...)

**Comment by zeffii** [comment]
an svg viewer, totally.  i gave up https://github.com/nortikin/sverchok/issues/780

**Comment by vicdoval** [comment]
> slightly offtopic, but maybe it's time to do a not-so-realtime renderer, with beauty-passes for AA with oversampling and render to disk.

I was thinking about this lately... it could pretty be cool to render the viewer draw from camera view to a image file so it can be mixed with the render in the compositor to saved to file.... eevee is cool but does not render edges and also with the viewer draw another kind of effects could be achieved... did you ever try something like that @zeffii ?

**Pull request merged**
