### PR TITLE
Plane node MK2 

### PR DESCRIPTION
**Pull request by DolphinDream**
Revamped plane node (MK2 currently in the extended generators). 
This version includes:
- clean up code 
- sanitize inputs
- add XY/YZ/ZX orientation 
- add normalize/size options (with size syncing option)
- preserves the previous plane node vectorization (list of list vectorization works)

### CODE REVIEW

**Comment by DolphinDream** [comment]
planemk2-ui

planenodemk2-demo1

**Comment by DolphinDream** [comment]
A few notes:

- The size sync is currently implemented so that every delta in one size is added to the other size. This may or may not be the desired effect since the ratio of the sizex/sizey is not preserved. If the ratio of the sizes should be preserved when the sizes are synced, then I change the sync code to behave this way.

- The outputs of the node seems to be embedded in parentheses (this is how the original plane output is btw). I wonder if the outputs should have outer [] instead of ().  I don’t fully understand how the () ended up in the outputs during the lists constructions using zips and all. Maybe it has something to do with this list of list vectorization of this node. Anybody have an idea why?

- And talking about output formats.. what is the recommended format? 

**verts**:

- [(x,y,z)] 
- [[x,y,z]]
- ([x,y,z])
- ((x,y,z))

**edges**:

- [[i1,i2]]
- [(i1,i2)]
- ([i1,i2])
- ((i1,i2))

**polys**:

- [[i1,i2,i3,i4]]
- [(i1,i2,i3,i4)]
- ([i1,i2,i3,i4])
- ((i1,i2,i3,i4))

**Comment by portnov** [comment]
Cool.

Though usually such "lock" button means "preserve aspect ratio".

**Comment by DolphinDream** [comment]
@portnov Done :+1: Yeah, it makes sense when you play with it, it's odd not to have it resize proportionally.

**Comment by zeffii** [comment]
good work @DolphinDream

**Comment by DolphinDream** [comment]
Thanks for merging this @zeffii  .. and for the compliments :grin:

**Comment by zeffii** [comment]
it's fun to use.  so thank _you_.

on a style related note, i want to encourage you to do indentation like
```diff
-    direction = EnumProperty(name="Direction", items=directionItems,
-                             default="XY", update=updateNode)

+    direction = EnumProperty(
+        name="Direction", items=directionItems,  default="XY", update=updateNode)
```
or
```diff
+    direction = EnumProperty(
+        name="Direction", items=directionItems,  
+        default="XY", update=updateNode)
```

else all the props have such a weird indentation.

**Comment by DolphinDream** [comment]
Roger that, @zeffii . I actually prefer your second suggestion. I only tried to reduce the vertical spread based on what I was told in the past. I think the consistent prop indentation is better :) I'll update that for this node and keep that in mind moving forward.

**Comment by zeffii** [comment]
>  I only tried to reduce the vertical spread based on what I was told in the past

Then that's a miscommunication and my fault. The eye glides easier over a constant indentation, method 1 or 2. Not a serious issue and some pep8 configurations will prefer to indent the less visually pleasing way.

**Comment by DolphinDream** [comment]
Cool. Also, I have some variables I used internally (e.g. sizeRatio and synching) Do these have to be made properties? I'm not sure what's the proper way to define class variables that are not properties the user can interact with via UI. I think I originally just defined them in the class as sizeRatio =1.0 and synching = False and for some reason they did not work (the methods using them using self.sizeRatio, self.synching did not seem to update them as class variables which is why i ended up creating them as properties).

**Comment by zeffii** [comment]
- within functions you can't define new `self.foo` , (well you can.. but it won't work like it does in a regular class )
- if you want to access a variable from anywhere that `self` is available it has to be made a proper `bpy.props....Property`  in the class definition.  <-- works fine, use it.

- or use a `self.node_dict = {}` for more elaborate data types ( do a search for that in the repo for some insight )

**Comment by DolphinDream** [comment]
When the Normalized is enabled obviously the step size entered directly in the node does not affect the output. Should these inputs be grayed out like other blender UI elements. You can modify them but they don’t affect the output.

 Note: if the step size is provided as list of sizes, it will affect the distribution of the lines along x/y but not the overall size x/y of course.

**Pull request merged**
