### PR TITLE
This should fix #2467.

### LINKED ISSUE #2467: Unit tests
## Problem statement

```Python
======================================================================
FAIL: test_ngon (simple_generator_tests.NGonNodeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\╨б╨╡╤А╨╡╨│╨╣\╨п╨╜╨┤╨╡╨║╤Б╨Ф╨╕╤Б╨║\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\tests\simple_generator_tests.py", line 51, in test_ngon
    self.assert_output_data_equals("Vertices", expected_data)
  File "D:\╨б╨╡╤А╨╡╨│╨╣\╨п╨╜╨┤╨╡╨║╤Б╨Ф╨╕╤Б╨║\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\utils\testing.py", line 552, in assert_output_data_equals
    self.assertEquals(data, expected_data, message)
AssertionError: Lists differ: [[(1.[118 chars]749475, -0.587785252292473, 0), (0.30901699437[28 chars] 0)]] != [[(1.[118 chars]749476, -0.587785252292473, 0), (0.30901699437[28 chars] 0)]]

First differing element 0:
[(1.0[117 chars]749475, -0.587785252292473, 0), (0.30901699437[27 chars], 0)]
[(1.0[117 chars]749476, -0.587785252292473, 0), (0.30901699437[27 chars], 0)]

  [[(1.0, 0.0, 0),
    (0.30901699437494745, 0.9510565162951535, 0),
    (-0.8090169943749473, 0.5877852522924732, 0),
-   (-0.8090169943749475, -0.587785252292473, 0),
?                      ^

+   (-0.8090169943749476, -0.587785252292473, 0),
?                      ^

    (0.30901699437494723, -0.9510565162951536, 0)]]

======================================================================
FAIL: test_text_viewer (simple_viewer_text_tests.TextViewerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\╨б╨╡╤А╨╡╨│╨╣\╨п╨╜╨┤╨╡╨║╤Б╨Ф╨╕╤Б╨║\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\tests\simple_viewer_text_tests.py", line 29, in test_text_viewer
    self.assertEquals(text, expected_text)
AssertionError: 'node[287 chars]865476, 0.0]\n[0.5555702330196023, 0.831469612[2832 chars]    ' != 'node[287 chars]865475, 0.0]\n[0.5555702330196023, 0.831469612[2832 chars]    '
Diff is 3514 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 84 tests in 2.852s

FAILED (failures=2, skipped=2)
```

## Steps to reproduce

1. open Blender
2. switch to Sverchok
3. press Run all tests

## Expected result

I think there should not be at least failures

## Sverchok version

Last

### PR DESCRIPTION
**Pull request by portnov**
## Addressed problem description

Fix for #2467.

### CODE REVIEW

**Comment by portnov** [comment]
@Durman please check; the source problem does not reproduce neither for me nor on CI, so I'm unable to check.

**Comment by Durman** [comment]
Yes, first problem has gone, but second still remain and Blender even crashing in the end of all test as well. I don't know what cause crushing, I have done tests on another computer before.
```Python
======================================================================
FAIL: test_text_viewer (simple_viewer_text_tests.TextViewerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User\YandexDisk\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\tests\simple_viewer_text_tests.p
y", line 29, in test_text_viewer
    self.assertEquals(text, expected_text)
AssertionError: 'node[287 chars]865476, 0.0]\n[0.5555702330196023, 0.831469612[2830 chars]    ' != 'node[287 chars]86547
5, 0.0]\n[0.5555702330196023, 0.831469612[2832 chars]    '
Diff is 3704 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 87 tests in 1.675s

FAILED (failures=1, skipped=2)

Error: EXCEPTION_ACCESS_VIOLATION
```

**Comment by Durman** [comment]
I confirm that Blender is crushing on both computers.

**Comment by Durman** [comment]
I actually noticed that blender is crashing during the test anyway if current branch is not master. 
Can any confirm such behavior?

**Comment by Durman** [comment]
Looks like second error has similar problem.
I heard that float figures should not be compared.

<details> 
  <summary>test result</summary>  

```Python
Socket DATA0; type VERTICES:
  (1) object(s)
  =0=   (2)
  =0=   (32)
  [1.0, 0.0, 0.0]
  [0.9807852804032304, 0.19509032201612825, 0.0]
  [0.9238795325112867, 0.3826834323650898, 0.0]
  [0.8314696123025452, 0.5555702330196022, 0.0]
- [0.7071067811865476, 0.7071067811865476, 0.0]
?                                       ^
+ [0.7071067811865476, 0.7071067811865475, 0.0]
?                                       ^
  [0.5555702330196023, 0.8314696123025452, 0.0]
  [0.38268343236508984, 0.9238795325112867, 0.0]
  [0.19509032201612833, 0.9807852804032304, 0.0]
  [6.123233995736766e-17, 1.0, 0.0]
  [-0.1950903220161282, 0.9807852804032304, 0.0]
  [-0.3826834323650897, 0.9238795325112867, 0.0]
  [-0.5555702330196023, 0.8314696123025451, 0.0]
  [-0.7071067811865475, 0.7071067811865476, 0.0]
  [-0.8314696123025453, 0.5555702330196022, 0.0]
  [-0.9238795325112867, 0.3826834323650899, 0.0]
  [-0.9807852804032304, 0.19509032201612816, 0.0]
  [-1.0, 1.2246467991473532e-16, 0.0]
  [-0.9807852804032304, -0.19509032201612836, 0.0]
  [-0.9238795325112868, -0.38268343236508967, 0.0]
  [-0.8314696123025452, -0.5555702330196023, 0.0]
  [-0.7071067811865477, -0.7071067811865475, 0.0]
  [-0.5555702330196022, -0.8314696123025452, 0.0]
  [-0.3826834323650895, -0.9238795325112868, 0.0]
  [-0.19509032201612866, -0.9807852804032303, 0.0]
  [-1.8369701987210297e-16, -1.0, 0.0]
  [0.1950903220161283, -0.9807852804032304, 0.0]
  [0.38268343236509, -0.9238795325112866, 0.0]
  [0.5555702330196018, -0.8314696123025455, 0.0]
  [0.7071067811865474, -0.7071067811865477, 0.0]
  [0.8314696123025452, -0.5555702330196022, 0.0]
  [0.9238795325112868, -0.38268343236508956, 0.0]
  [0.9807852804032303, -0.19509032201612872, 0.0]
  =1=   (32)
  [1.0, 0.0, 2.0]
  [0.9807852804032304, 0.19509032201612825, 2.0]
  [0.9238795325112867, 0.3826834323650898, 2.0]
  [0.8314696123025452, 0.5555702330196022, 2.0]
- [0.7071067811865476, 0.7071067811865476, 2.0]
?                                       ^
+ [0.7071067811865476, 0.7071067811865475, 2.0]
?                                       ^
  [0.5555702330196023, 0.8314696123025452, 2.0]
  [0.38268343236508984, 0.9238795325112867, 2.0]
  [0.19509032201612833, 0.9807852804032304, 2.0]
  [6.123233995736766e-17, 1.0, 2.0]
  [-0.1950903220161282, 0.9807852804032304, 2.0]
  [-0.3826834323650897, 0.9238795325112867, 2.0]
  [-0.5555702330196023, 0.8314696123025451, 2.0]
  [-0.7071067811865475, 0.7071067811865476, 2.0]
  [-0.8314696123025453, 0.5555702330196022, 2.0]
  [-0.9238795325112867, 0.3826834323650899, 2.0]
  [-0.9807852804032304, 0.19509032201612816, 2.0]
  [-1.0, 1.2246467991473532e-16, 2.0]
  [-0.9807852804032304, -0.19509032201612836, 2.0]
  [-0.9238795325112868, -0.38268343236508967, 2.0]
  [-0.8314696123025452, -0.5555702330196023, 2.0]
  [-0.7071067811865477, -0.7071067811865475, 2.0]
  [-0.5555702330196022, -0.8314696123025452, 2.0]
  [-0.3826834323650895, -0.9238795325112868, 2.0]
  [-0.19509032201612866, -0.9807852804032303, 2.0]
  [-1.8369701987210297e-16, -1.0, 2.0]
  [0.1950903220161283, -0.9807852804032304, 2.0]
  [0.38268343236509, -0.9238795325112866, 2.0]
  [0.5555702330196018, -0.8314696123025455, 2.0]
  [0.7071067811865474, -0.7071067811865477, 2.0]
  [0.8314696123025452, -0.5555702330196022, 2.0]
  [0.9238795325112868, -0.38268343236508956, 2.0]
  [0.9807852804032303, -0.19509032201612872, 2.0]
```

</details>

But occasionally I catch crashing of blender after finishing `utils.testing.run_all_tests` function.

**Comment by Durman** [comment]
Looks like it is okay now without saying about crashing, with what I can do nothing.

**Pull request merged**
