### PR TITLE
add annotations and svpep

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
i think this solves some pesky problems, mentioned in the commit log

**Comment by portnov** [comment]
@zeffii do you by any chance remember: why did we decide to identify node sockets in JSON by index, not by name?

**Comment by zeffii** [comment]
yes, because names can be duplicate on a node, where index can not.

**Comment by portnov** [comment]
Ah, I see. Theoretically there is "identifier", but mostly we do not provide these identifiers for our sockets...

**Pull request merged**
