### PR TITLE
Implementation of `Mesh filter` node

### PR DESCRIPTION
**Pull request by portnov**
This node filters vertices, edges and faces by several criterias, available via bmesh api: boundary vs interior, convex vs concave.
refs portnov#21
Please review and test.

### CODE REVIEW

**Comment by portnov** [comment]
Please note that this node has intersecting functionality with bmesh_verts.py module from @Kosvor branch. So their functionality probably needs to be merged in one node, to avoid duplication.

**Comment by Kosvor** [comment]
Let them be separated. To me, they are quite different from each other. Also, because their code will be easier to maintain this way.

**Comment by zeffii** [comment]
classnames and id names may be too generic in this case, to avoid potential clashing consider adding the `sv` prefix.

**Comment by portnov** [comment]
Done.

**Comment by zeffii** [comment]
Some really nice code in this. Another clean example for newcomers to study.

**Pull request merged**
