### PR TITLE
as per ideasman convo

### PR DESCRIPTION
**Pull request by zeffii**
After a short discussion with ideasman42, he suggested a few changes. My speed test on 16k verts+face is showing 20% speed increase for this method. Please also test to confirm. will do pull request

### CODE REVIEW

**Comment by nortikin** [comment]
is it tuple-list working that kind or update mesh instead lookuptable?

**Comment by nortikin** [comment]
old
Partial update from node Random Vector in 0.1494
Partial update from node Random Vector in 0.1677
Partial update from node Random Vector in 0.1114
Partial update from node Random Vector in 0.1688

new
Partial update from node Random Vector in 0.1962
Partial update from node Random Vector in 0.1439
Partial update from node Random Vector in 0.1437
Partial update from node Random Vector in 0.2009



It is convex hull.
but it not imports bmesh file. oups

**Comment by nortikin** [comment]
new
Partial update from node Random Vector in 0.8776
Partial update from node Random Vector in 0.8493
Partial update from node Random Vector in 0.8182
Partial update from node Random Vector in 0.8752
Partial update from node Random Vector in 0.8329
Partial update from node Random Vector in 0.8686


old
Partial update from node Random Vector in 0.9166
Partial update from node Random Vector in 0.8714
Partial update from node Random Vector in 0.9162
Partial update from node Random Vector in 0.8914
Partial update from node Random Vector in 0.8166
Partial update from node Random Vector in 0.8965


join triangles

second try
old
Partial update from node Random Vector in 0.9561
Partial update from node Random Vector in 0.8986
Partial update from node Random Vector in 0.8358
Partial update from node Random Vector in 0.9347

new
Partial update from node Random Vector in 0.8897
Partial update from node Random Vector in 0.9004
Partial update from node Random Vector in 0.8568
Partial update from node Random Vector in 0.9716
Partial update from node Random Vector in 0.9246
Partial update from node Random Vector in 0.9661
Partial update from node Random Vector in 0.9515

**Comment by nortikin** [comment]
what did i did wrong?

**Comment by zeffii** [comment]
Anything that uses `bmesh_from_pydata` should be a little bit faster. If anything it is at least cleaner code. If the biggest gains or obtained from BMesh Viewer, then already that is a success.

**Comment by zeffii** [comment]
Random Vector is not a node affected by this change. Using anything that first generates a bmesh using `bmesh_from_pydata`. But also say something about what you are testing it with, like how many verts are being processed and edges / faces

**Comment by zeffii** [comment]
>  is it tuple-list working that kind or update mesh instead lookuptable?
yeah, lookup table isn't needed when we are accessing from bm_verts[] instead.

**Comment by zeffii** [comment]
For instance a reasonable test would be a 
```
Cube of 60*60*60 -> BmeshViewer
```

**Comment by zeffii** [comment]
@nortikin are you OK buddy?

**Pull request closed without merging**
