### PR TITLE
Fix stethoschope xy location of high DPI screens automatically

### PR DESCRIPTION
**Pull request by zeffii**
## Requesting users with high DPI displays to test this

I need someone with a high DPI display to test this, and if the stethoscope is not displaying close to itself then please dig into this. ( meaning, debug this..spend some time figuring out how to automate it..) @DolphinDream  perhaps you have osx 

## Addressed problem description

this attempts to resolve the issue that retina display users have with the XY location of the displayed bgl in nodeview. This does not "Solve" (or attempt to) the scale/font size of the data we print, because you might want much smaller print font size, and that's still user configurable in Sv preferences as stethoscope "Scale"

## Solution description

make the location directly linked to the settings

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [ ] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [ ] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
```
Traceback (most recent call last):
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/scripts/addons/sverchok/__init__.py", line 143, in <module>
    node_list = make_node_list()
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/scripts/addons/sverchok/__init__.py", line 137, in make_node_list
    import_modules(names, '{}.{}'.format(base_name, category), node_list)
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/scripts/addons/sverchok/__init__.py", line 127, in import_modules
    im = importlib.import_module('.{}'.format(m), base)
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/python/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/scripts/addons/sverchok/nodes/text/stethoscope_mk2.py", line 28, in <module>
    from sverchok.utils.sn_node_utils import scaled_dpi
ImportError: No module named 'sverchok.utils.sn_node_utils'
Traceback (most recent call last):
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/scripts/addons/sverchok/__init__.py", line 143, in <module>
    node_list = make_node_list()
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/scripts/addons/sverchok/__init__.py", line 135, in make_node_list
    for category, names in nodes.nodes_dict.items():
NameError: name 'nodes' is not defined
Traceback (most recent call last):
  File "/home/travis/build/nortikin/sverchok/utils/testing.py", line 12, in <module>
    import sverchok
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/scripts/addons/sverchok/__init__.py", line 143, in <module>
    node_list = make_node_list()
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/scripts/addons/sverchok/__init__.py", line 135, in make_node_list
    for category, names in nodes.nodes_dict.items():
NameError: name 'nodes' is not defined
```

**Comment by portnov** [comment]
I proposed a post to russian vk group for @nortikin , asking for testers, I think he will publish it soon. @zeffii I think it might help if you post here something like instruction for testers (how to checkout the branch, what exactly to check and so on).
I might have access to a laptop with hidpi display (not retina though), but can't say when exactly.

**Comment by zeffii** [comment]
i'm thinking more and more it would be useful to have a sverchok "test mode", that instead of updating to the current master - would replace the download zip it points to and obtain the branch instead.

https://github.com/nortikin/sverchok/blob/d5c1f4c8093a8fdf54a3760ffad3b5e4cd4be7b7/utils/sv_update_utils.py#L157-L162

Just a small pain-in-ass for git users to test.. this non git-user stuff

**Comment by zeffii** [comment]
an operator to download the list of branches (i recall writing code that does this already.. will look for it..or recode whichever is faster or less effort.. ) this can fill an enum of choices, once picked proceed to download/"cross-grade" (not upgrade), the enum will not need to list master, there will be a button to return to master.

**Comment by zeffii** [comment]
https://api.github.com/repos/nortikin/sverchok/branches

image

but that list is waaaay to long... so perhaps we need to add a prefix to the branch names that we want people to test.

**Comment by zeffii** [comment]
best start a different thread for this. https://github.com/nortikin/sverchok/issues/2052

**Comment by zeffii** [comment]
[SV_UV_2_VCOL - 02_EDIT_2018_01_21_21_03.zip](https://github.com/nortikin/sverchok/files/1650202/SV_UV_2_VCOL.-.02_EDIT_2018_01_21_21_03.zip)

**Pull request closed without merging**
