### PR TITLE
Expose normalized line size parameter as an input socket

### PR DESCRIPTION
**Pull request by DolphinDream**
For now the size is not vectorized so it is will be the same for all vectorized lines.

- [ ] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [ ] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by DolphinDream** [comment]
@zeffii what's the verdict on this one? should it be made MK3? 
I abandoned the idea of vectrorizing the size for now and have the socket created/removed when normalize is ON/OFF.

**Comment by zeffii** [comment]
dude.. i just made an auto upgrade mk2.   https://github.com/nortikin/sverchok/pull/2265   if that works for people let's stick to mk2.

**Comment by DolphinDream** [comment]
ok.. i had already made the changes a while back so I figured I'd clean them up and push them. I can abandon this PR, no problem.

**Comment by zeffii** [comment]
my verdict is that preferably, i didn't waste 20 minutes of my life just now

**Comment by zeffii** [comment]
i haven't done any serious testing (computer is slow and doing other stuff).   but if it works i'll be happy to push mine and have it auto- upgrade when the process function encounters a node that doesn't yet have a `Size` socket

**Comment by zeffii** [comment]
yeah, this can close. i've merged mine https://github.com/nortikin/sverchok/commit/a8880e437709aa986750ae56069634f14884175a

**Pull request closed without merging**
