### PR TITLE
Oscillator node

### PR DESCRIPTION
**Pull request by vicdoval**
This node creates a oscillation signal from a lineal range.

Generating basic waves.
Oscillator_example_01

The "Wave" mode allows you to use a custom wave shape
Oscillator_example_02

As with the musical synths you can create complex waves out of mixing the basics
Oscillator_example_03

Surface modeled by a combination of Oscillator nodes
Oscillator_example_04

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by zeffii** [comment]
hehe.. i will add some kind of flac / wav writer operator -- unless you plan to

**Comment by vicdoval** [comment]
@zeffii that would be awesome :smiley:  then probably i will take a look to make a numpy implementation to try to handle faster the 44100 samples per second that will be needed

**Comment by enzyme69** [comment]
Should I click the "Merge Pull Request"?

This make my wishlist come true:
https://github.com/nortikin/sverchok/issues/2251

We still need OSC and MIDI node :D (MOM) and something that generate sound from another addon that's never got updated...

**Comment by zeffii** [comment]
@enzyme69   - let @vicdoval to that when he's ready.

**Comment by vicdoval** [comment]
Re-coded in Numpy (10 times faster) and custom icons
untitled_nodetree
untitled

**Comment by zeffii** [comment]
we should have more nodes that `accept / produce` only numpy, especially a numpy math node, I would totally use this to generate wavetable samples for synths :)

**Comment by zeffii** [comment]
next up.. 
- ADSR node.
- mixer

**Comment by enzyme69** [comment]
@vicdoval Eh the Oscillator node is not in Blender 2.79? 

While waiting for Blender 2.80 version of audio nodes:
https://github.com/nomelif/Audionodes

**Pull request merged**
