### PR TITLE
Completed N-panel and right-click menu of Math_mk2

### PR DESCRIPTION
**Pull request by vicdoval**
Just added the function menu to the N-panel and the inputs type (Float or Int) to the right-click menu
This enhancements are particularly useful in big nod-trees because you don't have to zoom in to change the parameters  
Also I changed the order of the list. First the Operators, after trigonometry and constants at the end. I think add/sub/multiply/divide should be the first as they are used more often. Also now in the menu of the node "A" is for Add, "S" for subtract, "M" for multiply... :D 

math_mk2
math_mk22

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
I'd suggest to add a call of `super().rclick_menu(context, layout)` to the end of `rclick_menu` implementation. Just in case something interesting will be added into base implementation later.

**Comment by zeffii** [comment]
seems like a useful enhancement : ) 

but... i'm weary of changing the enum numbers... does this play nice with stored jsons / .blends ?

**Comment by vicdoval** [comment]
@portnov  you mean in the global rclick menu of sverchok?

@zeffii  You are right It messes the blend files and works fine on the jsons. If we are going to re-arrange it the moment is now :) , other possibility would be turning this into mk3 and start filling the "old nodes" folder

**Comment by zeffii** [comment]
i intentionally resisted trying to make svb28 compatible with svb279.

but i realize that the math node is one of the more frequently used nodes that will kick people in the painful parts if they suddenly open svb28 test files that aren't working.. Maybe mk3 is justified.

**Comment by zeffii** [comment]
might be a nice opportunity to implement a "replace this node with new version" operator, stick it in the draw_buttons   "upgrade node to mk3".

yeah i might do that tomorrow !  don't move mk2 to old just yet.

**Comment by portnov** [comment]
@zeffii "replace with new version" is more or less already there, see default implementation of `rclick_menu` node method.

**Comment by zeffii** [comment]
> @zeffii "replace with new version" is more or less already there, see default implementation of `rclick_menu` node method.

yeah, OK. I welcome @vicdoval to add the upgrade option to the rclick menu then

**Comment by zeffii** [comment]
@vicdoval  consider 
https://github.com/nortikin/sverchok/blob/94686bb56bc45981b9853a2c5176bad843e87e3a/node_tree.py#L335

**Comment by vicdoval** [comment]
Done :)
By the way, it would be very cool if the "replacer operator" could remove the red frame when done :)

**Pull request merged**
