### PR TITLE
B28 vtext fix4

### PR DESCRIPTION
**Pull request by zeffii**
resolves the sockets not matching the input types

### CODE REVIEW

**Comment by zeffii** [comment]
it will still create a second  Frame node... todo..

**Comment by zeffii** [comment]
also this message occurs , and is triggered from inside this node's update function.
```
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\text\viewer_text_mk3.py", line 204, in update
    if not socket.bl_idname == socket.other.bl_idname:
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\sockets.py", line 67, in other
    return get_other_socket(self)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\data_structure.py", line 759, in get_other_socket
    other = socket.links[0].from_socket
IndexError: tuple index out of range

location: <unknown location>:-1

```

**Comment by zeffii** [comment]
i think that error happens when the input socket of viewertext is being disconnected (ie, the noodle is still attached to the mouse cursor..)

**Comment by zeffii** [comment]
wow.   socket.is_linked can be true, and still socket.links can be a zero length tuple

@portnov   when  a noodle is being disconnected from a node, and that node has an update function like viewer text..

**Comment by portnov** [comment]
I think it may also be in case when the socket is connected to "reroute" circle...

**Comment by zeffii** [comment]
there's a remaining bug(s)
- that the node generates two frame nodes..
- sometimes `Data0` has SvNoData (but i think that's part of a larger problem)

**Comment by zeffii** [comment]
still with bug, but better than before.. i think.

**Pull request merged**
