### PR TITLE
Update tree_import_tests.py

### PR DESCRIPTION
**Pull request by zeffii**
dont include this json in tests

### CODE REVIEW

**Comment by nortikin** [comment]
When i change draft mode numbers are zeroed. But there are limits inside nodes, so no zeros can be
Снимок экрана от 2020-04-27 22-20-11

**Comment by zeffii** [comment]
sorry @nortikin  i have not used draft mode. @portnov  ? :)

**Comment by zeffii** [comment]
sv init is overwriting these values i think.

**Comment by vicdoval** [comment]
this was not that bad idea, at least for the time being

**Comment by zeffii** [comment]
yes. i we should still resolve the issue.. but that doesn't have to happen in master.

**Pull request merged**
