### PR TITLE
Updated docstrings that appear in the browser

### PR DESCRIPTION
**Pull request by vicdoval**
The docstrings that appear in the search menu are sometimes missing, sometime useless due repeating the node name

I reviewed the menu and added some of them.
I tried to be as clear as possible
In some cases i added a shortcut as suggested  in https://github.com/nortikin/sverchok/issues/1663 
I tried to use different words to cover a bigger scope in the search.

I didnt change all the nodes, but i think 30 files is enough for this commit

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [ x] Code changes complete.
- [x ] Code documentation complete.
- [x ] Documentation for users complete (or not required, if user never sees these changes).
- [x ] Manual testing done. 
- [ x] Unit-tests implemented.??
- [x ] Ready for merge.

### CODE REVIEW

**Comment by zeffii** [comment]
we have a better/new docstring convention.

https://github.com/nortikin/sverchok/blob/5cd48f56591b329537f8e6aca935bafcff04fff2/utils/docstring.py
https://github.com/nortikin/sverchok/blob/dc5a2bb8ed36cbf112060a88fe31e5d839af8d3c/nodes/vector/color_input.py#L27-L36

**Comment by zeffii** [comment]
if you are willing to convert them to that.. that would be awesome :)

**Comment by vicdoval** [comment]
I'm glad there is a new/better convention :) although it would have been better to discover it before. :D (The pitfalls of working before asking). 
I'm not sure when i'll be able to change them to the new convention, but I think it would  good to push this changes now, because despite of not being totally updated they are an small improvement compared to the actual state

**Comment by zeffii** [comment]
ok : ) i don't have time to do it either

**Pull request merged**
