### PR TITLE
add help browser to a node if it has help_url

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
it could detect an internet connection and display the local docs/......./*.rst if none is found.

**Comment by nortikin** [comment]
cool
if python has rst librery...

**Comment by nortikin** [comment]
where we can put man, generated with make man?

**Comment by zeffii** [comment]
do you mean the output of `make html` ?

**Comment by zeffii** [comment]
image
might have to make it platform specific...

**Comment by zeffii** [comment]
can someone test if the offline version works for mac / linux ?

**Comment by zeffii** [comment]
I think most nodes their .rst or .html can be inferred automatically by their folder/filename, and only few have divergent paths..

**Comment by zeffii** [comment]
but it would be be made much less convoluted if the docs/nodes layout was the same as sverchok/nodes..

**Comment by zeffii** [comment]
for instance
```
>>> nodes['List Modifier'].__module__
'sverchok.nodes.list_basic.modifier'
```
whereas the docs it's
```
list_main/list_modifier
```

**Comment by zeffii** [comment]
quickly a list of nodes that don't automatically remap, or don't have docs
```
{'analyzer.bmesh_props': 'not analyzer.bmesh_props',
 'analyzer.closest_point_on_mesh': 'not analyzer.closest_point_on_mesh',
 'analyzer.colors': 'not analyzer.colors',
 'analyzer.colors2': 'not analyzer.colors2',
 'analyzer.image_components': 'not analyzer.image_components',
 'analyzer.neuro_elman': 'not analyzer.neuro_elman',
 'analyzer.normals': 'not analyzer.normals',
 'analyzer.object_raycast': 'not analyzer.object_raycast',
 'analyzer.polygons_centers_mk3': 'not analyzer.polygons_centers_mk3',
 'analyzer.scene_raycast': 'not analyzer.scene_raycast',
 'basic_data.BMOperators': 'not basic_data.BMOperators',
 'basic_data.blenddata_to_svdata': 'not basic_data.blenddata_to_svdata',
 'basic_data.bmesh_in': 'not basic_data.bmesh_in',
 'basic_data.bmesh_out': 'not basic_data.bmesh_out',
 'basic_data.bmesh_to_element': 'not basic_data.bmesh_to_element',
 'basic_data.cache': 'not basic_data.cache',
 'basic_data.dupli_instances': 'not basic_data.dupli_instances',
 'basic_data.filter_blenddata': 'not basic_data.filter_blenddata',
 'basic_data.get_blenddata': 'not basic_data.get_blenddata',
 'basic_data.getsetprop': 'not basic_data.getsetprop',
 'basic_data.instancer': 'not basic_data.instancer',
 'basic_data.node_remote': 'not basic_data.node_remote',
 'basic_data.obj_remote': 'not basic_data.obj_remote',
 'basic_data.objects': 'not basic_data.objects',
 'basic_data.set_blenddata': 'not basic_data.set_blenddata',
 'basic_data.sort_blenddata': 'not basic_data.sort_blenddata',
 'basic_data.switch': 'not basic_data.switch',
 'basic_data.text': 'not basic_data.text',
 'basic_data.wifi_in': 'not basic_data.wifi_in',
 'basic_data.wifi_out': 'not basic_data.wifi_out',
 'basic_debug.3dview_props': 'not basic_debug.3dview_props',
 'basic_debug.debug_print': 'not basic_debug.debug_print',
 'basic_debug.frame_info': 'not basic_debug.frame_info',
 'basic_debug.gtext': 'not basic_debug.gtext',
 'basic_debug.note': 'not basic_debug.note',
 'basic_debug.stethoscope': 'not basic_debug.stethoscope',
 'basic_view.empty_out': 'not basic_view.empty_out',
 'basic_view.viewer_bmesh_mk2': 'not basic_view.viewer_bmesh_mk2',
 'basic_view.viewer_curves': 'not basic_view.viewer_curves',
 'basic_view.viewer_curves_2d': 'not basic_view.viewer_curves_2d',
 'basic_view.viewer_indices': 'not basic_view.viewer_indices',
 'basic_view.viewer_mk2': 'not basic_view.viewer_mk2',
 'basic_view.viewer_polyline': 'not basic_view.viewer_polyline',
 'basic_view.viewer_skin': 'not basic_view.viewer_skin',
 'basic_view.viewer_text': 'not basic_view.viewer_text',
 'basic_view.viewer_typography': 'not basic_view.viewer_typography',
 'generator.basic_3pt_arc': 'not generator.basic_3pt_arc',
 'generator.basic_spline': 'not generator.basic_spline',
 'generator.formula': 'not generator.formula',
 'generator.profile': 'not generator.profile',
 'generator.script': 'not generator.script',
 'generator.script3': 'not generator.script3',
 'generator.script_mk2': 'not generator.script_mk2',
 'list_basic.converter': 'not list_basic.converter',
 'list_basic.decompose': 'not list_basic.decompose',
 'list_basic.func': 'not list_basic.func',
 'list_basic.join': 'not list_basic.join',
 'list_basic.length': 'not list_basic.length',
 'list_basic.levels': 'not list_basic.levels',
 'list_basic.mask': 'not list_basic.mask',
 'list_basic.mask_join': 'not list_basic.mask_join',
 'list_basic.match': 'not list_basic.match',
 'list_basic.modifier': 'not list_basic.modifier',
 'list_basic.sum_mk2': 'not list_basic.sum_mk2',
 'list_basic.zip': 'not list_basic.zip',
 'list_interfere.flip': 'not list_interfere.flip',
 'list_interfere.item': 'not list_interfere.item',
 'list_interfere.numpy_array': 'not list_interfere.numpy_array',
 'list_interfere.repeater': 'not list_interfere.repeater',
 'list_interfere.reverse': 'not list_interfere.reverse',
 'list_interfere.shift_mk2': 'not list_interfere.shift_mk2',
 'list_interfere.shuffle': 'not list_interfere.shuffle',
 'list_interfere.slice': 'not list_interfere.slice',
 'list_interfere.sort_mk2': 'not list_interfere.sort_mk2',
 'list_interfere.split': 'not list_interfere.split',
 'list_interfere.start_end': 'not list_interfere.start_end',
 'matrix.apply': 'not matrix.apply',
 'matrix.apply_and_join': 'not matrix.apply_and_join',
 'matrix.deform': 'not matrix.deform',
 'matrix.destructor': 'not matrix.destructor',
 'matrix.euler': 'not matrix.euler',
 'matrix.generator': 'not matrix.generator',
 'matrix.input': 'not matrix.input',
 'matrix.interpolation': 'not matrix.interpolation',
 'matrix.shear': 'not matrix.shear',
 'modifier_change.edges_intersect': 'not modifier_change.edges_intersect',
 'modifier_change.holes_fill': 'not modifier_change.holes_fill',
 'modifier_change.limited_dissolve': 'not modifier_change.limited_dissolve',
 'modifier_change.mesh_separate': 'not modifier_change.mesh_separate',
 'modifier_change.mirror': 'not modifier_change.mirror',
 'modifier_change.polygons_boom': 'not modifier_change.polygons_boom',
 'modifier_change.rotation': 'not modifier_change.rotation',
 'modifier_change.scale': 'not modifier_change.scale',
 'modifier_change.triangulate_heavy': 'not modifier_change.triangulate_heavy',
 'modifier_change.vertices_mask': 'not modifier_change.vertices_mask',
 'modifier_make.csg_boolean': 'not modifier_make.csg_boolean',
 'modifier_make.edges_adaptative': 'not modifier_make.edges_adaptative',
 'modifier_make.inset_special': 'not modifier_make.inset_special',
 'modifier_make.join_tris': 'not modifier_make.join_tris',
 'modifier_make.polygons_adaptative': 'not modifier_make.polygons_adaptative',
 'modifier_make.uv_connect': 'not modifier_make.uv_connect',
 'modifier_make.voronoi_2d': 'not modifier_make.voronoi_2d',
 'network.udp_client': 'not network.udp_client',
 'number.easing': 'not number.easing',
 'number.exponential': 'not number.exponential',
 'number.fibonacci': 'not number.fibonacci',
 'number.float_to_int': 'not number.float_to_int',
 'number.formula2': 'not number.formula2',
 'number.integer': 'not number.integer',
 'number.logic': 'not number.logic',
 'number.range_map': 'not number.range_map',
 'number.scalar': 'not number.scalar',
 'vector.axis_input': 'not vector.axis_input',
 'vector.drop': 'not vector.drop',
 'vector.interpolation': 'not vector.interpolation',
 'vector.interpolation_mk2': 'not vector.interpolation_mk2',
 'vector.interpolation_mk3': 'not vector.interpolation_mk3',
 'vector.line_evaluate': 'not vector.line_evaluate',
 'vector.math': 'not vector.math',
 'vector.move': 'not vector.move',
 'vector.noise': 'not vector.noise',
 'vector.normal': 'not vector.normal',
 'vector.vertices_delete_doubles': 'not vector.vertices_delete_doubles',
 'vector.vertices_sort': 'not vector.vertices_sort'}
```

**Comment by zeffii** [comment]
generate remapper
```python
import bpy
import sverchok
cats = sverchok.menu.make_node_cats()

print('----')
tplist = []

nodes = bpy.data.node_groups['NodeTree'].nodes
for k, v in cats.items():
    print('##', k)
    for i in v:
        n = nodes.new(i[0])
        f = '.'.join(n.__module__.split('.', 2)[2:])
        tplist.append((f, f))
        
        

for l in tplist:
    print(l, ',')

```

from remapper to explicit remaps
```python
import os
explicit_remaps = {}
for k, v in remapper.items():
    test_path = os.path.join(r'C:\Users\zeffi\Desktop\GITHUB\sverchok\docs\nodes', *k.split('.')) + '.rst'

    if os.path.exists(test_path):
        pass
    else:
        explicit_remaps[k] = 'not ' + k

import pprint
pprint.pprint(explicit_remaps)
```

**Comment by zeffii** [comment]
that's `124 / 180` that need to be explicitely remapped..

**Comment by nortikin** [comment]
cool. will test in evening later. I'm at my workplace under Windows.

**Comment by zeffii** [comment]
yes @nortikin  , I could build a remap dict when `https://github.com/nortikin/sverchok/blob/master/index.md` is parsed, and then make the directories and nodes.rst 
```rst
*****
Nodes
*****

.. toctree::
   :maxdepth: 3

   Generators <nodes/generator/generator>
   Transforms <nodes/transforms/transforms>
   Analyzer <nodes/analyzer/analyzer>
   Modifier Change <nodes/modifier_change/modifier_change>
   Modifier Make <nodes/modifier_make/modifier_make>

   Number <nodes/number/number>
   Vector <nodes/vector/vector>
   Matrix <nodes/matrix/matrix>
   Logic <nodes/logic/logic>
   List Main <nodes/list_main/list_main>
   List Structure <nodes/list_struct/list_struct>

   Viz <nodes/viz/viz>
   Text <nodes/text/text>
   Scene <nodes/scene/scene>
   Layout <nodes/layout/layout>

   Beta <nodes/beta/beta>
```

match eachother. For optimal lazyness

**Comment by zeffii** [comment]
luckily the organization of the docs already closely matches the custom menu :)

**Comment by zeffii** [comment]
I will do this @nortikin  , but I ask you to make a backup of the manual that you currently have online. I think you customized parts of it. I think the output of `make html` needs to match the online manual, if the layout needs fixing we fix it in the `make or js` -- am confident it can be done.

**Comment by zeffii** [comment]
I am about 1/6 done

**Comment by nortikin** [comment]
ok

**Comment by zeffii** [comment]
cool.  btw: 

```
>>> nodes = bpy.data.node_groups['NodeTree'].nodes
>>> nodes['Delaunay 2D'].__module__
'sverchok.nodes.modifier_make.voronoi_2d'

```
huh?

**Comment by zeffii** [comment]
oh yikes... these two nodes are declared in the same Python file? OK. that's fine :)

**Comment by zeffii** [comment]
just over half way..

**Comment by zeffii** [comment]
now, building the .rst doctree.. :)
```
import os
from os.path import basename, dirname

ppath = r'C:\Users\zeffi\Desktop\GITHUB\sverchok\docs\nodes'

def write_file(header):
    gather_lines = []
    stars = "*" * len(header)
    
    template = """\
{0}
{1}
{0}

.. toctree::
   :maxdepth: 2
""".format(stars, header, stars)

    gather_lines.extend(template.split('\n'))
    real_folder_name = header.replace(' ', '_').lower()
    directory = os.path.join(ppath, real_folder_name)
 
    for subdir, dirs, files in os.walk(directory):
        current_dir = basename(subdir)
        for file in files:
            if not file.endswith('.rst'):
                continue
            if file == (real_folder_name + '.rst'):
                continue
            gather_lines.append('   ' + file[:-4])

    return gather_lines



def poke_dir(basedir):
    for subdir, dirs, files in os.walk(basedir):
            current_dir = basename(subdir)
            if current_dir == 'nodes':
                continue

            header = current_dir.replace('_', ' ').title()
            fname = current_dir + '_index.rst'
            newfile = os.path.join(basedir, current_dir, fname)

            fdata = write_file(header)
            print(fdata)
            with open(newfile, 'w') as f:
                for line in fdata:
                    f.write(line + '\n')


poke_dir(basedir=ppath)



```

**Comment by zeffii** [comment]
OK , now the menu.py parser should be able to build a remap dict for the help files. Not tried yet.

```python
    Matrix       SvMatrixValueIn           ../matrix/input.rst
    (Header + bl_idname)              -> header/node_name
```

**Comment by zeffii** [comment]
almost there i think...

**Comment by zeffii** [comment]
OK. seems to work :)

**Comment by zeffii** [comment]
but @nortikin  will need to update the online docs to match the output of `make html` , untill then you can test with the offline docs..

**Comment by zeffii** [comment]
If i did this correctly,  then all we have to make sure is that we use the same filename for the `node's .py` as for the `node's .rst`, and that the `rst`  is placed in the directory that matches the `index.md` categorization.

**Comment by nortikin** [comment]
wow1!!!!11!!

**Comment by nortikin** [comment]
generators have to be generator or vice versa
analyzers vs analyzer
modifier change vs modifier_change
polygons_boom vs polygon_boom
many have to rename

**Comment by zeffii** [comment]
@nortikin before you put effort into renaming anything, please test with the offline help. The online help assumes an identical structure (which currently isn't the case unless you have run `make html` on the `node_help` branch and uploaded that to the website.

**Comment by zeffii** [comment]
Will add a page that the help goes to if the remapper didn't find a document corresponding to the node. 

something like:
```
It appears this node doesn't have any documentation associated with it, please contact us 

  - here (link, google groups.. or vk...or both)
  - or directly on the issue tracker
```

Some fine tuning still needs to happen for those nodes that share a python file.

**Comment by zeffii** [comment]
now if a node doesn't have an associated .rst file locally then a 404 is shown with some contact info..

image

**Comment by zeffii** [comment]
was considering adding a templating rule to the html to say 
```
   Sorry! It appears that <Node.bl_idname> has no help documents. ...etc 

```

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
i mean bl_label :)

**Comment by zeffii** [comment]
hm, it appears it's not possible to call 

```python
webbrowser.open('.....404.html?something=somethingelse')
```

**Comment by zeffii** [comment]
I'd like to push this soon! any objections?

**Comment by nortikin** [comment]
nohelp

**Comment by nortikin** [comment]
not sure, my linux have not normal python onboard. rosalinux is ex-mandriva

**Comment by nortikin** [comment]
nohelp

**Comment by zeffii** [comment]
@nortikin interesting, do you compile your own Blender?

**Comment by nortikin** [comment]
@zeffii no, only my rosa linux has troubles with python integration. i think soething with paths. i tried to start blendr with OS python, it failed, it needs 3.5, i have 3.4, so maybe there is my own problem.

**Comment by nortikin** [comment]
will propose to test my friend

**Comment by nortikin** [comment]
it works on linux, my friend says it is ok.

**Comment by zeffii** [comment]
i'm prepared to make it a 3.4 compatible, so you can test it :)

**Comment by zeffii** [comment]
somerthing like:
```python
tk = os.path.join(os.path.dirname(sverchok.__file__), 'docs', 'nodes', string_dir.replace(' ', '_'), filename + '.rst')

# modern
my_file = Path(tk)
VALID = my_file.is_file()

# classic

import os.path
VALID = path.exists(tk) and path.isfile(tk)
```

**Comment by zeffii** [comment]
@nortikin i've updated the code, test whenever you have a few minutes :)

**Comment by nortikin** [comment]
soorry. so sorry, it was my foult. I donno how exactly to deal with branches and made some mistakes.
So, it works well, thank you!!!

**Pull request merged**
