### PR TITLE
B28 waveform output

### PR DESCRIPTION
**Pull request by zeffii**
image

didn't feel like wasting more time on a fragment shader, not this time.

### CODE REVIEW

**Comment by zeffii** [comment]
not sure why the test is failing, code be the latest version of Blender handles custom node group (in relation to what we do in Monads) differently..

**Comment by zeffii** [comment]
ok.  it kind of works: 
image

@vicdoval

**Comment by zeffii** [comment]
now with initial tick support

tick every 128 samplers:
image

**Comment by zeffii** [comment]
image


i think minimized/hidden easing and waveoutput node should display their graph x=0 y=-labelwidth , ie.. above the label.

**Comment by zeffii** [comment]
i don't really know how useful this node is, but it's fun to have anyway.

**Comment by enzyme69** [comment]
Zeffii this waveform thing, can it plug into Audio Nodes? https://github.com/nomelif/Audionodes

**Comment by zeffii** [comment]
Audionodes is an entirely different engine, don't they have a waveform viewer?  SvWaveformViewer is Sverchok only.

**Pull request merged**
