### PR TITLE
Create troubleshooting_nodes.rst

### PR DESCRIPTION
**Pull request by zeffii**
## Addressed problem description

we can help people better debug their nodes and node trees. A significant number of people like to solve their own problems, and some of those people need a little help to understand the process and their options of finding solutions. Most of the time (and this is true for most new programmers) there comes a point where a user feels they understand something, but can't explain why a node has an error or won't work - the kneejerk reaction is to think there's a bug in the tool. Often, the bug is not in the tool. Most of the time we don't change any code to resolve an issue.

## Solution description

description of methods that we added and use to figure out what nodes are failing and why.

### CODE REVIEW

**Comment by zeffii** [comment]
not being a fluent programmer should not be a serious impediment to understanding the process of location a problem / bug.

**Comment by nortikin** [comment]
like this tongue

**Comment by zeffii** [comment]
http://alumni.cs.ucr.edu/~ratana/PaneRatanamahatanaMyers00.pdf

```
           Studying the Language and Structure in
         Non-Programmers’ Solutions to Programming
                        Problems
```

**Comment by portnov** [comment]
Do not see any reason for this to linger out of master branch :)

**Pull request merged**
