### PR TITLE
add example of onboard help

### PR DESCRIPTION
**Pull request by zeffii**
adds console context awareness to node.help invocation

image

something like this is possible, the exact visual representation and whether `n.help` should be added to the history before displaying items is for later implementation

### CODE REVIEW

**Comment by zeffii** [comment]
but a real drawback about `console` is that it's a dangerous place after the users hits `f8` (scripts.reload)  , any lines previously evaluated will point to a void when you try to execute them, and blender will exit to desktop

```
nodes = bpy.data.node_groups['NodeTree'].nodes
n = nodes['VD Experimental']
n.help
```
if you do `f8` and then
```
n.help
```
blender can vanish, because references are also wiped.

**Comment by zeffii** [comment]
we can print to the console from a node directly, if console is open..

**Comment by Durman** [comment]
Do you know the method for this? I am occasionally wondering if is it possible.))

**Comment by zeffii** [comment]
yeah, you iterate through spaces.. i'll add example code (temporarily)

**Comment by zeffii** [comment]
```python
import bpy
from console_python import get_console

AREA = 'CONSOLE'
for window in bpy.context.window_manager.windows:
    for area in window.screen.areas:
        if not area.type == AREA: continue

        for region in area.regions:
            if region.type == 'WINDOW':
                console, stdout, stderr = get_console(hash(region))
                print(dir(console))
        
        for s in area.spaces:
            if s.type == AREA:
                print(dir(s))
                break

```
i thought I'd figured out how to print to an arbitrary console in the past, but apparently not.  i'll keep digging..

**Comment by Durman** [comment]
Especially it would be nice to creates links to objects for them further inspection via console.

**Comment by zeffii** [comment]
@Durman 

i think you could probably inspect the content of a node at runtime, by returning the values you want from '`process()`

```python

def process(self):
    ...
    ...  # setting / getting socket data

    return [everything you want to query]

>>> nodes = bpy.data.node_groups['NodeTree']
>>> n = nodes[your node]
>>> data = n.process()
>>> print(data)
```

**Comment by zeffii** [comment]
that would be useful during node development / debugging.

if that works it's simpler than implementing `node_dict` to store objects for introspection - so i would prefer not to go there is `returning` data from process is adequate

**Comment by Durman** [comment]
Well, I just create variable in a module and then exports it via console. It works.)

**Comment by zeffii** [comment]
i won't be committing this

**Comment by Durman** [comment]
> Especially it would be nice to creates links to objects for them further inspection via console.

Actually I had found that `breakpoint()` (built in python function) is doing exactly what I need.

**Pull request closed without merging**
