### PR TITLE
Add new RangeSwitch node

### PR DESCRIPTION
**Pull request by DolphinDream**
New node to control ON/OFF switch status based on a value relative to a value range.

Current modes are:
- **Inside On** : switch is ON when value is inside the boundary range
- **Inside Off**: switch is OFF when value is inside the boundary range
- **Pass Through** : switch is toggled ON/OFF when value crosses the boundary range in any direction.

SV-RangeSwitch-UI1

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by DolphinDream** [comment]
And a live demo:

[](http://www.youtube.com/watch?v=ROeNdQ220eo "RangeSwitch node demo1")

**Comment by DolphinDream** [comment]
Testing node setup.

SV-RangeSwitch-Setup1

**Comment by vicdoval** [comment]
Hey @DolphinDream  did you know this node is not vectorized?
image

**Comment by DolphinDream** [comment]
@vicdoval oops :) I’ll update it shortly with a vectorized version.

**Comment by DolphinDream** [comment]
Vectorized the Range Switch node.

SV-RangeSwitch-demo3

**Pull request merged**
