### PR TITLE
Fix face indexing extrude region node

### PR DESCRIPTION
**Pull request by Durman**
## Addressed problem description

#3029

## Solution description

The attempt to solve the problem by using own mesh walker.

## Preflight checklist

- [ ] Create MKNext version
- [ ] Solve multiple disjoint islands problem.
- [ ] Speed test. And new mode if necessary.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
I'd suggest using "bmesh data layers" instead. Not sure how exactly... (not that I understand the problem you are dealing with); something like: remember the original Index of the face in it's data layer. See how it's done in the Bevel node for edges, for example: https://github.com/nortikin/sverchok/blob/master/nodes/modifier_change/bevel.py

**Comment by Durman** [comment]
I understand what do you mean. The problem is the new faces created by the extruded algorithm (side faces) can have different indexes from one execution to another. And it is impossible to set something into their layers directly. So I don't see how layers can help here.

**Comment by portnov** [comment]
Then I'd suggest to add an option to toggle that arranging algorithm on/off. Because in many cases it will just waste time without necessity (most "good" node trees will not depend on this order).

**Comment by Durman** [comment]
I'm going make a speed test. If slowdown will significant I will add the property. I have added this into todo list.

**Comment by Durman** [comment]
I think it will be better to add separate node for mesh sorting.

**Pull request closed without merging**
