### PR TITLE
"Unwrap" option for socket menus

### PR DESCRIPTION
**Pull request by portnov**
This option removes one pair of square brackets from a nested list, if it is
possible. If output data is empty, or output data is a list with more than one
item, this will raise an exception, and processing will stop. For example, if
the socket contains ``[[1, 2, 3]]``, then with this option enabled you will
have ``[1, 2, 3]``. But, if the socket contains ``[[1, 2], [3, 4]]``, then you
will have an exception.

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
Strange option. What is it useful for?

**Comment by portnov** [comment]
Some nodes are designed to work with nested input, so they produce nested output in general case. But then it can appear that you do not want so high nesting level, if you pass only one item to the input.

**Comment by Durman** [comment]
Which node expect such input `[1, 2, 3]`?

**Comment by portnov** [comment]
most expect ``[[1,2,3]]`, for example. But another nodes output ``[[[1,2,3]]]`` instead.

**Comment by Durman** [comment]
> most expect `[[1,2,3]]`, for example.

But you decided to convert it into `[1, 2, 3]` even if no one node expects such format and even raise an error in some cases. Looks like this option is breaking our vectorization conception.

**Comment by portnov** [comment]
This option removes *one*, outermost, pair of square brackets. User enables it when he knows that the output list contains exactly one object (one nested list) at the outer level.

**Pull request merged**
