### PR TITLE
Set use_fake_user attribute of Sverchok trees

### PR DESCRIPTION
**Pull request by Durman**
## Addressed problem description

#3648

- [x] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
@vicdoval Would you like to test?

**Comment by vicdoval** [comment]
Seems to work nicely :)

**Comment by Durman** [comment]
There is only one problem. After F8 and loading new file it does not work.

**Comment by vicdoval** [comment]
> There is only one problem. After F8 and loading new file it does not work.

This is only a problem developers will find and in a small set of cases so to me its not very important. If you find it important enough we can always go back to the previous solution

**Comment by Durman** [comment]
I also think it can stay as known issue but definitely should be fixed someday.

**Comment by Durman** [comment]
The problem somewhere there. If comment the line Sverchok can be even reloaded once and in a new file the new feature works. So in reload event the module starting to be like another instance of themself and if another module is trying to wright something in it it does not see.
https://github.com/nortikin/sverchok/blob/7a6ea8e5fe08433ffc0c27052bd87a0e3452ff3b/__init__.py#L78

**Comment by Durman** [comment]
http://pyunit.sourceforge.net/notes/reloading.html
https://stackoverflow.com/questions/437589/how-do-i-unload-reload-a-python-module

**Comment by Durman** [comment]
"Good" return for decorator 😑 

https://github.com/nortikin/sverchok/blob/65d2ee97653e1c49268573c630db10f822a9a902/data_structure.py#L1035

**Pull request merged**
