### PR TITLE
Fix "outdated internal index table" error in Offset node

### PR DESCRIPTION
**Pull request by portnov**
for Blender 2.73:
Node Offset Node had exception BMElemSeq[index]: outdated internal index table, run ensure_lookup_table() first

### CODE REVIEW

**Comment by zeffii** [comment]
I thought I already committed the fix, guess not..

**Comment by zeffii** [comment]
perhaps I postponed because it felt like there were too many such function calls.. but whatever works, I didn't give it much deep thought as soon as it started working again.

**Comment by zeffii** [comment]
It might be more sane to tests ones if such function call exists. and refuse to process any geometry if it doesn't exist, then we don't need to use the `hasattr()` in subsequent calls. Not using updated blender version isn't something we want to encourage (i think?) @ly29, @nortikin

**Comment by portnov** [comment]
In general, i think, we need to have a list of supported Blender versions stated somewhere. Maybe in README. I suppose not everyone got updated to 2.73 yet, so maybe we need to support 2.72 or even 2.71 (?). For example, Debian testing has only 2.72, stable has even 2.63. I think we obviously not going to support two-years-old blender versions; on the other hand, i think we need to support at least one previous version.

**Comment by zeffii** [comment]
Those are fair points, currently the readme does state 2.71, but I suspect this is due to laziness on our part more than a real effort to retain support. But I see your point, and that's another reason why we have the check elsewhere.

**Comment by nortikin** [comment]
guys, last i have not time and it seems not soon. agree, we need support latest version also.
What is refuse? just not working node? or we need to fix its behaviour? or we need global function that lookup in one line to execute in code?

**Comment by zeffii** [comment]
The commit is essentially the same as this https://gist.github.com/zeffii/56ed885a3b4fd920f7f7 which is my first attempt at fixing the offset node.

If the offsetnode has to process heavy meshes with many radial points for the fillet, it migh be a good idea to rewrite parts of it to avoid the `ensure_lookup_table` being called for every new vertex added.

```python
                    for o in range(n_ + 1):
                        q5 = self.a_rot((rot_ang * o / n_), rp_, axis_, q4)
                        bme.verts.new(q5)
                        bme.verts.index_update()
                        if hasattr(bme.verts, "ensure_lookup_table"):
                            bme.verts.ensure_lookup_table()

                        dict_0[j].append(bme.verts[-1])
                        list_3.append(bme.verts[-1])
```
Also aliasing the `bme.verts` as `bme_verts` is worth doing.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/558 I propose something more radical like this:

**Pull request merged**
