### PR TITLE
pushes as much as possible to sensible functions

### PR DESCRIPTION
**Pull request by zeffii**
## Addressed problem description

syntactic sugar for the iojson storage process.

## Solution description

perliminary stashing away logic into cohesive functions, and reusing self.storage_get_data more sanely.

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [ ] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [ ] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
"oops" :) I think we can congratulate ourselves: Travis did what it is created for, it seems first time for Sverchok :)

**Comment by zeffii** [comment]
heeh :) cool. yes. very helpful!

**Comment by zeffii** [comment]
@portnov ,  i don't think i ever used the old groupnode,  but still a question arises about the code i just added to support this relic. I'm tempted to drop it.

Nonetheless, an interesting recursion question: my pylinter doesn't throw a hissy-fit, but i'm not sure if the function `handle_old_groupnode` can call `create_dict_of_tree` .  The function is defined before `create_dict_of_tree` is, but only called from within it.

**Comment by zeffii** [comment]
yeah..that's not going to work.. :)

**Comment by portnov** [comment]
Afaik python's scoping rules allow this:

```python

def test1(x):
    return test2(x)+1

def test2(x):
    return x*x

print(test1(2)) # prints 5
```

Python is dynamic language, so it is required that name `test2` is defined at the moment of execution of `test1`, not at the moment of compilation. But I'd like to avoid such usage, it's very unobvious and can lead to confusion while maintaining the code.

**Comment by zeffii** [comment]
hmmm..

**Comment by zeffii** [comment]
hah, upon reading/digging around.. this function is needed for supporting monads .. i think.

**Comment by zeffii** [comment]
wtf.. anyway
```python
             handle_old_groupnode(node, k, v, groups_dict, create_dict_of_tree)            
```
has to work, because a few lines later there's 
```python
        if IsMonadInstanceNode and node.monad:
            pack_monad(node, node_items, groups_dict, create_dict_of_tree)
```
passing the function around works .

**Comment by nortikin** [comment]
saying sincerely, me afraid of:
```python
import json
import sys
import os
import re
import zipfile
import traceback
from time import gmtime, strftime
import urllib
from urllib.request import urlopen

from os.path import basename, dirname
from itertools import chain

import bpy
from bpy.props import StringProperty, BoolProperty, PointerProperty
from bpy.utils import register_class, unregister_class

from sverchok import old_nodes
from sverchok.utils import sv_gist_tools
from sverchok.utils.sv_IO_monad_helpers import pack_monad, unpack_monad
from sverchok.utils.logging import debug, info, warning, error, exception
```

**Comment by zeffii** [comment]
i intend to further modularize this file. agreed @nortikin   it's a frankestein's monster now.

**Pull request merged**
