### PR TITLE
replace shift+A menu, with ctrl+space menu

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
@nortikin  ? :)

**Comment by zeffii** [comment]
i'm ready to push this @nortikin

**Comment by nortikin** [comment]
I really love this menu with lines
Thanks

**Comment by zeffii** [comment]
i forgot to make sure that the categories match the doc categories : / oh well.. noone reads the docs :)

**Comment by nortikin** [comment]
sometimes they read them

**Comment by zeffii** [comment]
i'll check it out tomorrow..

anyway.. fuzzsearch maybe..

image

**Comment by enzyme69** [comment]
Yes, love this menu as well, thanks Zeffi and all! Feels very natural.

**Pull request merged**
