### PR TITLE
Select vertices/edges/faces parametrically

### PR DESCRIPTION
**Pull request by portnov**
Most obvious ways of "parametrically select" something are:

*   Select "leftmost" or "rightmost" vertices. More exactly, select vertices that have (direction, Vertex) >= X, where direction is specified vector and X is some number. And also select edges and faces that include selected vertices.
*    Select by normal direction. Select faces (and faces?), that have (Normal(Face), direction) >= X. And also select vertices that are included into selected faces.
*    Select "in range". Select vertices, that have distance(Vertex, Center) <= Radius. And also select edges and faces that include selected vertices.

See also #1320 .

### CODE REVIEW

**Comment by portnov** [comment]
output2

**Comment by kalwalt** [comment]
@portnov I see that is a select by normal option: with this node should be possible also add a displacement along normals?

**Comment by portnov** [comment]
@kalwalt 
This node only selects edges/faces/verts by some criteria. What to do with them you decide with other nodes. For example, you can use "Calculate normals" + "Move" to move along normals.

Btw, I think I can add yet another mode: select by cylinder. (Endless) cylinder can be defined by a point, a vector (direction), and radius.

**Comment by enzyme69** [comment]
@portnov And don't forget Dynamic Paint selector :D It's quite LIVE to select Vertices. It's weird, but works on Frame 1./

**Comment by portnov** [comment]
@enzyme69 
Interactive selections are discussed in #1320. There @zeffii said he is in general against it. So here we are discussing non-interactive aka parametric selections.

**Comment by zeffii** [comment]
> There @zeffii said he is in general against it

not against... and i won't even resist nice solutions,  just.. i hesitate to change BMeshViewer MK2 for features I don't need. BMViewerMK3 should be the goal..not changing MK2.

**Comment by portnov** [comment]
Added to new modes: "by plane" and "by cylinder".

By plane:

by-plane-1
by-plane-2
by-plane-3

**Comment by portnov** [comment]
By cylinder:

by-cylinder-1
by-cylinder-2

**Comment by portnov** [comment]
Also do not forget that it is possible to combine masks by logic functions:

by-sphere-not

**Comment by portnov** [comment]
Well, I accidentally made a tire... :)

tire-1

**Comment by portnov** [comment]
@zeffii 
I believe this is more or less ready for merge.

**Comment by zeffii** [comment]
Thank you @portnov  this covers us in most selection needs..

**Comment by DolphinDream** [comment]
Neato :) What about being able to select random vertices? or every other vertex (1010101) ? or every 3rd vertex (001001001)? or two vertices spaced by 3 vertices (11 000 11 000)? :) This looks like some sort mask value type of selection. I know this i possible with some list node magic, but if we are to have a vertex selection node it would be nice if we could select based on these kind of mask patterns. Just my 2¢

**Comment by portnov** [comment]
@DolphinDream 
I think it is possible right now if you create mask with "List input" node, and maybe apply also "List Match" node with "Cycle" mode.

**Comment by DolphinDream** [comment]
What would be the node setup where I have, let's say, a line of 12 verts and I want to offset the vertices at the index location given by this pattern: 0000 1 00 1 0000 ? (which is: offset the 5th an 8th verts along y, let's say).

**Comment by portnov** [comment]
@DolphinDream 
line-mask

https://gist.github.com/anonymous/d60325695bfb20192a5d41f504d44662

**Comment by DolphinDream** [comment]
@portnov neat. thx for the hint. That’ll do. 

However... I thought I’d take this to the next level and made up a concoction I call the “Transform Select Node” :) for lack of a better name. It sort of expands on the “mask vertices” node but it adds more to it to make it easier not only to separate the vertices but also to transform/group them (see the demo):

**Inputs**:

- mask # mask 0/1 with default repeat 0,1,0,1 if mask input is not linked
- vertices
- polyedges
- matrix True # matrix to transform the True (mask=1) verts
- matrix False # matrix to transform the False (mask=0) verts

**Outputs**:

- Vertices # Original Vertices but transformed by MT and MF
- PolyEdges # original polyEdges (pass through)
- PolyEdges O # polyEdges in the original set connecting the T set with the F set
- Vertices T # vertices transformed by MT
- PolyEdges T # polyEdges in original set that are also in T set
- Vertices F # vertices transformed by MF
- PolyEdges F # polyEdges in original set that are also in F set

transformselectnode-demo1

**Comment by DolphinDream** [comment]
And a circle demo with scale transform:

transformselectnode-demo2

**Comment by DolphinDream** [comment]
And a mesh-select node + transform-select node combo :)

transformselectnode-demo3

**Comment by portnov** [comment]
Cool :)

**Pull request merged**
