### PR TITLE
add draw_gl_polygonoffset property

### PR DESCRIPTION
**Pull request by zeffii**
adds option in buttons.ext , but maybe we'll automatically set it to True...

### CODE REVIEW

**Comment by portnov** [comment]
Why isn't it enabled by default?..

**Comment by zeffii** [comment]
because it's still tentative.  

i'd be happy to enable by default if someone can show me how to ensure that the opengl state is fully reset after leaving our draw callbacks. currently we have a few parameters that are reset when letting go, but not polygonoffset related stuff.

for some reason there appears to be some interaction with Blender's own viewport drawing.

**Comment by zeffii** [comment]
the condensed version of this new implementation is
```
bgl.glDisable(bgl.GL_POLYGON_OFFSET_FILL)
draw_edges(......)

bgl.glEnable(bgl.GL_POLYGON_OFFSET_FILL)
bgl.glPolygonOffset(1.0, 1.0)
draw_faces()

bgl.glDisable(bgl.GL_POLYGON_OFFSET_FILL)
```

**Comment by zeffii** [comment]
what i would like to guarantee is 
```
get_gl_state()

bgl.glDisable(bgl.GL_POLYGON_OFFSET_FILL)
draw_edges(......)

bgl.glEnable(bgl.GL_POLYGON_OFFSET_FILL)
bgl.glPolygonOffset(1.0, 1.0)
draw_faces(.......)

bgl.glDisable(bgl.GL_POLYGON_OFFSET_FILL)

revert_gl_state()
```

**Comment by zeffii** [comment]
i think the only property that needs to be tracked is the state 
stored by passing `glPolygonOffset(1.0, 1.0)`

**Comment by zeffii** [comment]
so.. maybe..  https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPolygonOffset.xhtml
```
glIsEnabled with argument GL_POLYGON_OFFSET_FILL, GL_POLYGON_OFFSET_LINE, or GL_POLYGON_OFFSET_POINT.

glGet with argument GL_POLYGON_OFFSET_FACTOR or GL_POLYGON_OFFSET_UNITS.
```

**Comment by zeffii** [comment]
hmmm.. we don't have acces to `glGet`

**Comment by zeffii** [comment]
so.. we use `bgl.glGetFloatV` , maybe

**Comment by zeffii** [comment]
```python
value = new <bgl.Buffer - type GL_FLOAT>
bgl.glGetFloatV(bgl.GL_POLYGON_OFFSET_FACTOR, value)
print(value)
```

**Pull request merged**
