### PR TITLE
fix #5036. node "Apply Vector Field" has a Gap if use circled curves

### LINKED ISSUE #5036: node "Apply Vector Field" has a Gap if use circled curves
Sverchok 1.3.0-Alpha, Blender 3.6.x, Windows 11

image

### PR DESCRIPTION
**Pull request by satabol**
fix #5036. Calc normals without out of surface with reverse directions of used vectors

Issue:
image

Fix:
image

File for tests:
[fix_5036_node_Apply_Vector_Field_has_a_Gap_if_use_circled_curves.v001.blend.zip](https://github.com/nortikin/sverchok/files/13199200/fix_5036_node_Apply_Vector_Field_has_a_Gap_if_use_circled_curves.v001.blend.zip)

Description of problem (short):
In the source algorithm calc points next to border of surface not on the border but step inside of surface. So this step of algorithm do a little gap on a finished mesh. So I put points in these places but reverse direction of vector that help calc normals then that vectors are reversed and got normals in border.

### CODE REVIEW

**Comment by satabol** [comment]
Hi @portnov . Can you see this PR?

**Comment by portnov** [comment]
General idea is sane, I used the same somewhere else. Though I did not check exact implementation, better to test.

**Comment by satabol** [comment]
Hi @portnov . I test many nodes that I found they used Surface Functions. It seams many of them look good except next nodes:
1. **16.  class SvBlendSurface(SvSurface)** and **22.  class SvReparametrizedSurface(SvSurface)** see #5038 
2. **17.  class SvConcatSurface(SvSurface)** and **18.  class SvCoonsSurface(SvSurface)**. Not found where they are used?

**Can you see tests?**

I append all these nodes to test file but some nodes need use swap, flip and other moves. Some tests are simple but some test is not simple. But I put test file here anyway: 
[fix_5036_node_Apply_Vector_Field_has_a_Gap_if_use_circled_curves.v002.blend.zip](https://github.com/nortikin/sverchok/files/13222096/fix_5036_node_Apply_Vector_Field_has_a_Gap_if_use_circled_curves.v002.blend.zip)


sverchok\utils\surface\algorithms.py
01.  class SvInterpolatingSurface(SvSurface):
02.  class SvDeformedByFieldSurface(SvSurface):
03.  class SvRevolutionSurface(SvSurface):
04.  class SvExtrudeCurveVectorSurface(SvSurface):
05.  class SvExtrudeCurvePointSurface(SvSurface):
06.  class SvExtrudeCurveCurveSurface(SvSurface):
07.  class SvExtrudeCurveFrenetSurface(SvSurface):
08.  class SvExtrudeCurveZeroTwistSurface(SvSurface):
09.  class SvExtrudeCurveTrackNormalSurface(SvSurface):
10.  class SvExtrudeCurveMathutilsSurface(SvSurface):
11.  class SvExtrudeCurveNormalDirSurface(SvSurface):
12.  class SvConstPipeSurface(SvSurface):
13.  class SvCurveLerpSurface(SvSurface):
14.  class SvSurfaceLerpSurface(SvSurface):
15  class SvTaperSweepSurface(SvSurface):
16.  class SvBlendSurface(SvSurface):
17  class SvConcatSurface(SvSurface):

sverchok\utils\surface\coons.py
18.  class SvCoonsSurface(SvSurface):

sverchok\utils\surface\core.py
19.  class SvSurfaceSubdomain(SvSurface):
20.  class SvFlipSurface(SvSurface):
21.  class SvSwapSurface(SvSurface):
22.  class SvReparametrizedSurface(SvSurface):
23.  class SvLambdaSurface(SvSurface):

sverchok\utils\surface\freecad.py
24.  class SvSolidFaceSurface(SvSurface):

sverchok\utils\surface\nurbs.py
25.  class SvNurbsSurface(SvSurface):

sverchok\utils\surface\primitives.py
26.  class SvPlane(SvSurface):

sverchok\utils\surface\rbf.py
27.  class SvRbfSurface(SvSurface):

sverchok\utils\surface\sphere.py
28. class SvEquirectSphere(SvSurface):
29. class SvLambertSphere(SvSurface):
30. class SvGallSphere(SvSurface):
31. class SvDefaultSphere(SvSurface):

**01.  class SvInterpolatingSurface(SvSurface)**
node 'Surface From Curves'. Look Good.
image

**02.  class SvDeformedByFieldSurface(SvSurface)**
node 'Apply Field To Surface'. Look Good.
image

**03.  class SvRevolutionSurface(SvSurface)**
node 'Revolution Surface'. Loog Good.
image

**04.  class SvExtrudeCurveVectorSurface(SvSurface)**
node 'Revolution Surface'. Look good
image

**05.  class SvExtrudeCurvePointSurface(SvSurface)**
node 'Extrude to Point'. Look good
image


**06.  class SvExtrudeCurveCurveSurface(SvSurface)**
**07.  class SvExtrudeCurveFrenetSurface(SvSurface)**
**08.  class SvExtrudeCurveZeroTwistSurface(SvSurface)**
**09.  class SvExtrudeCurveTrackNormalSurface(SvSurface)**
**10.  class SvExtrudeCurveMathutilsSurface(SvSurface)**
**11.  class SvExtrudeCurveNormalDirSurface(SvSurface)**
node 'Extrude Curve along Curve'. Loog good.
image

**12.  class SvConstPipeSurface(SvSurface)**
node 'Pipe Surface Along Curve'. Look Good.
image

**13.  class SvCurveLerpSurface(SvSurface)**
node 'Ruled Surface'. Look Good.
image

**14.  class SvSurfaceLerpSurface(SvSurface)**
node 'Surface Lerp'. **Look close to a good than to a bad**.
image

**15.  class SvTaperSweepSurface(SvSurface)**
node 'Taper Sweep Surface'. Look Good.
image

**16.  class SvBlendSurface(SvSurface)**
see #5038 
node 'Blend Surface'. Look Good.
image

**17.  class SvConcatSurface(SvSurface)**
Node not found. Where is it used???

**18.  class SvCoonsSurface(SvSurface)**
Node not found. Where is it used?

**19.  class SvSurfaceSubdomain(SvSurface)**
node 'Surface subdomain'. Look good.
image

**20.  class SvFlipSurface(SvSurface)**
node 'Flip Surface'. Look good
image

**21.  class SvSwapSurface(SvSurface)**
node 'Swap Surface'. Look good
image

**22.  class SvReparametrizedSurface(SvSurface)**
see #5038 
node 'Reparametrize Surface'. Look Good.
image

**23.  class SvLambdaSurface(SvSurface)**
node 'Surface Formula'. Look Good.
image

**24.  class SvSolidFaceSurface(SvSurface)**
node 'Solids->Solid Face (Surface)'. Look Good.
image

**25.  class SvNurbsSurface(SvSurface)**
node 'Nurbs Input'. Look Good
image

**26.  class SvPlane(SvSurface)**
node 'Plane (Surface)'. Look Good
image

**27.  class SvRbfSurface(SvSurface)**
node 'Minimal Surface'. Look Good
image

**28. class SvEquirectSphere(SvSurface)**
**29. class SvLambertSphere(SvSurface)**
**30. class SvGallSphere(SvSurface)**
**31. class SvDefaultSphere(SvSurface)**
node 'Sphere (Surface)'. Look Good.
image

**Comment by portnov** [comment]
> 17. class SvConcatSurface(SvSurface) and 18. class SvCoonsSurface(SvSurface). Not found where they are used?

SvConcatSurface is not used in any node, yet. There was an idea to create a node that can "glue" two surfaces together, similar to concatenating two curves. But it is not implemented yet. Currently such functionality can be achieved via scripted node.

SvCoonsSurface is used in "Surface from Boundary Curves".

**Comment by portnov** [comment]
About other tests — ok, looks good to me :)

**Pull request merged**
