### PR TITLE
Implement Fibonacci sequence node

### PR DESCRIPTION
**Pull request by portnov**
Shortly this was described in #517 as No.4.
Please review.

### CODE REVIEW

**Comment by zeffii** [comment]
github suggests there's a conflict, and this can't be merged automatically. If you fix it I'll accept the pull request for the fib node

**Comment by zeffii** [comment]
probably in `menu.py` I recommend never added a new item at the end of the list,. We could structure the list differently but it's just as easy to put the Item somewhere in the middle of the list.

**Comment by portnov** [comment]
I re-pushed it. Should work now.

**Comment by zeffii** [comment]
excellent, our apologies for this inconvenience.

**Pull request merged**
