### PR TITLE
follow active quad

### PR DESCRIPTION
**Pull request by Durman**
## Preflight checklist

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete.
- [x] Manual testing done. 
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
I think there should be some input to indicate which quad is active...

**Comment by Durman** [comment]
Yes, I slightly redone interface of the node.)

**Comment by Durman** [comment]
Possible unwrapping of a box, just with Sverchok nodes.

**Comment by Durman** [comment]
Unwrapping relatively to shape of map of active quad:

unwrap active quad

**Comment by Durman** [comment]
Supporting multiple active quads. Useful for unwrapping a mesh with disjointed parts.

**Comment by Durman** [comment]
I have added protection from re unwrapping faces. So it is possible to unwrap all disjoint parts of a mesh even without knowing exactly which indexes of faces related to each disjoint part.

Probably it would be useful to put button unwrap all (or more explicit name?) somewhere.

**Pull request merged**
