### PR TITLE
Number Node

### PR DESCRIPTION
**Pull request by zeffii**
- [x] hot-switch between Int and Float sockets
- [x] true Thru of input
- [ ] Auto int->float float->int casting of input (optional... not implemented initially)
- [x] add to `to3d` ( SvLayoutScanProperties )

ewwgif

### CODE REVIEW

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
ewwgif

**Comment by zeffii** [comment]
ewwgif

**Comment by nortikin** [comment]
min-max is great idea

**Comment by zeffii** [comment]
also now able to implement min/max for snlite sliders in the same way..

**Comment by zeffii** [comment]
i updated the image.. by separating the min/max sliders vertically it doesn't truncate the min/max numbers

**Comment by zeffii** [comment]
ewwgif

**Comment by zeffii** [comment]
image

**Pull request merged**
