### PR TITLE
Update color in/out nodes to use the new SvColorSocket type

### PR DESCRIPTION
**Pull request by DolphinDream**
Note: Further cleanup could have the ColorOut node socket use the default prop (use_prop) instead of the "unit_color", though in that case this node will have to rely on the SvColorSocket default color values for the prop.

### CODE REVIEW

**Comment by zeffii** [comment]
seen as the node is a beta implementation I encourage doing an `MK1` using the appropriate sockets and move the beta node to old nodes.

**Comment by DolphinDream** [comment]
Cool. I made MK1 color in/out nodes and moved the other ones to the “old nodes” (added them to __init__ btw). Is this the process for the old nodes or is there something else to be done about them ?

**Comment by DolphinDream** [comment]
I rebased this on latest master (after the #1847 was integrated, which includes the color socket type). 
If there are no objections we could probably integrate this into master as well.

**Comment by zeffii** [comment]
if new bl_idname , and old node is moved. .. then go for it :)

**Comment by portnov** [comment]
@DolphinDream @zeffii  hmm. For some reason I can't properly open blend files that were using old color nodes. Getting output like

```
2017-12-18 19:31:09,672 [INFO] root: Initializing Sverchok logging. Blender version 2.79 (sub 0), Sverchok version 0.5.9.6, branch master, commit c0a514c9
...
/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/node_tree.py:257
rna_uiItemR: property not found: Node.g_
```

Color nodes are red and not working. Something with loading old nodes?

**Comment by portnov** [comment]
Hmm. At second time it loaded, though 
```
Loaded SvColorsInNode. 1 nodes are left unregisted.
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/old_nodes/__init__.py", line 116, in register_old
    mod.register()
AttributeError: module 'sverchok-master.old_nodes.tools' has no attribute 'register'
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/core/handlers.py", line 114, in sv_post_load
    old_nodes.load_old(ng)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/old_nodes/__init__.py", line 105, in load_old
    unregister_old(bl_id)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/old_nodes/__init__.py", line 130, in unregister_old
    mod.unregister()
AttributeError: module 'sverchok-master.old_nodes.tools' has no attribute 'unregister'
Cannot find SvColorsInNode among old nodes
Loaded SvColorsInNode. 1 nodes are left unregisted.
Cannot find ToolsNode among old nodes
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/core/handlers.py", line 119, in sv_post_load
    upgrade_nodes.upgrade_nodes(ng)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/core/upgrade_nodes.py", line 156, in upgrade_nodes
    old_nodes.load_old(ng)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/old_nodes/__init__.py", line 105, in load_old
    unregister_old(bl_id)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/old_nodes/__init__.py", line 130, in unregister_old
    mod.unregister()
AttributeError: module 'sverchok-master.old_nodes.tools' has no attribute 'unregister'
```

...

**Comment by zeffii** [comment]
well.. i changed a few things in the old_node directory ( like automatic parsing of old nodes )  it's quite possibly not tested to exhaustion.

**Comment by zeffii** [comment]
sorry :)

**Comment by zeffii** [comment]
`class ToolsNode(bpy.types.Node, SverchCustomTreeNode)`

node has to register / unregister

**Comment by zeffii** [comment]
to be honest.. i think we could ignore that node entirely. (remove it.. or explicitely ignore it in 
`https://github.com/nortikin/sverchok/blob/master/utils/sv_oldnodes_parser.py`

**Comment by zeffii** [comment]
@portnov   https://github.com/nortikin/sverchok/commit/6626add23bf1b9b886422e10e41804c0dbaeb6cf

this is a unusable node anyway. maybe remove it.

**Pull request merged**
