### PR TITLE
Bevel Curve node.

### PR DESCRIPTION
**Pull request by portnov**
This is more or less an analog of standard Blender's "bevel a curve" functionality.
Taper object can be optionally provided.

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
Screenshot_20190609_151949
Screenshot_20190609_152524
Screenshot_20190609_153333

**Comment by portnov** [comment]
Screenshot_20190609_154344

**Comment by portnov** [comment]
Screenshot_20190609_163332

**Comment by portnov** [comment]
Screenshot_20190609_164709

**Comment by portnov** [comment]
Screenshot_20190609_183617
Screenshot_20190609_183728

**Comment by Durman** [comment]
Great node.))
I see we have our own mesh data structure now. :rocket:
I have asked before about using named tuple for vectors before. Zweffii says that this will slow down computation. Is it possible that with such data structure we can have similar effect?

**Comment by portnov** [comment]
Well, actually, it does...
But I think it's better to optimize this structure, than to have more verbose code in the node...

**Comment by Durman** [comment]
In the circumstances I think there is a point to start to talk about new socket - Mesh. It could decrease extra connections between nodes, and probably to decrease complexity for newcomers.

**Comment by portnov** [comment]
Well, that definitely goes to "after 2.8" milestone :)

**Comment by Durman** [comment]
And one more question about own class of mesh. Would not it be repeating of already existed Bmesh class of blender?

https://docs.blender.org/api/blender_python_api_current/bmesh.types.html#module-bmesh.types

**Comment by portnov** [comment]
Yes, it does partially repeat the same functionality. My hope was that, since my class implements only very basic functionality, it will be faster than bmesh (each method of bmesh is a call from python to C part of blender).
This hypothesis still requires confirmation from profiling results. Will check.

**Comment by portnov** [comment]
Checked: no, bmesh is actually faster. Will rewrite to bmesh.

**Comment by Durman** [comment]
I have extra question about Taper Verts socket. I haven't understood what data expected for running with scaling. I try to use radiuses of curve for scaling. Is it possible?

**Comment by zeffii** [comment]
ported just now, because i wanted to try it :)

**Comment by zeffii** [comment]
while bmesh structure is fast, it does not guarantee face/edge index consistency - and this is why we do not use that pervasively or as a first class socket.

**Comment by zeffii** [comment]
( i didn't port over the docs yet ..)

**Comment by Durman** [comment]
> This is more or less an analog of standard Blender's "bevel a curve" functionality.

It looks like more then less.))

**Comment by portnov** [comment]
@Durman , it expects a curve elongated along the orientation axis (for example, Z, if your bevel object is in XY).
List of radiuses is not enough, since it is not known which Z coordinate corresponds to which radius.

**Comment by Durman** [comment]
<details> 
  <summary>node tree</summary>  



</details>

bevele curve node

**Comment by zeffii** [comment]
image

**Comment by Durman** [comment]
Using f-curve for scaling

**Comment by nortikin** [comment]
it will work with SN toe node generator

**Pull request merged**
