### PR TITLE
B28 mirror lite

### PR DESCRIPTION
**Pull request by zeffii**
adds new mirror lite 
image

### CODE REVIEW

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
image

this mostly does what i need in a mirror node, but boy is it fussy / unpredictable. 

makes it very tempting to take a different approach. @portnov

**Comment by zeffii** [comment]
wow. `bmesh.ops.symmetrize` , does all of this stuff in one operation.

**Comment by zeffii** [comment]
image

it always mirrors over the Origin.

**Comment by zeffii** [comment]
i think anymesh that results in ngons during this operation, will have disparate normals on those faces. I'm not sure if this is an artifact of the symetry algorithm, or the VD experimentals mandatory tesselation of anything non `tri`.

the recalc normal doesn't seem to help

**Comment by portnov** [comment]
Suggestions:
* Rename this to "mirror mk2"
* For symmetrize functionality, I'll create a separate node.

**Comment by zeffii** [comment]
OK. the end product of this node (in it's current state) i'll rename SvSymmetry.

perhaps the earlier state of the node (where matrix socket was still enabled) would indeed be appropriately named Mirror.

**Comment by portnov** [comment]
I'm going to overtake this theme and develop two nodes - "symmetrize" and "mirror". @zeffii hope you don't mind? :)

**Comment by zeffii** [comment]
be my guest @portnov

**Comment by portnov** [comment]
symmetrize_1

**Comment by portnov** [comment]
symmetrize_3

**Comment by portnov** [comment]
Continued in #2741

**Pull request closed without merging**
