### PR TITLE
small upgrades

### PR DESCRIPTION
**Pull request by zeffii**
fixing some things that annoy me most

- [x] add `bpy` to locals
- [x] add `self.user_filename`  (the ui will show `filename: [.........]` )
- [x] add new directive `filehandler / fh` to allow convenient user driven text-file loading.
- [x] auto inject output list variable names
- [ ] resolve the .blend reload resetting the node's parameters.

### CODE REVIEW

**Comment by zeffii** [comment]
cool, this works now..
```
"""
in param1 s d=0.2 n=2
in param2 s d=0.2 n=2
out verts v
fh
"""
verts.append([])

print(self.user_filename)
verts[0].append([(param1*i, param2*i, i) for i in range(10)])

```

**Comment by kalwalt** [comment]
@zeffii Cool! I want to try this!

**Comment by zeffii** [comment]
i'll fix the slider values issue in a new branch..   maybe

**Comment by kalwalt** [comment]
so `inject` is not needed anymore in the header of the script for the `vectorize` func? we can just add `fh`?

**Comment by zeffii** [comment]
directives:
```text
fh:    makes a filehandler / stringproperty / prop_search
inject:    inserts the variable 'parameters'
```
they're separate directives @kalwalt . vectorize doesn't need to be imported anymore, but you do need to state `vectorize(parameters)`.

**Comment by kalwalt** [comment]
@zeffii now i get the difference. i think ScriptNode lite is becoming better.

**Comment by zeffii** [comment]
I haven't used SN1 since SNLite hit master :)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1310

**Comment by kalwalt** [comment]
self_filename_test
It works, tested with a script that i'm developing for importing .ter (terragen) files into blender and sverchok.

**Comment by zeffii** [comment]
: D

**Pull request merged**
