### PR TITLE
Mask from index node

### PR DESCRIPTION
**Pull request by Kosvor2**

### CODE REVIEW

**Comment by Kosvor2** [comment]
index_mask2

**Comment by zeffii** [comment]
```diff
- bl_label = 'SvIndexToMaskNode'
+bl_label = 'Index To Mask'
```

**Comment by zeffii** [comment]
instead of vert-poly mask , call it `topo mask`  : )

**Comment by zeffii** [comment]
please write some docs for it.. i'm not sure i appreciate the extra complexity of datamasking toggle and vert-poly toggle.   or images :)

**Comment by zeffii** [comment]
@Kosvor2 

http://stackoverflow.com/questions/33101207/efficiently-filling-numpy-array-using-lists-of-indices

**Pull request merged**
