### PR TITLE
Verts as matrices

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
The only problem i see with that is that some nodes still use `SvGetSocket` directly.. maybe this will force a more complete push-through of the `sv_get`  @ly29

**Comment by ly29** [comment]
@zeffii 
I find one any references to ```SvGetSocket``` or ```SvSetSocket``` outside base system.
However many use the older interface of ```SvGetSocketAnyType``` and ```SvSetSocketAnyType```

```python
def SvGetSocketAnyType(self, socket, default=None, deepcopy=True):
    out = SvGetSocket(socket, deepcopy)
    if socket.is_linked:
        return SvGetSocket(socket, deepcopy)
    elif default:
        return default
    else:
        raise LookupError

def SvSetSocketAnyType(self, socket_name, out):
    SvSetSocket(self.outputs[socket_name], out)
```
However here we could just redirect to ```sv_get``` anyway....

```python
def SvGetSocketAnyType(node, socket, default=None, deepcopy=True):
    return socket.sv_get(default=default, deepcopy=deepcopy)

def SvSetSocketAnyType(node, socket_name, data):
    node.outputs[socket_name].sv_set(data)
```

**Comment by ly29** [comment]
120 hits for ``SvGetSocketAnyType``` which is trivial but boring.

**Comment by zeffii** [comment]
> I find one any references to SvGetSocket or SvSetSocket outside base system.
However many use the older interface of SvGetSocketAnyType and SvSetSocketAnyType

i probably confused the two function names then, i think the point still stands because there's an extra level of indirection. 

Nonetheless, a trivial matter if we really want to settle this code.

**Comment by ly29** [comment]
Yeah it would be extra level redirects but the advantage is that we would have one true interface, and behind one implementation instead of two interfaces. 
But best would be to kill the extra interface directly of course.

**Comment by enzyme69** [comment]
What is exactly Verts as Matrices?

**Comment by zeffii** [comment]
@enzyme69  using a vertex list / lists as if it were a Matrix list. A Vector can be transformed into a Matrix, that carries only Location information.

part of this thread ( with visual examples ) https://github.com/nortikin/sverchok/issues/1060

**Comment by ly29** [comment]
Interpreting vertices as location for matrix, skipping the matrix node when you only use location, which seems to be the most common use case

**Comment by zeffii** [comment]
image

right now it says  Matrix 1 , but i've changed it to indicate the number of stored matrices.

**Comment by zeffii** [comment]
maybe a `data_structure_helper` module is appropriate, i don't feel OK just adding these helper functions into the `data_structure` file.

**Comment by zeffii** [comment]
maybe a `data_structure_helper` module is appropriate, i don't feel OK just adding these helper functions into the `data_structure` file.

But .. there's quite an eclectic mix of functionality in the data_structure file.. so maybe no harm?

**Comment by ly29** [comment]
Make a ```socket_helper``` file in core and move all socket/data storage functionality into there perhaps except the old interface.
```data_structure``` should be dismanteled bit by bit I think but this is a different task.

**Comment by zeffii** [comment]
right on.

**Comment by ly29** [comment]
it is a bit obfuscated but quite simple system.

**Comment by zeffii** [comment]
am leaning towards getting the verts2matrix to master before doing too much to `data_structure`..

**Comment by ly29** [comment]
That sounds sane

**Comment by zeffii** [comment]
forcing `deepcopy=False` for this operation btw. else we'll get unintended geometry :)

**Comment by zeffii** [comment]
i haven't tried running the last 4 commits yet..but logic looks sound. hooking them up later

**Comment by zeffii** [comment]
image

**Comment by ly29** [comment]
Having looked things over I some reorganisation is sane

The test for the other socket should be moved into the class definition for sockets with ```cross_test_socket``` into the base class and using them into the relevant class. 

Also, even if no solution is found now - as definitely not a show stopper, some thought of how this could support proper OO code would be good. Refactor of ```.sv_get``` into a base case and use ```super()```. This is perhaps better left for later actually.

I for pushing this into master and getting it tested.

**Comment by zeffii** [comment]
I have more issues with this, but doing docs for easing now.

of course the socket cross over stuff should be part of the socket interface, i see this implementation more as experimental prior to the design phase.

**Comment by zeffii** [comment]
i'd be happy to push but to make the user aware that crossover connections will remain in a state of flux for a while. behaviour may change (un-nesting automatically etc)

**Comment by Durman** [comment]
I do not see sense to wright two figures in socket labels. In the particular case number of matrixes can be either two or five but not both simultaneously.

**Comment by zeffii** [comment]
it's not 51. zoom in.  the number to the right is the combined count of all internal vectors

image

**Comment by zeffii** [comment]
that's 3 years ago, i don't remember exactly why that convention was settled on, but i find it useful for the following reason:
it's useful to see the number of 'container' lists represented in the socket without having to navigate to the origin of a socket.

i don't consider this broken, but maybe under-documented is a fair assessment.

**Pull request merged**
