### PR TITLE
Move dependencies and nodes from Sverchok-Extra

### PR DESCRIPTION
**Pull request by portnov**
After this PR, the only remaining nodes in Sverchok-Extra will be the most questionable (ones that are too slow or too fragile etc). So, Sverchok-Extra can become a sort-of playground for Sverchok: if you are thinking about a node, which is too complex to be a scripted node, but too experimental to be in core Sverchok, put it into Sverchok-Extra.

This PR is supposed to work with "sverchok_move_2" branch of sverchok-extra repo.

## Work plan for this PR

* [x] Move infrastructure
* [x] Move nodes
* [x] Support dummy nodes
* [x] Test that everything works, more or less
* [x] Rename SvEx classes to Sv where it will not break compatibility (which means nodes will remain SvEx).
* [x] Add some code documentation
* [x] Nodes documentation (more or less):
  * [x] Curve category
  * [x] Surface category
  * [x] Field category
  * [x] Former Spatial category
  * [x] Exchange category
  * [ ] Ladybug category - will delegate to @vicdoval  :)
* [x] Nodes icons (more or less)

## Work to be done after this is merged

* Update readmes and wikis and docs of both Sverchok and Sverchok-Extra about the new state of things
* #3385, #3386.

## Moved nodes

The following nodes are moved:

* *Curve* category:
  * RBF (interpolation) Curve (uses [SciPy][4])
  * Catenary Curve (uses [SciPy][4])
  * NURBS Curve (uses [Geomdl][3] library)
  * NURBS Interpolation Curve (uses Geomdl library)
  * NURBS Approximation Curve (uses Geomdl library)
  * Circlify (pack a set of circles into another circle) (uses [Circlify][15] library)
  * Marching Squares (uses [Scikit-Image][5] library)
  * Intersect Curve with Plane (uses [SciPy][4])
  * Orthogonal Projection onto Curve (uses [SciPy][4])
  * Nearest Point on Curve (uses [SciPy][4])
  * Approximate Bezier Curve (uses [SciPy][4])
  * Curve Extremes (uses [SciPy][4])
  * Interpolate Frame on Curve
* *Surface* category:
  * NURBS Surface (uses Geomdl)
  * NURBS Interpolation Surface (uses Geomdl)
  * NURBS Approximation Surface (uses Geomdl)
  * Quads to NURBS (uses Geomdl)
  * Minimal Surface (uses SciPy)
  * Minimal Surface from (closed) Curve (uses SciPy)
  * Curves to Surface (optionally uses SciPy and/or Geomdl)
  * Marching Cubes (optionally uses either [PyMCubes][8] or [Scikit-Image][5]; has slower implementation in pure Python)
  * Nearest Point on Surface (uses SciPy)
  * Raycast onto Surface (uses SciPy)
  * Raycast onto Implicit Surface (scalar field iso-surface) (uses SciPy)
  * Orthogonal Projection onto Surface (uses SciPy)
* Former *Spatial* category of Sverchok-Extra => Modifier Make category of Sverchok:
  * Voronoi 3D (uses SciPy)
  * Spherical Voronoi (uses SciPy)
  * Delaunay 3D (uses SciPy)
* *Field* category (please refer to the [wiki page][11] about used concept of the field; most of these nodes do not use external libraries, except for numpy):
  * Mesh Nearest Normals Field (optionally uses SciPy)
  * RBF Scalar Field (uses SciPy)
  * RBF Vector Field (uses SciPy)
  * Scalar Field Graph (uses [Scikit-Image][5])
  * Surface Extremes (uses SciPy)
* *Exchange* category:
  * NURBS In (input Blender's NURBS curve or surface objects into Sverchok tree)
  * NURBS to JSON (uses Geomdl to represent NURBS surfaces or curves in JSON format which can be converted to Rhino's `3dm` by [rw3dm][12]
  * JSON to NURBS (uses Geomdl to read NURBS surfaces or curves from the same JSON format)
* *Ladybug** category (use Ladybug package):
  * Location
  * Sun position

## Remaining nodes

The following nodes remain in Sverchok-Extra for the time being:

* Intersect Surface with Plane — too young and fragile, usable only for small number of cases
* Surface Curvature Lines — reasons described in #3243
* Implicit Surface Solver: the algorithm itself is questionable. What this node does is takes a starting point and then tries to find a point, which lies on implicit surface (iso-surface of scalar field), by using some sort of Newtonian equation solving algorithm. So in many cases it will find nearest point on the implicit surface to the given point. But there are also cases when the point will not be nearest.
* Smooth Bivariate Spline. Questionable node.
* Vector Field Lines on a Surface (uses SciPy). Questionable node.

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

[1]: http://blender.org
[2]: https://github.com/nortikin/sverchok
[3]: https://onurraufbingol.com/NURBS-Python/
[4]: https://scipy.org/
[5]: https://scikit-image.org/
[6]: https://pypi.org/project/pip/
[7]: https://cython.org/
[8]: https://github.com/pmneila/PyMCubes
[9]: https://nurbs-python.readthedocs.io/en/latest/install.html
[10]: https://github.com/portnov/sverchok-extra/archive/master.zip
[11]: https://github.com/portnov/sverchok-extra/wiki/Fields
[12]: https://github.com/orbingol/rw3dm
[13]: https://bootstrap.pypa.io/get-pip.py
[14]: https://pip.pypa.io/en/stable/installing/
[15]: https://github.com/elmotec/circlify
[16]: https://en.wikipedia.org/wiki/Differentiable_curve#Frenet_frame

### CODE REVIEW

**Comment by portnov** [comment]
Screenshot_20200708_220123

**Comment by portnov** [comment]
Screenshot_20200709_193707

**Comment by portnov** [comment]
Screenshot_20200709_202328

**Comment by portnov** [comment]
Screenshot_20200709_203748

**Comment by portnov** [comment]
Screenshot_20200710_002809

**Comment by portnov** [comment]
Screenshot_20200711_181528

**Comment by portnov** [comment]
Screenshot_20200711_223520
Screenshot_20200711_224355

**Comment by portnov** [comment]
Screenshot_20200711_234314

**Comment by portnov** [comment]
Screenshot_20200712_113856

**Comment by portnov** [comment]
Screenshot_20200712_145806

**Comment by portnov** [comment]
Screenshot_20200712_161246

**Comment by portnov** [comment]
Screenshot_20200712_184801

**Comment by portnov** [comment]
Screenshot_20200712_205006

**Comment by portnov** [comment]
Screenshot_20200713_002437

**Comment by portnov** [comment]
Screenshot_20200715_222202

**Comment by portnov** [comment]
Screenshot_20200715_230325

**Comment by portnov** [comment]
Well, I consider this (more or less) ready. @zeffii @vicdoval maybe someone wants to do a review or testing before merge? :)

**Comment by zeffii** [comment]
it's epic work @portnov  .  plenty to learn from

**Comment by vicdoval** [comment]
Awesome work @portnov, thanks!
I have seen you have moved import/export  solid nodes out of the "Solids" category... that makes them move out from the "Solids menu" ... i guess they can be placed again in the menu with some tweaks (right now the menu is created from the  category and the `solid_catergory` attribute) but I'm not sure is a good idea to move them out of the Solids category .

Another approach would be mixing the "Exchange" category with the "Network" category (where I placed the "File Path" node).

Minor thoughts compared to your great work...

**Comment by vicdoval** [comment]
As the branch was created before #3396 the search menu is not working when there are missing dependencies... it will work when you merge the PR but in case you wanted to know :)

**Comment by portnov** [comment]
Well, I'm merging this. @vicdoval feel free to rearrange categories the other way in a separate PR.

**Pull request merged**
