### PR TITLE
Make new branch for Text IO node fixes

### PR DESCRIPTION
**Pull request by zeffii**
- [x] fix Text In to accept parenthesised Data 
- [x] fix Text In Selected File name to use prop_search + string instead of EnumProperty
- [x] fix Text Out Selected File name to use prop_search + string instead of EnumProperty

### CODE REVIEW

**Comment by portnov** [comment]
Huh. Maybe one wants to output log directly to 3D scene? :)

**Comment by zeffii** [comment]
realllly ? ok...

**Comment by portnov** [comment]
Just kidding :) Though I would not be very surprised if saw something like this in enzyme69's videos :)

**Comment by zeffii** [comment]
that's like world record running backwards 100m. absolutely no point, other than " look mom, backwards "

**Comment by zeffii** [comment]
..but i'll try not to be too judgemental.

**Comment by zeffii** [comment]
(thinning out thread)

```python
>>> import ast
>>> test = "([[0,1,2],[3,4,5]],)"
>>> ast.literal_eval(test)
([[0, 1, 2], [3, 4, 5]],)

```

didn't think this was the problem..but this is some proof. problem is elsewhere.

**Comment by zeffii** [comment]
oh....LOL
```python
        if isinstance(data, list):
            self.list_data[n_id] = data
            self.use_custom_color = True
            self.color = READY_COLOR
            self.current_text = self.text
        else:
            self.use_custom_color = True
            self.color = FAIL_COLOR
```

**Comment by zeffii** [comment]
now, let's see what kind of minefield lies ahead

**Comment by zeffii** [comment]
@nortikin @portnov  i'm not super happy with how this is solved, but it does seem to allow us to avoid moving to a MK2 of Text Out..  Which i think is good because the node was "broken" anyway.

**Comment by zeffii** [comment]
we can't just 
```diff
- text = EnumProperty(....................)
+ text = StringProperty(.....)
```
existing blends that use Text Out will open with an exception and self.text will be an empty String.

**Comment by portnov** [comment]
Do I understand correctly that the dummy value is used to mark node as already upgraded? Ok, not very nice, but not so bad for as for me.

**Comment by zeffii** [comment]
yeah, that's what it comes down to (this marks that it's upgraded). I could name the variable/string better before pushing... maybe i should.. i hadn't thought of naming it properly. like "TEXT_IN_UPGRADE_TOKEN" or something.

else.. it needs to be a MK2.. unless you have a more down to earth idea.

**Comment by zeffii** [comment]
i have not yet io/json tested this..

.. i fear it will need an MK2 anway..

**Comment by portnov** [comment]
#1959

**Comment by zeffii** [comment]
trying to load Text IO saved in `master` , into blender / sverchok with `TextIO_Fixes` branch, results in this sequence of errors. Not hard to fix..

i am just recording them here as a reminder.

```python
2017-12-21 14:01:44,517 [ERROR] sverchok.utils.sv_IO_panel_tools: 'bpy_prop_collection[key]: key "" not found'
Traceback (most recent call last):
  File "\sverchok\utils\sv_IO_panel_tools.py", line 606, in add_nodes
    add_node_to_tree(nodes, n, nodes_to_import, name_remap, create_texts)
  File "\sverchok\utils\sv_IO_panel_tools.py", line 593, in add_node_to_tree
    apply_post_processing(node, node_ref)
  File "\sverchok\utils\sv_IO_panel_tools.py", line 550, in apply_post_processing
    node.load()
  File "\sverchok\nodes\scene\text.py", line 283, in load
    self.load_sv()
  File "\sverchok\nodes\scene\text.py", line 432, in load_sv
    self.load_sv_data()
  File "\sverchok\nodes\scene\text.py", line 448, in load_sv_data
    f = bpy.data.texts[self.text].as_string()
KeyError: 'bpy_prop_collection[key]: key "" not found'
2017-12-21 14:01:44,556 [ERROR] sverchok.utils.sv_IO_panel_tools: 'bpy_prop_collection[key]: key "Text out" not found'
Traceback (most recent call last):
  File "\sverchok\utils\sv_IO_panel_tools.py", line 657, in make_links
    ng.links.new(*resolve_socket(*link, name_dict=name_remap))
  File "\sverchok\utils\sv_IO_panel_tools.py", line 649, in resolve_socket
    ng.nodes[t_node].inputs[to_socket])
KeyError: 'bpy_prop_collection[key]: key "Text out" not found'
2017-12-21 14:01:44,564 [ERROR] sverchok.utils.sv_IO_panel_tools: bpy_prop_collection[index]: index 0 out of range, size 0
Traceback (most recent call last):
  File "\sverchok\utils\sv_IO_panel_tools.py", line 657, in make_links
    ng.links.new(*resolve_socket(*link, name_dict=name_remap))
  File "\sverchok\utils\sv_IO_panel_tools.py", line 648, in resolve_socket
    return (ng.nodes[f_node].outputs[from_socket],
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0
2017-12-21 14:01:44,571 [ERROR] sverchok.utils.sv_IO_panel_tools: failed total: 2
2017-12-21 14:01:44,577 [ERROR] sverchok.utils.sv_IO_panel_tools: [['Circle', 0, 'Text out', 0], ['Text in', 0, 'Viewer Draw', 0]]
```

**Comment by zeffii** [comment]
on second thoughts.. i think MK2 for these nodes is the way to go. In conjunction with splitting them up into two separate files. Any common structures could make it into a `/utils/sv_text_io_helpers` .

**Pull request closed without merging**
