### PR TITLE
Pulga Physics Node

### PR DESCRIPTION
**Pull request by vicdoval**
From its docs :D
> This node creates simulations from input parameters, it is meant to be used in form-finding purposes.
> It creates the simulation using the inputed vertices as spheric particles that react to applied forces.
> The node is a basic NumPy implementation of basic physics system heavily inspired in "The Nature of Code" by Daniel Shiffman and the Kangoroo Plugin for Grasshopper. Due the nature of the algorithm it can get very intensive, handle with responsibility...

Pulga Physics
Pulga Physics
Pulga Physics
Pulga Physics
Pulga Physics Example
tensileCover
attractorsField
catenary_modeling
reactionsOnPins

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [x] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
Hello.
Wow! :)

* where is pulga_physics_core  module? was it merged before?
* am I correct that this module implements physics by itself, and does not rely on external libraries?
* Maybe it is possible to split such a big node into several? It would be easier to create different combinations of effects.

**Comment by vicdoval** [comment]
Thanks @portnov!

_ I added the pulga_physics_core  to sverchok/utils mainly to split the code between UI and the calculation process.
It has never been published or merged before anywhere :)

_ You are right, this module implements physics only relying in NumPy.

_ Many smaller nodes could came out of this node by taking out features but they wouldn't be able to produce the same results by mixing them (that's why I added the top toggles, so the user can choose between the features combination).
It could be splitted with a bunch of new socket types in to a set of dedicatted nodes connected to a main one. This approach could be interesting... maybe for the 2.8...

**Comment by zeffii** [comment]
superb! i look forward to using it.

**Comment by nortikin** [comment]
ahaha!!!
Much of fun ahead.

**Comment by vicdoval** [comment]
It was ported to 2.8 in https://github.com/nortikin/sverchok/pull/2299/commits/d11ca09476b430190944ee4cc68afc72b269529c :)

**Pull request merged**
