### PR TITLE
GP Node Push 2

### PR DESCRIPTION
**Pull request by zeffii**
the less talking happens on this pull request, the faster it will be completed.

### CODE REVIEW

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
my experience shows that GP is unstable when controller dynamically, expect many occurrences of Blender closing to the desktop without warning.

**Comment by nortikin** [comment]
i think it is from creating new layers for GP

**Comment by zeffii** [comment]
currently it doesn't create new layers, only strokes.  (add / removes  / update strokes )

**Comment by zeffii** [comment]
seen as it's not possible to get the Layername, from the Stroke..in `strokes`, (not even using strokes.id_data - which just returns the GP name (like id_data returns the NodeTree, not the node )

**Comment by zeffii** [comment]
a slight redesign is needed. It will look more like the other viewers i think..

**Comment by zeffii** [comment]
this will not be the PR..

**Pull request closed without merging**
