### PR TITLE
Faster Box node

### PR DESCRIPTION
**Pull request by vicdoval**
Faster implementation of the box node, 
Old: create a cube and bisect it
New: creates 6 planes, and remove doubles.

For 50x50x50 is over 3 times faster. For 100x100x100 is over 6 times faster

Added vectorization, list matching modes, origin selection and a Matrix input.

change  

change  

Also a simplify property to join the boxes, flat the output or leave at multi-object level
change  

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [x] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by vicdoval** [comment]
I am not sure of how to proceed with the two failed tests... any idea @portnov?

**Comment by portnov** [comment]
@vicdoval did you try it without use of bmesh at all? At a first glance it seems to be overkill (yes, initial implementation was super-overkill). I'd suggest to try to calculate vertices with numpy.linspace + numpy.meshgrid, and then write an algorithm to calculate edges and faces indices (it would not be that easy, you'll have to calculate all indices by some formulas like `i*n+j` etc, but that would allow to not to use any structures like maps/dicts/bmeshes/etc, so no storage room and no lookups). At a first glance, I'd say that should be faster... But I may be wrong...

**Comment by zeffii** [comment]
i'd also like to see a numpy implementation.

**Comment by zeffii** [comment]
flashbacks:  https://github.com/nortikin/sverchok/issues/494

**Comment by zeffii** [comment]
recode as snlite
```python
"""
in size s d=1.0 n=2
in divx s d=10 n=2
in divy s d=10 n=2
in divz s d=10 n=2
out verts v
out faces s
"""

import numpy 
import itertools

def make_verts(size, divx, divy, divz):
    size /= 2
    sidex = numpy.linspace(-size, size, divx)
    sidey = numpy.linspace(-size, size, divy)
    sidez = numpy.linspace(-size, size, divz)
    plane = lambda z: [(x, y, z) for x in sidex[1:-1] for y in sidey[1:-1]]
    
    base = plane(-size)
    top = plane(size)
    mid = []
    add_mid = mid.append

    for z in sidez:
        # side 1 
        for y in sidey:
            add_mid(tuple((sidex[0],y,z)))
        # side 2
        for x in sidex[1:-1]:
            add_mid(tuple((x,sidey[-1],z)))
        # side 3
        for y in sidey[::-1]:
            add_mid(tuple((sidex[-1],y,z)))
        # side 4
        for x in sidex[1:-1][::-1]:
            add_mid(tuple((x,sidey[0],z)))
    return [(mid + base + top)][0]


def roll_around(direction, outside, inside, divx, divy, num_iplanar):
    final_list = []
    final_list.append(outside[0:divy])

    stride = divy-2
    for idx, i in enumerate(range(0, num_iplanar, stride)):
        side1 = outside[-(idx+1)]
        side2 = outside[divy+idx]
        final_list.append([side1] + inside[i:i+stride] + [side2])

    opposite = divy + (divx-2)
    final_list.append(outside[opposite:opposite+divy][::-1])

    face_list = []
    for i in range(divx-1):
        for j in range(divy-1):
            top_row = final_list[i][j:j+2]
            low_row = [final_list[i+1][j+1], final_list[i+1][j]]
            storage = top_row + low_row
            if direction == 'ccw':
                storage = storage[::-1]
            face_list.append(storage)
    return face_list

def make_faces(size, divx, divy, divz):
    z_spread = (divx+divx+divy+divy) - 4
    faces = []
    idx = 0
    
    # per z ring, loop and closing extend
    for z_ring in range(divz-1):
        offset = z_spread * z_ring
        for idx in range(z_spread-1):
            i = idx + offset
            faces.extend([[i, i+1, i+1+z_spread, i+z_spread]])

        faces.extend([[
            z_spread - 1 + offset, 
            offset, 
            z_spread + offset, 
            z_spread + z_spread -1 + offset
            ]])

    top_max = divz * z_spread
    top_outer_ring = list(range(top_max-(z_spread), top_max))
    bottom_outer_ring = list(range(0, z_spread))

    # num internal planar
    num_iplanar = (divx-2) * (divy-2)

    # book keeping        
    num_verts_bass = divx * divy
    num_verts_ring = len(top_outer_ring)
    num_verts_ring_total = (divz - 2) * num_verts_ring
    last_vertex_idx = (num_verts_bass * 2) + num_verts_ring_total

    top_internal = list(range(last_vertex_idx-num_iplanar, last_vertex_idx))
    bottom_internal = [i-num_iplanar for i in top_internal]

    f = roll_around('cw', top_outer_ring, top_internal, divx, divy, num_iplanar)
    faces.extend(f)

    f = roll_around('ccw', bottom_outer_ring, bottom_internal, divx, divy, num_iplanar)
    faces.extend(f)
    
    return faces

verts.append(make_verts(size, divx, divy, divz))
faces.append(make_faces(size, divx, divy, divz))
```

**Comment by vicdoval** [comment]
You were right, i'm working on the numpy implementation, and is over 10 times faster than the bmesh implementation and over 30 times faster than the actual overkill method. Numpy rules :rocket:

**Comment by vicdoval** [comment]
With a box 100 x 100 x 100 (divisions)
Box mk1 2.800 seconds
Box mk2 0.088 seconds

Box mk2 output Numpy 0.003 seconds.... I hope one day this will be the default

**Comment by enzyme69** [comment]
Took me a while to realize there is that Matrix In node and all the vectorization you added... Vic, you are genius~

**Pull request merged**
