### PR TITLE
Callback reshuffle

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
this will be interesting.

**Comment by zeffii** [comment]
@kalwalt @ly29 

image

**Comment by zeffii** [comment]
handled by this
```python

class SvTextureViewerDirSelect(bpy.types.Operator, SvGenericDirectorySelector):
    """ Pick the directory to store images in """
    bl_idname = "node.sv_texview_dirselect"
    bl_label = "Pick directory"

```

**Comment by zeffii** [comment]
@kalwalt  

whenever you want to pass extra parameters to 
```python
def save_bitmap(self, operator):
```
like `alpha` , either make `alpha` a property of the node , so you can do `self.alpha` inside the function,  or pass it as a property to the operator
```python
op = rightside.operator(callback_to_self, text="Save").fn_name = "save_bitmap"
op.alpha = False
```
remember to add `alpha` as a bpy.props.BoolProperty to 
```python
class SvTextureViewerOperator(bpy.types.Operator, SvGenericCallbackWithParams):
    """ Save the image with passed settings """
    bl_idname = "node.sv_texview_callback"
    bl_label = "Execute a function on the calling node"

    alpha = bpy.props.BoolProperty()   # < --- this sucker

```

**Comment by zeffii** [comment]
hope i didn't screw up anything there.

**Comment by ly29** [comment]
The end result will be saner

**Pull request merged**
