### PR TITLE
Fcurve sampler

### PR DESCRIPTION
**Pull request by zeffii**
slightly botchy fcurve sampler :)

several modes for this..(the node auto detects)

- default:  one value (take frame number, or if unconnected input..use `bpy.context.scene.current_frame`)
- multi_sample: take a sequence (a range, or ranges) and generate the evaluated range (or ranges)

### CODE REVIEW

**Comment by zeffii** [comment]
state 1 , single frame or current frame
image

state 2: multiple frames, including subframe
image

**Comment by zeffii** [comment]
right now it only samples fcurves[0]  , which is probably whichever kind of property you first set keyframes for. In the example image above that's Location of `[Object Action]`

**Comment by zeffii** [comment]
@durman test it.

it wont work is a json/gist because it assumes scene data

**Comment by zeffii** [comment]
it could also accept custom properties, rather than hijacking a location keyframe. Maybe an enum between `Default |  custom` .
 - where default expects location keyframes, and either xyz  
 - and custom takes a float property (so no array_index needed)

**Comment by Durman** [comment]
looks working

fcurve


But if object hasn't any actions we have got an error. :/
```Python
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\ad
dons\sverchok-fcurve_sampler\nodes\scene\FCurve_in.py", line 42, in draw_buttons

    action = bpy.data.objects[self.object_name].animation_data.action
AttributeError: 'NoneType' object has no attribute 'action'
```

Also what do you think about UI like choosing material of Bmesh weaver?

I am positive that we can want to use many instances of f-curve and it can be a bit confusing to use index only. List could feature all actions that an object has and with plus button we can create custom property with key on the first frame. I think it can become easier for newcomers to sort out in this node.

Also I noticed that it is possible to hide object and still have f-curve available for editing with pressed this button.

**Comment by Durman** [comment]
fcurve test

**Comment by Durman** [comment]
F-curve has loads of interesting modifiers ))

**Comment by Durman** [comment]
fcurve test3

**Comment by zeffii** [comment]
thanks for testing @Durman  yeah, the UI isn't sorted out yet :)

error handling and UI tweaks will come soon.

**Comment by zeffii** [comment]
the simplest solution to "picking objects that don't have animation data / keyframes" @Durman  is to add a button that adds a location keyframe (standard property)

it's maybe worth going with that option first, because adding keyframes for a custom ID property has wasted an hour of my time already.

**Comment by zeffii** [comment]
regarding the UI ugliness of picking an array index.. well i agree, named property selection would be awesome. Just the code is a little bit more boring/involved at this early stage.

**Comment by zeffii** [comment]
image

**Pull request merged**
