### PR TITLE
return back 'prop' attribute of vector socket

### PR DESCRIPTION
**Pull request by Durman**
## Addressed problem description

https://github.com/nortikin/sverchok/pull/3507#issuecomment-689675989

### CODE REVIEW

**Comment by Durman** [comment]
@portnov Can you check the branch on your old layouts?

**Comment by portnov** [comment]
I tried with the file I attached earlier. In GUI, the node looks like it remembers the correct value, but the node does not see it, it receives (0,0,0) from sv_get().

**Comment by portnov** [comment]
@Durman as far as I understand, the problem is that old implementation stores the property value in the *node* object, while your new implementation works with properties of *sockets*...

**Comment by Durman** [comment]
No. The problem is that I renamed this property. I forgot about sv_get, will fix.

**Comment by Durman** [comment]
@portnov Now should work

**Comment by portnov** [comment]
Yes, works for me.

**Comment by portnov** [comment]
@Durman it seems setting the default value of such property in `sv_init` still does not work :/ Nodes are created with (0,0,0) as default value.

**Comment by Durman** [comment]
I hope that now it will work as expected.

**Pull request merged**
