### PR TITLE
Texture Displace (Displace Modifier)

### PR DESCRIPTION
**Pull request by vicdoval**
image
and his little companion Texture Evaluate
image

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
Uh. In skimage, there is a function to find contour (iso-lines) in images (they can be extracted as blender curve meshes and filled if you wish). Do you think such feature would be useful for textures? If yes, I'll put it on my todo for sverchok-extra :)

**Comment by vicdoval** [comment]
@portnov I think that function can be very useful in many cases, vectorizing an image for example or to create crazy topologies 😄

**Comment by portnov** [comment]
Could you place "color_channels" enum into some module under `sverchok.utils`? Maybe some other functions too, but I'm not so sure about them...

**Comment by portnov** [comment]
@vicdoval Probably I'm mistaken... but as far as I understood, "Texture" data blocks are sort-of deprecated in 2.8x? How are you creating them for this node to use?

**Comment by vicdoval** [comment]
@portnov the texture nodes don't work but brush textures and "displace modifier" textures  seem to work fine
texture_evaluate_sverchok_blender_example_1

**Pull request merged**
