### PR TITLE
"Extrude region" node

### PR DESCRIPTION
**Pull request by portnov**
This node limbed in my local repo for two years for unknown reason :)

I'm going to add documentation near days, but in general usage is more or less obvious, similar to "extrude separate faces" node.

To select faces to extrude this node uses simple face mask; i wonder why this node and "extrude separate faces" does not suffer of bmesh edges/faces ordering problem, i can't see it here.

I'm probably going to update it a bit during near days, so please do not merge it right now.

Please review and test.

### CODE REVIEW

**Comment by portnov** [comment]
extrude-region-1

**Comment by zeffii** [comment]
i'd remove all the later `.is_linked` tests.. just sv_set anyway.  the data is calculated anyway.

**Comment by portnov** [comment]
@zeffii 
I remember at some time sverchok printed a warning if i tried to sv_set() on unlinked output...

**Comment by zeffii** [comment]
yeah, that's no longer the case.

**Comment by portnov** [comment]
Ah, ok, will remove this check then.

**Comment by zeffii** [comment]
i look forward to using this!

**Comment by portnov** [comment]
@zeffii 
Well, now I think this is more or less ready for merge.

**Comment by zeffii** [comment]
ok I have no issues with the code... but some  stylistic indentation things.. in the properties and bmesh.ops - but am happy to merge anyway.

**Comment by nortikin** [comment]
https://vk.com/public35076122?w=wall-35076122_8145

**Pull request merged**
