### PR TITLE
Selection graber

### PR DESCRIPTION
**Pull request by Durman**
## Addressed problem description

Sometimes there is need in selecting part of mesh by hand. 
Short instruction: 
- Generate object via Sverchok. 
- Bake the object on stage when topology won't be changed. 
- Select required elements of mesh. 
- Bake selection in new node.
- Continue working with selected part of the object.

Also this node gives all features in selection which there are in Blender.
Downside - topology of object should be constent.

## Preflight checklist

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
Any suggestion about node name? 😕

**Comment by portnov** [comment]
Also check out  discussion in #1320.

**Comment by Durman** [comment]
@zeffii By the way according my observations in Houdini such approach is widely using. I mean creating masks by manual selection of elements. I think it meant that such approach could be quite convenient in procedural modeling.

**Comment by enzyme69** [comment]
Vertex with Selection is one example that would well quite well, if index remains stable. I use it with Skin Modifier. The output is actually "dynamic" because Skin Modifier continuously trying to adapt. 

Screen Shot 2020-04-04 at 11 29 36 pm

**Pull request merged**
