### PR TITLE
Set uv map

### PR DESCRIPTION
**Pull request by Durman**
## Addressed problem description

This node is created to give opportunity do UV Map with power of Sverchok. I think best approach to solve the problem should be discussed in this theme.)) I already gave some examples here: #1809

## Solution description

The sense is to make opportunity create UV map and Unwrapping can be done with standard nodes of Sverchok.

[test_2018_05_15_17_12.zip](https://github.com/nortikin/sverchok/files/2006011/test_2018_05_15_17_12.zip)

## Preflight checklist

- [ ] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [ ] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by nortikin** [comment]
ok, @Durman, write to me nikitronn (собака) yandex.ru

**Comment by Durman** [comment]
It looks like `UVtextures` node distorts real UV map.

**Comment by Durman** [comment]
I'm experimenting with uv operators and I have faced with such problem:

recursion bug

```
Smart Projection time: 0.00
2018-06-01 21:10:35,814 [ERROR] sverchok.core.update_system: Node Objects in mk3 had exception: maximum recursion depth
exceeded while calling a Python object
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\core\update_system.
py", line 325, in do_update_general
    node.process()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\nodes\scene\objects
_mk3.py", line 231, in process
    with hard_freeze(self) as _:
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\contextlib.py", line 136, in helper
    return _GeneratorContextManager(func, args, kwds)
RecursionError: maximum recursion depth exceeded while calling a Python object
Smart Projection time: 0.00
```

**Comment by Durman** [comment]
Experiments will continue in 2.8

**Comment by gerroon** [comment]
Hi

How is this used? I am confused about how to make it work, also there is additional objects input and output there. Is this for creating new uvmaps ?

I would like to create some uvs procedurally in Sverchok.

thanks

**Comment by vicdoval** [comment]
@gerroon check the docs :) https://github.com/nortikin/sverchok/blob/master/docs/nodes/object_nodes/set_custom_uv_map.rst

**Comment by Durman** [comment]
@gerroon 2 and 3 inputs of the node expect 2D mesh of UV mapping. It's possible to use for this inputs the same mesh the object socket has. In this case the mesh will be projected into XY surface. 

To object output socket it's possible to connect other nodes like `assign material`. It lets to set order of applying attributes to an object.

**Comment by gerroon** [comment]
thanks guys your answers were very helpful.

**Pull request closed without merging**
