### PR TITLE
Add shift parameter to TorusKnot node

### PR DESCRIPTION
**Pull request by DolphinDream**
Add shift parameter to allow points to be shifted along the curve

Shift values are 0-1, where 0 = no shift, and 1 = a complete shift of the points along the curve.

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by DolphinDream** [comment]
Btw, should this update be an MK2 node? (one extra setting parameter / input socket was added)

**Comment by Durman** [comment]
Adding new sockets destroy work of existing layouts with such nodes.

**Comment by DolphinDream** [comment]
> Adding new sockets destroy work of existing layouts with such nodes.

That’s what I thought.. just confirming. So, it’s a MK2 then.
What exactly is the process for making a MK2? Do I need to move the old node to some retired location or should i just add the new node files without moving the old files?

**Comment by Durman** [comment]
File with old version of node should be moved to `old_nodes` directory.
Label of new node should not point to version of the node.
All other things which should be changed will be pointed by passing test of this PR.
You can use this PR as template: #2815 probably I have missed something.

**Comment by zeffii** [comment]
@DolphinDream  you should be trying to merge into "master", not `b28_prelease_master`

**Comment by DolphinDream** [comment]
> @DolphinDream you should be trying to merge into "master", not `b28_prelease_master`

Is **master** now the Blender 2.8x stable branch?

**Comment by zeffii** [comment]
2.83+ even.

**Comment by DolphinDream** [comment]
How do I implement a node replacement feature so that old blends using old torus knot version can easily be replaced and reconnected with the new node version? any examples I can follow?

**Comment by Durman** [comment]
I think you have to rename file with documentation to `torus_knot_mk2.py` as well.

**Comment by DolphinDream** [comment]
> I think you have to rename file with documentation to `torus_knot_mk2.py` as well.

fixed. and btw.. we don’t need to keep the old node documentation, correct?

**Comment by zeffii** [comment]
> we don’t need to keep the old node documentation, correct?

correct: https://github.com/nortikin/sverchok/pull/2998

**Comment by zeffii** [comment]
if someone really wants to read docs of the old node there's always the git history

**Comment by vicdoval** [comment]
Something like this has to be added to the old node to use the replacement operator https://github.com/nortikin/sverchok/blob/ed61384f3024e73ee0930c6518ab6791f88324d1/old_nodes/box.py#L38

**Comment by DolphinDream** [comment]
A live demo of the shift setting.

SV-TorusKnotNodeMK2-Demo1

**Pull request merged**
