### PR TITLE
Bug Fix no Vector Sort Connect and Docs

### PR DESCRIPTION
**Pull request by vicdoval**
## Addressed problem description

Error on vector Sort by Connex

## Solution description

Typo fix

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [ x] Code changes complete.
- [ x] Code documentation complete.
- [x ] Documentation for users complete (or not required, if user never sees these changes).
- [x ] Manual testing done. 
- [? ] Unit-tests implemented.
- [x ] Ready for merge.

### CODE REVIEW

**Comment by zeffii** [comment]
uuuuuuhm. why are there so many commits in this small fix ?  @vicdoval  perhaps you should start patches, by doing a fresh clone of Sverchok (rebasing?) and then write the path, then do the PR.

**Comment by zeffii** [comment]
i merged as one PR.

**Comment by vicdoval** [comment]
Sorry , i'm new  with git and github and i dont understand everything yet.
I have just merged from the master to my fork but it still says my fork is 46 commits ahead...
I'm using the web interface to manage all this so maybe it is because of this....

**Comment by vicdoval** [comment]
Maybe i should delete my repository before any more contributions?

**Comment by zeffii** [comment]
yeah, could be. it's worth learning git - you'll get by without being an expert. I started out using the git web interface, then the github desktop app, then command-line git.

- before you edit code
- you pull from sverchok/master (to make sure you are up to date)
- then branch
- then edit
- then do a pull request.

**Comment by Durman** [comment]
It's seems to me that it will be less commits if at first create branch and update it from sverchok/master after that, becouse all  commits in own copy of master come to branches.

**Comment by zeffii** [comment]
I can only suggest the procedure that I know works for me.

**Comment by zeffii** [comment]
@vicdoval 
it took me a while (years) to learn my way around `git` just enough to stay out of "trouble".  If it seems overwhelming, it is a normal response. However there's a subset of git commands (maybe 7) that are all you really need for most of the contributions.

**Comment by nortikin** [comment]
merge to custom branch before merge to master works for me. I'm still new to git.

**Comment by vicdoval** [comment]
Thanks for your advice about git, :) now I'm starting to face it, i hope it gets clear as soon as look it straight!

**Pull request merged**
