### PR TITLE
Iojson codeshuffle

### PR DESCRIPTION
**Pull request by zeffii**
stage 1 import modularized.

### CODE REVIEW

**Comment by zeffii** [comment]
essentially it is the same working code as before these commits, but massively shuffled around into simpler sub sections.
5.Sverchok Spread still has an intermittant bug (must be order, and hashing related)

**Comment by zeffii** [comment]
sometimes it will give this error, if the current_text is already present.
```python
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 607, in execute
    import_tree(ng, self.filepath)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 520, in import_tree
    generate_layout(fullpath, nodes_json)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 493, in generate_layout
    name_remap = add_nodes(nodes_to_import, nodes, create_texts)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 421, in add_nodes
    add_node_to_tree(nodes, n, nodes_to_import, name_remap, create_texts)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 407, in add_node_to_tree
    add_texts(node, node_ref)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 376, in add_texts
    perform_svtextin_node_object(node, node_ref)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 335, in perform_svtextin_node_object
    texts[current_text].from_string(node_ref['text_lines'])
  File "C:\Users\zeffi\Downloads\blender-2.76\blender-2.76.0-git.50a19cc-AMD64\2.77\scripts\modules\bpy_types.py", line 518, in from_string
    self.write(string)
TypeError: Text.write(): error with argument 1, "text" -  Function.text expected a string type, not dict

location: <unknown location>:-1
```
will be easy enough to fix.

**Comment by ly29** [comment]
Looking good, lean functions are nicer in general

**Comment by zeffii** [comment]
```python
def perform_svtextin_node_object(node, node_ref):
    '''
    as it's a beta service, old IO json may not be compatible - in this interest
    of neat code we assume it finds everything.
    '''
    texts = bpy.data.texts    
    params = node_ref.get('params')
    current_text = params['current_text']
    node.textmode = params['textmode']

    if not current_text:
        print(node.name, "doesn't store a current_text in params")

    elif not (current_text in texts):
        new_text = texts.new(current_text)
        if node.textmode == 'JSON':
            json_str = json.dumps(node_ref['text_lines']['stored_as_json'])
            new_text.from_string(json_str)
        else:
            new_text.from_string(node_ref['text_lines'])

    else:
        texts[current_text].from_string(node_ref['text_lines'])
```
it's executing the last else statement.. it should do some more introspection in the else.. for now.

**Comment by zeffii** [comment]
but I think the last `else` can perhaps be dropped... the logic is a little wonky at first glance.

**Pull request merged**
