### PR TITLE
Add new spiral node (WIP)

### PR DESCRIPTION
**Pull request by DolphinDream**
Starting a new Spiral node. (anyone missed such a node ? :)

Currently this includes a few spiral types: Archimedean, Logarithmic, Spherical, Cornu and one of my own making called Exo (double exponential spiral between two circles). The spherical spiral is the only 3D spiral so far but I’ll be extending these to 3D later on to create helixes and such. Any suggestions are welcome. 

sv-spiralnode-1

### CODE REVIEW

**Comment by DolphinDream** [comment]
Any suggestions for what’s the best way to render lines ? I tried skin mesh or curve viewer but this makes the animation way less interactive. I wish there was a node to create an inset/outset around a line :) https://github.com/nortikin/sverchok/issues/1295 to create a very simple mesh (2D would do for now).

**Comment by zeffii** [comment]
regarding "best way" to render lines.

The options for live / interactive rendering aren't really fantastic at the moment. I'll stress that this isn't an area we've considered imperative to fix either, with 2.8 around the corner and new bgl/gawain paradigms this may change.

- outputting verts+edges to a BMeshViewer gives reasonable speed, and can be rendered using the Animation OpenGL option (A Blender feature)
- _Curve Viewer_ or _PolyLine Viewer_ will work as they just push data into objects of type Curve, there may be some slowdown but if you are rendering this won't be significant compared to the rendertime of a frame.

an inset/outside node might help you, but will involve drawing more than double the amount of geometry (and that's a tick in the slowdown category)

**Comment by DolphinDream** [comment]
A little preview .. into the Ovoidal spirals. I call this “The Spinning Duality”  :)

sv-spiralnode-demo1

**Comment by DolphinDream** [comment]
First round of development is coming to an end (to be merged in shortly). Here is the latest update of the UI and the types of spirals currently implemented.

sv-spiralnode-ui3

sv-spiralnode-collage2

**Comment by DolphinDream** [comment]
And an interactive demo of the types/presets. 
(the node has a list of presets with various settings for each type of spiral).

sv-spiralnode-demo5

**Comment by zeffii** [comment]
I hope to one day find a use for it :)

**Comment by DolphinDream** [comment]
@zeffii I doubt you will.. unless you go camping 😉 
(btw, are you hinting that I shouldn’t have merged this node in?)

**Comment by zeffii** [comment]
this node is fine, just not something for me / can't promise i'll test it much. looks like good fun

**Comment by enzyme69** [comment]
I want this Spiral node :D will use it for Live Noding.

**Comment by DolphinDream** [comment]
@enzyme69 It’s merged in.. Please keep in mind though that I kept this as a beta node for now since I’m considering making further adjustments to it. Feedback is always appreciated 👍

**Comment by DolphinDream** [comment]
Settings demo - Archimedean spiral

sv-spiralnode-demo6-archimedean

**Comment by DolphinDream** [comment]
Settings demo : Exo spiral

sv-spiralnode-demo6-exo

**Comment by DolphinDream** [comment]
Settings demo - Ovoidal spiral:

Note: the eR/iR are not quite intuitive for the moment (and the height is ignored). Next update will make the iR change the horizontal cross section radii without changing the height of the spiral and the eR/H will both affect the height and vertical cross section radius.  

sv-spiralnode-demo6-ovoidal

**Comment by DolphinDream** [comment]
Some fun examples.. :) two seven arm, counter rotating fibonacci vortices.. opening a portal between Sun and Earth 

sv-spiralnode-demo7-a
sv-spiralnode-demo7-b

**Comment by enzyme69** [comment]
Very cool! By the way, I am still not getting push update. Wonder why...

**Comment by zeffii** [comment]
@enzyme69  assuming you are using git...
```git
git checkout master
git pull
```

**Comment by enzyme69** [comment]
Ooh... "Show Latest Commit" does the job!

Cheers for the Git tips again, Zeff!

**Comment by enzyme69** [comment]
screen shot 2017-10-31 at 22 02 31

**Comment by DolphinDream** [comment]
@zeffii btw.. if i have incremental changes to this node do I need to create a PR or should i just merged them in ?

**Comment by DolphinDream** [comment]
I meant to ask this a while back when i was working on the Torus Knot node.. for some values of the parameters the result output is a set of disjoint curves and if I use vectorization that creates different versions of the spiral each having multiple arms (thus disjoint curves) when i try to pozition them via Viewer Draw + Line, each individual spiral (arm) is being positioned on the line grid instead of each spiral (with all of its arms). Any ideas how to go about this issue? Do i need to create a tripple nested lists or something ? Does the Bmesh viewer or Viewer Draw node know how to handle tripple nested lists this way ?

**Comment by DolphinDream** [comment]
Some more ovoidal spiral fun demos: “The Flux Capacitor” :)

sv-spiralnode-demo8

**Comment by Durman** [comment]
I have not well understood your problem but if we want to create some structure inside object we can use mask list. For example:

list of vectors - [[(V1),(V2),(V3)],...]
mask - [[0,0,1],...]

Where zero will select vectors V1 and V2, one will select vector V3.
In this case we can receive more difficult structure without triple nested list of vectors.

**Comment by zeffii** [comment]
> @zeffii btw.. if i have incremental changes to this node do I need to create a PR or should i just merged them in ?

because it's a beta node you can just push, it's up to the users to avoid these nodes in critical works.

> . for some values of the parameters the result output is a set of disjoint curves and if I use vectorization that creates different versions of the spiral each having multiple arms (thus disjoint curves) when i try to position them via Viewer Draw + Line, each individual spiral (arm) instead of each spiral (with all of its arms) is being positioned on the line grid. Any ideas how to go about this issue?

I'm not sure I follow, show images.

**Comment by DolphinDream** [comment]
@zeffii Here’s a setup. I have a spiral setup with 2 arms (arms are separate lists in the spiral) and I create (vectorize) versions with 1,2,3,4 turns. The purple draw shows all of them overlapping. the blue draw shows the spread/moved at different locations (via line). As you can see the location of each (separate) arm is distributed at the given line locations instead of each spiral as a whole (with both arms). What I want of course is to put 2-arm spiral with 1 turn at L1, 2-arm spiral with 2turns at L2 etc. I know i can do all sorts of grouping and merging with other nodes but I was wondering if there is something simpler I can do within the node so that this setup just works (e.g. Viewer Draw to just know to put the first to lists at L1, next two lists at L2 etc).

gist: https://gist.github.com/6b4db73d06abc30c0501f33b5fabe5e3

sv-multiarmspiralreplication

**Comment by zeffii** [comment]
I see. Let's reduce the example to 4... instead of 8

When a node outputs `verts. 4` in my opinion it should really represent 4 sets of verts, each part of an individual "object" `[verts, verts, verts, verts]`. At present we don't really have a way for the list of verts to carry metadata about itself to say "this `verts` is made up out of this number of disjoint parts, starting by index 0, 12, 23, 45".. Mostly this is because it's an extra layer of complication.

You came up with a solution, an output mast lists. it would output something like
```
output_meta_data = [[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,1,1,1,1,1,1,1],[0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2,2,2]......]
```
where each vert inside a list of verts is indexed by a mask. That takes the complexity of dealing with the sublists out of the node, and might require a matrix apply node with understanding of the masking. And if that's workable, new nodes that need this sub-list-indexing can use the same scheme. (like Generator/Cylinder' s "separate" functionality )

**Comment by nortikin** [comment]
just WOWOWOW!!!
Amazing work.

**Comment by 0000888888880000** [comment]
GNP

**Pull request merged**
