### PR TITLE
fix 4959. Dot product can be used to realize side of mesh.

### PR DESCRIPTION
**Pull request by satabol**
Sverchok 1.3-alpha, Blender 3.6.1,  windows 11.

#4959 

Description of problem:
https://github.com/nortikin/sverchok/blob/44e611da468d60c3134fa8d31634d8b1c1907b00/utils/sv_mesh_utils.py#L376-L389

Core of problem is line 386:
https://github.com/nortikin/sverchok/blob/44e611da468d60c3134fa8d31634d8b1c1907b00/utils/sv_mesh_utils.py#L386-L386

In some cases "point == location + axis * 0.00001"

Solution for box with size=600:

image

### CODE REVIEW

**Comment by satabol** [comment]
if old code do not check mesh for closed and self intersections (and other validity) so drill faces is a not precise method. May be test normal is enough precise and safe?

**Comment by satabol** [comment]
if old code do not check mesh for closed and self intersections (and other validity) so drill faces is a not precise method. May be test normal is enough precise and safe?

@portnov What do you think about this method?

**Comment by portnov** [comment]
I'm not sure. Probably better to test both approaches on different meshes and compare.

**Comment by satabol** [comment]
What to do if comparison are different?

**Comment by portnov** [comment]
select the method which gives better results, i think.

**Comment by satabol** [comment]
Mmm. How to test what results are better?

**Comment by portnov** [comment]
create several meshes of different forms (for example concave ones). Supposedly, on some forms one algorithm will work fine and another will not. Then the algorithm which works for more forms is better :)

**Review by Durman — APPROVED** [review]

**Comment by satabol** [comment]
image

**Pull request merged**
