### PR TITLE
Nested Matrices for Apply matrices node

### PR DESCRIPTION
**Pull request by Durman**
## Addressed problem description

Supporting nested list of matrix as input for `matrix apply` node. Use case is copy mesh inside mesh.

## Preflight checklist

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete.
- [x] Manual testing done. 
- [x] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
@vicdoval I did not catch of the idea of `output numpy: face`?

**Comment by Durman** [comment]
I think the node should be simplified (not in the PR). 
- It should  not have any options other than `join mesh`. 

- If inputs vertices are numpy array numpy implementation should be used. 
- If numpy implementations is used output also should be numpy array.

In this PR I'm not going change existing logic so new version `mk++` of the node does not need.

**Comment by vicdoval** [comment]
> @vicdoval I did not catch of the idea of output numpy: face?

The node only changes the faces if "join" is applied other ways outputs a copy of input faces "as is"



> I think the node should be simplified (not in the PR).
> 
> * It should  not have any options other than `join mesh`.
>   
> * If inputs vertices are numpy array numpy implementation should be used.
> * If numpy implementations is used output also should be numpy array.
> 
> In this PR I'm not going change existing logic so new version `mk++` of the node does not need.

I don't agree bout this topic because although is a very "expert stuff" I think it does not harm and gives more control to the user about  where to start and to stop the numpy chain for performance fine tuning.
Maybe a "Auto" mode could be added that makes some assumptions and hides the other buttons but i would definitely keep that possibility to choose somewhere

**Comment by Durman** [comment]
> The node only changes the faces if "join" is applied other ways outputs a copy of input faces "as is"

If you set property `output is numpy` and get python list instead you think it is Okay? Is this documented behaviour?

Having of a node tree where switch between python and numpy should be done in every node manually has too obvious downsides to explain them I think.

**Comment by vicdoval** [comment]
> If you set property output is numpy and get python list instead you think it is Okay? Is this documented behaviour?

That is a bit weird and could be improved 😄 

The thing of transforming manually is a tricky thing because 
Numpy Node to Numpy Node (+1 +1) (boost the first and the last)
Numpy node to python node (+1, -1)  (boost the first and slows the last )
Numpy node to two python nodes( +1 -2)
and so on...
So it is really dependant of the nodetree when is the best to cut the chain... it could be super cool to have a optimizer operator that makes some test in our nodetree and chooses when is better to switch....

**Comment by Durman** [comment]
If a node does not have numpy implementation it won't output numpy arrays. So you will never get such chain: numpy - python - numpy - python. If second node does not support numpy then all next nodes will be deal with python data and use python implementation automatically.

I would suggest you to make concludes about performance of a node tree on a concrete examples. I would expect that in many layouts difference between python and numpy implementation of the node is nothing by comparison performance of such nodes as `remove doubles` or `adaptive polygons` for example.

**Comment by vicdoval** [comment]
Is true it could be very small difference defending on the case, what I mean is:
_ `.tolist()` is slow (in some times is the 90% of the node processing time) 
_ `np.array(another_np_array)` is faster than `np.array(python_list)`
_ `for v in np_array` is slower than `for v in python_list`
_ in some cases  `np.array(python_list) + numpy implementation + .tolist()` is faster than using a python implementation.

With this rules i see that depending on the nodetree structure de performance can be improved if you know where to output numpy and when not. Anyway probably just a few users can use this wisely...

**Comment by Durman** [comment]
> Anyway probably just a few users can use this wisely...

Exactly.

My rules are simpler:
- Numpy is faster than Python. 
- If a node get numpy data numpy implementation is used otherwise Python. 
- If you want boost performance of a node will try to grant numpy data to it. 

With this rules everyone can use Sverchok wisely.

**Comment by vicdoval** [comment]
> If you want boost performance of a node will try to grant numpy data to it.

If you feed a viewer draw or a bmesh.ops node with numpy data it will make it slower...

**Comment by Durman** [comment]
I already have said about performance and how it should be measured.

**Pull request merged**
