### PR TITLE
Mathutils matrix

### PR DESCRIPTION
**Pull request by Kosvor2**

### CODE REVIEW

**Comment by zeffii** [comment]
i don't know what way to go with this.

**Comment by portnov** [comment]
Well, at least you have to make tests passing. It may occur that non-passing tests indicate some compatibility problems that users will face.

**Comment by portnov** [comment]
I'll try to take a closer look this week...

**Comment by Kosvor2** [comment]
Where is `assert_sverchok_data_equal()` ? it seems what problem is in it.

**Comment by Kosvor2** [comment]
I will try conversion to lists just for test itself.

**Comment by Kosvor2** [comment]
All tests passed now. Ready for merge i guess...

**Comment by zeffii** [comment]
this will need considerable review... i do not have the time.

**Pull request merged**
