### PR TITLE
"miura fold" script node

### PR DESCRIPTION
**Pull request by asahidari**
## Addressed problem description

Currently (June 2020) I could not find nodes related to 'origami', and I found #1381 'WISHLIST: Sverchok for Origami Simulation'. Though this new file would not fully satisfied the 'WISH' immediately, It can be a start point to implement the full 'Origami Solver'.

## Solution description

I added 'miura_fold.py' to 'node_scripts/SNLite_templates/utils/' directory. The Miura fold is one of typical patterns of origami and relatively easy to implement. So it can be a help to develop Origami Solver.

## Preflight checklist

- [x] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by vicdoval** [comment]
Thanks for contributing! 😄 

For consistency with the rest of Sverchok could you please remove the Vector() conversion of the vertices?
In Sverchok vertices are List or Tuples

**Comment by asahidari** [comment]
> For consistency with the rest of Sverchok could you please remove the Vector() conversion of the vertices?
In Sverchok vertices are List or Tuples

Thank you for your comments. I removed the Vector() from miura_fold.py.
And sorry for late reply. In my previous commit, author name and e-mail address was not right, so I modified them and push with force (-f) option. Please confirm this commit is not wrong.

**Comment by vicdoval** [comment]
@asahidari  Thanks and congratulations! 🥳

**Comment by asahidari** [comment]
Thank you for merging, @vicdoval -san!😄

**Pull request merged**
