### PR TITLE
Common object-handler mixin + operator (callback)

### PR DESCRIPTION
**Pull request by zeffii**
Tick doesn't mean it works. or is tested, just means I added the bulk of the required code to the proposed mixin.

- [x]  `getting children` of the node  (`objs = `)
- [ ]  generating truely unique object / data names using a sverchok dict, rather than scene tests
- [x]  setting materials
- [x]  generating material (one material for all...)
- [x]  cleanup orphan objects
- [x]  hide / hide_select / hide_render / select operations.
- [x]  include layer handling
- [x] reuse UI icon code ( kinda klunky at the moment...)
- [x] add grouping code (no ungroup?)
- [x] add parenting code (no unparent?)
- [x] fix merging in BMVmk3
- [x] add nodetree/nodename to callback operator (else the node UI must be active/selected first )
- [ ] migrate all viz nodes to name their "objects" using some form of this line.
     ```python
     data_name = node.basedata_name + '.' + str("%04d" % obj_index)
     ```
- [ ]  include per object material passing. (material name per object)
- [ ]  easy auto update the node switches for hide/select/hide_select https://github.com/nortikin/sverchok/issues/1930
- [x] convert PolylineViewerMK2 to use `sv_obj_helper`
- [x] convert BMeshViewerMK3 to use `sv_obj_helper`
- [x] convert CurvesViewerMK2 to use `sv_obj_helper`
- [x] convert CurvesViewer2DMK2 to use `sv_obj_helper`
- [x] convert SkinViewerMK2 to use `sv_obj_helper`
- [ ] convert TypographyViewerMK2 to use `sv_obj_helper`
- [ ] convert MetaballViewer(MK2?) to use `sv_obj_helper`

### CODE REVIEW

**Comment by zeffii** [comment]
node/self will from now on have these standard attributes
```python
basedata_name   # so can be used for Curve / Mesh / Whatever.

object_hide
object_hide_select
object_hide_render
object_select
```

**Comment by zeffii** [comment]
i wrote `get_random_init` but barely understand what it's doing now.  👻 

- why am i testing the `object.type` at all.  An object name is a name, it's either used or not.

**Comment by zeffii** [comment]
polyline viewer mk2 sort of works now. still an issue with one of the icons, but i haven't tried debugging it.

the node no longer attaches itself to the cursor . overriding self.select was a stupid idea.

**Comment by zeffii** [comment]
converting PolyLineViewer to MK2 using SvObjHelper took about 5 minutes.

**Comment by portnov** [comment]
@zeffii Can I help here? Where to start from?

**Comment by zeffii** [comment]
You could convert metaball viewer to get the hang of it, followed by CurveViewer+CurveViewer2D (maybe combine those two cleverly).  Make suggestions / modifications to the mixin. It's complicated, but you of all people can handle that :)

I will then do SkinViewer and TypeViewer.

**Comment by portnov** [comment]
viewer_polyline_mk2.py still does some objects-bookkeeping-magic in `def get_obj_curve(obj_index, node)`. I think this logic should be moved to mixin too.

**Comment by zeffii** [comment]
> I think this logic should be moved to mixin too.

yes. the transition is not complete -- i wasn't in a hurry.

**Comment by zeffii** [comment]
i think i'll continue on this today. so i'm going to assume you haven't made a branch @portnov .

**Comment by zeffii** [comment]
@portnov  i know you offered to help, please don't be suprised if I convert CurvesViewer2D+3D ( i might have uncommitted code to this effect )

**Comment by portnov** [comment]
No, i haven't yet.

**Comment by zeffii** [comment]
good. because CurveViewer* is not a nice node at the moment:)

**Comment by zeffii** [comment]
5 hours into converting CurveViewer 2d+3d into a unified node. Closer but still far away.

**Comment by zeffii** [comment]
notes to self
image
later
image

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
i'm not sure skinmodifier will benefit much from this helper mixin..

**Comment by portnov** [comment]
Mostly it will be us who will benefit :) From not having duplicated code.

**Comment by zeffii** [comment]
> Mostly it will be us who will benefit :) From not having duplicated code.

right :)

i'll need to stare at skinmesher a little longer. (slightly offtopic --> ) it's really stupid that modifiers can't be moved programmatically without bpy.ops. I can imagine a really really roundabout "attr copying" loop that serialises a modifier and recreates it, but that seems like a bloody mess.

**Comment by portnov** [comment]
I'm going to start porting Metaball viewer. Should I push to this branch or create a separate PR?

**Comment by zeffii** [comment]
push to this branch is fine. ( i think ? )

**Comment by zeffii** [comment]
looks "not bad" @portnov : ) , amazing that we had so much duplication .

**Comment by portnov** [comment]
I wanted to generalize MetaballOut a bit, add possibility to create several Meta objects. But, I cant' figure out how to generate a list of lists of matrices >__<

Also, If I pass list of lists of vertices to MatrixSocket input, then inside node I see flatterned list of matrices. This is due to flatterning logic in socket_connections.py line 52. @zeffii was it intended so?

**Comment by zeffii** [comment]
> @zeffii was it intended so?  

yes. brutally yes.

**Comment by zeffii** [comment]
i'm not sure we even have any nodes that can handle nested matrices as input, so it seemed pointless at the time to preserve the nestedness.

**Comment by zeffii** [comment]
>  But, I cant' figure out how to generate a list of lists of matrices (by means of Sverchok nodes)

i think we can implement an override for the implicit vector->matrix conversion, that shouldn't be a problem, then you'd do `matrix_socket.sv_get(...,...,...,nested_matrices_from_vectors=True)` or something.

**Comment by zeffii** [comment]
please `pull` @portnov  , small changes to the UI code . there's a new `tracked_operator` function which passes nodetree/nodename automatically.

**Comment by portnov** [comment]
ok

**Comment by zeffii** [comment]
@portnov  regarding vertex->matrix override.  https://github.com/nortikin/sverchok/issues/2020

**Comment by zeffii** [comment]
might get skinmesher in line today. and fix the hide_select icon choice for the initial state.

**Comment by portnov** [comment]
I have several local branches that rely on changes in this one:
* WIP on trying to do fewer tree recalculations
* WIP on Metaball Out to be able to produce several Meta objects (this also needs #2024)
*  Lamp Out (#1949)

Also I see there will be some work/discussion in #2034. So, I propose to:

1. Rebase this branch to current master.
2. For remaining items from this PR and items mentioned above, make new PRs against branch of this one.
3. After all these related PRs are merged into this one, merge this PR into master.

**Comment by portnov** [comment]
Or, if you think SvObjHelper class by itself is more or less complete, we could merge this PR to master as it is, and do remaining things just in new PRs against master.

**Comment by zeffii** [comment]
@portnov  there are parts I haven't tested yet, but they are all unused by existing nodes so the code involved in SvObjHelper can live happily in master without too many issues. I'm just not sure if I want to push the various updated object-viewer nodes yet. 

It would be nice to get it in master, for the reasons you state.

**Comment by zeffii** [comment]
any nodes that i've changed in this PR, are `mk += 1` ,  The alternative approach to zeropadding object names (and making it consistent across nodes) forced me to use new bl_idnames even if these object-viewer nodes are all "technically" beta/alpha.

**Comment by zeffii** [comment]
anyway.. there's a few things that need to be resolved obj/data names.

image

**Comment by zeffii** [comment]
all of this was injected into 2.8 straight.

**Pull request closed without merging**
