### PR TITLE
Upgraded HexaGrid MK1 to Polygon Grid

### PR DESCRIPTION
**Pull request by vicdoval**
## Addressed problem description
As stated in the  PR #2246 
The hexaGrid node is great working with hexagons but  does not  handle any other polygon.

## Solution description

I expanded the node so it can work also with triangles and squares.
Also added:
Possibility to define polygon by radius or side length.
A smart Remove Doubles (when scale is 1 and "separate is unchecked) 
List handling. Now if you click "separate" you will get the unpacked polygons unless you are creating many grids simultaneously.

HexaGrid Mk1 was moved to old_nodes and a right-click link has been added  to it in orther to be replaced in old layouts by the new node

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
I'm receiving 
```
Exception in module register(): '/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/__init__.py'
Traceback (most recent call last):
  File "/home/portnov/SSD/soft/blender-2.79-linux-glibc219-x86_64/2.79/scripts/modules/addon_utils.py", line 350, in enable
    mod.register()
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/__init__.py", line 93, in register
    menu.register()
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/menu.py", line 332, in register
    menu, node_count, original_categories = make_categories()
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/menu.py", line 303, in make_categories
    items=[SverchNodeItem(props[0]) for props in nodes if not props[0] == 'separator']))
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/menu.py", line 303, in <listcomp>
    items=[SverchNodeItem(props[0]) for props in nodes if not props[0] == 'separator']))
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/menu.py", line 128, in __init__
    self.make_add_operator()
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/menu.py", line 152, in make_add_operator
    class SverchNodeAddOperator(bl_operators.node.NodeAddOperator, bpy.types.Operator):
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/menu.py", line 155, in SverchNodeAddOperator
    bl_idname = "node.sv_add_" + self.get_idname()
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/menu.py", line 141, in get_idname
    return get_node_idname_for_operator(self.nodetype)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/menu.py", line 199, in get_node_idname_for_operator
    raise Exception("Can't find registered node {}".format(nodetype))
Exception: Can't find registered node SvHexaGridNodeMK1
2018-07-18 19:48:48,627 [WARNING] py.warnings: /home/portnov/.config/blender/2.79/scripts/addons/svrx/util/transforms.py:1899: UserWarning: failed to import module _transformations
  warnings.warn("failed to import module %s" % name)
```

I think you have to remove SvHexaGridNodeMK1 from index.md, once you moved it to old_nodes.

**Comment by portnov** [comment]
... and add your new node there. I was not able to find it in menus :)

**Comment by vicdoval** [comment]
Sorry I copied the wrong index.md now it is corrected

**Comment by Durman** [comment]
As I see now this node can't replace `plane` node because they have different algorithm of creating grid.
There is an example what `plane` node can do and polygon grin node can't on the picture below.

**Comment by nortikin** [comment]
why not merged?

**Comment by vicdoval** [comment]
Because I couldn't merge it :smiley:

**Comment by nortikin** [comment]
added @vicdoval to collaborator. Beautifull node. Love it.

**Comment by vicdoval** [comment]
Thanks @nortikin, I really appreciate Sverchok and I feel thankful about being able to collaborate with the project. 🎉

**Pull request merged**
