### PR TITLE
template json upgrade

### PR DESCRIPTION
**Pull request by kalwalt**
ref: https://github.com/nortikin/sverchok/issues/1526

I updated these jsons, as i check.(re-importing the json to verify) in some case the nodes are not in te place in which i saved. Don't know why, i will re-check again if this issue persist.

### CODE REVIEW

**Comment by kalwalt** [comment]
trying to export AdaptiveSpread.json with new objects in nodes i get this error:
```
Cannot find ObjectsNode among old nodes
Cannot find ObjectsNode among old nodes
Text in seems to reuse a text block loaded by another node - skipping
Failed to load JSON data
Text in seems to reuse a text block loaded by another node - skipping
update lists:
['Text Input', 'Objects input:Vertices', 'Adaptive Polygons', 'VersR']
['Text Input', 'Objects input:Polygons', 'Adaptive Polygons', 'PolsR']
['Text Input.001', 'Objects input.004:Vertices', 'Adaptive Polygons', 'VersD']
['Text Input.001', 'Objects input.004:Polygons', 'Adaptive Polygons', 'PolsD']
['Adaptive Polygons', 'Vertices', 'Viewer Draw2', 'vertices']
['Adaptive Polygons', 'Poligons', 'Viewer Draw2', 'edg_pol']
Traceback (most recent call last):
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 590, in make_links
    ng.links.new(*resolve_socket(*link, name_dict=name_remap))
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 581, in resolve_socket
    return (ng.nodes[f_node].outputs[from_socket],
KeyError: 'bpy_prop_collection[key]: key "Objects input:Vertices" not found'

Traceback (most recent call last):
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 590, in make_links
    ng.links.new(*resolve_socket(*link, name_dict=name_remap))
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 581, in resolve_socket
    return (ng.nodes[f_node].outputs[from_socket],
KeyError: 'bpy_prop_collection[key]: key "Objects input:Polygons" not found'

failed total 2
[['Text Input', 'Objects input:Vertices', 'Adaptive Polygons', 'VersR'], ['Text Input', 'Objects input:Polygons', 'Adaptive Polygons', 'PolsR']]
Processed  Text Input.001 in: 0.0001
Processed  Adaptive Polygons in: 0.0000
cache miss: Viewer Draw2 -> vertices from: Adaptive Polygons -> Vertices
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/core/update_system.py", line 322, in do_update_general
    node.process()
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/nodes/viz/viewer_mk2.py", line 363, in process
    propv = inputs['vertices'].sv_get(deepcopy=False, default=[])
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/node_tree.py", line 185, in sv_get
    return SvGetSocket(self, deepcopy)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/core/socket_data.py", line 106, in SvGetSocket
    raise SvNoDataError
Node Viewer Draw2 had exception 
Failed to load JSON data
Processed  Text Input.001 in: 0.0001
Processed  Adaptive Polygons in: 0.0000
cache miss: Viewer Draw2 -> vertices from: Adaptive Polygons -> Vertices
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/core/update_system.py", line 322, in do_update_general
    node.process()
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/nodes/viz/viewer_mk2.py", line 363, in process
    propv = inputs['vertices'].sv_get(deepcopy=False, default=[])
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/node_tree.py", line 185, in sv_get
    return SvGetSocket(self, deepcopy)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/core/socket_data.py", line 106, in SvGetSocket
    raise SvNoDataError
Node Viewer Draw2 had exception 
Processed  Text Input.001 in: 0.0001
Processed  Adaptive Polygons in: 0.0000
cache miss: Viewer Draw2 -> vertices from: Adaptive Polygons -> Vertices
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/core/update_system.py", line 322, in do_update_general
    node.process()
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/nodes/viz/viewer_mk2.py", line 363, in process
    propv = inputs['vertices'].sv_get(deepcopy=False, default=[])
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/node_tree.py", line 185, in sv_get
    return SvGetSocket(self, deepcopy)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/core/socket_data.py", line 106, in SvGetSocket
    raise SvNoDataError
Node Viewer Draw2 had exception 
Failed to load JSON data
Traceback (most recent call last):
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 681, in execute
    layout_dict = create_dict_of_tree(ng)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 191, in create_dict_of_tree
    json_as_dict = json.loads(text_str)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/python/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/python/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/python/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

location: <unknown location>:-1

location: <unknown location>:-1

```

i would also understand this template, what should do it?

**Comment by zeffii** [comment]
i'll fix that one :)

**Comment by zeffii** [comment]
actually, first line of the Error:

    > Cannot find ObjectsNode among old nodes

you might be able to load it if you change the bl_idname to `ObjectsNodeMK2`

**Comment by zeffii** [comment]
(rename it in the template's  json)

**Comment by kalwalt** [comment]
ok i will try in this way!

**Comment by kalwalt** [comment]
`ObjectsNodeMK2` is also a deprecated node i switch to `SvObjectsNodeMK3` and it's fine now.

**Comment by kalwalt** [comment]
`SkinViewerNode`  is deprecated, which node is the upgraded version? (see spidershape.json)

**Comment by zeffii** [comment]
SvSkinViewerNodeMK1b

**Comment by kalwalt** [comment]
Perfect!

**Comment by kalwalt** [comment]
i think that only ROADS_LARGE_nikitron.json now needs a upgrade, i will do tomorrow or when i have a bit of time. If you want you can merge it and i will send a new PR after.

**Comment by zeffii** [comment]
many thanks @kalwalt  - this kind of stuff is a pain to do - another way to get a better idea of what sverchok can do :)

**Comment by kalwalt** [comment]
That's true, it doesn't  seems but it require a bit of time, but yes you get a better idea of sverchok.

**Comment by zeffii** [comment]
oh yeah, i did the last node upgrade push for templates :  https://github.com/nortikin/sverchok/commit/9389e275fc7d861e4b707de2d253e7269211f8e4  :)

**Pull request merged**
