### PR TITLE
To create bezier_in_lite.py

### PR DESCRIPTION
**Pull request by maxim1967**
## Addressed problem description

Creating a new node Bezier in Lite With the function of saving the curve object to a json file

## Solution description

Creating a new node Bezier in Lite

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
What is it `SvGenericNodeLocator`? I can't find this class.

**Comment by maxim1967** [comment]
File \utils\sv_operator_utils.py the very first class in this file

**Comment by Durman** [comment]
Now I see. Strange that it's not in your master, though.

https://github.com/maxim1967/sverchok/blob/56f635975695db89b23f19bed3a0857bb2b1597e/utils/sv_operator_utils.py#L18-L27

**Comment by Durman** [comment]
The problem is that `self.node_dict` is empty during JSON exporting.

**Pull request closed without merging**
