### PR TITLE
line mk3 with AB and OD modes

### PR DESCRIPTION
**Pull request by vicdoval**
## Addressed problem description

The line node does not accept multiple inputs on the size socket
Also if you want to make a line from A to B in Sverchok you have to deal with vector evaluation or another tricks.
This also happens if you want to create a line from one origin point with one direction.
The new node tries to be friendly for new users and to mimic the classical definitions of a line

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [x] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by vicdoval** [comment]
Images for docs:
line1
line2
line3
line4
line5
line6

**Comment by zeffii** [comment]
interesting, i won't oppose.

I also wouldn't oppose having a dedicated node for the new features,  "line topology iterator" (topoloft).

**Comment by zeffii** [comment]
i've been busy moving Sverchok to blender 2.8, and have not had time to do _due diligence_ here. Hence tagging @DolphinDream.

**Comment by vicdoval** [comment]
It is not a big change, except of changing the class names in the test.
@zeffii i have been following your updates on the 2.8 prerelease (huge!) and i was not sure if it should wait to this commit to be merged.
I also paused the docs update waiting for the review but maybe i should finish them and merge everything if there are not complains

**Comment by zeffii** [comment]
@vicdoval for most nodes the conversion to 2.8 is a painless process. By all means keep coding for 2.79 as if nothing has changed. Generators and Effectors.

The Curve/PolyLine/BMesh/GLviewer nodes are the only nodes that I would actively discourage making changes to for 2.79, because their code in 2.8 is about 70%+ different.

2.8 is still a little quirky with some unexpected introduction of bugs, as soon as I understand them i'll document them and point at which nodes need more dedicated tweaking.

**Comment by vicdoval** [comment]
Lets keep it up!

**Comment by nortikin** [comment]
i like aproach. You kept this scheme and added A to B and direction, it was needed, but i used to go dificult way, not even see this issue. Thanks!!!
line01
line02

**Comment by vicdoval** [comment]
Can I merge this? Because it was created before lasts nodes Gcode Exporter and Evaluate Image and I'm not sure if it will overwrite the index.md or just the line I changed...

**Comment by zeffii** [comment]
most of the time the github conflict checker does a good job at bringing conflicts to our attention avoiding.

**Comment by enzyme69** [comment]
Wooh.. maybe can make fur using this ...
screen shot 2018-11-18 at 10 25 26 am

**Pull request merged**
