### PR TITLE
"Attraction vectors" node

### PR DESCRIPTION
**Pull request by portnov**
This node calculates vectors directed from given vertices to the attractor. Vector lengths are calculated by one of physics-like falloff laws (like 1/R^2), so it looks like attractor attracts vertices. 
Attractor can be specified as:
* single point or set of points
* straight line (specified by point lying on the line and directing vector)
* plane (specified by point lying on the plane and normal vector).

Documentation is in progress, will push it in near time.

### CODE REVIEW

**Comment by portnov** [comment]
plane-to-circle
box-to-two-points
torus-to-line
sphere-to-plane
plane-to-point
plane-extrude

**Comment by zeffii** [comment]
Awesome.

**Comment by portnov** [comment]
This

glass_cup_1

is now as simple as

cup-nodes

:)

**Comment by portnov** [comment]
output

**Comment by kalwalt** [comment]
Indeed very interesting !

**Comment by Kosvor2** [comment]
Vert socket type has build in vector prop. Use `self.inputs.new('VerticesSocket', 'name').use_prop = True`

This way no need to create default values like `directions_s = self.inputs['Direction'].sv_get(default=[[(0,0,1)]])`

**Pull request merged**
