### PR TITLE
General testing facility and some tests

### PR DESCRIPTION
**Pull request by portnov**
## General testing facility description for developers

Automated tests are implemented by usage of standard Python's `unittest` module (https://docs.python.org/3/library/unittest.html).
In `sverchok.utils.testing` module there is a number of utility methods and some base classes for test cases. 
Test cases themselves are under `tests/` directory. The files have to be named `*_tests.py`.
Test data files are located under `tests/references/` directory. There are `.blend.gz` and `.json` files used as patterns/references for comparison. 

Test cases can be run in two ways:
* From running Blender. For this you have to enable "Developer mode" under Sverchok addon preferences. Then in Sverchok's N panel you will see Testing panel and a button "Run all tests" in it.
* From command line. There is script named `run_tests.sh` in root directory (this is for bash,  I imagine anyone familiar with Windows's `cmd.exe` / Powershell scripting can easily write similar script for Windows). If your blender executable is not available as simple `blender` command, you have to pass it in the command line, like `BLENDER=~/soft/blender-2.79-linux-glibc219-x86_64/blender ./run_tests.sh`.

## Testing plan
* For right now I feel necessity to test JSON export/import code. But after this PR is merged, everyone is welcome to write tests for everything: nodes, utility functions, ...
* Export testing.
  * [x] Exporting of single simple nodes. The simplest approach is to programmatically create nodes, export them and compare resulting JSON to expected. We need to have at least one test per each supported property type (so I'm guessing about ~5 such tests for starters):
    * IntProperty
    * FloatProperty
    * BoolProperty
    * EnumProperty
  * [x] Exporting simple complex nodes (Monad, Script and so on). For now I'm going to use the same approach for testing. But, it is too complicated to create such nodes programmatically. Instead, I'm going to link the whole node tree from specially prepared .blend file. This group should have at least 1 test per each complex node class.
  * [x] Exporting trees with links. The same approach as for single complex nodes. There should be at least 1 such test for starters, and then we can add more complicated tests gradually.
* Import testing:
  * [x] For simple nodes, it is possible to write generic comparing function. So: create a node programmatically, load another node from JSON, compare two nodes. Again we need ~1 test per supported property type.
  * [ ] For complex nodes or complete node trees, it will take too much effort to write generic comparing function. So: link a tree from reference .blend file, load another tree from JSON, then compare certain subset of settings of two trees. And then improve this test gradually. We need at least 1 such test per complex node class, plus at least 1 test for complete tree.

### CODE REVIEW

**Comment by portnov** [comment]
@zeffii 
It appears that SNlite node relies on context in it's work. When I load node tree programmatically, and then try to export it, I receive

```
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/tests/tree_export_tests.py", line 13, in test_export
    export_result = create_dict_of_tree(self.tree)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 298, in create_dict_of_tree
    node.storage_get_data(node_dict)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/nodes/generator/script1_lite.py", line 493, in storage_get_data
    storage = self.node_dict[hash(self)]['sockets']
KeyError: -9223363244641757632
```

It looks like `self.node_dict` is automatically filled only in some specific case. Should I make separate ticket for this?

**Comment by zeffii** [comment]
> Should I make separate ticket for this?

@portnov  yes please

**Comment by zeffii** [comment]
include exact steps to reproduce.

**Comment by portnov** [comment]
```
2018-01-05 23:15:16,430 [INFO] sverchok.utils.testing: Test cases result:
test_box_export (simple_export_tests.ExportSingleSimpleNode) ... ok
test_cylinder_export (simple_export_tests.ExportSingleSimpleNode) ... ok
test_torus_export (simple_export_tests.ExportSingleSimpleNode) ... ok
test_box_import (simple_import_tests.ImportSingleSimpleNode) ... ok
test_cylinder_import (simple_import_tests.ImportSingleSimpleNode) ... ok
test_torus_import (simple_import_tests.ImportSingleSimpleNode) ... ok
test_mesh_expr_export (tree_export_tests.MeshExprExportTest) ... ok
test_profile_export (tree_export_tests.ProfileExportTest) ... ERROR
test_script_uv_export (tree_export_tests.ScriptUvExportTest) ... ok
test_mesh_expr_import (tree_import_tests.MeshExprImportTest) ... ok
test_profile_import (tree_import_tests.ProfileImportTest) ... ERROR
test_script_uv_import (tree_import_tests.ScriptUvImportTest) ... ok

======================================================================
ERROR: test_profile_export (tree_export_tests.ProfileExportTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/tests/tree_export_tests.py", line 22, in test_profile_export
    self.assert_json_equals_file(export_result, "profile.json")
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/utils/testing.py", line 178, in assert_json_equals_file
    expected_result = json.loads(data)
  File "/home/portnov/SSD/soft/blender-2.79-linux-glibc219-x86_64/2.79/python/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/portnov/SSD/soft/blender-2.79-linux-glibc219-x86_64/2.79/python/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/portnov/SSD/soft/blender-2.79-linux-glibc219-x86_64/2.79/python/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_profile_import (tree_import_tests.ProfileImportTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/tests/tree_import_tests.py", line 22, in test_profile_import
    import_tree(new_tree, self.get_reference_file_path("profile.json"))
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 713, in import_tree
    nodes_json = json.load(fp)
  File "/home/portnov/SSD/soft/blender-2.79-linux-glibc219-x86_64/2.79/python/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/portnov/SSD/soft/blender-2.79-linux-glibc219-x86_64/2.79/python/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/portnov/SSD/soft/blender-2.79-linux-glibc219-x86_64/2.79/python/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/portnov/SSD/soft/blender-2.79-linux-glibc219-x86_64/2.79/python/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 12 tests in 0.113s

FAILED (errors=2)
```

**Comment by zeffii** [comment]
yeah, tackling profilenodemk2 `def storage_*` now

**Comment by portnov** [comment]
I consider main goals of this PR as done and going to merge it.
Off course current set of tests is very small, but this is only the beginning.

@zeffii @DolphinDream @vicdoval  @Kosvor2 @nortikin @Durman 
Please familiarize with description of this PR, and you are welcome to review the tests.
Also everyone is welcome to start writing tests for other parts of code.

I also managed to set up a travis-ci.org builds, I started from separate branch in my clone of this repo. You can see what it looks like at https://travis-ci.org/portnov/sverchok/ . Do we want such thing for this repo? If yes, then we need to ask @nortikin to set up an account (it is pretty easy).

**Comment by zeffii** [comment]
can you merge master into this and test it please portnov?

**Comment by portnov** [comment]
Yes, i'm doing it now.

**Comment by portnov** [comment]
@zeffii Yes, and tests work now: https://travis-ci.org/portnov/sverchok :)

**Comment by zeffii** [comment]
it's good for me to occasionally re-read that iojson code.  It's not obfuscated on purpose :)

**Comment by zeffii** [comment]
obligatory unit testing gif:

https://i.imgur.com/3b4uf.gif

**Comment by portnov** [comment]
huh.

**Comment by zeffii** [comment]
the thief did not consider the exit camera, and that's the only camera that spotted him carrying the flatscreen :)

**Comment by nortikin** [comment]
ok, how to do it?

**Comment by nortikin** [comment]
i see we need to make new push commit for travis to work? am i right?

**Comment by portnov** [comment]
@nortikin you need just to "activate" this repo in settings of your travis profile. After that, any push to this repo will initiate a build. And moreover, any pull-request will initiate a build too, so that we will be able to see if PR brokes some tests.

**Pull request merged**
