### PR TITLE
New Distance Point Plane Node

### PR DESCRIPTION
**Pull request by vicdoval**
Keeping on with the basics

distance_point_plane_sverchok_blender_project_on_plane

distance_point_plane_sverchok_blender_project_on_plane

distance_point_plane_sverchok_blender_nodes

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
Huh :)

I was thinking about a series of nodes that work with generic equations of line and plane. For example, a node that takes two planes and returns line... For now it's just API in #2421.

**Comment by portnov** [comment]
Probably we should somehow merge two versions of API, it has similar functionality (but not exactly the same).

**Comment by vicdoval** [comment]
@portnov :) 
I was also perceiving the convergence of our ideas.
When I was doing the previous node i found the mathutils.geometry functions and I thought they could be pretty useful for sverchok.
I did all the nodes and they are in this branch (in the analyzer category https://github.com/vicdoval/sverchok/tree/geometry_nodes
I decided to split them in different pull request to expose them one  by one.
On this three  #2416 #2425  and #2426  I have done a NumPy implementation that usually perfoms faster
I have not pulled but coded:
- intersect_cirlce_circle
- intersect_line_line
- intersect_line_sphere
- intersect_plane_plane

The nodes just match the data and call to the mathUtils function. Probably would be faster a NumPy implementation but I'm not sure if i will do it before making the pull request because they already work and it could take a while to crush the math part.
There is missing intersect_line_plane but it could be very similar to the others

You could use them as a base or something to compare or improve.

This node offers already two different implementations but if you find another which can be faster at any case it could be added :)

Also i have started to add the images of the docs to this branch https://github.com/vicdoval/sverchok/tree/docs_images so they don't loose the images names if you want to use it to just create do a PR with your changes

**Comment by portnov** [comment]
NumPy approach has a lot of performance potential in case when you are computing a lot of data at once (for example, compute distances from many points to the plane): it can effectively vectorize computations (afaik numpy uses SIMD processor instructions when they are available). When dealing with single values, I don't think numpy is any faster than mathutils.
It has to be reflected in API; for example, you can write a method like distances_from_points(points_list), which will be much faster than `[distance_from_point(point) for point in points_list]`.

**Comment by portnov** [comment]
Also, I have a request. Could you please add some comments to your code, especially to parts where you are doing numpy calls? Something like `vp0 = p_triang - v0[np.newaxis, :]` is not obvious for one who does not know what algorithm you are implementing. It might help to describe mathematical background of such code in comments, maybe add wikipedia links if necessary.

**Comment by vicdoval** [comment]
You are right, NumPy could be even slower when you calculate just a couple of points, but the performance problems came when you need to do many calculations, and that is when Numpy shines.

I added this [link](https://www.scratchapixel.com/lessons/3d-basic-rendering/ray-tracing-rendering-a-triangle/barycentric-coordinates) in the numpy implementation and expand some variable names :D

**Comment by nortikin** [comment]
https://vk.com/wall-35076122_10454

**Pull request merged**
