### PR TITLE
Torus node MK2 with angle units + new features

### PR DESCRIPTION
**Pull request by DolphinDream**
- Add angle units support via the AngleHelper class
- Add new “exponent” settings (for additional toroidal shapes)
- Update variable names to conform to python style
- Minor UI update and optimizations

:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

SV-TorusMK2-UI1

### CODE REVIEW

**Comment by DolphinDream** [comment]
An **exponent** setting example.

SV-TorusMK2-Example1

**Comment by vicdoval** [comment]
Something that could be added to this node is "Parallels Profile" and "Meridians Profile" as in the `Cylinder Node `
image

**Comment by DolphinDream** [comment]
And a live demo..

TorusMK2-Demo1

**Comment by DolphinDream** [comment]
I guess we *could* call this Super Toroid node :) 

https://en.wikipedia.org/wiki/Supertoroid

800px-Supertorus_table

**Comment by vicdoval** [comment]
@DolphinDream have you ever used NumPy? I think the node performance could benefit a lot from a Numpy implementation 😃

**Comment by DolphinDream** [comment]
More samples ...

SV-TorusMK2-ExponentSamples-NodeTree

SV-TorusMK2-ExponentSamples-1

SV-TorusMK2-ExponentSamples-2

**Comment by DolphinDream** [comment]
> @DolphinDream have you ever used NumPy? I think the node performance could benefit a lot from a Numpy implementation 😃

I have not :) It’s pretty fast as it is though. Btw, the demo animation above looks choppy because it’s a gif conversion from a mov capture :)

**Comment by DolphinDream** [comment]
A squarish Mobius band example. 

SV-TorusMK2-Demo2

**Pull request merged**
