### PR TITLE
New Formula Mk5 node

### LINKED ISSUE #3727: Formula+ overrides default node property "dimensions"
I'm trying to fix some issues with the SV Display Nodes panel

Everything seems fixable but this override makes me doubt:
Do we need a new version of the node "mk5" or just change that property and potentially break some layouts?

Another idea would be changing the code of the "Display Nodes panel" to get node.width and node.height in stead of node.dimensions....

### PR DESCRIPTION
**Pull request by vicdoval**
Fixes #3727 and gathers some of the ideas said in that issue.

More flexibility with a new formula socket that has some properties:
  Depth: Exposed depth to the formula 1 would mean exposing scalars, 2 would be [scalar, ]
  Transform: Pre transformation to Vector, to Numpy Array, to set or to String

image
image
Output socket options:
image

Numpy can be used for calculations
image

Example exposing attributes of a surface and using the node to perform a to_nurbs transform
image

- [x] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
If the node is in Alpha category should new version of it be created? I thought Alpha category means that API of a node can be changed without backward compatibility.

**Comment by vicdoval** [comment]
the mk4 has been there since may of 2020...

**Comment by nortikin** [comment]
Ahahaha!! that is what I wanted! Thanks!!!

**Comment by Durman** [comment]
The name of the Formula socket is at least strange. I always thought that we have sockets type to determine which type of data the node is expecting.

**Comment by 0000888888880000** [comment]
[MBEW.O____NOITCNUF_SUIBAF____O____FABIUS_FUNCTION____O.WEBM](https://github.com/mcneel/compute.rhino3d/assets/139945999/4d7104c6-f2f4-4402-ae99-d094f5064837)

                                                                                                                                                    [⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F) [FƨuidaF](HTTP://WEB.ARCHIVE.ORG/web/RESOURCES.WOLFRAMCLOUD.COM/FunctionRepository/resources/FabiusF) [⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://GHOSTARCHIVE.ORG/search?term=https%3A%2F%2Fgithub.com%2Fnortikin%2Fsverchok%2Fpull%2F3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://ARCHIVE.IS/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://WEB.ARCHIVE.ORG/web/*/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://WEB.ARCHIVE.ORG/web/*/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://ARCHIVE.IS/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://GHOSTARCHIVE.ORG/search?term=https%3A%2F%2Fgithub.com%2Fnortikin%2Fsverchok%2Fpull%2F3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F) [FabiusF](HTTP://WEB.ARCHIVE.ORG/web/RESOURCES.WOLFRAMCLOUD.COM/FunctionRepository/resources/FabiusF) [⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)                                                                                                                                                    
                                                                                          [⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F) [DԐtolPnoiƨroTɘrutavruϽ](HTTP://WEB.ARCHIVE.ORG/web/RESOURCES.WOLFRAMCLOUD.COM/FunctionRepository/resources/CurvatureTorsionPlot3D) [⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://GHOSTARCHIVE.ORG/search?term=https%3A%2F%2Fgithub.com%2Fnortikin%2Fsverchok%2Fpull%2F3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://ARCHIVE.IS/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://WEB.ARCHIVE.ORG/web/*/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://WEB.ARCHIVE.ORG/web/*/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://ARCHIVE.IS/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://GHOSTARCHIVE.ORG/search?term=https%3A%2F%2Fgithub.com%2Fnortikin%2Fsverchok%2Fpull%2F3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F) [CurvatureTorsionPlot3D](HTTP://WEB.ARCHIVE.ORG/web/RESOURCES.WOLFRAMCLOUD.COM/FunctionRepository/resources/CurvatureTorsionPlot3D) [⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)                                                                                          
                                                                                          [⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F) [DԐtolPnoiƨroTɘrutavruϽ](HTTP://WEB.ARCHIVE.ORG/web/RESOURCES.WOLFRAMCLOUD.COM/FunctionRepository/resources/CurvatureTorsionPlot3D) [⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://GHOSTARCHIVE.ORG/search?term=https%3A%2F%2Fgithub.com%2Fnortikin%2Fsverchok%2Fpull%2F3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://ARCHIVE.IS/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://WEB.ARCHIVE.ORG/web/*/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://WEB.ARCHIVE.ORG/web/*/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://ARCHIVE.IS/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://GHOSTARCHIVE.ORG/search?term=https%3A%2F%2Fgithub.com%2Fnortikin%2Fsverchok%2Fpull%2F3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F) [CurvatureTorsionPlot3D](HTTP://WEB.ARCHIVE.ORG/web/RESOURCES.WOLFRAMCLOUD.COM/FunctionRepository/resources/CurvatureTorsionPlot3D) [⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)                                                                                          
                                                                                                                                                    [⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F) [FƨuidaF](HTTP://WEB.ARCHIVE.ORG/web/RESOURCES.WOLFRAMCLOUD.COM/FunctionRepository/resources/FabiusF) [⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://GHOSTARCHIVE.ORG/search?term=https%3A%2F%2Fgithub.com%2Fnortikin%2Fsverchok%2Fpull%2F3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://ARCHIVE.IS/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://WEB.ARCHIVE.ORG/web/*/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://WEB.ARCHIVE.ORG/web/*/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://ARCHIVE.IS/GITHUB.COM/NORTIKIN/SVERCHOK/pull/3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)[◌](HTTP://GHOSTARCHIVE.ORG/search?term=https%3A%2F%2Fgithub.com%2Fnortikin%2Fsverchok%2Fpull%2F3874)[⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F) [FabiusF](HTTP://WEB.ARCHIVE.ORG/web/RESOURCES.WOLFRAMCLOUD.COM/FunctionRepository/resources/FabiusF) [⚪](HTTP://WEB.ARCHIVE.ORG/web/*/BE.WIKIPEDIA.ORG/wiki/%D1%96%D0%BD%D1%82%D1%83%D1%96%D1%86%D1%8B%D1%8F)                                                                                                                                                    

[MBEW.O____NOITCNUF_SUIBAF____O____FABIUS_FUNCTION____O.WEBM](https://github.com/mcneel/compute.rhino3d/assets/139945999/4d7104c6-f2f4-4402-ae99-d094f5064837)

**Pull request merged**
