### PR TITLE
Mesh viewer refactoring - using pointer property

### PR DESCRIPTION
**Pull request by Durman**
## Addressed problem description

#3371
#3390

The node should work much faster. More readable code. Collection selector will be available. No name intersection problems.

## TODO
- [x] Selection objects and create material operators
- [x] Picking names refactoring ?
- [x] Apply matrixes (two variants to object/mesh ?)
- [x] Merge mesh
- [x] Smooth mesh
- [x] Wireframe mesh
- [x] Apply material indexes
- [x] Show / hide data by node tree request
- [x] Topology changes test option
___
- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete.
- [x] Manual testing done. 
- [x] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
Final UI:

**Comment by vicdoval** [comment]
A small suggestion:
Leaving the  label as "Mesh Viewer" and only changing it when the node is hidden so it is clearer in every screenshot what node is being used

**Comment by Durman** [comment]
2.5 times speed up if input topology is changed

```Text
[DEBUG] sverchok.core.update_system: Processed  Viewer BMesh in: 0.3033
```

```Text
[DEBUG] sverchok.core.update_system: Processed  Mesh viewer in: 0.1215
```

5.5 times speed up if topology is unchanged:

```Text
[DEBUG] sverchok.core.update_system: Processed  Viewer BMesh in: 0.1707
```

```Text
[DEBUG] sverchok.core.update_system: Processed  Mesh viewer in: 0.0315
```

**21 times speed up if input vertices are float 32 array:**

```Text
[DEBUG] sverchok.core.update_system: Processed  Mesh viewer in: 0.0080
```

speed test 2

speed test 1

**Comment by Durman** [comment]
Show in viewport with tree property changes.

show viewport

**Comment by Durman** [comment]
Unlock origin -
unlock origin

**Comment by vicdoval** [comment]
@Durman  A little detail :)
The matrix socket: the quik_link button does not disappear and it does not provide list length information. (makes it look broken) 
image

**Comment by Durman** [comment]
I will have a look.

**Comment by vicdoval** [comment]
@Durman when you did this refactor did you test this?
```
me.edges.add(count=len(verts))
me.edges.foreach_set("vertices", edges.ravel())
```

Taken from here https://blender.stackexchange.com/questions/190547/mesh-edges-foreach-set-doesnt-update

**Comment by Durman** [comment]
Look at the `generate_mesh` function in this file - https://github.com/nortikin/sverchok/blob/mesh_data_structure/nodes/mesh/viewer_mesh.py

I found out that using bmesh approach is faster and much more robust. Adding mesh data right inside mesh data block is fragile solution which can very eaily cause a Blender crash.

I was posting some tests here - https://github.com/nortikin/sverchok/issues/2767#issuecomment-586945916

**Comment by vicdoval** [comment]
I see.. 
The only thing is that bmesh does not like numpy arrays. Does it?
And if you have numpy edges it is slower to turn them to python and setting  them than to set them directly in numpy
```
import bpy
from timeit import timeit
import numpy as np

NUM = 1000000

def get_mesh():
    me = bpy.context.active_object.data
    me.clear_geometry()
    me.vertices.add(NUM)
    me.edges.add(NUM - 1)
    return me

edges = [[i, i + 1] for i in range(NUM - 1)]
np_edges = np.array(edges, 'i')

def test1(me, edges):
    for me_e, e in zip(me.edges, edges):
        me_e.vertices = e
        
def test2(me, edges):
    me.edges.foreach_set('vertices', [i for e in edges for i in e])
    
def test3(me, np_edges):
    me.edges.foreach_set('vertices', np_edges.flatten())
    
def test4(me, np_edges):
    me.edges.foreach_set('vertices', [i for e in np_edges for i in e])

def test5(me, np_edges):
    me.edges.foreach_set('vertices', [i for e in np_edges.tolist() for i in e])

print("Test 3", timeit("test3(me, np_edges)", "from __main__ import test3, np_edges, get_mesh; me = get_mesh()", number=1))
print("Test 4", timeit("test4(me, np_edges)", "from __main__ import test4, np_edges, get_mesh; me = get_mesh()", number=1))
print("Test 5", timeit("test5(me, np_edges)", "from __main__ import test5, np_edges, get_mesh; me = get_mesh()", number=1))
print("Done")


```

```
Test 3 0.1472976000000017
Test 4 0.7561349000000064
Test 5 0.2072122000000718
```

**Comment by Durman** [comment]
Probably this is one of the reasons why we don't use numpy edges.))

But if the Mesh Viewer node would use the `me.edges.foreach_set` function how to make the fast test that the input mesh is correct? 
When you reconnect the node from one mesh to another you cant reconnect `vertices`, `edges` and `polygons` simultaneously. So there can be the cases when given edges point to non existent points and this causes the crash.

**Comment by vicdoval** [comment]
maybe `np.amax(np_edges)>NUM_VERTS` could do a fast check

Anyway accepting numpy edges with a tolist in the mesh viewer wouldn't be that bad...

**Pull request merged**
