### PR TITLE
Csg boolean mk2

### PR DESCRIPTION
**Pull request by Kosvor2**
Now accepts a nested lists of meshes. In addition, there is a new mode in which the nested objects are connected to each other one by one.

csg_booleanmk2_1

### CODE REVIEW

**Comment by kalwalt** [comment]
Did you see this my post in blender-stackexchange? :smile: 
https://blender.stackexchange.com/questions/78104/what-is-the-best-approach-to-do-boolean-operations-with-multi-meshes-in-sverchok

**Comment by Kosvor2** [comment]
СSG creates unconnected islands of geometry which become noticeable if you subdivide the resulting mesh and smooth the vertices after that. I just want to say that this is not caused by changes in this pull request, but this problem was originally there.

**Comment by Kosvor2** [comment]
Added option to output only result of last iteration instead of each one like on first pic.

**Comment by kalwalt** [comment]
It works perfectly! Thank a lot for this!

**Comment by enzyme69** [comment]
@Kosvor2 This matrix thing does CSG Boolean to first Object?

For example:
- Start with Monkey
- Next sequences = bunch of boxes

Monkey + Cube + Cube + Cube?
Or Monkey - Cube - Cube - Cube?

**Comment by Kosvor2** [comment]
@enzyme69
When nested mode is used, it does apply next object to result of applying of previous object to previous result and so on. In normal mode, it applies object "A" to object "B" until they all ends (A shorter list of objects it extends to be of the same size as longer list).

**Comment by zeffii** [comment]
looks like this now
image

**Pull request merged**
