### PR TITLE
Object ID out MK2

### PR DESCRIPTION
**Pull request by Kosvor2**

### CODE REVIEW

**Comment by Kosvor2** [comment]
obj out

Now can output Vert\Poly normals and have obj socket. Also works faster because of "is_linked" checks.

**Comment by Kosvor2** [comment]
Perhaps it worth to also add PolygonCenters and PolygonArea sockets?

**Comment by zeffii** [comment]
`Matrices` not matrixes

**Comment by nortikin** [comment]
out? maybe it is in?

**Comment by zeffii** [comment]
or `Object to PyData`

**Comment by Kosvor2** [comment]
Icospheres placed on torus:
ice in blender

**Comment by enzyme69** [comment]
Gasp, I didn't know Sverchok can do this...!?! Keep it coming Kosvor, I am
learning.



------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by nortikin** [comment]
i think people not look at alpha nodes menu at all, have to make docs for alpha and finish what can be.
so we have also missunderstanding in kosvor methods. That is real gap. Show some pipelines and make jsons templates will help, but maybe it is time to make menu folder for blander-aided kosvor nodes. @Kosvor2 how to describe your nodes in one word?

**Comment by Kosvor2** [comment]
There are still a lot of things to be done to bring these nodes in decent condition that they could be advertised. By the way, "Vertex Colors" node is not visible in the menu just for me, or in the master branch too?

**Comment by zeffii** [comment]
it's very possible that I missed a few nodes in the menu shuffle.. for the help feature..

**Comment by zeffii** [comment]
currently there are errors in the menu, missing nodes (I don't know what to call this)

AttributeError: 'RNA_Types' object has no attribute 'SvPointOnMeshNode'
AttributeError: 'RNA_Types' object has no attribute 'SvRayCastSceneNode'

**Comment by Kosvor2** [comment]
i have droped them into "old_nodes" directory:

https://github.com/nortikin/sverchok/blob/master/old_nodes/closest_point_on_mesh.py
https://github.com/nortikin/sverchok/blob/master/old_nodes/scene_raycast.py

perhaps i need to delete them from index.md?

**Comment by zeffii** [comment]
yep

**Comment by zeffii** [comment]
yeah, i'm sure that the reason that Vertex Colors node won't show in the menu's is because the error encountered before in the list..  SvRayCastSceneNode  /  SvRayCastObjectNode

**Comment by zeffii** [comment]
tested. yep. that was the reason.

**Comment by zeffii** [comment]
@nortikin maybe @Kosvor2 needs collaborator status again so he can push autonomously ? :)

**Comment by nortikin** [comment]
forgot how to give collaborator... (((

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/invitations
invited, it is easy.

**Pull request merged**
