### PR TITLE
File Path Node

### PR DESCRIPTION
**Pull request by vicdoval**
A small File Path Node (#3232)
It can select many files or one directory.
Also added new socket type and a way to define it in the SNL (the only use at the moment)

Example of extracting location from EPW file (using sverchok-extra with LadyBug)
image

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by vicdoval** [comment]
For me is more than enough to pass only the strings and I don't see clearly the use of doing anything else but I'm open another ideas

**Comment by zeffii** [comment]
no i think it's ok, nodes that use the FL socket can implement their own way of reading/decomposing the filepaths , but passing FP to output should be consistent across all nodes that use that socket type.

**Comment by zeffii** [comment]
i think this will either be fine, or we will figure out soon if another 'convention' is preferred.

**Comment by nortikin** [comment]
```python
"""
in verts v .=[[]] n=2
enum = золотое.kml серебрянное.kml
inject
include <золотое>
out  verts  v
out  names  s
"""


def ui(self, context, layout):
    layout.prop(self, 'custom_enum',expand=True)
    cb_str = 'node.scriptlite_custom_callback'
    a = layout.operator(cb_str, text='.kml>names+verts')
    a.cb_name='my_operator'

#ND = self.node_dict.get(hash(self))               #
#if ND:                                            #
#    callbacks = ND['sockets']['callbacks']        #    this will be hidden in the node eventually 
#    if not 'my_operator' in callbacks:            #
#        callbacks['my_operator'] = my_operator    #

def my_operator(self, context):
    ''' converting kml to sverchok data '''

    import bpy
    import re
    import ast
    from sverchok.utils.listutils import listinput_set_rangeI

    t = bpy.data.texts['золотое']
    tt = t.lines[0].body
    nc = re.findall(r'<name>([\d\w\-\"\.\,\s]+)</name>\S+<coordinates>(\S+)</coordinates>',tt)
    names,verts = [],[]
    for n,c in nc:
        names.append(n)
        verts.append([i for i in ast.literal_eval(c)])
    self.id_data.nodes['Scripted Node Lite'].outputs['names'].sv_set([names])
    self.id_data.nodes['Scripted Node Lite'].outputs['verts'].sv_set([verts])
    print('Парсинг городов закончился: ',names,verts)

    # all the shit with list input node
    LN = self.id_data.nodes.new('SvListInputNode')
    listinput_set_rangeI(LN,verts)
    return {'FINISHED'}

self.make_operator('my_operator')
```

**Comment by nortikin** [comment]
https://gist.github.com/605f50169b27410b7d56be06485423b1

**Pull request merged**
