### PR TITLE
Lamp out node (WIP)

### PR DESCRIPTION
**Pull request by portnov**
TODO:
* [ ] #1936
* [x] Use SvColorSocket
* [ ] documentation

### CODE REVIEW

**Comment by portnov** [comment]
screenshot_20171218_201451

**Comment by nortikin** [comment]
just ne rabotaet
colors defined by one object of colors and every color in separate object both approaches not work.


http://pasteall.org/pic/fe2e517b4e30f4acdd019701c5630213

**Comment by Kosvor2** [comment]
@nortikin are you tested in current master or in this branch? I tried in master and
it works for both metods:
lamp_colors234

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/blob/master/nodes/viz/lamp_out.py#L210
and
https://github.com/nortikin/sverchok/blob/master/nodes/viz/lamp_out.py#L290
something wrong with this line and all next lines.
and why color without alpha come error? https://github.com/nortikin/sverchok/blob/master/nodes/viz/lamp_out.py#L248 here is no alpha needed

**Pull request merged**
