### PR TITLE
Automat

### PR DESCRIPTION
**Pull request by zeffii**
not full implementation yet.

### CODE REVIEW

**Comment by zeffii** [comment]
this seems to work.. i haven't found anything broken as a result..

**Comment by zeffii** [comment]
any objections to this?

**Comment by ly29** [comment]
I have some lingering doubts but I think we should do this. 

Next boilerplate we could remove is all the register class in each file and use register module instead,

**Comment by zeffii** [comment]
at any rate, we won't be hand enumerating  the content of the nodes directories anymore. even if the code to populate `nodes_dict` eventually is nothing like this PR.

**Comment by ly29** [comment]
Exactly.

**Pull request merged**
