### PR TITLE
Zeffii patch 3

### PR DESCRIPTION
**Pull request by zeffii**
should test OK.

### CODE REVIEW

**Comment by zeffii** [comment]
ideally we should start using more unique names for these Object basenames within our example .jsons , to avoid object/datablock "polution".

**Comment by zeffii** [comment]
@portnov right?

**Comment by zeffii** [comment]
the other side is ofcourse that these json tests are going to be repeatedly and sequentially loaded into a .blend which is unlike the normal user experience. But the .blend file in a state where there are many Objects from viewers in previous json imports,  but we lack a cleanup step.

**Comment by portnov** [comment]
So, you've just renamed objects in those jsons to make tests pass?...

**Comment by zeffii** [comment]
just a different basename , i think we can call this issue "name space polution".  

until we have a "wipe current blend datablocks" function prior to each json test,   this renaming is a sane solution.

**Comment by zeffii** [comment]
because what would be the behaviour in real usecase scenario , where the is an active BMeshViewer generating Alpha objects,  and you then import a json that creates PolyLines with basedata_name Alpha.

not very satisfying :) but at least it's clear why the test is/was failing.

**Comment by zeffii** [comment]
maybe SvObjectHelper should include a test functing, called at the very top of `process`, to end early and raise an Exception if it is in the same .blend as a Node generating objects with the same Basename.

i've tried to avoid thinking about that logic.

**Pull request closed without merging**
