### PR TITLE
Add 3DProject node (WIP)

### PR DESCRIPTION
**Pull request by DolphinDream**
The node projects a mesh from 3D space onto a 2D space.

For start, the node does a perspective projection onto a plane.
Further development will add cylindrical and spherical projection as well and other features.

- [ ] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [ ] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

sv-3dprojectnode-ui

sv-3dprojectnode-example1

### CODE REVIEW

**Comment by DolphinDream** [comment]
Here's the node tree used for the previous screen capture.

sv-3dprojectnode-nodetree-example1

And the Blend containing the node tree:
[3DProjectNode-dev1.blend.zip](https://github.com/nortikin/sverchok/files/2917649/3DProjectNode-dev1.blend.zip)

As well as some live demos here:

https://youtu.be/DINKhTH0w_4
https://youtu.be/OVxfOxEoBEw

**Comment by DolphinDream** [comment]
And some live demos here:

[](http://www.youtube.com/watch?v=DINKhTH0w_4 "3DProjectNode Demo1")

[](http://www.youtube.com/watch?v=OVxfOxEoBEw "3DProjectNode Demo2")

(note: embedded links generated using this little tool: http://embedyoutube.org)

And in case the embedded youtube videos do not work for you here are the actual links:

https://youtu.be/DINKhTH0w_4
https://youtu.be/OVxfOxEoBEw

**Comment by Durman** [comment]
I tried something similar before.


<details> 
  <summary>gif</summary>  

projection to matrix

shadows


</details>

**Comment by portnov** [comment]
This should be rebased to b28 branch too I think?

**Comment by DolphinDream** [comment]
> This should be rebased to b28 branch too I think?

Certainly. I've been working on this (for 2.79). i'll try to rebase and integrate this in B28 soon.
 
Btw, what's the status of 2.79? Should any new nodes be added to this branch (master)? If i finish this node should i put in 2.79, 2.80 or both ?

**Comment by portnov** [comment]
I'd suggest that
1) all new features go to b28 only
2) 2.79 branch would be still master for now, as it is much better tested
3) 2.79 branch would receive bugfixes
4) in some foreseeable feature we would rename current master to b279_master and current b28 branch to master.

**Comment by portnov** [comment]
@zeffii  your thoughts on this?

**Comment by zeffii** [comment]
@portnov   yes, as you say. that's a logical progression.

**Comment by DolphinDream** [comment]
(minor aspect) Any suggestions as to what would be the more appropriate name for this node?
Currently it’s 3D Project and I was considering changing the name to either:

- 3D Projection
- 3D Projector 
- 3D to 2D Projection 
- 2D Project 
- 2D Projection
- 2D Projector

The node projects a mesh in 3D space onto a 2D surface (whether a plane, cylinder or sphere).

**Comment by portnov** [comment]
"Project mesh to surface"?

**Comment by vicdoval** [comment]
Did you check the Flat Geometry node?

**Pull request closed without merging**
