### PR TITLE
adds new option to solidify

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
seems to work as a direct replacement, no need for mk2 @ly29  test before push

**Comment by ly29** [comment]
Working fine but I have some structural issues. Restored for my sanity.

Mainly removing the self argument and (older) set creation in main function.

**Comment by ly29** [comment]
@zeffii 
otherwise working fine.

**Comment by zeffii** [comment]
mode_options = [(op, op, '', idx) for idx, op in enumerate(['fast','accurate'])]

**Comment by zeffii** [comment]
this doesnt work `mode_options = [(op, op, '', idx) for idx, op in enumerate(['fast accurate'])]`

**Comment by zeffii** [comment]
pushed fix

**Comment by ly29** [comment]
Good.

**Pull request merged**
