### PR TITLE
"Objects along edge" update

### PR DESCRIPTION
**Pull request by portnov**
* Simplify default algorithm a bit.
* Introduce 2 new algorithms of object rotation calculation. It is in general not a trivial task to rotate a 3D object along a vector, because there are always 2 other axes of object and it is not clear where should they be directed to. So, this node supports 3 different algorithms of object rotation calculation: Householder, Tracking and Rotation Difference. In many simple cases, all these algorithms will give exactly the same result. But in more complex setups, or in some corner cases, results can be very different. So, just try all algorithms and see which one fits you better.
* For Tracking algorithm, "Up axis" parameter is introduced.
* Clean up UI a bit.

Default algorithm is the Householder, which was the only algorithm previously available. So the changes are fully backwards compatible, the new code should work in old scenes exactly the same way.

I'm more or less sure in this code, but gonna wait a couple of days before merging, in case someone has some ideas about code or smth.

### CODE REVIEW

**Comment by portnov** [comment]
For the illustration, the same thingy with different algorithms:

Householder:
householder

Tracking:
tracking

**Comment by portnov** [comment]
suzanne-spiral

**Comment by enzyme69** [comment]
How did you make this one so tidy:
https://github.com/nortikin/sverchok/pull/1884#issuecomment-347963376

**Comment by portnov** [comment]
@enzyme69 
https://gist.github.com/9b3e6902f0476e194f5fa471b287fb25

**Pull request merged**
