### PR TITLE
fix id prop name, drop punctuation

### LINKED ISSUE #3583: Sverchok Not working anymore with Blender daily build 2.91.0
Sverchok Not working anymore with Blender daily build 2.91.0

image

### PR DESCRIPTION
**Pull request by zeffii**
IDProps can now no longer include punctuation.

fixes #3583

### CODE REVIEW

**Comment by portnov** [comment]
I've run this on 2.90, Line node works as expected :) What else to check? Export/import?

**Comment by portnov** [comment]
Export/import seems to be working too..

**Comment by Durman** [comment]
Import/export does not deal with IDProps

**Comment by zeffii** [comment]
only nodes that call Freeze/ unfreeze i think..

**Comment by Durman** [comment]
I'm having fun with import/export about a week and didn't see using ID properties yet.

**Pull request merged**
