### PR TITLE
sweep node

### PR DESCRIPTION
**Pull request by zeffii**
maybe we need it, maybe we don't

### CODE REVIEW

**Comment by zeffii** [comment]
image

there are several issues to resolve..

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
image

**Comment by enzyme69** [comment]
Hi Zeffii, got blend with working sweep node modulator to make that elephant trunk above? Is the node supposed to module different shapes and make interpolation weep?

**Pull request merged**
