### PR TITLE
Line mk2

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
more likely to be useful with a mode switch, 

 - one that expects a list of lists containing various step distances  `[[1.2, 2.2],[3.2, 1.2]]`
 - one that just expects a single list of step widths  `[[2.0, 2.3, 4.3]]

I don't think i'd ever need to make my setup so complicated as to need both modes mixed,

**Comment by nortikin** [comment]
than makeline put to geom.py file ???

**Comment by nortikin** [comment]
than series of lines - from point to point, from point to direction, ortho

**Comment by enzyme69** [comment]
So... Line MK2 will not happen? I'll use List Split in the mean time. [[ []
[] [] ]]

**Comment by zeffii** [comment]
i thought about it more, and while it makes sense to have an axis picker for all generators (where it makes sense) , a simpler solution for now is a single rewire node.

image

it solved a more general problem.

**Comment by zeffii** [comment]
image

**Comment by enzyme69** [comment]
That's cool, I like it!

**Comment by zeffii** [comment]
also making it so you can send 0 to X,Y,or Z  (0 or -1, 1 )

**Pull request closed without merging**
