### PR TITLE
B28 join fix

### PR DESCRIPTION
**Pull request by zeffii**
simpler code, but doesn't solve the real problem either.

doing anything inside `self.update`,  will trigger any time the update function of any other node is triggered.

so if you do a print('hahah') in list join's  `def update()` it is triggered by connecting/touching a socket of any other node, even if that node is not connected to anything..

### CODE REVIEW

**Comment by zeffii** [comment]
maybe we should capture the update function also.. in the svnodecommon
```
sv node common:

    update_triggered_by_node: StringProperty(...)

    def update(self):
        update_triggered_by_node = self.name
        try:
            self,sv_update()
        finally:
            update_triggered_by_node = ""

```

i don't know .. this update stuff is starting piss me off and mystify me.

**Comment by Durman** [comment]
Update function is called upon any changes of a node tree. It is [default behaviour.](https://docs.blender.org/api/current/bpy.types.Node.html#bpy.types.Node.update) If new node is created or deleted or new link is created or deleted update function is called of every node in tree.

**Comment by zeffii** [comment]
i didn't realize that every single node which implements the update function, gets that function called by editor changes, it would be more useful ( i think..)  if we could localize what node triggered the update.

**Comment by Durman** [comment]
I have made some investigation in update system of Blender:

If `some_node.outputs.new('StringSocket', 'Name')`:
- nodetree update fuction is called
- the node update fuction is called **(update fuction of other nodes is not called)**

if `node_group.links.new(Socket1, Socket2)`:
- nodetree update function is called
- update function of all nodes in the nodetree is called

**Comment by zeffii** [comment]
yep, and sockets.remove / move also trigger updates.

**Pull request closed without merging**
