### PR TITLE
duplicate image found

### PR DESCRIPTION
**Pull request by stansu**
as title

### CODE REVIEW

**Comment by Durman** [comment]
Do you think you can generate right picture?

**Comment by stansu** [comment]
If the author did not have original file, maybe I can.

**Comment by Durman** [comment]
The layout seems pretty simple to recreate it from scratch.))

**Comment by stansu** [comment]
> 
> 
> The layout seems pretty simple to recreate it from scratch.))

how can i upload image?

**Comment by Durman** [comment]
You can attach an image to a message in this thread, this will generate a link which can be used to put into the documentation.

**Comment by stansu** [comment]
圖片
圖片
圖片
圖片
圖片
圖片
圖片
圖片

**Comment by stansu** [comment]
@Durman is this ok to you?
https://github.com/stansu/sverchok/blob/patch-1/docs/nodes/list_struct/levels.rst

**Comment by Durman** [comment]
Looks like this is repeated twice now.

**Comment by stansu** [comment]
圖片

**Comment by stansu** [comment]
> 
> 
> Looks like this is repeated twice now.
> 

my bad. now should be ok.

**Comment by Durman** [comment]
Thanks. Now changes are in docs - http://nortikin.github.io/sverchok/docs/nodes/list_struct/levels.html

**Pull request merged**
