### PR TITLE
Revert: SvRecursiveNode mixin (#3954)

### PR DESCRIPTION
**Pull request by Durman**
If data with vertices was connected to mask socket it changed shape fo all output data.

## Preflight checklist

- [x] Code changes complete.

### CODE REVIEW

**Comment by vicdoval** [comment]
Why would you connect vertices data to the mask input? Is makes sense if you input a mask with a level 3 (as the vertices lists) the matching of data changes the output compared to if you input the usual level 2 mask

**Comment by Durman** [comment]
I used mask node for filtering vertices data. The node does not provide another way.

I'm not against new functionality but it should extend existing functionality or create next version of a node if it changes existing behaviour.

**Comment by vicdoval** [comment]
> I used mask node for filtering vertices data. The node does not provide another way.
> 
> I'm not against new functionality but it should extend existing functionality or create next version of a node if it changes existing behaviour.

This behaviour look to me more like a bug than a feature (what vectors are a True mask (1,1,1), (0,2,1)...)

**Comment by Durman** [comment]
Hm.. it doesn't look like a bug to me. Any way it's useful functionality and there is no any alternative to it. I used it in many layouts and I guess that other users may do this too. My opinion is that this changes should cause another node version to be created.

**Comment by vicdoval** [comment]
But in which cases the vector in interpreted as false value? Only when is (0,0,0)?

**Comment by Durman** [comment]
I guess never.

**Comment by vicdoval** [comment]
This pr may break layouts made after the SvRecursiveNode mixin to avoid breaking layouts (with a weird feature use) that existed previously. I think it should be reversed.

**Pull request merged**
