### PR TITLE
Fix tests for blender 2.80 (WIP)

### PR DESCRIPTION
**Pull request by portnov**
## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [ ] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [ ] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
@zeffii some tests currently give an error:

```
======================================================================
ERROR: test_intersect_edges (intersect_edges_tests.IntersectEdgesTest2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.80/scripts/addons_contrib/sverchok/tests/intersect_edges_tests.py", line 16, in test_intersect_edges
    result_verts = get_output_socket_data(node, "Verts_out")
  File "/home/portnov/.config/blender/2.80/scripts/addons_contrib/sverchok/core/socket_data.py", line 150, in get_output_socket_data
    socket_id = socket.socket_id
AttributeError: 'NodeSocket' object has no attribute 'socket_id'

======================================================================
ERROR: test_script_uv_export (tree_export_tests.ScriptUvExportTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.80/scripts/addons_contrib/sverchok/tests/tree_export_tests.py", line 13, in test_script_uv_export
    export_result = create_dict_of_tree(self.tree)
  File "/home/portnov/.config/blender/2.80/scripts/addons_contrib/sverchok/utils/sv_IO_panel_tools.py", line 303, in create_dict_of_tree
    node.storage_get_data(node_dict)
  File "/home/portnov/.config/blender/2.80/scripts/addons_contrib/sverchok/nodes/generator/script1_lite.py", line 496, in storage_get_data
    self.make_new_locals()
  File "/home/portnov/.config/blender/2.80/scripts/addons_contrib/sverchok/nodes/generator/script1_lite.py", line 292, in make_new_locals
    self.update_sockets()
  File "/home/portnov/.config/blender/2.80/scripts/addons_contrib/sverchok/nodes/generator/script1_lite.py", line 235, in update_sockets
    if not self.add_or_update_sockets(k, v):
  File "/home/portnov/.config/blender/2.80/scripts/addons_contrib/sverchok/nodes/generator/script1_lite.py", line 186, in add_or_update_sockets
    sockets[idx].replace_socket(*socket_description[:2])
AttributeError: 'NodeSocket' object has no attribute 'replace_socket'

======================================================================
ERROR: test_script_uv_import (tree_import_tests.ScriptUvImportTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.80/scripts/addons_contrib/sverchok/tests/tree_import_tests.py", line 24, in test_script_uv_import
    self.assert_nodes_linked("ImportedTree", "UV Connection", "vertices", "Viewer Draw", "vertices")
  File "/home/portnov/.config/blender/2.80/scripts/addons_contrib/sverchok/utils/testing.py", line 266, in assert_nodes_linked
    node2 = get_node(node2_name, tree_name)
  File "/home/portnov/.config/blender/2.80/scripts/addons_contrib/sverchok/utils/testing.py", line 153, in get_node
    return bpy.data.node_groups[tree_name].nodes[node_name]
KeyError: 'bpy_prop_collection[key]: key "Viewer Draw" not found'

----------------------------------------------------------------------
Ran 41 tests in 1.281s

FAILED (errors=3, skipped=1)
```

**Comment by portnov** [comment]
Also, we have to decide what are we going to do with all json examples we have in sverchok distribution. Most of them are currently unusable in 2.80. We have to either reimplement them in 2.80, or remove from distribution.

**Comment by zeffii** [comment]
ooooh boy - i totally don't want to do any of this.

**Comment by zeffii** [comment]
i say ditch all examples and build them up again.. there will be still be some renaming of node class names, and some of the demos are somewhat esoteric.

**Comment by portnov** [comment]
Well, I was able to get tests running by cost of removing most of json examples from distribution. I've created a separate issue (#2540) for creation of new examples.

**Pull request merged**
