### PR TITLE
"Select similar" node

### PR DESCRIPTION
**Pull request by portnov**
This is the implementation of Blender's "select similar" (Shift+G) feature.

### CODE REVIEW

**Comment by zeffii** [comment]
cool..

can you make the docstring `""" <short descrption>  ///   <longer description, ...rest > """`

**Comment by zeffii** [comment]
for instance:
```python
class SvProfileNode(bpy.types.Node, SverchCustomTreeNode):
    '''
    svg-like 2d profiles ///

    SvProfileNode generates one or more profiles / elevation segments using;
    assignments, variables, and a string descriptor similar to SVG.
```
image

**Comment by portnov** [comment]
@zeffii 
Done, please check.

**Comment by zeffii** [comment]
sorry to be a pain :)

**Comment by zeffii** [comment]
it will show `bl_label    <    >    description  `   best make the description give information not present in the bl_label

**Comment by zeffii** [comment]
maybe.. "Like blender's ctrl+G ///    """ i think that fits

**Comment by kalwalt** [comment]
should be added in all the nodes this?

**Comment by portnov** [comment]
@zeffii 
ok :)

**Comment by zeffii** [comment]
well... if we're going to be using the extended search menu more... it would be nice yes :)

**Comment by zeffii** [comment]
and the docstring is used currently _nowhere_

**Comment by kalwalt** [comment]
ok...so plans for the near future!

**Comment by kalwalt** [comment]
maybe when it will be in the master, we can add to all nodes. (or at list one part of them)

**Comment by kalwalt** [comment]
of course i was refering to the search feature

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1521 discuss it further here

**Pull request merged**
