### PR TITLE
Gistbutton

### PR DESCRIPTION
**Pull request by zeffii**
Adds direct Gist Download button 
   - This will look at the URL in your clipboad ( no error handling yet )
    
image

also fixes Ctrl+Space menu submenus.

### CODE REVIEW

**Comment by nortikin** [comment]
where to auto export gist?

**Comment by nortikin** [comment]
and share link with email to collect gists

**Comment by zeffii** [comment]
the way export works at the moment is it copies the url to clipboad, is this not enough (it is for me.. )
seting up an auto email with smtp user/pw is not hard, but not high on my todo :)

**Comment by nortikin** [comment]
yes + ethic question

**Pull request merged**
