### PR TITLE
Test fixing

### PR DESCRIPTION
**Pull request by vicdoval**
Small fixes
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
Still fails :/
https://github.com/nortikin/sverchok/pull/3636

**Comment by vicdoval** [comment]
I see... but when i run the tree_export_import_tests in my computer they are successful...

**Comment by vicdoval** [comment]
Any hint?

**Comment by portnov** [comment]
Tests fail on my machine too. Maybe the problem is with blender version? I use Blender 2.90 on debian.

**Comment by portnov** [comment]
```
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.90/scripts/addons_contrib/sverchok/core/update_system.py", line 384, in do_update_general
    node.process()
  File "/home/portnov/.config/blender/2.90/scripts/addons_contrib/sverchok/nodes/viz/viewer_draw_mk4.py", line 807, in process
    geom = generate_mesh_geom(config, vecs)
  File "/home/portnov/.config/blender/2.90/scripts/addons_contrib/sverchok/nodes/viz/viewer_draw_mk4.py", line 389, in generate_mesh_geom
    config.v_shader = gpu.shader.from_builtin('3D_SMOOTH_COLOR')
SystemError: GPU functions for drawing are not available in background mode
```
I think this is the root of the problem.

**Comment by portnov** [comment]
```
diff --git a/nodes/viz/viewer_draw_mk4.py b/nodes/viz/viewer_draw_mk4.py
index 061afe811..017a2a1fb 100644
--- a/nodes/viz/viewer_draw_mk4.py
+++ b/nodes/viz/viewer_draw_mk4.py
@@ -764,6 +764,8 @@ class SvViewerDrawMk4(bpy.types.Node, SverchCustomTreeNode):
 
     def process(self):
 
+        if bpy.app.background:
+            return
         self.handle_attr_socket()
         if not (self.id_data.sv_show and self.activate):
             callback_disable(node_id(self))
```
This fixes tests for me.

**Pull request merged**
