### PR TITLE
Import MixInputs node from 2.79 to 2.80

### PR DESCRIPTION
**Pull request by DolphinDream**
- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

SV-MixInputsNode

### CODE REVIEW

**Comment by DolphinDream** [comment]
Any ideas why the checks fail on this PR? I can’t make sense of the log. Btw, the node creates properties on the fly based on the mode.. and I think these should be created as annotations.. though I have no clue how to do this. Any suggestions? gracias.

**Comment by portnov** [comment]
```
======================================================================

FAIL: test_all_node_docs_in_trees (docs_tests.DocumentationTests) (directory='number')

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/nortikin/sverchok/installation/blender/2.80/scripts/addons_contrib/sverchok/tests/docs_tests.py", line 51, in test_all_node_docs_in_trees

    check_dir(directory, fnames)

  File "/home/travis/build/nortikin/sverchok/installation/blender/2.80/scripts/addons_contrib/sverchok/tests/docs_tests.py", line 45, in check_dir

    self.fail("Not all node documentation files are mentioned in their corresponding indexes.")

AssertionError: Not all node documentation files are mentioned in their corresponding indexes.

----------------------------------------------------------------------
```

**Comment by portnov** [comment]
It seems mix_input.rst is not mentioned in number_index.rst.

**Comment by portnov** [comment]
And there is another problem
```
Warning: class SvMixInputsNode contains a property which should be an annotation!

/home/travis/build/nortikin/sverchok/installation/blender/2.80/scripts/addons_contrib/sverchok/nodes/number/mix_inputs.py:371
```

**Comment by portnov** [comment]
` vars()[attr_name] = make_prop(m, l)` — I think this should be something like `vars().__annotations__[name] = ...`.

**Comment by DolphinDream** [comment]
@portnov 
with this
vars().__annotations__[name] = ...

I get this error:
AttributeError: 'dict' object has no attribute ‘__annotations__'

**Comment by Durman** [comment]
Because the vars functions returns dictionary:
```Python
vars()['__annotations__'][new_var] = ...
```

**Comment by DolphinDream** [comment]
This node btw, obsoletes the MixNumbers node.

**Pull request merged**
