### PR TITLE
Triangle Fill node (WIP)

### PR DESCRIPTION
**Pull request by portnov**
bmesh.ops.triangle_fill.

Screenshot_20191217_230413

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [ ] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [ ] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
Screenshot_20191218_230607

**Comment by Durman** [comment]
Strange result:

**Comment by portnov** [comment]
Yeah. This bmesh function is not very clever, it does not even try to detect "holes". It works properly only if you specify the edges of the hole to be filled by EdgeMask input.
We could automatically detect holes by calling bmesh.ops.holes_fill() first; but then it is not clear, why do we need to use triangle_fill() at all — we could triangulate faces returned by holes_fill() instead.
So I'm not currently sure if this node is very useful.

**Comment by Durman** [comment]
I think we should at first to make up a purpose of designed node and then to think how existing tools can help us. Or we should to investigate existing tools and try to think what can they bring to Sverchok.)) Straight implementation of Bmesh operators has less use I think. 

In this particular case I see that this operator can fill closed edge loops with triangles. So the input of this node should be set of closed edge loops I think if it would not use other alorithms.

**Pull request closed without merging**
