### PR TITLE
B28 geom 2d package fix2

### PR DESCRIPTION
**Pull request by zeffii**
case sensitivity conflict

### CODE REVIEW

**Comment by zeffii** [comment]
@Durman  checks this.. seems OK.

**Comment by zeffii** [comment]
i had to 
```
git config core.ignorecase false

git rm -r --cached nodes/cad
git rm -r --cached docs/nodes/cad

commit ...

git config core.ignorecase true
```

**Comment by Durman** [comment]
Thanks for helping =)

**Comment by zeffii** [comment]
awesome pullrequest @Durman 

this allows us to do some crazy 2d stuff :)

**Pull request merged**
