### PR TITLE
New "List Item Insert" and "Mask To Index" nodes

### PR DESCRIPTION
**Pull request by vicdoval**
List Item Insert: The reverse of List Item that can also replace items
List Item Insert
Mask to Index: 

In this PR also:
Renamed "item" input to "index" in List Item Node
Moved "Index to Mask" Node from Alpha to List Mask category/folder
Docs for "Index to Mask"
Icons for the four affected nodes

- [X] Code changes complete.
- [X] Code documentation complete.
- [X] Documentation for users complete (or not required, if user never sees these changes).
- [X] Manual testing done. 
- [ ] Unit-tests implemented.
- [X] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
By the way `list mask (out)` node also has `true index` and `false index` output.

**Comment by vicdoval** [comment]
I think you are right @Durman 
Those outputs don't bother me but maybe it would be cleaner to remove them.
What do you think @zeffii , @nortikin ?

**Comment by zeffii** [comment]
don't remove the outputs. List Mask out rocks the way it is.

**Comment by vicdoval** [comment]
Regarding breaking compatibility:
Apart of renaming one of the inputs of the List Item Node I renamed `ListItem2Node` to `SvListItemNode`  following the actual conventions.
This will break the compatibility of this node so there are three solutions.
1 Leave it like this (this is a break point so it would be understandable)
2 Move the old file to old_nodes
3 Undo the changes i have done and leave that node stay as it was.

Any thoughts on this?

**Comment by zeffii** [comment]
upgrade it with the Sv prefix, and stick the old one in the old nodes.

using the 'index' socket does feel more pythonic.

**Comment by zeffii** [comment]
also..   index_insert  seems like a cool node :)

**Comment by vicdoval** [comment]
thanks! @zeffii.   
(I guessed that more pythonic means better also in this case 😄)

Now is ready to be merged :)

**Comment by nortikin** [comment]
all nodes are cool. No need to remove something

**Pull request merged**
