### PR TITLE
Allow users to try arbitrary branches (from a list we curate in issue 2053)

### PR DESCRIPTION
**Pull request by zeffii**
### warnings for gitusers:  don't use this feature, it's not for you.

Allow users to test arbitrary branches that we [list in this issue](https://github.com/nortikin/sverchok/issues/2053)

image

will show up like

image

then, when picked

image

### CODE REVIEW

**Comment by portnov** [comment]
Maybe better maintain some .txt file in the git repo, instead of issue?

**Comment by zeffii** [comment]
I quite like the idea of maintaining an issue .. or a gist (but issue is the easiest...) because it's not reliant on any branch .

**Comment by nortikin** [comment]
maintain is time-consuming.

**Comment by portnov** [comment]
Huh. We could instead have an agreement to name all such branches after certain pattern, for example "test_*". And code would just list all existing branches from repo by that pattern.

**Comment by zeffii** [comment]
i mentioned what i thought were reasonable approaches with varying levels of sanity : https://github.com/nortikin/sverchok/issues/2052#issuecomment-358074035

- the downside to just a prefix is that it doesn't let users try a non `nortikin/sverchok/` branch, users might communicate among each-other to develop features, prior to getting commit access.
- allowing a user defined sverchok .zip path has the only drawback that it requires the path to be pasted/typed correctly.
- if we curate a list we can also theoretically allow users to propose non `nortikin/sverchok` archives.
    so rather than just 
    ```text
    - branch_name              # resolving to:   ....nortikin/sverchok/branch_name.zip
    
    # we could allow
    - user_name/branch_name    # resolving to:   ....user_name/sverchok/branch_name.zip
    ```

we could also just allow all of these options :)  with a tabbed interface

**Pull request closed without merging**
