### PR TITLE
Some new noises

### PR DESCRIPTION
**Pull request by vicdoval**
I optimized the code of the 'Vector Noise', then I thought: A Numpy implementation sure is faster.  
After digging inside of the Perlin magic my implementation was slower than the previous optimised code.... but opened up some control over the Noise generation so I added 4 types of noise with some options :)
Random Cells:
noise_sverchok_blender_example_5
Ortho Gradients
noise_displace_blender_sverchok_example_8
Random Gradients:
noise_sverchok_blender_example_7
And Numpy Perlin
noise_sverchok_blender_example_9

The are available in the Vector Noise node and on the Noise Displace node

Also on this PR:
- Float to Int node will ouput Numpy arrays if has a numpy input
- get_nesting_level of data_structure.py  accepts numpy

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by vicdoval** [comment]
image
image
image

**Comment by vicdoval** [comment]
Travis is in quarantine?

**Comment by zeffii** [comment]
sexy!

**Comment by zeffii** [comment]
your next commit might awaken travis

**Pull request merged**
