### PR TITLE
Update extrude_separate.py

### PR DESCRIPTION
**Pull request by Durman**
If will add vector to scale socket you can control scale per axises.

imaguuu

### CODE REVIEW

**Comment by zeffii** [comment]
i see.. you can generate `m_r` directly using `mathutils.Matrix` , pass it a matrix3x3 and call `.to_4x4()` on the result.

```python
m_r = Matrix(list([*zip(x_axis, y_axis, z_axis)])).to_4x4()
```

**Comment by zeffii** [comment]
or.. because you'd be zipping over Vectors..you'll have to decompose the vector into a simple list
```
m_r = Matrix(list([*zip(x_axis[:], y_axis[:], z_axis[:])])).to_4x4()
```

**Comment by zeffii** [comment]
@Durman  also
```python
if vector_in:
    vec = scale
else:
    vec = (scale, scale, scale)
```
can be restated like this
```python
vec = scale if vector_in else (scale, scale, scale)
```

**Comment by Durman** [comment]
It's better now. 
After merging may I delete this branch?

**Comment by zeffii** [comment]
this looks a little goofy
```python
                if normal[0] == 0 and normal[1] == 0 and normal[2] >= 0: m_r = Matrix()
                elif normal[0] == 0 and normal[1] == 0 and normal[2] < 0: m_r = Matrix.Rotation(pi,4,'X')
                else:    
                    z_axis = normal
                    x_axis = (Vector((z_axis[1] * -1, z_axis[0], 0))).normalized()
                    y_axis = (z_axis.cross(x_axis)).normalized()

                    m_r = Matrix(list([*zip(x_axis[:], y_axis[:], z_axis[:])])).to_4x4()
```
python allows you to place the if and resulting clause on the same line.. but don't do that please for larger if-elif-else :)
```python
                if normal[0] == 0 and normal[1] == 0:
                    m_r = Matrix() if normal[2] >= 0 else Matrix.Rotation(pi,4,'X')
                else:    
                    z_axis = normal
                    x_axis = (Vector((z_axis[1] * -1, z_axis[0], 0))).normalized()
                    y_axis = (z_axis.cross(x_axis)).normalized()
                    m_r = Matrix(list([*zip(x_axis[:], y_axis[:], z_axis[:])])).to_4x4()
```
also, it's OK to remove the commented out code, you can always look back at previous version of the node.
```diff
-               #rotation = face.normal.rotation_difference((0,0,1)).to_matrix().to_4x4()
-               #rotation = autorotate(z, face.normal).inverted()
```

and further. we have adapted the convention to set the data of the output socket regardless of whether it is connected. If the data has been been calculated already.
```python
        outputs = self.outputs
        outputs['Vertices'].sv_set(result_vertices)
        outputs['Edges'].sv_set(result_edges)
        outputs['Polygons'].sv_set(result_faces)
        outputs['ExtrudedPolys'].sv_set(result_extruded_faces)
        outputs['OtherPolys'].sv_set(result_other_faces)
```
obviously.. you could still add a few checks in the loop 
```python
for face, mask, height, scale in zip(extruded_faces, masks, heights, scales):
```
to test whether or not the node needs to calculate certain data in the first place, depending on whether a socket output is linked..  --- but for this node I don't think we need to worry about that here.

**Comment by zeffii** [comment]
@Durman 

> After merging may I delete this branch?

I can accept the pull request, as it current is. Or you can change the code areas I suggested. I will likely make these edits myself if you don't.

but yes, after that we'll certainly delete the branch. Thanks for your participation :)

**Comment by zeffii** [comment]
let me know if you want to make these code-changes yourself, or if you'd like us to accept the Pull Request and do small cleanup afterwards.

**Comment by zeffii** [comment]
i grew impatient. and will accept the PR and commit additional cleanup myself :)  @Durman  thanks for the contribution :) much appreciated

**Comment by zeffii** [comment]
this is what I mean: 
https://github.com/nortikin/sverchok/pull/1857

**Pull request merged**
