### PR TITLE
gl_FragColor fix

### LINKED ISSUE #3480: Mesh Viewer 2D is broken on osX, shader compile error
Screen Shot 2020-08-25 at 10 59 01 am

```
2020-08-25 10:58:36,292 [ERROR] sverchok.core.update_system: Node Viewer 2D had exception: Shader Compile Error, see console for more details
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/core/update_system.py", line 383, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/viz/viewer_2d.py", line 813, in process
    geom = generate_mesh_geom(config, vecs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/viz/viewer_2d.py", line 478, in generate_mesh_geom
    config.v_shader = get_2d_smooth_color_shader()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/viz/viewer_2d.py", line 156, in get_2d_smooth_color_shader
    return gpu.types.GPUShader(smooth_2d_vertex_shader, smooth_2d_fragment_shader)
Exception: Shader Compile Error, see console for more details
EVENT: node_property_update          IN: SvIcosphereNode           INSTANCE: IcoSphere                
GPUShader: compile error:
ERROR: 0:33: Use of undeclared identifier 'gl_FragColor'

2020-08-25 10:58:36,327 [ERROR] sverchok.core.update_system: Node Viewer 2D had exception: Shader Compile Error, see console for more details
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/core/update_system.py", line 383, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/viz/viewer_2d.py", line 813, in process
    geom = generate_mesh_geom(config, vecs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/viz/viewer_2d.py", line 478, in generate_mesh_geom
    config.v_shader = get_2d_smooth_color_shader()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/viz/viewer_2d.py", line 156, in get_2d_smooth_color_shader
    return gpu.types.GPUShader(smooth_2d_vertex_shader, smooth_2d_fragment_shader)
Exception: Shader Compile Error, see console for more details
```

### PR DESCRIPTION
**Pull request by vicdoval**
Tries to fix #3480

I dont have a mac OS to try this out but seems to go in the right direction and does not break anything on Windows

Seemed that gl_FragColor is now depreciated so i added this line
```
  uniform vec4 color;
+ layout(location = 0) out vec4 gl_FragColor;
  void main()
  {
```

- [x] Ready for merge.

### CODE REVIEW

**Comment by vicdoval** [comment]
Can you test `Viewer 2d` on this branch @enzyme69 ? otherwise I will merge it blindly

**Comment by zeffii** [comment]
@vicdoval   is `layout(location=0`  strictly necessary ? i don't even understand what that's supposed to be doing. https://www.khronos.org/opengl/wiki/Layout_Qualifier_(GLSL)

**Comment by vicdoval** [comment]
I took it from here, https://www.reddit.com/r/opengl/comments/7s2wgz/whats_the_replacement_of_gl_fragcolor/ the last day seemed to fail otherwise but now works perfectly without it. 
I hope this fixes the problem 🌵

**Comment by zeffii** [comment]
i'll add the same to the other nodes mentioned, else those are also all useless on osx.

**Comment by vicdoval** [comment]
I think a I already changed all the affected nodes. I was waiting any tester before merging but I guess we can merge it anyway

**Comment by zeffii** [comment]
do it

**Comment by enzyme69** [comment]
Maybe just blindly merge it anyway Victor?

**Pull request merged**
