### PR TITLE
Move what possible from Sverchok-Extra (WIP)

### PR DESCRIPTION
**Pull request by portnov**
In this PR, I'm moving things that do not have any external dependencies, from Sverchok-Extra to Sverchok:

* Abstract classes for Curve, Surface, Field.
* Some nodes from Curve category.
* Some nodes from Surface category.
* Some nodes from Field category.

It is supposed that in the end, Sverchok-Extra will contain only things that are not possible without external dependencies.

At the moment, this PR branch is supposed to work with `sverchok_move` branch of Sverchok-Extra.

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Core code changes complete.
- [x] Rename SvEx* classes to Sv
- [x] Implement `__repr__()` methods
- [x] Code documentation complete.
- Documentation for users complete:
- - [x] Curve category
- - [x] Surface category
- - [x] Field category
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
@zeffii  / @vicdoval  you may wish to review this :) I understand that there is a lot of code, but maybe there will be some general remarks or maybe your eye will catch something.

I'll start writing documentation...

**Comment by portnov** [comment]
Screenshot_20200322_195255

**Comment by zeffii** [comment]
yikes, that's a big PR :) 

i'm taking a break from Sverchok for a while, to see if I can maybe learn a compiled language before the end of the world as we know it :)

**Comment by portnov** [comment]
Screenshot_20200322_233101

**Comment by Durman** [comment]
Should another shape of sockets really used? Is not using different colors is enough?

**Comment by portnov** [comment]
Why not? :)

**Comment by Durman** [comment]
Have a look at this post:
https://github.com/nortikin/sverchok/issues/2720#issuecomment-595621353

I think it would be nice to keep the same logic as it going be in `everything nodes` project.
I just don't what is format of output sockets in your nodes what make them to have different shape.

**Comment by portnov** [comment]
Screenshot_20200324_002205

**Comment by portnov** [comment]
Screenshot_20200324_202518

**Comment by portnov** [comment]
Screenshot_20200324_232120

**Comment by vicdoval** [comment]
This is awesome @portnov i looked the code (just some parts :D) an looks as good as usual, 
Some ideas:
_  ensure_nesting_level does not understand numpy (until i commit #2997). It would be nice if this nodes could accept and produce numpy arrays.   Maybe after my commit you want to merge it in your branch or add the line to data_structure.py  (and manage later the git conflicts) to test this branch with numpy inputs

_ In the curve range node the ouputs should have one extra [ ] ?

_it would be awesome to add some routine to the stethsocope to read the new geometry types better than 
image

**Comment by vicdoval** [comment]
Another suggestion:
Changing the imported classes suffix from 'SvEx' to 'Sv'

**Comment by portnov** [comment]
Screenshot_20200329_214608

**Comment by portnov** [comment]
Screenshot_20200330_003702

**Comment by zeffii** [comment]
i was looking at the Stethoscope implementation last week, and got the itch to move stethoscope specific drawing stuff back out of the nodeview callback and back into the node's own .py file.. or maybe a module. I agree with @vicdoval  it would be useful to add more information / `repr` to objects of the SvEx classes.

**Comment by portnov** [comment]
Yes, I'll add `__repr__()` definition to classes.

**Comment by portnov** [comment]
Screenshot_20200406_011910

**Comment by portnov** [comment]
Screenshot_20200407_234921

**Comment by portnov** [comment]
bend_revolve_1

**Comment by portnov** [comment]
Screenshot_20200413_222646

**Comment by enzyme69** [comment]
@portnov Ilya, where should I start if I want to try all these special nodes? is there on list of every nodes like this? Is it easy to use?

**Comment by portnov** [comment]
If you're using Sverchok from git, you can do
```
git fetch origin
git checkout -b extra_move origin/extra_move
```
and then run blender as usual. After that, use `git checkout master` to switch to the master branch back.

**Comment by portnov** [comment]
Screenshot_20200415_210115

**Comment by portnov** [comment]
Screenshot_20200415_211714

**Comment by portnov** [comment]
Screenshot_20200415_230352

**Comment by portnov** [comment]
Screenshot_20200416_020925
Screenshot_20200416_021004

**Comment by portnov** [comment]
Screenshot_20200416_194107
Screenshot_20200416_194148
Screenshot_20200416_195136

**Comment by portnov** [comment]
Screenshot_20200416_235740
Screenshot_20200416_235858
Screenshot_20200416_233921

**Comment by portnov** [comment]
Screenshot_20200417_010034

**Comment by portnov** [comment]
Screenshot_20200417_212341
Screenshot_20200417_214359

**Comment by portnov** [comment]
Screenshot_20200417_233545

**Comment by portnov** [comment]
Screenshot_20200417_235007
Screenshot_20200417_235149
Screenshot_20200417_235432

**Comment by portnov** [comment]
Wow. At least most of the documentation is ready. It could be of better quality, but let's leave that for future PRs..

**Comment by zeffii** [comment]
epic effort @portnov

**Comment by vicdoval** [comment]
The curve range had  also a missing [ ]
image

**Comment by portnov** [comment]
That's already fixed.

**Comment by portnov** [comment]
Screenshot_20200418_170750

**Comment by portnov** [comment]
Screenshot_20200418_193853

**Comment by portnov** [comment]
Well, I guess the only way for wider testing is to merge this...

**Comment by vicdoval** [comment]
awesomeness all around... :) Are you going to publish it in Facebook, Twitter and/or Blender Artists??

**Comment by portnov** [comment]
@vicdoval I think I'll publish it in russian community in VK. Also probably in the thread on the blenderartists. You're free to publish in other sources :)

**Comment by Durman** [comment]
@portnov Great work!

**Comment by portnov** [comment]
https://gist.github.com/d9716b5f7ee1f8907b873cefcd721f03
Screenshot_20200419_172802

**Comment by enzyme69** [comment]
I made #Alien Unlimited Worship Sculpture Generator using the new node :) Just less than 5 nodes.

Screen Shot 2020-04-21 at 3 59 30 pm

Screen Shot 2020-04-21 at 3 59 30 pm

**Comment by enzyme69** [comment]
I think we are missing Surface UV Flip node and also we need ability to output Surface with UV, like Blender Surface?

**Comment by enzyme69** [comment]
Question:
Can force field curve projected or affected by 3D surface or 3D volume?

**Comment by portnov** [comment]
No, there is no such funcitonality in Sverchok currently. If you install sverchok-extra, there are "minimal vector field" and "mesh nearest normal" nodes, may be they appear what do you want. Sorry, no documentation for them yet.

**Comment by portnov** [comment]
> missing Surface UV Flip node 
Yes, it's missing currently. 

About UV maps... it would require some kind of "output" node that would output Blender's Surface objects instead of mesh object. I didn't try to make such thing, yet.

**Comment by portnov** [comment]
@enzyme69 
> Can force field curve projected or affected by 3D surface or 3D volume?

Maybe you are talking about "Bend along Curve Field" / "Bend Along Surface Feild" nodes?...

**Comment by DolphinDream** [comment]
Awesome job, @portnov ! This is pretty impressive. I’m looking forward to check it out.

**Pull request merged**
