### PR TITLE
remove use of bgl module in all nodes. ( B3.5+ )

### PR DESCRIPTION
**Pull request by zeffii**
Addresses the Blender.org deprecation of the `bgl` module. This means that the nodes listed in [this issue](https://github.com/nortikin/sverchok/issues/4895) should be revised to meet the new specifications. Should be cool, if all bgl features have a `gpu.state` analogue

- addresses https://github.com/nortikin/sverchok/issues/4915 too
- also `blf` module has gained modifications between 3.4 and 3.5+/4.0

## Preflight checklist

- [x] sverchok appears in window list. and loads
     
image
 
- [ ] Code changes complete.
- [ ] Code documentation complete.
- [ ] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
Are you going to drop the support of B3.4- by the changes?

If so my proposal is to make release 1.2 and commit the changes in next Sv version. There are a few issue which would be good to solve before the release - https://github.com/nortikin/sverchok/milestone/11.

**Comment by zeffii** [comment]
> Are you going to drop the support of B3.4- by the changes?

i would prefer to support both, so that's a slight annoyance that needs a tidy solution. good point. 

and there's changes in `blf` too..
```python
blf.size() takes exactly 2 arguments (3 given)
```
fun :)

**Comment by zeffii** [comment]
point size and line width don't seem to work at the moment,  at least --- on my machine.

**Comment by zeffii** [comment]
@Durman  is it sane to try to support pre b3.5?

One way i could imagine doing that is by making a wrapper for the bgl/blf functions we do use. With little code modifications we can then port over ~much~ some of the code unchanged. Rather than having forks in the code of each node, put the forks in the wrapper.

```python
from sverchok.utils import bgl_wrapper as bgl
```
and then code like this would still be valid
```python

        bgl.glLineWidth(config.line_width)
```
but in `bpy.app.version >= (3, 5, 0):`   it would call instead
```python
        gpu.state.line_width_set(config.line_width)

```

**Comment by zeffii** [comment]
additionally, drawing triangles using vdmk4 ..
```
    ibo = GPUIndexBuf(type=type, seq=indices)
TypeError: IndexBuf.__new__: invalid sequence length. expected 3, got 4
```
this appears to have changed at some point.

**Comment by zeffii** [comment]
i'm still looking for a way to do the `offset polygon` in gpu.state , else.... it might have to be done in the shader.

**Comment by Durman** [comment]
We can drop support of B3.4 and lower. Also we can support both the new and old API. In this case it would be nice to keep code so it would be simple to remove old API some day. I think function implementation could look like this

```py
def universal_fun():
    if bl_v >= 3.5:
        fun_a()
    else:
        fun_b()
```
In this example `fun_b` calls old API and can be removed some day. Also similar thing can be done with classes which could be called something like `DrawingEngine`. One class for calling old API and another for calling new one. But that probably will take more time to code.

**Comment by zeffii** [comment]
@Durman yes a `DrawingEngine` makes sense, and I think I will do that before the issue is pushed.

**Pull request closed without merging**
