### PR TITLE
start exodus

### PR DESCRIPTION
**Pull request by nortikin**
## Beta migration

nodes repatriation invitation

## do it

docs for non-documented nodes
git mv beta/py to original if needed
menu ui/nodeview_space_menu
menu index.md

## Process

- [x] Create docs for alpha-beta
- [x] Move docs.
- [x] Move nodes if needed.
- [x] Old nodes move.
- [x] Menues changed.
- [x] Test docs in sphinx.
- [ ] Check for consistency.
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/issues/2427
to link issue

**Comment by nortikin** [comment]
menu
Menu for 2.79

**Comment by Durman** [comment]
It looks like the material node to be happened. Which category will be appropriate for such node? And I'm going to add extra nodes like assign material node and something like UVmap node. Where this nodes should be placed? 

BPY data category looks like trash can for nodes which did not found appropriate place for themselves.

**Comment by nortikin** [comment]
As @zeffii mentioned, we should continue in 2.8 blender branch. so, i will merge it and close for now. Later will go on in 2.8 indeed.
Propose `Color` section to rename to material section.
That is it.

**Comment by nortikin** [comment]
it says import test failed, but i can import by myself. what is wrong? have i change tests to be sure?
Anyway, as i see, i can merge.
Tomorrow

**Comment by vicdoval** [comment]
The ci checks inform that many examples have the "Float" and" Int" nodes that now are in the old nodes folder..

**Comment by nortikin** [comment]
@vicdoval yes, but i donno what to do?
it works with deprecated nodes frame and it is ok as for me. shoul i back this nodes?

**Comment by nortikin** [comment]
now it is ready

**Comment by nortikin** [comment]
```
FAIL: test_cylinder_export (simple_export_tests.ExportSingleSimpleNode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/scripts/addons/sverchok/tests/simple_export_tests.py", line 33, in test_cylinder_export
    self.assert_json_equals_file(export_result, "cylinder.json")
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/scripts/addons/sverchok/utils/testing.py", line 251, in assert_json_equals_file
    self.assert_json_equals(actual_json, expected_result)
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.79/scripts/addons/sverchok/utils/testing.py", line 242, in assert_json_equals
    self.assertEquals(actual_data, expected_data)
AssertionError: '{\n [140 chars]    "height": 100.0,\n      "hide": false,\n  [365 chars]]\n}' != '{\n [140 chars]    "color": [\n        0.0,\n        0.5,\n  [467 chars]]\n}'
Diff is 697 characters long. Set self.maxDiff to None to see it.
```

**Comment by zeffii** [comment]
just moving the old nodes back is not a really good final fix.

if someone wants to move those jsons to 2019 then load those jsons:
```
for every json containing Float or Integer node:
    replace the Floats with ANumber (float mode)
    replace the Integers with ANumber (int mode)
    apply value previous stored in Float / Integer
    apply min max if needed
```
big job,  but i removed Float/Integer from svb28 (because it's time to lay them to rest)

**Comment by nortikin** [comment]
ok ,names are changed, but attributes not so simple with script.
maybe by hands is more productive?

**Comment by zeffii** [comment]
i think this PR is stale now.

**Pull request closed without merging**
