### PR TITLE
Branch side panel

### PR DESCRIPTION
**Pull request by ly29**
#805

### CODE REVIEW

**Comment by zeffii** [comment]
each time i start blender or f8, this appears in the messages / console
```python
** Sverchok loaded with 183 nodes **
added keyboard items to Text Editor.
fatal: Invalid symlink 'C:/Users/zeffi/Desktop/scripts/addons_contrib/sverchok': Function not implemented
** version:  (0, 5, 6, 3)  **
```

this as discussed in a thread somewhere is windows/python not being able to use the first route to get the git branch..  am slightly puzzled that it prints any message in the first place since there are no prints in the except of either try/except..
https://github.com/nortikin/sverchok/blob/master/ui/development.py

**Comment by ly29** [comment]
Probably standard error or what it is called on Windows. 
Change order of the tests perhaps

**Comment by zeffii** [comment]
or make it os specific, on windows do my thing, and posix do yours

**Comment by ly29** [comment]
Also good

**Pull request merged**
