### PR TITLE
add exception display in the nodeview

### PR DESCRIPTION
**Pull request by zeffii**
this addresses a longstanding pain-in-the-butt issue with distance between the error and the node where the error occurs.

first a simple implementation, with as little overhead as humanly possible.

image

image

image

### CODE REVIEW

**Comment by zeffii** [comment]
@portnov @Durman @vicdoval @nortikin 

maybe we can offer a variety of debug formats here..  despite having used the exception mechanism extensive i'm a little lost as to what is a good message to show us / the users . 

any input is welcome.    remember, the actual rendering of this message will probably not be using blf, but the code i wrote for the console node.

**Comment by nortikin** [comment]
this debug stuff is dark matter for me :(

**Comment by zeffii** [comment]
me too @nortikin .

hope you are doing well :)

**Comment by portnov** [comment]
@zeffii I'd say it's better to output exception message only, without stack trace. Stack trace can be found in the log / console, if someone needs it.

**Comment by zeffii** [comment]
i wish to keep the stack trace, seen as this mode is optional anyway, and I find it useful to see more information from the nodeview when I don't have big screenspace.

but stacktrace could be optional... eventually.

**Pull request merged**
