### PR TITLE
CAD->bisect node. Fix fill holes on complex objects (ex. torus).

### PR DESCRIPTION
**Pull request by satabol**
Windows 11, Blender 3.3.1, Sverchok-master

ex. #4799 if replay with Bisect then result is unexpected too:

image

But Blender do bisect well:

image

What the problem? The part of problem is in operator **bmesh.ops.bisect_plane**. The Bisect Operator does not fill holes! (Unexpected!).
See:

https://github.com/blender/blender/blob/3780a402651aeac0caa86767f823a8517a6f8bae/source/blender/editors/mesh/editmesh_bisect.c#L322-L333

image

But how Blender do fill? It do fill later with **triangle_fill** operator (https://docs.blender.org/api/current/bmesh.ops.html#bmesh.ops.triangle_fill)! 

https://github.com/blender/blender/blob/3780a402651aeac0caa86767f823a8517a6f8bae/source/blender/editors/mesh/editmesh_bisect.c#L346-L355

image

But how Sverchok do fill on bisect [see line 49]?

https://github.com/nortikin/sverchok/blob/9ff8f36eab43ccb926840123dff58469c50bff6b/nodes/modifier_make/bisect.py#L44-L49

I think this is a problem. So I try replace **bmesh.ops.edgeloop_fill** to **bmesh.ops.triangle_fill**. And I got next result that look good:

image

Bisect 001

With joined mesh:

Bisect 002

Suzanne tomography:

Bisect 003

Suzanna has non-manifold geometry so glitches are expected.

for test this pull request: https://gist.github.com/78671a6264b9255acbb3883779fefc73

### CODE REVIEW

**Comment by satabol** [comment]
It is very old function. 

image

May I ask somebody for approve or test? (I did several test and did not see unexpected results but I believe it is very important)

**Comment by satabol** [comment]
Can't stop play with that:

https://gist.github.com/f397c61f7275217008fb28b29bdfb260

Bisect 010 edited

image

image

**Comment by portnov** [comment]
Huh. If you will be able to make the Waffel node do it's work for this thing, you'll probably be able to CNC it :)

**Comment by rendetto** [comment]
I've made a test with one of my interactive scenes and it does not affect the performance.

**Review by Durman — APPROVED** [review]

**Pull request merged**
