### PR TITLE
get / set property node additions.

### PR DESCRIPTION
**Pull request by zeffii**
getset prop node needs surgery

### CODE REVIEW

**Comment by Durman** [comment]
Portnov insists that all debug message was done via logger.)

**Comment by zeffii** [comment]
in my test branch i will do what is most convenient for _me_.

**Comment by Durman** [comment]
I meant only messages that are intended to be in master.

**Comment by zeffii** [comment]
i will use the logger, maybe even before hitting master :)  This is one of those nodes where a one-off verbose message to the user is supremely useful

**Comment by zeffii** [comment]
fixing every possible conceivably usage of this node is not going to happen today, but here as some thoughts for future me

# Set Mode
- you can use a wrapper (like local_updateNode) to call the node's own process function.
    - why? because this node has no output socket, and is therefore a deadend for "updateNode"
    - example, float_prop and int_prop do nothing when updated on the node, only when they get external socket input.
- what if the property is `type_prop_array` and takes only 3 components, unlike 4 that the default FloatVectorProperty sets... offer a second FloatVectorProperty.. name `Col3` , `Col4` . This can get complicated quick if the color property is expecting some HSV etc.. i don't know.

# Get Mode 
- this probably deserved direct converting to our "SvColorSocket"

**Pull request merged**
