### PR TITLE
Objmk2 test

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
oops. the operator  'insertion'  is called in sv panels too, needs small fix :)

**Comment by zeffii** [comment]
doesn't release all objects, if no objects selected while GET is pressed. will fix asap..

**Comment by zeffii** [comment]
am still battling with this one @nortikin  :)

**Comment by zeffii** [comment]
I think this is has reached feature parity again, would love some testing with existing blends :)

**Comment by nortikin** [comment]
but it takes 1 object (((
sadly

**Comment by zeffii** [comment]
@nortikin  no, this Pullrequest is for edits/fixes to `objects_mk2.py`

**Comment by zeffii** [comment]
obj in _lite_ is a different node, for different purposes :)

**Comment by zeffii** [comment]
I wanted to fix a few things in `objects_mk2.py` before attempting to fix the _live input for edit mode_.

**Comment by zeffii** [comment]
question about how live update worked ...  I recall coding this . but I don't know exactly how it worked.

1. updates from edit mode directly propagated to `objects_in` ?  or
2. updates edits to `objects_in` automatically, but only when the user tabs out of edit mode to object mode. 

probably 1 ? :)   2 works..

**Comment by zeffii** [comment]
since I first coded this Blender devs made slight modifications to how the `modal operators` work, I think this affects this feature.

**Comment by zeffii** [comment]
I don't think the live feature ever updated while  the object was in edit mode, that would require the process function in `objects_in`, to test if an object was in edit mode, and then use `bmesh.from_edit_mesh` or something to get the current state.

**Pull request merged**
