### PR TITLE
test genererating new FCStd file on the fly

### PR DESCRIPTION
**Pull request by zeffii**
tests

### CODE REVIEW

**Comment by luzpaz** [comment]
If merged should close #4432

**Comment by luzpaz** [comment]
Aside, is there a detailed tutorial of how to:
* build blender and sverchok
* build freecad 
* so one can test these developments locally?

**Comment by zeffii** [comment]
@luzpaz 
- building Blender is way beyond the scope of the sverchok issue tracker or wiki
- Sverchok is merely an add-on which should run on any recent Blender, on any platform, b2.9.3 and upwards
- certain (optional) Sverchok nodes have dependencies and they might expect a particular version of Python. 
    - an example of such dependency is FreeCAD which may not be available with a python interface supported by Blender 2.9.x
    - in essence you would need to match the Blender version that is built with the same version as the python FreeCAD library is buit with.

The docs do offer some dependency hints: https://github.com/nortikin/sverchok/wiki/FreeCAD

**Comment by zeffii** [comment]
not sure if this is standard for FreeCAD api, but this seems to create a `FCStd` and `FCStd1`. I will assume for now that this is desired behaviour, Blender does this too.

**Pull request merged**
