### PR TITLE
Linear approximation node.

### PR DESCRIPTION
**Pull request by portnov**
The new node tries to approximate provided set of vertices by either a plane or a straight line. In other words, it searches for such a plane / line, that all provided vertices have the minimum distance to it.

CodeCogsEqn

This PR also contains a set of utility functions/classes in `geom.py`, which may be useful for other nodes, included scripted ones.

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [x] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
Screenshot_20190523_212234
Screenshot_20190523_212613
Screenshot_20190523_222700

**Comment by portnov** [comment]
Screenshot_20190523_223737

**Comment by portnov** [comment]
Screenshot_20190524_181947

**Comment by portnov** [comment]
Select part of complex shape, approximate that part by plane and draw a cylinder in that plane.

Screenshot_20190524_190811

**Comment by portnov** [comment]
Example of new API usage: calculation of two planes intersection:

Screenshot_20190525_214954

```python
from sverchok.utils.geom import PlaneEquation

def sv_main(point1=[[]], normal1=[[]], point2=[[]], normal2=[[]]):

    in_sockets = [
        ['v', 'point1', point1],
        ['v', 'normal1', normal1],
        ['v', 'point2', point2],
        ['v', 'normal2', normal2]        
    ]
    
    if normal1 == [[]]:
        point3 = (0,0,0)
        dir3 = (0,0,0)
    else:
        print(normal1, normal2, point1, point2)
        plane1 = PlaneEquation.from_normal_and_point(normal1[0][0], point1[0][0])
        plane2 = PlaneEquation.from_normal_and_point(normal2[0][0], point2[0][0])
        line = plane1.intersect_with_plane(plane2)
        point3 = tuple(line.point)
        dir3 = tuple(line.direction)

    out_sockets = [
        ['v', 'point', [[point3]]],
        ['v', 'direction', [[dir3]]]
    ]

    return in_sockets, out_sockets
```

**Comment by portnov** [comment]
@vicdoval , @DolphinDream I think you might be interested in the new API for generic geometry (see changes in geom.py).

**Comment by portnov** [comment]
Size of each small cube is proportional to distance from approximating plane:
Screenshot_20190526_122511

**Comment by Durman** [comment]
Something related: ))
https://github.com/fhirschmann/rdp
https://rdp.readthedocs.io/en/latest/

**Pull request merged**
