### PR TITLE
List split and slice accept numpy

### PR DESCRIPTION
**Pull request by vicdoval**
split and slice

- [x] Ready for merge.

### CODE REVIEW

**Comment by zeffii** [comment]
yep good, wicked!

**Comment by zeffii** [comment]
what about `/list_struct/slice_lite.py`

**Comment by vicdoval** [comment]
> what about `/list_struct/slice_lite.py`

If you make the docs I can give it a go

**Comment by zeffii** [comment]
i'll look tomorrow, it might be deprecatable seen as listsplit now does numpy too.

**Comment by vicdoval** [comment]
i have never used it, i see now is a list split with no unwrap possibility... maybe could be added as an option to the list split node

**Pull request merged**
