### PR TITLE
Add scale/multiplier to TextureViewerLite node to fix rendering

### PR DESCRIPTION
**Pull request by DolphinDream**
Port the same preference settings for xy/scale into the TVL node to fix the location and the size of the rendering.

- [x] Code changes complete.
- [x] Ready for merge.

Before..

sv-tvl-renderfix-before

After...

sv-tvl-renderfix-after

### CODE REVIEW

**Comment by zeffii** [comment]
quite possibly we'll need to add an even handler for the `undo`, to go through the nodes in ng.nodes and see if any viewer nodes (`node_id(self)`) are present in the bgl callback pool. and drop if there are.

**Comment by DolphinDream** [comment]
Btw, is it just me or the two colors (the selected color in the Color input node and the output of the TVL node) are different ? Could it be the BGL rendering is not doing the same gl composition as the CI node ? The TVL output seems a bit darker.

**Comment by zeffii** [comment]
in 2.80 it seems to swing the other way, it's waay brighter. Not sure what to do about that @DolphinDream

**Comment by DolphinDream** [comment]
> in 2.80 it seems to swing the other way, it's waay brighter. Not sure what to do about that @DolphinDream

I wonder if it’s related to the color management module in Blender.

**Comment by DolphinDream** [comment]
any objections to merging this into master?

**Comment by zeffii** [comment]
nope. work away!

**Pull request merged**
