### PR TITLE
A bit better handling for SvNoDataError

### PR DESCRIPTION
**Pull request by portnov**
At least print name of missed socket.

Was:

      File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/core/update_system.py", line 322, in do_update_general
        node.process()
      File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/nodes/transforms/apply.py", line 43, in process
        mats_ = self.inputs['Matrixes'].sv_get(deepcopy=False)
      File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/node_tree.py", line 143, in sv_get
        raise SvNoDataError
    Node Matrix Apply (verts) had exception

now:

      File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/core/update_system.py", line 322, in do_update_general
        node.process()
      File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/nodes/transforms/apply.py", line 43, in process
        mats_ = self.inputs['Matrixes'].sv_get(deepcopy=False)
      File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/node_tree.py", line 143, in sv_get
        raise SvNoDataError(self)
    Node Matrix Apply (verts) had exception: No data passed into socket `Matrixes'

### CODE REVIEW

**Comment by portnov** [comment]
Any thoughts about how to report errors properly? I mean, display them in Blender's UI, not in console.

**Comment by zeffii** [comment]
I'm all for more exact Exception messages

Sverchok is a complex beast constantly in a state of development, unlike thousands of other add-ons, it can fail in many but unspectacular ways. We can expect our users to have their terminal open (or get used to having it open).

I am not sure there's a nice UI way to display exceptions per node, other than drawing with bgl onto the nodeview as was the new approach in Sverchok Redux. But.. if we go that way it should be optional.

**Comment by portnov** [comment]
Well, this PR is relatively simple change. Things like BGL will require more investigations, that will be separate PR anyway.

**Comment by zeffii** [comment]
cool

**Pull request merged**
