### PR TITLE
Planar edgenet to polygons

### PR DESCRIPTION
**Pull request by Durman**
## Addressed problem description

#86
This will be base for other 2D manipulation with mesh.

## Solution description

This node fill all closed contours of edges graph but graph have to be planar.

## Preflight checklist

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by nortikin** [comment]
so, it is the same as fill holes node?

**Comment by Durman** [comment]
not the same
https://gist.github.com/b0eb16271d33924457e443d74ac3c8d1

**Comment by nortikin** [comment]
have to discribe it in docs

**Comment by Durman** [comment]
ok, added this picture in documentation

**Comment by zeffii** [comment]
add `planar_edgenet_to_polygons` to `sverchok/docs/nodes/alpha_nodes/alpha_nodes_index.rst` , then this can be pushed..

**Comment by zeffii** [comment]
nice one Durman, my apologies for the delay.

**Comment by enzyme69** [comment]
screen shot 2018-08-22 at 12 42 19 am

This is really weird, but with Planar Edgenet result, and manual edit selecting each and every face, I can basically Y operation and separate each face cleanly...

**Comment by Durman** [comment]
New `Edges to faces 2D` node should replace this node but I have found that new node is less robust. There are still some cases which can crash the node. I'm too tired to fix this right now probably in future. So the `planar` node should be remained for a while.

**Pull request merged**
