### PR TITLE
Colornodes

### PR DESCRIPTION
**Pull request by zeffii**
just make them already

### CODE REVIEW

**Comment by zeffii** [comment]
image

prelim implementation. break it in.

**Comment by zeffii** [comment]
maybe this node set needs a mixRGB node.

**Comment by portnov** [comment]
Isn't "mix RGB" just a "vector linear interpolation"?

**Comment by zeffii** [comment]
there tonnes of ways to mix rgb, like photoshop layer mixing..   
- "Vector Linear Interpolation" would be average
- mix maximum of each component
- mix minimum of each component
- subtract a from b 

etc.

**Comment by enzyme69** [comment]
I think Vector Interpolation is acting a bit like Color Ramp. Will make video about it.

screen shot 2017-02-21 at 12 24 51

[evaluate_lerp_001_2017_02_21_01_24.zip](https://github.com/nortikin/sverchok/files/788841/evaluate_lerp_001_2017_02_21_01_24.zip)

I think the Color In and Out are fine like that. Simple. MixRGB would be cool.

**Pull request merged**
