### PR TITLE
test simple fix

### PR DESCRIPTION
**Pull request by zeffii**
updating tests

@DolphinDream  please "squash and merge" PR in the future.  Github reset that option a while back,  next time you commit a PR make sure it is set to squash and merge, and that's what it will do in future.

note to self. quick recreation of json test

```python
import bpy
import sverchok
import json

from sverchok.utils.testing import *
from sverchok.utils.sv_IO_panel_tools import create_dict_of_tree

tree = bpy.data.node_groups['NodeTree']

node = create_node("SvTorusNodeMK2", tree.name)
node.mode = "MAJOR_MINOR"
node.Separate = 0
node.torus_eR = 1.2799999713897705
node.torus_R = 1.0299999713897705
node.torus_r = 0.25
node.torus_iR = 0.7799999713897705
node.torus_n1 = 33
node.torus_n2 = 17
node.torus_rP = 0.029999999329447746
node.torus_sP = 0.029999999329447746
node.torus_sT = 1

export_result = create_dict_of_tree(tree)
string_json = json.dumps(export_result)

text = bpy.data.texts.get('torus.json')
text.from_string(string_json)
```

### CODE REVIEW

**Comment by DolphinDream** [comment]
I wasn’t sure what to do with these tests. What is the process?

**Comment by zeffii** [comment]
if the tests fails, 
1. then click on the X and read the details.
2. you'll see a section showing details of the test-failures, 
3. think about what those failures mean, 
4. then address those.

for the few nodes that export to json as a test, the above snippet is useful.

**Comment by DolphinDream** [comment]
A thought about squashing commits before merge. I do agree squashing in general is recommended.. however, with these MK# promoting updates and moving of the old files to the old_nodes if you squash commits it’s hard to see from the history what are the changes done to the MKn+1 node vs MKn node since the old files are relocated and new files are added.

**Comment by zeffii** [comment]
OK. there's never going to be a perfect system. i won't get hung up on it

**Pull request merged**
