### PR TITLE
Adding Deepcopy version of FullList

### PR DESCRIPTION
**Pull request by Durman**
object mode
#1984

### CODE REVIEW

**Comment by zeffii** [comment]
"object_mode" doesn't strike me as a good name for that mode.  "deepcopy" mode, would be less ambiguous

also, this can be tidier:
```python
        if self.object_mode:
            fullList_deep_copy(X_, max_obj)
            fullList_deep_copy(Y_, max_obj)
            fullList_deep_copy(Z_, max_obj)
        else:
            fullList(X_, max_obj)
            fullList(Y_, max_obj)
            fullList(Z_, max_obj)
```
maybe
```python
        fullList_main = fullList_deep_copy if self.deepcopy_mode else fullList
        fullList_main(X_, max_obj)
        fullList_main(Y_, max_obj)
        fullList_main(Z_, max_obj)
```

interesting that you want to change the nestedness, (i'm not saying that's wrong.. just it might not be suitable as a replacement to vector_in with the same bl_idname.  old .blends may rely on "broken" behaviour)

**Comment by Durman** [comment]
@zeffii I am not sure that deep copy is clear for users that don't know about Python. This new button lets to generate objects correctly so it seems more suitable name for this function but i can fix it of course.))

**Comment by zeffii** [comment]
yes, please change it anyway.  `object_mode` is too much like Blender's own "Object Mode".

**Comment by zeffii** [comment]
It might also be more appropriate to have that button in `draw_buttons_ext`, what do you think @portnov  @nortikin @DolphinDream   , or as the default behaviour of a `SvVectorInMk2` node, and give the draw_buttons_ext a toggle for the `non-deepcopy`.

**Comment by portnov** [comment]
Can we set the property to be defaulting to False (old behaivour) for existing node, but to True for newly created nodes?

**Comment by portnov** [comment]
For example, make BoolProperty(default=False), but set it to true in sv_init.

**Comment by portnov** [comment]
And yes, I'd prefer this to be in draw_buttons_ext.

**Comment by nortikin** [comment]
If we do such things, maybe to thing of generalize them?
I.e. 

1. Other nodes may need that too. 
2. Unify that function property also needed. 
3. Also if there is already such function we need deal with it also.

**Comment by Durman** [comment]
@zeffii I have problem with switcher. Switcher does not appear when I add draw_buttons_ext function :/
Like this:
```Python
    def draw_buttons_ext(self, context, layout):
        layout.row().prop(self, 'object_mode')
```

**Comment by Durman** [comment]
@nortikin Which nodes is needed to fix? I noticed that polar input node already works right.

**Comment by nortikin** [comment]
not sure
beside of subject:
list split changes level at changing unwrap flag. it ruine IO.

**Comment by zeffii** [comment]
> Switcher does not appear when I add draw_buttons_ext function :/
> Like this:
>    ```python
>    def draw_buttons_ext(self, context, layout):
>        layout.row().prop(self, 'object_mode')
>   ```

no reason that doesn't work @Durman  , check your error console?

image

**Comment by Durman** [comment]
@zeffii Oh, I didn't notice that this function create switcher for N panel. :/

**Comment by zeffii** [comment]
if you want you could add another boolean to the class `show_switcher`, and do
```
def draw_buttons(self, context, layout):
    ...
    ...
    if self.show_switcher:
        layout.row().props(self, "deepcopy_mode")
    ...
```

**Comment by zeffii** [comment]
then 
```python
def draw_buttons_ext(self, context, layout):
    layout.prop(self, 'show_switcher')  # <-- set here if you want to show it in draw_buttons
    layout.prop(self, 'deepcopy_mode')  # <-- always show this here.
```

**Comment by zeffii** [comment]
with the new contextual right-click menu for nodes, @portnov might be able to show a way to add this "show_me" option as a rightlick menu entry, so you don't have to use the N-panel if it's inconvenient.

**Comment by portnov** [comment]
Huh. I'm not sure, will layout.prop() work for menus? You can try anyway :)
After #2023 it can look like (in node class):

```python
  def rclick_menu(self, layout, context):
    super().rclick_menu(layout, context)
    layout.prop(self, "deepcopy_mode")
```

Or if it occurs that Blender doesn't support properties in menus, then you'll have to write an operator to be called from menu...

**Comment by zeffii** [comment]
@portnov 

image

but as it receives a click event, the menu disappears. it will work, but ..

**Comment by Durman** [comment]
Ok, I will wait.

@nortikin All generators nodes can't  generate mesh in the same object but we can do it with existing means:

vectorize generetion nodes

**Comment by Durman** [comment]
I added rclick function but it does not work:

**Comment by portnov** [comment]
Sorry then — rclick_menu(layout, context) :) See how it is defined in node_tree.py.

**Comment by Durman** [comment]
I have looked ofcourse but it is dark forest for me.)) I think it can be merged in this condition.

**Comment by zeffii** [comment]
@Durman  in nodetree.py each node gets this function by default
```python
    def rclick_menu(self, context, layout):
        """
        Override this method to add specific items into
        node's right-click menu.
        Default implementation calls `node_replacement_menu'.
        """
        self.node_replacement_menu(context, layout)
```
if you wanted to override that you would add this function to the node and make it something like this:

```python
    def rclick_menu(self, context, layout):
        layout.prop(self, "advanced_mode", text="use deep copy")

        # ignore this for now 
        # self.node_replacement_menu(context, layout)
```

**Comment by Durman** [comment]
It works )

right click

**Comment by zeffii** [comment]
the rightclick stuff is relatively new to us too.  but I think useful to users / devs alike

**Comment by nortikin** [comment]
amazing. really it can handle one parameter for all nodes for some property. for example, separate flag

**Comment by zeffii** [comment]
shall we merge this now @nortikin @portnov @Durman   ?

**Comment by zeffii** [comment]
@Durman  remember you can make a macro for this node so it always ticks that box for you automatically when you add it.  See steps here : https://github.com/nortikin/sverchok/issues/1653

**Comment by zeffii** [comment]
@Durman  your `../279/datafiles/sverchok/node_defaults/node_defaults.json` could look like this
```json
{
    "GenVectorsNode":  {"props": [["advanced_mode", True]]}
}

```

**Comment by portnov** [comment]
I'd prefer "old school" checkbox in the N panel. For all other, I'm fine with merging this.

**Comment by zeffii** [comment]
wait.. i thought the check was both in the N panel and appearing in the Rclick menu. it definitely needs to be in both.

**Comment by zeffii** [comment]
well.. it _is_ in `draw_buttons_ext` too , i understand the reticence to the bool in a menu, but it's not a blocker for me.

**Comment by portnov** [comment]
ah, so it is in two places. Ok then.

**Comment by zeffii** [comment]
Fingers crossed :)

**Pull request merged**
