### PR TITLE
Nodes: bend mesh along path or along surface

### PR DESCRIPTION
**Pull request by portnov**
This introduces two new nodes, which are similar but different:

* Bend object along the path. For example, take a cylinder and bend it so that it's Z axis will follow the curve.
* Bend object along the surface. For example, take a box and bend it so that it's XY plane will follow the surface.

Documentation and examples are in process.

### CODE REVIEW

**Comment by portnov** [comment]
Bend cylinder along curve:
screenshot_20171205_220406

Bend torus along curve:
screenshot_20171205_204934

Bend hex grid along curve:
screenshot_20171205_205517

**Comment by portnov** [comment]
Suzanne amused being bent along surface (the surface is specified by 16 Empties):
screenshot_20171205_235216

Plane bent along toroidal surface (specified by 16 Empties), then Adaptive Polygons applied:
screenshot_20171205_230905

**Comment by portnov** [comment]
Hexa grid along surface
screenshot_20171206_003018

**Comment by portnov** [comment]
screenshot_20171206_004243

**Comment by enzyme69** [comment]
Is one of these does the effect like "rivet button" attached on cloth surface?

**Comment by zeffii** [comment]
looks great!   

ps, whats going on in the Torus bending image?

**Comment by portnov** [comment]
>  whats going on in the Torus bending image?

imagine you are trying to roll up a hola hoop made of rubber :)

**Comment by zeffii** [comment]
yes, it looks cool but

**Comment by portnov** [comment]
The "thihg" on the right is more or less ok (maybe it could look a bit smoother with better precision): just the "tube" of torus is turned out under such angle which we rarely see.
The "things" on the left are actually self-intersections of bent torus, because of too sharp angle under which it is bent (the red polygon in XOY plane connects knots of the path, you can see that it has a sharp angle at left).

**Comment by portnov** [comment]
> Is one of these does the effect like "rivet button" attached on cloth surface?

I'm no quite sure what exactly do you mean :)

@enzyme69 , @zeffii could you please test this branch? I'm a bit worried about performance of "bend along surface" node. "Bend along path" peforms very well for me.

**Comment by portnov** [comment]
hexa-torus-1

**Comment by zeffii** [comment]
portnov, you could make it easy for me to test your branches by branching from `nortikin:sverchok` , and not `portnov:sverchok`.  I don't like having to point my `head` or whatever its called.

**Comment by portnov** [comment]
@zeffii Hmm, will think next time. For now I pushed the same commits into nortikin:bend_along_surface_n.

**Comment by zeffii** [comment]
much appreciated. will test `nortikin:bend_along_surface` . warning.. i have a slow computer :)

**Comment by zeffii** [comment]
and i'm writing music at the moment :)

**Comment by zeffii** [comment]
loaded branch. about to open :)

**Comment by zeffii** [comment]
image

obviously another very cool set of nodes. you'll forgive me please for not having an immediate use for it :)

**Comment by zeffii** [comment]
image
lovely stuff!

**Comment by enzyme69** [comment]
Yeah, I will test when it is merged, I don't feel comfortable using branch
and git yet. But "Rivet" is like when 3D artist like to "parent to vertex"
3D objects into Cloth. Hoping it to follow surface normal without flipping.

**Comment by portnov** [comment]
https://www.youtube.com/watch?v=_ifV6KkVtFs

https://www.youtube.com/watch?v=ygi6_-F0Epw

**Comment by portnov** [comment]
Well, I'm merging this for now.

**Comment by nortikin** [comment]
fap-fap-fap!!

**Comment by nortikin** [comment]
https://gist.github.com/2cd6b123682a241817ae1a2fbf072dc5
something error checking nestiness

**Comment by portnov** [comment]
@nortikin fixed. But i'm not sure it is good idea of interpolation_mk2 to output "numpy.float64", it is very possible that other nodes expect float.

**Comment by portnov** [comment]
https://gist.github.com/f41dfc9089dbd1d3597768f5d6e1d0ce

**Comment by portnov** [comment]
Just found out that "bend along surface" is actually a long-awaited loft node: 
[loft_1_2017_12_10_15_01.zip](https://github.com/nortikin/sverchok/files/1545741/loft_1_2017_12_10_15_01.zip)

**Comment by nortikin** [comment]
it replace somewhere pattern in interpolation vector mk2. so... coool stuff

**Comment by enzyme69** [comment]
@portnov You mean I can "loft" circles with different number of points? Can you show a screenshot of this example? Let me check....

**Comment by portnov** [comment]
@enzyme69 Yes, it is possible. https://gist.github.com/be5a194ad4328da4a8eb102616ea242f

[loft_difff_circles_2017_12_14_04_01.zip](https://github.com/nortikin/sverchok/files/1557903/loft_difff_circles_2017_12_14_04_01.zip)

**Comment by vktcl** [comment]
image
I don’t understand what Grouped does. Can we have an example, please? Thank you very much

**Comment by vktcl** [comment]
@portnov

**Comment by Durman** [comment]
@vktcl https://github.com/nortikin/sverchok/blob/master/docs/nodes/transforms/bend_along_surface.rst

**Comment by nortikin** [comment]
> @vktcl https://github.com/nortikin/sverchok/blob/master/docs/nodes/transforms/bend_along_surface.rst

Grouped. If checked, then the node expects list of lists of vertices at Vertices input. If not checked, then node expects list of vertices at 
@vktcl  that means you split list by some of tools. example list split can output unwrapped
input will looks like [[[[ ]]]] and not [[[ ]]]

**Pull request merged**
