### PR TITLE
fix #4854: "Bend along surface field": Src U/V parameters are not documented good enough

### LINKED ISSUE #4854: "Bend along surface field": Src U/V parameters are not documented good enough
When Orientation == Z, Src U Min/Max for some reason correspond to min/max Y, not X!

### PR DESCRIPTION
**Pull request by satabol**
Windows 11, Blender 3.6.3, Sverchok 1.3.0-alpha
fix #4854:

- Rename old class name to bl_idname: SvBendAlongSurfaceFieldNode -> SvExBendAlongSurfaceFieldNode
- create new version SvExBendAlongSurfaceFieldNodeMK2
- also fixed example

Wrong Bend:
image

Fixed (Expected):
image

**file for tests**: 

[fix_4854.Bend along surface field.test.blend.zip](https://github.com/nortikin/sverchok/files/12754256/fix_4854.Bend.along.surface.field.test.blend.zip)

The main problem is in:
https://github.com/nortikin/sverchok/blob/687ce56547b227a60ee3c8ec7c4d17a166c6b4d3/utils/field/vector.py#L997
image

### CODE REVIEW

**Comment by satabol** [comment]
Hi @portnov! Can you test this PR? And there is yet one problem with "examples\Architecture\Curve Hexagonal Truss". May be this is about numpy we discussed some days ago?

image

**Comment by portnov** [comment]
I would prefer bl_idname = 'SvBendAlongSurfaceFieldMk2Node'. SvEx prefix is used by Sverchok-Extra nodes.

**Comment by portnov** [comment]
"object has no len()" — probably a numpy issue, yes.

**Comment by satabol** [comment]
@portnov . Fixed SvExBendAlongSurfaceFieldNodeMK2->SvBendAlongSurfaceFieldMk2Node.

**Review by portnov — APPROVED** [review]

**Pull request merged**
