### PR TITLE
Console node colours

### PR DESCRIPTION
**Pull request by zeffii**
this is a branch from the console node branch, it applies syntax highlighting. eventually.

- [x] generate random colour lookup table for each char in `self.multiline_text`
- [x] generate correct shader to handle a list of indices to colour multiply
- [x] convert tokenized output to indexmap per character

### CODE REVIEW

**Comment by zeffii** [comment]
code depo
```
vertex_shader = '''
    uniform mat4 ModelViewProjectionMatrix;

    in vec2 texCoord;
    in vec2 pos;
    in int lexer;

    out int v_lexer;
    out vec2 texCoord_interp;

    void main()
    {
       v_lexer = lexer;
       gl_Position = ModelViewProjectionMatrix * vec4(pos.xy, 0.0f, 1.0f);
       gl_Position.z = 1.0;
       texCoord_interp = texCoord;
    }
'''

fragment_shader = '''
    in vec2 texCoord_interp;
    in int v_lexer;

    out vec4 fragColor;
    
    uniform sampler2D image;
    uniform bool ColorMode;
    
    void main()
    {
        vec4 test_color = vec4(1.0, 1.0, 1.0, 1.0);
        vec4 tint = vec4(0.3, 0.3, 0.3, 1.0);
        if (ColorMode) {
           
           // if (v_lexer == 0){ tint = vec4(0.3, 0.3, 1.0, 1.0); }
           // if (v_lexer == 1){ tint = vec4(0.7, 0.3, 1.0, 1.0); }
           // if (v_lexer == 2){ tint = vec4(0.3, 0.7, 1.0, 1.0); }
           // if (v_lexer == 3){ tint = vec4(0.6, 0.3, 0.5, 1.0); }
           
           // fragColor = texture(image, texCoord_interp) * tint;
           test_color = texture(image, texCoord_interp);
           fragColor = test_color * tint;

        } else {
           fragColor = texture(image, texCoord_interp);
        }
    }
'''


```

**Comment by zeffii** [comment]
ok good, multiplication works.
image

**Comment by zeffii** [comment]
harrr! 
image

**Comment by zeffii** [comment]
hHARRR!!
image

**Comment by zeffii** [comment]
for the moment this code expects `\n` line endings, but i think sverchok.log uses `\r\n` ..and other texts might too. It will need to autodetect `newline`.

**Comment by zeffii** [comment]
no.. that's not it.

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
maybe a mode to do the last 20 lines..

**Comment by Durman** [comment]
Would be it possible to show warnings from arbitrary node? for example right below a node like in animation nodes:

**Comment by zeffii** [comment]
yes! it is the next logical step. this is more lightweight than I thought it would be. Especially if I only show the last N lines (say....20 should be enough)

**Comment by zeffii** [comment]
but first i must find how to load the png into a buffer without using bpy.data.images

**Comment by zeffii** [comment]
well well well !  that is a nice new developmen

https://docs.blender.org/api/blender2.8/imbuf.html
```
imbuf.load(filepath)

```

**Comment by zeffii** [comment]
instead.. i'll use the numpy feature to write the image to disk ( `numpy.save`, `numpy.load` ), with instructions on how to generate such a bitmap, and limitations i imposed arbitrarily.

**Pull request closed without merging**
