### PR TITLE
add polyline mk1 file

### PR DESCRIPTION
**Pull request by zeffii**
far from usable yet.

### CODE REVIEW

**Comment by zeffii** [comment]
image

**Comment by enzyme69** [comment]
Updating Sverchok now! Zeffii the man.

**Comment by zeffii** [comment]
it's a branch. you should learn git.

**Comment by kalwalt** [comment]
@enzyme69  you should create a branch:
 
`git branch polyline_mk1`

pull from this into your local:

`git pull git@github.com:nortikin/sverchok.git polyline_mk1`

**Comment by zeffii** [comment]
i'll add Object selection, for `curve.bevel_object`

**Comment by enzyme69** [comment]
Fatal. Nope.

~ git branch polyline_mk2
fatal: Not a git repository (or any of the parent directories): .git

~ git pull git@github.com:nortikin/sverchok.git polyline_mk1
fatal: Not a git repository (or any of the parent directories): .git

**Comment by zeffii** [comment]
well, you have git installed at least. :)

steps (maybe refine this and stick it in the wiki as a how to)

1. make a folder in a sane place called `scripts'
2. inside scripts create two folders
    - addons
    - addons_contrib   (optional)
3. go into addons / open the folder from terminal
4. type `git clone https://github.com/nortikin/sverchok.git`
5. this will create a folder called `sverchok` in the addons folder, it will also download all references to the various branches we have
6. while the terminal is pointed at `../addons` enter sverchok dir by typing `cd sverchok`
7. type `git branches` to see a list of branches
    - to make sverchok switch to one of those branches type `git checkout branchname` (but don't do that yet)
8. open Blender, go to addons and find where Blender is currently looking for sverchok (open Finder at that location because you're going to remove the folder later), disable sverchok and remove the sverchok folder from that location.
9. save users prefs. / startup file
10. go to user prefs / File 
    
    image
    make the scripts path point at your scripts path. _Save user settings_
11. go to addons and find the Sverchok (there should be only one reference to sverchok now - located in your scripts/addons folder )
12. enable it. save user settings / startup file.
13. open blender , check sverchok.   and 
     ## `don't press check for updates / upgrade anymore. ever`
14. to update we now, go back to the terminal and type `git pull` .  boom. wait.  Once complete usually an F8 in Blender will refresh the addons. else restart blender.
15. to check a different Branch you type `git checkout branchname` , and wait for it to switch over.  Press f8 or restart Blender to try out the new branch.
16. to return to master type `git checkout master`.

**Comment by zeffii** [comment]
image

needed.
- obj out
- fillcaps if bevel object

**Comment by zeffii** [comment]
see https://github.com/nortikin/sverchok/pull/1284

**Comment by enzyme69** [comment]
Feedback @zeffii Thanks for the step by step, I am learning something new!

I follow the step by step, but there is no "git pull", I tried.  And I am only seeing "master" for branch.

~/bsscript/addons cd sverchok/
~/bsscript/addons/sverchok git pull
Already up-to-date.
~/bsscript/addons/sverchok git branch
* master
~/bsscript/addons/sverchok git checkout branchname
error: pathspec 'branchname' did not match any file(s) known to git.
~/bsscript/addons/sverchok git branch
* master
~/bsscript/addons/sverchok 

So far, no polyline mk2

**Comment by enzyme69** [comment]
~/bsscript/addons/sverchok git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.

**Comment by enzyme69** [comment]
~/bsscript/addons/sverchok git branch polyline_mk1
~/bsscript/addons/sverchok git pull git@github.com:nortikin/sverchok.git polyline_mk1
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
~/bsscript/addons/sverchok

**Comment by kalwalt** [comment]
@enzyme69 try with the http version:

`git pull https://github.com/nortikin/sverchok.git polyline_mk1`

**Comment by kalwalt** [comment]
of course you have to be in polyline_mk1 branch, before to pull remember to:

`git checkout polyline_mk1`

**Comment by zeffii** [comment]
also.. the branch to test is now https://github.com/nortikin/sverchok/pull/1293

**Comment by enzyme69** [comment]
Tada, still failed.
~/bsscript/addons/sverchok git checkout polyline_mk1
Switched to branch 'polyline_mk1'
~/bsscript/addons/sverchok git pull https://github.com/nortikin/sverchok.git polyline_mk1
fatal: Couldn't find remote ref polyline_mk1
~/bsscript/addons/sverchok

**Comment by enzyme69** [comment]
But...

~/bsscript/addons/sverchok git checkout polyline_mk1b_code_reuse
Branch polyline_mk1b_code_reuse set up to track remote branch polyline_mk1b_code_reuse from origin.
Switched to a new branch 'polyline_mk1b_code_reuse'
~/bsscript/addons/sverchok git pull https://github.com/nortikin/sverchok.git polyline_mk1b_code_reuse
From https://github.com/nortikin/sverchok
 * branch            polyline_mk1b_code_reuse -> FETCH_HEAD
Already up-to-date.

I am not stupid/ I hope

**Comment by enzyme69** [comment]
screen shot 2017-03-03 at 23 24 49

Not I understand!

**Comment by kalwalt** [comment]
> ~/bsscript/addons/sverchok git pull https://github.com/nortikin/sverchok.git polyline_mk1
> fatal: Couldn't find remote ref polyline_mk1
> ~/bsscript/addons/sverchok

Probably because that branch was deleted @enzyme69  see the link of the new branch @zeffii provided.

**Pull request closed without merging**
