### PR TITLE
Vd attr node

### PR DESCRIPTION
**Pull request by zeffii**
## Addressed problem description

Please describe what problem does this PR solve. If it was already was discussed in an issue, it is enough to give a link as #number.
If this adds a new feature (a new node, for example), please state why (for what cases) do you think it is needed.

## Solution description

Please describe how do you intend to solve the problem: change some method, or introduce new class, or whatever.

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [ ] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [ ] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by nortikin** [comment]
so much work not merged

**Comment by zeffii** [comment]
it's merged :)   but not this version of the code.

**Comment by zeffii** [comment]
@nortikin : https://github.com/nortikin/sverchok/pull/2299/commits/dcc89b04fdd23008937db190a7307b84d721dceb

**Comment by zeffii** [comment]
iojson stuff not implemented yet for vd_attrs_node  .   ooooops :)

**Pull request closed without merging**
