### PR TITLE
Turtle API (WIP)

### PR DESCRIPTION
**Pull request by portnov**
refs #2759

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [ ] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [ ] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
https://gist.github.com/28a9fb8ddcb9c80a009a3f6b7e3220c0

Screenshot_20191223_222312

**Comment by portnov** [comment]
https://gist.github.com/a66cd00fb657cb4cce8be9b282e410bb
Screenshot_20191225_002453

**Comment by portnov** [comment]
https://gist.github.com/f4ba0eda672332add2347a5b55284ec1

Screenshot_20191227_203145

**Comment by Durman** [comment]
Looks like this:
https://bl.ocks.org/mbostock/97f1cdb9e0a695cd8df4

**Comment by portnov** [comment]
https://gist.github.com/e04e7c9056125492c71692fe69315537

Screenshot_20191227_205636

**Comment by portnov** [comment]
Well, actual maze generation is somewhat more complex algorithm than a simple random walk, but I believe it can be written in terms of "turtle api".

**Pull request merged**
