### PR TITLE
Turning live update mode from Operator to Handler

### PR DESCRIPTION
**Pull request by Durman**
## Addressed problem description

#2458 
Previous pull request have revealed that Operators are not appropriate for monitoring objects changes. 
I decided that having two different modes of `live update` mode is too much in spite of this approach is completely different. So I have deleted old approach. If it will be found that it had some benefits we can return it back. There is need in testing new approach. I expect that it can become part of update system in 2.8. 

Also i deleted options of enabling this mode in preferences of Sverchok. I don't see that 3D panel is overweight now and can't keep button of this node constantly.

If there will not be any objections against such changes I merge it to master. 

## Preflight checklist

- [x] Code changes complete.
- [x] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by zeffii** [comment]
You might want to revert the behaviour to like how it was for a number of years, which worked fine for me and others. 

as for the handlers, they are different in 2.8 - and by no means a priority (for Blender Devs). it's not that this isn't an interesting issue (it clearly is.. ).  but the handlers and scene update information is not granular enough imo ( or show me how it is )

**Comment by Durman** [comment]
I understood you. 
In this case I see two ways of developing those features:
- It have to become separate mode. 
- Or it can replace old code but after enough testing. 

Which way will be more welcome?

**Comment by zeffii** [comment]
i think what might happen when updates from `edit_mode` / `object_mode transforms` are obtained by a handler, is the time between tree update request may become dramatically smaller than the time needed by the python interpretter to do the update. Complexity of nodetree downstream and computer speed will of course play a massive roll.  This is another reason why the operator is fine for functional usage,  i don't really get the real need to have instant feedback,.it's not a live performance tool where latency must be as minimal as possible.

> Which way will be more welcome?

i don't know

**Comment by Durman** [comment]
I don't understand idea with timer. 

I'm imagining working of Blender like video game. There is such important parameter like FPS. Translating to Blender language updates events per second. Blender like video game can generate for example 60 FPS. We can reduce the number but what purpose for? If you can computer unable to calculate 60 events per second this number will be reduced automatically. 

If you have timer 13 FPS it won't be work if performance of computer can't handle even with such number of update events. By the way timer can be implemented to handler. There is no difference here with Operator.

Complexity of node tree cause the same effect on performance with Operator and Handler implementation. They have similar code in this part.

> i don't really get the real need to have instant feedback,.it's not a live performance tool where latency must be as minimal as possible.

Here I'm really suprised. 😕
What was all this discussion about? #2420
In this case probably the name of this mode should be renamed. It looks that `live update` is not suitable enough.

**Comment by zeffii** [comment]
> I don't understand idea with timer.

with timer set to something low, it's likely easier for any computer to handle - depending on complexity (but equally as easy to grind the machine to a halt by `unlucky input` / `heavy processing` steps)

i don't know if updates handler events are queued while waiting for python interpretter, but i assume they are.
------

i suspect there are two very different types of Sverchok users. 

1.  set up layout, control everything algorithmically ( sort of static input, but parametric requiring no live user input )
2.  some users mix the features of the tool as a live-interface that depends at times on their input, and processes that input constantly.

with the set of people in group 2 i'm not super interested in entertaining / spending time on. yet again, i guess i'll better leave this to person(s) who do need this live interaction.

**Comment by Durman** [comment]
Okay, I will revert all changes which I done to this mode and won't do any others.

**Pull request closed without merging**
