### PR TITLE
Pentagon Tiler

### PR DESCRIPTION
**Pull request by vicdoval**
image
image
image
image
image

- [x] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by vicdoval** [comment]
This is what i have so far, im going to merge it like this. Maybe someone or me in another time will be encouraged to code the missing 6 to 13 pentagon types docs
image
image
image

**Comment by portnov** [comment]
Wow.
The next goal is the Penrose tiling?

**Comment by vicdoval** [comment]
@portnov it could be great to have Pernose tiling in a node... maybe some day... by now this still works https://elfnor.com/generative-art-penrose-tilings.html :)

**Comment by portnov** [comment]
@vicdoval 
Just created the node and ticked "Separate" checkbox
```
2020-01-04 21:33:08,708 [ERROR] sverchok.core.update_system: Node Pentagon Tiler had exception: unsupported operand type(s) for +: 'int' and 'tuple'
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.82/scripts/addons_contrib/sverchok/core/update_system.py", line 343, in do_update_general
    node.process()
  File "/home/portnov/.config/blender/2.82/scripts/addons_contrib/sverchok/nodes/generators_extended/pentagon_tiler.py", line 236, in process
    verts, edges, polys = self.pentagon_tiler(par)
  File "/home/portnov/.config/blender/2.82/scripts/addons_contrib/sverchok/nodes/generators_extended/pentagon_tiler.py", line 213, in pentagon_tiler
    vert_list = center(vert_list)
  File "/home/portnov/.config/blender/2.82/scripts/addons_contrib/sverchok/utils/modules/vertex_utils.py", line 25, in center
    avr = list(map(sum, zip(*vec)))
TypeError: unsupported operand type(s) for +: 'int' and 'tuple'
```

**Comment by vicdoval** [comment]
@portnov thanks for reporting 😄

**Pull request merged**
