### PR TITLE
Import the edge list caching from 2.79 to 2.80

### PR DESCRIPTION
**Pull request by DolphinDream**
Import edge list cache (will be needed by other nodes soon to be ported to 2.80)

### CODE REVIEW

**Comment by DolphinDream** [comment]
@zeffii If no objections, I can integrate this in b28_prelease_master.

**Comment by zeffii** [comment]
yes go for it.   but i caution against retrofitting existing nodes/classes initially.  get it working first, then become confident that it is implemented correctly. then (later) draw up a plan / protocol to implement it in any node where it would reasonable be a net positive.

**Comment by DolphinDream** [comment]
@zeffii any preference to the merge type? Create a merge commit / Squash and Merge / Rebase and Merge.

**Comment by zeffii** [comment]
squash and merge. please

**Pull request merged**
