### PR TITLE
Connectors Operators

### PR DESCRIPTION
**Pull request by vicdoval**
:)
VEP Conector: 
'V' key

untitled

Temporal Viewer:
Ctrl + Left Click

untitled2

Temporal Sthetoscope:
Ctrl + Right Click (iterates through outputs)
untitled1

- [ ] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by vicdoval** [comment]
I am having troubles to add properties to de keymap
```
        kmi = km.keymap_items.new('node.sv_temporal_viewer', 'LEFTMOUSE', 'RELEASE', ctrl=True)
        kmi.properties.cut_links = False    # this is the conflict line
        nodeview_keymaps.append((km, kmi))
```
returns
`AttributeError: 'OperatorProperties' object has no attribute 'cut_links'`

But the property is there and can be activated in the Blender properties panel
Has any of you found that problem? Am I doing something wrong?

**Comment by vicdoval** [comment]
I found the answer to my problem, It was the   registering order of the modules, the nodeview_keymap was being registered before the new operators...

**Comment by zeffii** [comment]
cooool.  how about `ctrl+middlemouse scroll` while stethoscope is active, and it will iterate through the outputs of the data-passing node ..

i use that in my own addon for TextEditor to scroll through the active Text datablock :)  works nicely.

**Comment by zeffii** [comment]
> the nodeview_keymap was being registered before the new operators...

phew  :)

**Comment by zeffii** [comment]
` from sverchok.ui.nodeview_rclick_menu import get_verts_edge_poly_output_sockets ` 

isn't perfect but i'm glad you reuse it.

**Comment by Durman** [comment]
It will be nice to create `wheel` menu for this as well. [Have a look](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/getting_started/interface.html#viewer) how it is done in AN:

**Comment by vicdoval** [comment]
> cooool. how about `ctrl+middlemouse scroll` while stethoscope is active, and it will iterate through the outputs of the data-passing node ..
> 
Ctrl + Middlemouse is taken for horizontal scrolling...

> It will be nice to create wheel menu for this as `well`. Have a look how it is done in AN:

It could work too, this is nearer to the approach of the node-wrangler add-on but i agree more menus could be added to sverchok

**Comment by vicdoval** [comment]
Additive linking:
additive

Cut previous and link:
cut_links

**Comment by enzyme69** [comment]
@vicdoval From quick test, in my testing, V connect but does not update, until I scrub on the parameter and then it gets updated.

It's great addition however I will test the rest of features!

**Comment by vicdoval** [comment]
@enzyme69  I was fine with that behaviour because usually you connect first and tweak later but maybe should intermediately update anyway...even if is not necessary in some cases

**Pull request merged**
