### PR TITLE
Mesh viewer ensure list

### PR DESCRIPTION
**Pull request by vicdoval**
Mesh Viewer fails when inputting numpy arrays so i added a check to convert the inputs to list if needed
- [x] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
It's actually was supporting np.arrays of vectors which increased performance significantly. See the comment.

https://github.com/nortikin/sverchok/pull/3475#issuecomment-680010778

**Comment by vicdoval** [comment]
But was failing if merge was enabled.
This solution is not ideal but more robust... feel free to remove the check if you manage to do it numpy-ready

**Comment by Durman** [comment]
It would be better to create bug report instead if you are not ready to supply normal solution.

**Comment by vicdoval** [comment]
> It's actually was supporting np.arrays of vectors which increased performance significantly. See the comment.
> 
> [#3475 (comment)](https://github.com/nortikin/sverchok/pull/3475#issuecomment-680010778)

I was not aware of this feature and i could only see the node was failing when numpy arrays were given so thought this was a "normal solution"

**Pull request merged**
