### PR TITLE
Shader utils more primitives + timegraph updates

### PR DESCRIPTION
**Pull request by zeffii**
several useful 2d shapes
- [x] line
- [x] rounded rect
- [x] circle
- [x] arc
- [x] bezier
- [ ] polyline

sample script..
```python
"""
in origin_a v d=(0,0,0) d=2
in origin_b v d=(1,0,0) d=2
in origin_x v d=(3,3,0) d=2
in width s d=2.0 n=2
in precision s d=32 n=2
in rect_r s d=1.2 n=2
out verts v
out faces s
"""

from sverchok.utils.modules.shader_utils import ShaderLib2D

x1, y1 = origin_a[:2]
x2, y2 = origin_b[:2]
x3, y3 = origin_x[:2]

black = (0.0, 0.0, 0.0)
f = ShaderLib2D()
f.add_rect(2, -3, 6, 4, black)
f.add_line(x1, y1, x2, y2, width, black)
f.add_circle(x1, y1, width, black, precision)
f.add_arc(x1, y1, 0, np.pi/2, 15.0, 3.2, black, precision=15)
f.add_rect_rounded(x3+15, y3, 12, 6, black, rect_r, precision=4)
f.add_bezier(((0, 0), (10, 0), (10, 10), (20, 10)), width, black, precision) 

g = f.compile()

add_z = lambda n: (n[0], n[1], 0.0)
verts.append(list(map( add_z, g.vectors)))
faces.append(g.indices)
```
image

### CODE REVIEW

**Comment by zeffii** [comment]
thanks for your feedback @durman.

**Comment by Durman** [comment]
You also can thank me here #4127

And in future PRs looking like a spam like these #4081 #4102, if I won't be too tired ))

**Comment by zeffii** [comment]
@enzyme69  it will be a small library for creating multiple parametric 2d shapes for use in "bgl" drawing to nodeview or 3dview as a 2d overlay (POST_PIXEL). right now i've only implemented add_rect, because i use it in the time-graph.

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
2d polyline will have to wait.

**Pull request merged**
