### PR TITLE
Implementation Exponential sequence node

### PR DESCRIPTION
**Pull request by portnov**
Shortly this was described in #517 as No.5.
Please review.

### CODE REVIEW

**Comment by zeffii** [comment]
I have one concern, it's the `mode change` code. In your case (and probably in the node you copied it from -- I wrote this probably) it is overkill to store the current mode and have a test for it upon mode change.

```python
    current_mode = StringProperty(default="ALPHA")

    modes = [
        ("ALPHA", "Log", "Specify coefficient in exp(alpha*n)", 1),
        ("BASE",  "Base", "Specify base in base^n", 2),
    ]

    def mode_change(self, context):

        # just because click doesn't mean we need to change mode
        mode = self.mode
        if mode == self.current_mode:
            return

        if mode == 'ALPHA':
            self.inputs[1].prop_name = 'alpha_'
        else:
            self.inputs[1].prop_name = 'base_'

        self.current_mode = mode
        updateNode(self, context)

    mode = EnumProperty(items=modes, default='ALPHA', update=mode_change)

    func_dict = {'ALPHA': exponential_e,
                 'BASE': exponential_b }
```

would just be (something like)
```
    modes = [
        ("ALPHA", "Log", "Specify coefficient in exp(alpha*n)", 1),
        ("BASE",  "Base", "Specify base in base^n", 2),
    ]

    def prop_change(self, context):
        if self.mode == 'ALPHA':
            self.inputs[1].prop_name = 'alpha_'
        else:
            self.inputs[1].prop_name = 'base_'
    
        updateNode(self, context)

    mode = EnumProperty(items=modes, default='ALPHA', update=prop_change)

    func_dict = {'ALPHA': exponential_e, 'BASE': exponential_b }
```
less code, not a big deal to set the inputs again. I might even suggest
```python
    modes = [
        ("alpha_", "Log", "Specify coefficient in exp(alpha*n)", 1),
        ("base_",  "Base", "Specify base in base^n", 2),
    ]

    def prop_change(self, context):
        self.inputs[1].prop_name = self.mode
        updateNode(self, context)

    mode = EnumProperty(items=modes, default='alpha_', update=prop_change)

    func_dict = {'alpha_': exponential_e, 'base_': exponential_b }
```

**Comment by zeffii** [comment]
if you were to ask me why I have that kind of code in my nodes, i'm not sure if I would be able to give a satisfying answer.

**Comment by portnov** [comment]
ok, will change it :)

**Comment by portnov** [comment]
Done.

**Pull request merged**
