### PR TITLE
Inset faces node

### PR DESCRIPTION
**Pull request by Durman**
## Addressed problem description

This PR is attempt to utilize `inset face` features ([inset_individual](https://docs.blender.org/api/current/bmesh.ops.html#bmesh.ops.inset_individual), [inset_region](https://docs.blender.org/api/current/bmesh.ops.html#bmesh.ops.inset_region)) of bmesh operators.

There is known issues with bmesh operators. They does not design to deal with multiple values:
#1910

I have made some trick to avoid the problem and it looks like it's working.
Now working time grows linear with linear increasing number of input faces. 

## Preflight checklist

- [x] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete.
- [x] Manual testing done. 
- [ ] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
@portnov I mean like this approach:

By the way, `inset_individual` operator have managed perfectly with distributing custom data of faces.))

**Comment by Durman** [comment]
10000 custom insertions for 1 second.  Not too bad I think. =)

**Comment by portnov** [comment]
So you are using a "custom data layer" to store "index of the face in the initial mesh" to untangle face indexes after the bmesh op. I wonder if this approach has better or worse performance comparing to storing each field of "per-face data" in separate custom data layer. Will check...

**Comment by portnov** [comment]
It appears that your approach is faster, at least comparing to my implementation. Will leave it here, for future reference

```python
class SvItemData(object):
    def __init__(self, *args, **kwargs):
        self.int = dict()
        self.float = dict()
        self.string = dict()
        self.material_index = None
        self.tag = None
        self.select = None

        if args:
            if len(args) == 1:
                value = args[0]
                if isinstance(value, (int, str, float)):
                    self.value = value
                elif isinstance(value, (list, tuple)):
                    self.set_list("value", value)
                else:
                    raise TypeError("Unsupported type of single argument for SvItemData(): {}: {}".format(value, type(value)))
            else:
                self.set_list("value", args)

        if kwargs:
            for key, value in kwargs.items():
                self[key] = value

    def set_list(self, key_base, values):
        for i, value in enumerate(values):
            key = "{}[{}]".format(key_base, i)
            self[key] = value

    def __getitem__(self, key):
        if key in self.int:
            return self.int[key]
        elif key in self.float:
            return self.float[key]
        elif key in self.string:
            return self.string[key]
        else:
            return None

    def __setitem__(self, key, value):
        if isinstance(value, int):
            self.int[key] = value
        elif isinstance(value, float):
            self.float[key] = value
        elif isinstance(value, str):
            self.string[key] = value
        else:
            raise TypeError("Unsupported type of custom data for key {}: {}: {}".format(key, value, type(value)))

    def __int__(self):
        value = self.value
        if isinstance(value, int):
            return value
        else:
            raise TypeError("This is not an integer value")

    def __float__(self):
        value = self.value
        if isinstance(value, float):
            return value
        else:
            raise TypeError("This is not a float value")

    def __str__(self):
        value = self.value
        if isinstance(value, str):
            return value
        else:
            raise TypeError("This is not a string value")

    @property
    def value(self):
        return self["value"]

    @value.setter
    def value(self, new_value):
        self["value"] = new_value

    @staticmethod
    def from_bmesh_faces(bm):
        result = []
        for face in bm.faces:
            data = SvItemData()
            data.material_index = face.material_index
            data.tag = face.tag
            data.select = face.select
            for key, layer in bm.faces.layers.int.items():
                data.int[key] = face[layer]
            for key, layer in bm.faces.layers.float.items():
                data.float[key] = face[layer]
            for key, layer in bm.faces.layers.string.items():
                data.string[key] = face[layer]
            result.append(data)
        return result

    @staticmethod
    def assign_to_bmesh_faces(data_list, bm):
        data_list_up = []
        for data in data_list:
            if not isinstance(data, SvItemData):
                data = SvItemData(data)
            data_list_up.append(data)
            for key in data.int:
                layer = bm.faces.layers.int.get(key)
                if layer is None:
                    print("new int key:", key)
                    bm.faces.layers.int.new(key)
            for key in data.float:
                layer = bm.faces.layers.float.get(key)
                if layer is None:
                    print("new float key:", key)
                    bm.faces.layers.float.new(key)
            for key in data.string:
                layer = bm.faces.layers.string.get(key)
                if layer is None:
                    print("new string key:", key)
                    bm.faces.layers.string.new(key)

        for data, face in zip(data_list_up, bm.faces):
            if data.material_index is not None:
                face.material_index = data.material_index
            if data.tag is not None:
                face.tag = data.tag
            if data.select is not None:
                face.select = data.select

            for key, value in data.int.items():
                layer = bm.faces.layers.int.get(key)
                #print("L[{}]: {}".format(key, layer))
                #print("F: {}: {}: {}".format(face, layer, value))
                face[layer] = value

            for key, value in data.float.items():
                layer = bm.faces.layers.float.get(key)
                if layer is None:
                    layer = bm.faces.layers.float.new(key)
                face[layer] = value

            for key, value in data.string.items():
                layer = bm.faces.layers.string.get(key)
                if layer is None:
                    layer = bm.faces.layers.string.new(key)
                face[layer] = value

```

**Comment by Durman** [comment]
Face mask selection output socket:
face_mask

**Comment by Durman** [comment]
`Inset region` mode with random face selection of a cube.

**Comment by portnov** [comment]
What is the difference between "extrude separate/region" and "inset separate/region"?

**Comment by Durman** [comment]
I think their are different only in ultimate desirable result. But some extra options make them nearly or maybe entirely equal. At least, extruding does not expect scaling of inserted face. Also they can shoes normals differently for shifting inserted faces.

**Comment by Durman** [comment]
Improving selection mask:
mask generation

**Pull request merged**
