### PR TITLE
Implement Suzanne/Monkey primitive.

### PR DESCRIPTION
**Pull request by portnov**
I can't say it is very useful, but it looked strange that Sverchok did not have this primitive.

### CODE REVIEW

**Comment by portnov** [comment]
screenshot_20171126_151436

**Comment by zeffii** [comment]
beside it being a useful primitive, it's also a useful example of the mechanics of a simplest node.

**Comment by nortikin** [comment]
maybe sverchok-beast node?

**Comment by zeffii** [comment]
Mascot node with switch between monkey and cricket

**Comment by nortikin** [comment]
i have an idea, will test week later.
Cricket with different parameters.

**Pull request merged**
