### PR TITLE
Handler update

### PR DESCRIPTION
**Pull request by ly29**
So this seems to be working quite nicely without any problems.

I am sure there are some however, since this changes how edit changes are handled.

@zeffii 
Would be nice if you could test if this resolves the crash you experienced.

### CODE REVIEW

**Comment by ly29** [comment]
I thinks is pretty much good to go, but would like to hear a second opinion.

**Comment by zeffii** [comment]
I aim to test after breakfast.

**Comment by zeffii** [comment]
think you forgot to push a few commits
```python
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\node_tree.py", line 387
    if not self.is_frozen()
                          ^
SyntaxError: invalid syntax
BCPrompt: operators registered
```

**Comment by ly29** [comment]
Indeed I did, getting sloppy.

**Comment by ly29** [comment]
Turned on linter now btw.

**Comment by zeffii** [comment]
A fresh connection to bmeshviewer misses an update , reproduce

- make snlite (petal_sine), 
- connect verts to bmeshviewer,   (obj is created)
- now connect edges,  and the bmviewer doesn't generated edges until it is triggered to update from petal sine.

I'm not sure if this was always the behaviour, but the same is not the case for vdmk2

**Comment by ly29** [comment]
Switching to pre seems to fix that for me.

**Comment by ly29** [comment]
Many small things will likely pop up, sadly, but avoiding crashes and then try squash other changes of behaviour seems like the sane way forward for me.

**Comment by zeffii** [comment]
not worried about the many smaller things that might arise. The ability to use a new Blender build is worth it :)  

Thanks!

**Pull request merged**
