### PR TITLE
travis to 2.82a

### PR DESCRIPTION
**Pull request by vicdoval**
Trying to move travis to 2.82

### CODE REVIEW

**Comment by vicdoval** [comment]
I will push this changes i hope it does not break everything

**Comment by zeffii** [comment]
do it :)

**Comment by portnov** [comment]
@vicdoval you probably have to update tests/references/userpref.blend...

**Comment by portnov** [comment]
```
ln: failed to create symbolic link '/home/travis/build/nortikin/sverchok/installation/blender/2.82/scripts/addons_contrib/sverchok': No such file or directory
```
this seems to be the problem. I wonder why.

**Comment by vicdoval** [comment]
Now it works #3104

**Pull request merged**
