### PR TITLE
Set custom UV map

### PR DESCRIPTION
**Pull request by Durman**
## Addressed problem description

Continue of experiments from here: #2218

In this time I would like to create very simple node which just takes X Y coordinates of given mesh and creates UV map from them. It will be already useful for 2d meshes but for 3d mesh unwrapping nodes are required (not in this PR).

## Preflight checklist

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete.
- [x] Manual testing done. 
- [x] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
Example of result which I'm expecting from working of this node and `Inset faces` node.

**Comment by Durman** [comment]
This works as flat projection:

**Comment by portnov** [comment]
Another possible option will be to start from any face and walk from it in all directions (either depth-first or breadth-first), unwrapping all faces without deformation. Mappings of different faces will obviously overlap, but for some kinds of textures this is okay.

**Comment by Durman** [comment]
Yes, but this should be another node like here:

**Comment by Durman** [comment]
I'm looking for a way of update an object after resetting uv coordinates. It looks like some update event should be caused for this. It works only if change frame number now.

It looks like does not work:
https://blender.stackexchange.com/questions/140789/what-is-the-replacement-for-scene-update

**Comment by Durman** [comment]
https://blender.stackexchange.com/questions/163300/how-to-update-an-object-after-changing-by-script-of-uv-coordinates

**Comment by Durman** [comment]
I have been got the answer =D
`obj.data.update()`

**Comment by enzyme69** [comment]
Cricket with diamond UV https://skfb.ly/6SQxB

**Pull request merged**
