### PR TITLE
Snlite revision

### PR DESCRIPTION
**Pull request by zeffii**
this allows user to load blends that crash .blender

### CODE REVIEW

**Comment by vicdoval** [comment]
Btw is it possible to set deepcopy=False in the Snlite?

**Comment by zeffii** [comment]
>  Btw is it possible to set deepcopy=False in the Snlite?

should be..

**Comment by zeffii** [comment]
found the problem in snlite anyway..

**Comment by zeffii** [comment]
@vicdoval  do you think all input from sockets should be `deepcopy=False` by default? :)

snlite uses sv_get only in `make_new_locals()`
```

       ...
       ...
            if s.is_linked:
                val = s.sv_get(default=[[]])
                if sock_desc[3]:
                    val = {0: val, 1: val[0], 2: val[0][0]}.get(sock_desc[3])
            else:
                val = sock_desc[2]
                if isinstance(val, (int, float)):
                    # extra pussyfooting for the load sequence.
                    t = s.sv_get()
                    if t and t[0] and len(t[0]) > 0:
                        val = t[0][0]
```

**Comment by zeffii** [comment]
i would be happy to make a preprocessor directive like 
```
deepcopy=True
in verts v
out verts_out v
...etc
...etc
```
and otherwise assume user is OK with `deepcopy=False`

**Comment by zeffii** [comment]
or just `deepcopy`

**Comment by zeffii** [comment]
anyway. i need to eat.

**Comment by Durman** [comment]
Is it really need for SNL? I think if you need a performance make a normal node.

**Comment by zeffii** [comment]
i'll add it because it makes sense, it will be the default.

imho it's bad practice to modify incoming data "in-place" in the first place. let these reason be obvious.

**Comment by Durman** [comment]
Am I correctly understand that `deepcopy=False` means that data is get by reference?

**Comment by vicdoval** [comment]
I would go for deepcopy=False as the default, think for most of the cases is better and you can always make a deepcopy inside the node. 
But even better if you add that preprocessor directive :)

@Durman I thought about this testing a SNL vs a node, i think is a good idea to give the chance to make a faster SNL

**Comment by zeffii** [comment]
just to recap, the default will be `deepcopy=False`,  the user  doesn't have to do anything. if the user really wants to deepcopy, then they add the `directive` at the top.

**Comment by Durman** [comment]
I don't think that SNL has such a chance. The performance will be lousy anyway. 

I see the node as a good way for experiments for newcomers. `deepcopy=False` can lead to unexpected results and make SNL more difficult tool. It can lead to new issues and take time of Sverchok developers for explaining of SNL tricky behaviour. We should try to make things more simple and do not overcomplicate them. Than less we have to keep in mind then better. Even standard `sv_get` method has `deepcopy=True` by default. It had took long to understand difference between getting data by reference and as copy for me.

**Comment by zeffii** [comment]
it will take a while to get around to this.

**Comment by zeffii** [comment]
actually, you might be right @Durman  , maybe the default will be `deepcopy=True`, and only if the user wants to not use deepcopy, then they use the directive `no deepcopy`

**Comment by Durman** [comment]
I have made simple test of adding 100000 vectors for comparison with `vector math` node. SNL is faster but I'm not sure that with more complex code it can have the same advantage.

```
2020-03-12 20:50:59,324 [DEBUG] sverchok.core.update_system: Processed  Line in: 0.2084
2020-03-12 20:50:59,642 [DEBUG] sverchok.core.update_system: Processed  Scripted Node Lite in: 0.3160
2020-03-12 20:51:01,641 [DEBUG] sverchok.core.update_system: Processed  Vector Math in: 0.4199
```

```Python
'''
in v1 v d=[] n=1
in v2 v d=[] n=1
out v_out v
'''

v_out = list(map(lambda u, v: (u[0]+v[0], u[1]+v[1], u[2]+v[2]), *[v1, v2]))
```

**Comment by vicdoval** [comment]
@Durman  was you test before #2957?
testing your script with 100000 vectors this is what I get
```
2020-03-12 20:23:36,531 [DEBUG] sverchok.core.update_system: Processed  Line in: 0.1077
2020-03-12 20:23:36,806 [DEBUG] sverchok.core.update_system: Processed  Scripted Node Lite.001 in: 0.2742
2020-03-12 20:23:36,901 [DEBUG] sverchok.core.update_system: Processed  Vector Math in: 0.0878
```

**Comment by Durman** [comment]
Before. The point of test was that the SNL was doing the same code as math node.

**Pull request closed without merging**
