### PR TITLE
Obj boolean internal

### PR DESCRIPTION
**Pull request by zeffii**
hahah.. i don't know..

image

### CODE REVIEW

**Comment by Durman** [comment]
Probably it would be possible to create series of `set modifier` nodes and `set boolean modifier` could be one of them.

**Comment by portnov** [comment]
@Durman , the problem is, you will have to write UI and write some code for each modifier. In fact, this is what Sorcar consists of.

**Comment by Durman** [comment]
Well then should we have such nodes? It is possible just adding modifiers via standard Blender UI. 
Or creating such nodes can gain some benefits?

**Comment by Durman** [comment]
`Sorcar` code of `boolean modifier` node:
https://github.com/aachman98/Sorcar/blob/8cd2ed94902a7b16075c5ca3c5ecc447565ef356/nodes/modifiers/ScBooleanMod.py#L1-L39

**Comment by zeffii** [comment]
i'm geared up to add only a few modifier nodes.
- array
- screw
- 
..even if it's just to see how useful that would be.

**Comment by zeffii** [comment]
image

it's a bit wonky.

**Comment by zeffii** [comment]
yeah, i think i'll not do this. People who want this kind of stuff should know that a lot is possible
image

**Pull request closed without merging**
