### PR TITLE
Polishing icons, forgetting nodes, matrix nodes to matrix category

### PR DESCRIPTION
**Pull request by vicdoval**
A lot for a PR but I hope you don't mind in this case.
The PR covers this topics
_Polishing some icons and adding some more to the new nodes.
image

_Take action on #2601
_Matrix category filled with Beta Matrix Nodes
image
image

_Added Matrix Normal Docs
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
It seems tests were using old nodes. Could you please update tests to use new nodes?...

**Comment by vicdoval** [comment]
Well..., i was deleting the references to the old nodes... not sure how to deal with some of the tests.. but maybe i should try...

**Comment by vicdoval** [comment]
I did some more cleaning also matching folders and menu and 
Inset Special Docs

CAD menu and folder
image
Transforms Menu and folder
image

I am not very attached to this changes but I think they go in the right direction so if nobody is against I will merge all this changes and they can always be discussed and reverted later

**Comment by vicdoval** [comment]
I am going to merge this PR before I start moving everything (and I leave that to you @zeffii )  :D

**Pull request merged**
