### PR TITLE
adds ui reshuffle

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
```md
[12:39] <zeffii> ideasman42, is there any way to figure out what we need to disable or set?  
        https://github.com/nortikin/sverchok/blob/master/nodes/viz/texture_viewer.py  
        it only happens on osx..not on windows/linux
[12:40] <ideasman42> zeffii, just set texture state back to how it was originally
        <ideasman42> zeffii, there are many gl-debugging tools
```
@kalwalt

**Comment by kalwalt** [comment]
@zeffii  i like the new layout,

i will look into it again if i have a bit of time.

**Comment by enzyme69** [comment]
I would probably never mix float scalar modulo and degree that way, but thanks for showing.

**Pull request merged**
