### PR TITLE
Simple test case for reload.

### PR DESCRIPTION
**Pull request by portnov**
## Addressed problem description

See #2066.

## Solution description

Add simple testcase that triggers reload and then tries to import `sverchok.core`.
Do not abort first processing after reload.

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [x] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by zeffii** [comment]
best continue here

> @zeffii what's the point in that "return" after "reload_sverchok()"? Are there situations when "reload_sverchok()" call leads to something in process_tree() not working?

looking.

**Comment by zeffii** [comment]
another test is to enable / disable the sv addon.

**Comment by portnov** [comment]
I believe we can merge this? no point in hanging PRs...

**Comment by zeffii** [comment]
do it!

**Pull request merged**
