### PR TITLE
Scripting nodes to Script category

### PR DESCRIPTION
**Pull request by vicdoval**
image
Anyone against this PR?

### CODE REVIEW

**Comment by zeffii** [comment]
maybe `mesh eval` too?
`profile mk3`

**Comment by vicdoval** [comment]
I was thinking about those nodes too...
image
Any other candidate?

**Comment by portnov** [comment]
Do we really support "SN Functor B"? Maybe it should go to Alpha, or even to Old nodes?

**Comment by zeffii** [comment]
snfunctor b, should indeed perhaps be demoted to Alpha. I never got around to pumping real time into that.

**Comment by nortikin** [comment]
cool. it makes more sence now
move recieve from sorcar to exchange section!

**Pull request merged**
