### PR TITLE
"Adaptive tessellate" node

### PR DESCRIPTION
**Pull request by portnov**
## Addressed problem description

Given a Surface object, it is easy to convert it to mesh by evaluating it on a cartesian grid, by use of "Evaluate Surface" node. However, in some cases a cartesian grid is not suitable. When the surface has some "almost flat" places and others, that are much more "bent" or even "sharp", a naive cartesian grid approach:

* generates too many points on flat areas
* and generates too few points in the curvy areas.

## Solution description

* Start with a cartesian grid.
* Then add more points into "most interesting" grid cells. "Interesting" cells may be defined as:
  * Having larger area (more precisely, area stretching factor)
  * Having bigger curvature value. Curvature may be defined as Gaussian curvature, mean curvature or as bigger one of the principal curvatures.
* Make a Delaunay triangulation of all these points
* And then map this triangluated thing onto the surface.

This approach can not automatically handle cases where the surface should have sharp edges. However, if we just happen to know where these sharp edges are, we can manually add points on these edges before building a Delaunay triangluation.

On the left: a surface evaluated with cartesian grid; on the right: the same surface with adaptive tessellation. Each of these meshes has (nearly) the same count of triangles - 41K.
Screenshot_20200503_224620
The same with wireframe enabled.
Screenshot_20200503_224647

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
Since the node uses Delaunay triangulation, it is enough to just apply Dual Mesh node to have a Voronoi subdivision:

Screenshot_20200503_000638

**Comment by portnov** [comment]
Screenshot_20200504_131747

**Comment by portnov** [comment]
Screenshot_20200504_200952
Screenshot_20200504_201725
Screenshot_20200504_201756
Screenshot_20200504_201858
Screenshot_20200504_202116
Screenshot_20200504_202734
Screenshot_20200504_202840

**Comment by vicdoval** [comment]
Wouldn't you like to add some separators to the menu of the new categories? Would make them easier to read/understand or even a any sub-menu

**Comment by portnov** [comment]
Yeah, probably it's the time.

**Pull request merged**
