### PR TITLE
New Topologic Folder

### PR DESCRIPTION
**Pull request by wassimj**
Topologic for Sverchok/Blender: Tutorial on how to merge two Cells into a CellComplex and to explode the result.

## Addressed problem description
Per your request, I am adding Topologic examples.

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [ ] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [ ] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by nortikin** [comment]
add more examples!
Cool!

**Comment by vicdoval** [comment]
The folder should be in the topologic addon. Tell me when you have it ready a I will tell you how to make it appear in the sverchok examples menu

**Comment by wassimj** [comment]
> The folder should be in the topologic addon. Tell me when you have it ready a I will tell you how to make it appear in the sverchok examples menu

Sure. I added an "examples" folder inside the topologicsverchok.zip file.

**Comment by nortikin** [comment]
> > The folder should be in the topologic addon. Tell me when you have it ready a I will tell you how to make it appear in the sverchok examples menu
> 
> Sure. I added an "examples" folder inside the topologicsverchok.zip file.

https://github.com/wassimj/topologicsverchok/tree/main/examples

**Comment by vicdoval** [comment]
- Add this file https://github.com/vicdoval/sverchok-open3d/blob/master/examples.py to your repo
- Change lines 5 and 19
- In the init file: 
  - Import the file https://github.com/vicdoval/sverchok-open3d/blob/787d27b2051f226f4c1f21654fd84a17b21879bc/__init__.py#L36  
  - Register the file from https://github.com/vicdoval/sverchok-open3d/blob/787d27b2051f226f4c1f21654fd84a17b21879bc/__init__.py#L166

With that it should appear on the sverchok Examples menu

**Pull request closed without merging**
