### PR TITLE
"Fix faces" nodes

### PR DESCRIPTION
**Pull request by portnov**
This introduces two new nodes:

* "Split faces". Split NGon faces into smaller ones. This can split either non-planar faces, or concave faces (NB: this means concave polygons, not that it tries to make mesh convex). This is a wrapper for bmesh.ops.connect_verts_nonplanar and bmesh.ops.connect_verts_concave.
* "Make faces planar". Move vertices to make NGon/Quad faces planar (flat). This is a wrapper for bmesh.ops.planar_faces.

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
Screenshot_20191217_223723
Screenshot_20191217_223941
Screenshot_20191218_001351

**Comment by portnov** [comment]
Screenshot_20191217_234750

Screenshot_20191218_002015

**Comment by Durman** [comment]
Cool nodes.) Split faces looks like does not work with simple polygons:

**Comment by portnov** [comment]
Try to connect Edges input. It may help.

**Comment by Durman** [comment]
I have tried. The same result.

**Comment by portnov** [comment]
Well, then this is just how this bmesh function works, i guess...

**Comment by Durman** [comment]
Probably it is possible to make a test before calling Bmesh operator whether is sense in calling?

**Comment by Durman** [comment]
> Well, then this is just how this bmesh function works, i guess...

The thing is the Bmesh operators was not designed specially for Sverchok. They should be adapted in some way for using. You can have a look at `inset faces` node. It can seems quite tricky in some parts. ^_^

**Comment by portnov** [comment]
Well, that was not bmesh's function problem, it was just result interpretation problem.

**Pull request merged**
