### PR TITLE
"Formula interpolate" node

### PR DESCRIPTION
**Pull request by portnov**
This node is designed to perform interpolation between several control points.

The user defines control points by specifying expressions for X and Y
coordinates. Given these control points, the node will take another value of X
and calculate the corresponding Y by interpolating between the control points.

The node supports linear and cubic interpolation.

This node can be considered as a partial replacement of "Curve Mapper" node. A drawback is that the user can not edit the curve visually, he has to provide numbers or formulas for control points. On the other hand, this node allows one to parametrize the curve by use of custom variables.

Screenshot_20200425_133732
Screenshot_20200425_135424
Screenshot_20200425_140022

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
@zeffii @vicdoval FYI.
Also, maybe someone has a better name for this node? I'd like to emphasize that this is something like "curve mapper", but without visual representation of the curve, but controlling the control points by formulas instead.

**Comment by zeffii** [comment]
then `formula evaluate` ?

**Comment by portnov** [comment]
I prefer "interpolate", because it does interpolation... "evaluate" is what usual "Formula" node does.

**Comment by zeffii** [comment]
it's like a CurveFitter then.

**Comment by vicdoval** [comment]
super cool node, is great that you can parametrize the points. Thanks :) 

maybe in the tooltip could be changed to  `Triggers: Curve Mapper Pro` so it appears in the search menu when you search for `map `and `curve`

**Pull request merged**
