### PR TITLE
Node cats preprocessor

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
@ly29  @nortikin   what do you think?  simplifies the node cat creation i think..

comments could be added as `> this is a comment`

**Comment by ly29** [comment]
It certainly is nicer than having to write the lists etc
I would almost like a completely automatic method using ```.__subclasses__()``` and the module name and perhaps  have beta as tag on the node. But there is also something nice to say for being able to organize the nodes automatically...

**Comment by zeffii** [comment]
you mention exactly what I was thinking... we could add extra `sv_category = "Scene"`  , but I don't see how we could also then force an order in the menu (not without something pretty convoluted).

i'd love to go further and drop the need to use the `,` ,  but then we enter fixed position line

     bl_idname = line[:30].strip()
     item_shortname =line[30: ...]
     ugly....

we can certainly auto populate `/nodes/__init__.py`,  order being irrelevant I think...

**Comment by ly29** [comment]
What I meant to say, the automation isn't worth the trouble. The ```nodes/__init__``` would be nicer to get rid of.

**Comment by zeffii** [comment]
Seen as this isn't accepted yet, i 'll go ahead and drop the `comma` divided but rather use a character positional system. The more I think of this the more relaxing it looks. The commas as the most likely thing to trip us up anyway. We just inforce rules 

  - (no tabs..etc) 
  - indent a node using 4 spaces
  - use an editor with a ruler set to 80 char line width, set the icon rightaligned to the last character
  - follow the existing convention you'll be fine.
  - if you must use comments use `> this is a comment`

**Comment by ly29** [comment]
I like it, getting rid of ```nodes/__init__``` is a separate issue, Some nice comments in a header explaining said rules

**Comment by zeffii** [comment]
do any nodes import from other nodes? the viewers might... ifso then functionality must be pushed to a util/____somename__.py file.

**Comment by zeffii** [comment]
sublime even has a nice package to display markdown neatly, also this looks reasonable

https://github.com/nortikin/sverchok/blob/node_cats_preprocessor/index.md

**Comment by ly29** [comment]
Perhaps use ```.bl_label``` as default and only require ```.bl_idname```

**Comment by zeffii** [comment]
yeah, it does make sense..  i think many bl_labels do not correspond to the shortname, though it would simplify things in some ways.

**Comment by ly29** [comment]
The ```bl_label``` **should** correspond in general I think

**Comment by zeffii** [comment]
it should.. :)  but i'm fairly certain i've never restricted myself to do that..

**Comment by zeffii** [comment]
i mean.. it should.. ideally.  and we can defo go that route.

**Comment by zeffii** [comment]
it simplifies the `index.md` , and icon could then go on `column 35`

**Comment by zeffii** [comment]
i must head out. bbl.

**Comment by ly29** [comment]
It is worth doing a quick survey of ```.bl_label``` and the menu label.

**Comment by zeffii** [comment]
which would be so much easier if the bl_idname and classname where identical for all nodes. which they aren't.

**Comment by ly29** [comment]
You can get the class from bpy.types but yeah also bad form.

**Comment by zeffii** [comment]
I think it's about time we rectify this. but i don't know if changing bl_label of all deviating nodes will be issue free.

going forward it would simplify the whole index/menu setup

**Comment by ly29** [comment]
.bl_label should be fine, .bl_idname is the only magical property.

**Comment by zeffii** [comment]
cool, wasn't positive.

probably won't be today tho..

**Comment by zeffii** [comment]
not as bad as I thought.. but many shortname as very different to the initial bl_label

**Comment by zeffii** [comment]
here the gist https://gist.github.com/zeffii/2eaea534ff714855b683613c286680a4

**Comment by nortikin** [comment]
sorry. today i write docs and move nodes from beta to other menu. Just a moment, please.
I will say when it is ready.

**Comment by zeffii** [comment]
no problems @nortikin

**Comment by zeffii** [comment]
assuming we don' t automate the node_cats generator yet...
```
lines = '''\
    SvBoxRoundedNode              Rounded Box
    HilbertNode                   Hilbert
    Hilbert3dNode                 Hilbert3d
    HilbertImageNode              Hilbert image
    ImageNode                     Image                              FILE_IMAGE
    SvProfileNode                 ProfileParametric
    SvGenerativeArtNode           Generative Art
    SvScriptNode                  Scripted Node                   SCRIPTPLUGINS
    SvScriptNodeMK3               Script 3 Node                   SCRIPTPLUGINS
'''

temp_list = []
for l in lines.split('\n'):
    if not l.strip():
        continue
    
    f = l.strip().split(' ', 1)
    bl_idname = f[0]
    second_part = f[1].strip()
    verbose_mode = (len(second_part) == 45)

    if verbose_mode:
        icon_length = len(second_part[::-1].split(' ')[0])
        shortname = second_part[:-icon_length].strip()
        icon = second_part[-icon_length:]
        print('bl_idname =', bl_idname, ',shortname =', shortname, ',icon =', icon)
    else:
        shortname = second_part
        print('bl_idname =', bl_idname, ',shortname =', shortname)

```

**Comment by nortikin** [comment]
did it!!
Now menu changed

**Comment by zeffii** [comment]
i will resolve conflicts manually @nortikin  keep working away :)

**Comment by nortikin** [comment]
folder reordering for nodes needed. Just to do it. maybe have time tomorrow to reorder. folders as in menu now. + sorting available maybe. But icons??? what to do with icons?

**Comment by zeffii** [comment]
i like icons, and so do other people.  especially beginners.

**Comment by nortikin** [comment]
so... separate icon's list?

**Comment by zeffii** [comment]
it _is_ separate.  icons are optional for scripters to add, and optional to display.  this way I keep it in a simple list inside the index/menu

We have had this discussion before, that's why there's a tickbox in userpreferences _show icons in ctrl+space menu_

**Comment by zeffii** [comment]
I've moved the beta/alpha machines to their new destinations in index.md too

**Comment by zeffii** [comment]
but if we could store the icon information inside the node, i would be amicable to that too. in-fact it would be preferable.

**Comment by zeffii** [comment]
we can totally do this automatically, without adding icons to the index.md / menu.py

```python
>>> sverchok.node_tree.bpy.types.SvLimitedDissolve.bl_icon
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
AttributeError: type object 'SvLimitedDissolve' has no attribute 'bl_icon'

>>> sverchok.node_tree.bpy.types.SvScriptNodeMK3.bl_icon
'OUTLINER_OB_EMPTY'
```
svlimited dissolve doesn't declare an icon, scriptnode3 does.

It's not a lot of work to update those nodes that have a useful icon. then fix space menu do use that..

**Comment by zeffii** [comment]
I would like to merge this first..

**Comment by zeffii** [comment]
or maybe tomorrow i'll edit the nodes bl_icon and merge that instead...  it's late. brain stopped.

**Comment by nortikin** [comment]
why not just make icons for categories? not nodes. so nodes will inherit icons from "parant"... (sadly object-oriented language).

**Comment by zeffii** [comment]
only 30 nodes have an icon in space_bar menu, i'll experiment tomorrow with dropping the icon from index.md and instead adding bl_icon to those nodes and loading them at runtime.

overal it is simpler, letting scripters suggest their preferred node_icon from their node's code is a good feature i think.

**Comment by zeffii** [comment]
> why not just make icons for categories? not nodes. so nodes will inherit icons from "parant 
because then you have 20 nodes with the same icon, then there's no point to adding an individual icon.. defeating the purpose of icons.

**Comment by zeffii** [comment]
note to self:

if bl_icon == 'OUTLINER_OB_EMPTY' , skip

**Comment by zeffii** [comment]
this is superseded by https://github.com/nortikin/sverchok/pull/878

**Pull request closed without merging**
