### PR TITLE
IcoSphere node.

### PR DESCRIPTION
**Pull request by portnov**
I think this node was waited enough :)

Some time ago @zeffii said that it would be better to have one node representing all bmesh primitives. But, for now, Sverchok already have more extensive set of primitives then bmesh does. Only primitives left (implemented in bmesh ,but not in sverchok) are Icosphere and Suzanne.

### CODE REVIEW

**Comment by portnov** [comment]
icosphere

**Comment by zeffii** [comment]
oooooookaay :)   i think though you might want to implement a `limit` not only a soft_limit on the IntProperty for subdiv... but also a "hard limit" property set to a sane 5 by default in `draw_buttons_ext` ,..because 6 or 7 is going to be a very unpleasant experience..especially vectorized.

**Comment by zeffii** [comment]
and the hard limit would also apply to values incoming from sockets..

**Comment by zeffii** [comment]
icosphere can be a prime generator,  seems a lot more useful than having it in `generators extended` .

**Comment by zeffii** [comment]
@portnov   please :)

**Comment by kalwalt** [comment]
This is a generator that i wait a lot, really appreciated that is in the family now.
I agree with you @zeffii , maybe better to limits the num. of subdivisions on the node ( but maybe let this freedom in the properties?)

**Comment by nortikin** [comment]
basic generators also ring planemk2 linemk2

**Comment by enzyme69** [comment]
I imagine: Procedural Suzanne one can tweak the eyes, mouth. Maybe one day...

**Comment by portnov** [comment]
@zeffii 
Is it possible to set hard_max for property programmatically, not in IntProperty() constructor? If so, how? :)

**Comment by portnov** [comment]
@enzyme69 
Blender's Suzanne primitive creation procedure does not have any parameters to tweak at all. But, if you want, you may use "mesh expression" for that. Though writing down required formulas for such a model can get a lot of time...

**Comment by zeffii** [comment]
Check out the new " A.number " node for example on how to use .get .set, unfortunately hard and soft limits can not be overwritten _ get/set is the nearest solution.

**Comment by portnov** [comment]
@zeffii 
See #1489.

@nortikin , @zeffii 
I'd suppose not only move Plane and Line Mk2 to Generators, but also deprecate old Line and Plane and remove them from menu. Why would we need that old nodes, new nodes have more features...

**Comment by nortikin** [comment]
do it, @portnov not even ask.

**Pull request merged**
