### PR TITLE
multiple prop_search fixes

### PR DESCRIPTION
**Pull request by zeffii**
## Addressed problem description

many nodes use `prop_search` layout function, the value that this stores has been changed over time to include a few leading whitespaces. The leading whitespaces are poorly justified **imo**, but a reality we must solve.

here the list of nodes / utils affected https://github.com/nortikin/sverchok/issues/3091

## Solution description

Here i'm cleaning up the nodes as I see fit..

## Preflight checklist

- [ ] Code changes complete.
- [ ] Manual testing done. 
- [ ] Ready for merge.

### CODE REVIEW

**Comment by zeffii** [comment]
in profile_mk3 @portnov  you have the top code, i would like to replace it with the second version. objections?
```python
    def write_values(self, text, values):
        """

        """
        texts = bpy.data.texts.items()
        exists = False
        for t in texts:
            if bpy.data.texts[t[0]].name == text:
                exists = True
                break

        if not exists:
            bpy.data.texts.new(text)
        bpy.data.texts[text].clear()
        bpy.data.texts[text].write(values)


    def write_values(self, text_name, values):
        """
        text = some node name, used as a textname
        values = data to write

        """
        
        exists = False
        for text in bpy.data.texts:
            if text.name == text_name:
                exists = True
                break

        if not exists:
            bpy.data.texts.new(text_name)

        bpy.data.texts[text_name].clear()
        bpy.data.texts[text_name].write(values)
```

**Comment by portnov** [comment]
no objections.

**Comment by zeffii** [comment]
in that case i'll go for the more obvious implementation
```
    def write_values(self, text_name, data):
        """
        text_name :  a string, used to name the bpy.data.texts datablock
        data      :  the string to write to the text datablock
        """
        if not (text_name in bpy.data.texts):
            bpy.data.texts.new(text_name)

        bpy.data.texts[text_name].clear()
        bpy.data.texts[text_name].write(data)
```

**Comment by zeffii** [comment]
i think for bpy.data.texts i may write an interface for sv
```python
def get_text_datablock(text_name, make_new=False):
    if text_name in bpy.data.texts:
        return bpy.data.texts[text_name]
    elif text_name.strip() in bpy.data.texts:
        return bpy.data.texts[text_name.strip()]
    else:
        if make_new:
            bpy.data.texts.new(text_name)
            return bpy.data.texts[text_name]

    return None
```

**Comment by zeffii** [comment]
i already know that I don't want to do the rest of these using `.strip()` for each StringProperty that represents a datablock name..

**Comment by zeffii** [comment]
OK. closing this because this is not the way to solve the issue. See new PR here

**Pull request closed without merging**
