### PR TITLE
Port Formula mk3 to 2.80

### PR DESCRIPTION
**Pull request by portnov**
This ports #2379 to 2.80 branch.

### CODE REVIEW

**Comment by nortikin** [comment]
why formula node not vectorised?
formula

**Comment by nortikin** [comment]
an old formula node was able to calculate tuples/lists and digits also tuples with tuples.
...
I have to admit, i need this old node back

**Comment by Durman** [comment]
I'm also demanding vectorization. =)

**Comment by portnov** [comment]
@Durman 
Is this the expected result?
Screenshot_20200105_202807

**Comment by Durman** [comment]
@portnov  Yes =)

**Comment by portnov** [comment]
@Durman pushed to b28 master, please check.

**Pull request merged**
