### PR TITLE
Random points on mesh

### PR DESCRIPTION
**Pull request by Durman**
## Addressed problem description

#1810

## Preflight checklist

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete.
- [x] Manual testing done. 
- [ ] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
Probably it would be interesting to have input weight of faces for correction of points distribution, but i'm not sure. Probably in next time.

**Comment by Durman** [comment]
Distribution of points on sphere surface according distance to floating point:
random point

**Comment by portnov** [comment]
It would be good to be able to generate some sort of faces between those points (non-degenerated faces, I mean).

**Comment by Durman** [comment]
Do you mean something like remesh node? I don't think that this is simple thing to do. 

By the way I have found new function in geometry module for Blender 2.81 only: [delaunay_2d_cdt](https://docs.blender.org/api/current/mathutils.geometry.html#mathutils.geometry.delaunay_2d_cdt)
It would be interesting to have a node based on this function but I'm afraid that in this case Sverchok will lose compatibility with Blender 2.80.

**Comment by portnov** [comment]
Well, worth exploring anyway!

**Comment by portnov** [comment]
>> Vertex coordinates (2d)

:(

Though, that should be faster that our Python implementation anyway...

**Comment by nortikin** [comment]
> > > Vertex coordinates (2d)
> 
> :(
> 
> Though, that should be faster that our Python implementation anyway...

lets use it!!!

**Comment by Durman** [comment]
Voronoi from unevenly distributed points on faces.

**Pull request merged**
