### PR TITLE
2017 matrix in mk2

### PR DESCRIPTION
**Pull request by nortikin**
why angle still not interactive?
matrixinmk2

### CODE REVIEW

**Comment by zeffii** [comment]
i think all props should use `s.prop_name` there..

**Comment by zeffii** [comment]
not really a big deal... but we use this so infrequently 
```diff
+        s = self.inputs.new('VerticesSocket', "Location")
+        s.use_prop = True
+        s = self.inputs.new('VerticesSocket', "Scale")
+        s.use_prop = True
+        s.prop = (1, 1 , 1)
+        s = self.inputs.new('VerticesSocket', "Rotation")
+        s.use_prop = True
+        s.prop = (0, 0, 1)
```

**Comment by nortikin** [comment]
did

**Comment by nortikin** [comment]
wait

**Pull request merged**
