### PR TITLE
Update jig

### PR DESCRIPTION
**Pull request by zeffii**
this recreates @DolphinDream 's switch input node, from scratch - to better understand the issues in this node.

i try to commit to this when I have time.

### CODE REVIEW

**Comment by zeffii** [comment]
it occurs to me that doing 
```python
socket.hide_safe = some_bool
```
will disconnect such a socket, if the state of the socket is already not-hidden, and the property is being bassed `False`. This should perhaps be a no-op.

I can't quickly think of a reason why setting the hide_safe would disconnect a socket that way.

**Comment by zeffii** [comment]
so currently
```python
    @hide_safe.setter
    def hide_safe(self, value):
        # handles both input and output.
        if self.is_linked:
            for link in self.links:
                self.id_data.links.remove(link)

        self.hide = value
```
would maybe be
```python
    @hide_safe.setter
    def hide_safe(self, value):
        # handles both input and output.
        if self.is_linked:
            for link in self.links:
                self.id_data.links.remove(link)
        if self.hide == value:
            return
        self.hide = value
```

**Comment by zeffii** [comment]
yikes.
image

**Comment by zeffii** [comment]
see https://github.com/nortikin/sverchok/pull/2554

**Comment by DolphinDream** [comment]
Why "yikes" ? This looks cool :)

**Pull request closed without merging**
