### PR TITLE
update to new py API (2.77 and above)

### PR DESCRIPTION
**Pull request by Kosvor2**
Now with old ones intact (for users on 2.76 and below).

### CODE REVIEW

**Comment by Kosvor2** [comment]
Also with 'object' sockets instead of 'data'.

**Comment by nortikin** [comment]
did you put old nodes in folder with old nodes?

**Comment by Kosvor2** [comment]
Done.

**Comment by Kosvor2** [comment]
By the way, i don't have write access on this new account so don't wait for me here.

**Comment by nortikin** [comment]
oups
object reycast line 69 bool is not subscribable

**Comment by nortikin** [comment]
the problem in object get id

**Comment by nortikin** [comment]
please, use socket SvObjectSocket
@Kosvor2

**Comment by nortikin** [comment]
will upload object socket soon in text vewer

**Comment by nortikin** [comment]
also only out mod working, also you forgot convert vectors4 to (x,y,z)

**Comment by nortikin** [comment]
polygon's indexes are broken also. try to fix asap

**Comment by nortikin** [comment]
will you fix in your fork?

**Comment by nortikin** [comment]
or me?

**Comment by nortikin** [comment]
there are too many bugs easier to write from scratch

**Comment by Kosvor2** [comment]
You mean old raycast? i haven't changed it. Must work for old blender versions.

**Comment by nortikin** [comment]
no, new one

**Comment by nortikin** [comment]
output <Vector(x,y,z,w)> or even no output

**Comment by nortikin** [comment]
i ll try download again

**Comment by nortikin** [comment]
ok, it works
sorry
maybe you not added to main menu correctly, i have not in menu

**Comment by Kosvor2** [comment]
they are in beta list, but you can send them back where there were old versions.

**Comment by nortikin** [comment]
thanks

**Pull request merged**
