### PR TITLE
B28 nodes fix

### PR DESCRIPTION
**Pull request by nantille**
## Nodes fix

Fix 1, Scale mk2: fixed operation on vectors, my shortest commit. :)

Fix 2, Objects in mk3: fixed 'Get selected' button for a nasty case. When you've got an object in the viewport and delete it, it stays in bpy.data.objects and its attribute select_get() is still set to True and so when you select another object in the viewport and hit 'Get selected', this function sometimes gets a previously deleted object that we can't access in the UI anymore. I added a check on users_scene and the new users_collection.

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by zeffii** [comment]
you might be right about the edits in move_mk2 and scale_mk2 , but i'm not sure. 

`@` is now used most `M x V` calculations:   see https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API

**Comment by zeffii** [comment]
cool. accepting.  ` m` is a variable name we should be reserving for matrices only. :) thanks for the PR.

**Comment by nantille** [comment]
Yeah the variable was already named like that and that's why I initially thought a matrix was passed but it's just a scalar, this should be renamed. You're welcome!

**Comment by zeffii** [comment]
done and pushed. Thanks!

**Comment by zeffii** [comment]
try to stick to one topic per issue

**Pull request merged**
