### PR TITLE
Update string_tools.py

### PR DESCRIPTION
**Pull request by KoreTeknology**
orthographic correction "brakes" > "breaks" in string_tools.py

### CODE REVIEW

**Comment by portnov** [comment]
As far as I understand, this will break existing layouts :/

**Comment by KoreTeknology** [comment]
> As far as I understand, this will break existing layouts :/

? but keep_breaks  is a unique identifier, right?
how this can breaks the layout ? i am curious here, is there any other use of this identifier in the addon ?

**Comment by portnov** [comment]
You can conduct an experiment:
* Roll back to sverchok master
* create some layout using "string tools" node, and, for example, check that "keep_brakes" flag. Save the blend file.
* Switch back to your version of code
* Load saved blend file again. You will see that "keep_breaks" flag is not checked. That is because in blend file the flag was saved under it's old name, and Blender does not have idea that newly created flag should inherit the value of old property. Accordingly, the node works differently. Consider the level of confusions of users, whose layouts suddenly start to work differently :)

To avoid such sudden changes, we have mechanism of "old nodes" and new versions of nodes, see http://nortikin.github.io/sverchok/docs/contributing/node_api.html#upgrade-node
I'm just not sure if it worth to create a new version of node for such a small change.

**Comment by KoreTeknology** [comment]
i see... understood now... yes, may it not worth the change right now, until a major update of the addon, thnks for your explaination... i am working on extending the text nodes category. 
by the way, is ther any dev plateform other than on github where you are discussing changes and updates ? i would like to be in touch with the core team. thx

**Comment by portnov** [comment]
Apart of github issues and github discussions, we use discord https://discord.gg/pjHHhjJz8Z .

**Comment by Durman** [comment]
I will close it since it seems there is no easy way to fix this.

**Pull request closed without merging**
