### PR TITLE
Update contributing.rst; add testing.rst.

### PR DESCRIPTION
**Pull request by portnov**
This adds some information of how we do testing.

### CODE REVIEW

**Comment by portnov** [comment]
@zeffii @nortikin @Kosvor2 @DolphinDream @vicdoval Please review.

**Comment by zeffii** [comment]
@portnov  i will have a look at writing a cmd windows test script so it's not just .sh users

**Comment by zeffii** [comment]
note to self: the .sh is  / currently

https://github.com/nortikin/sverchok/blob/9143bacb4767e1e9a27e5b8cceb32d3928972a1a/run_tests.sh#L1-L13

**Comment by zeffii** [comment]
output.. i'm not worried that this fails a few tests..
https://gist.github.com/zeffii/39ab93c411296e5f732168fbd3fd3b7e

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2079

**Pull request merged**
