### PR TITLE
Do not update whole tree upon `show` attribute switching of a node tree

### PR DESCRIPTION
**Pull request by Durman**
## Addressed problem description

fix show tree

- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
Btw, there is Screen.is_scrubbing property (https://docs.blender.org/api/current/bpy.types.Screen.html). As far as I understand, it was introduced in 2.90 (https://wiki.blender.org/wiki/Reference/Release_Notes/2.90/Python_API). It would be good to not recalculate the tree during such "scrubbing".

**Comment by Durman** [comment]
I did not catch about which scrubbings? We does not use sliders for known reasons.

**Comment by portnov** [comment]
I'm talking about when you're take some parameter in the node and drag it with the mouse to change the value. Currently we update the tree on each small change of the parameter during such drag; if the tree is slow, this looks terrible. It would be ideal to do not try to recalculate on each small change during drag, only not more often than 0.5-1second (should relate to tree recalculation time).

**Comment by Durman** [comment]
I'm not sure that this will hit desirable effect. I guess it will look like it is always lagging.

**Comment by portnov** [comment]
Well, in systems that support asynchronous work, this works as follows:
* on any small change, UI is checking if previous recalculation is currently in progress
* if it is, then interrupt it and post a new recalculation job, and accept next actions from the user (so that UI does not freeze)

As far as I understand, we have no such luxury as possibility to implement asynchronous processing (but maybe we have? may be worth investigation). But maybe we can imitate similar behaviour with some kind of timeouts tricks.

**Comment by Durman** [comment]
Have a look at this, probably you can learn something. I did not experiment with that module.
https://docs.blender.org/api/current/bpy.app.timers.html#use-a-timer-to-react-to-events-in-another-thread

**Comment by rendetto** [comment]
May I suggest if we do:

> ...imitate similar behavior with some kind of timeouts tricks

to have it as an option of switch it on or off, or have a controllable parameter which sets the amount of those timeouts. 
I heavily rely on the "almost realtime" calculated node trees for some of my setups and any forced timeouts will ruin the process.

Thanks

**Pull request merged**
