### PR TITLE
Text viewer

### PR DESCRIPTION
**Pull request by nortikin**

### CODE REVIEW

**Comment by nortikin** [comment]
not all have been done and not sure this is right time.

**Comment by zeffii** [comment]
@nortikin you still have an underscore in the classname + bl_idname of `ViewerNode_text`  please remove it for consistency with the rest of all the other nodes.

**Comment by nortikin** [comment]
now will do

**Comment by nortikin** [comment]
made additional job. i think it can be merged. will merge now

**Pull request merged**
