### PR TITLE
Implement NGon node.

### PR DESCRIPTION
**Pull request by portnov**
refs #517.
Please review :)

### CODE REVIEW

**Comment by zeffii** [comment]
As pull requests we've decided to allow new nodes into the beta menu first, or alpha if you want. But to leave beta we ask that you supply documentation.

**Comment by portnov** [comment]
Seems all fixed.

**Comment by zeffii** [comment]
ok looks good, btw  image syntax for rst is 
```
.. image:: images/ball1.gif
```

**Comment by zeffii** [comment]
I propose to have seed as an integer instead, similar to Random Vector.  Strictly speaking it doesn't matter, but I don't see seed as a float almost anywhere, (except Random number in sverchok..but it's too late to change that without replacing the node)

**Comment by portnov** [comment]
ok, will do.

**Comment by portnov** [comment]
See last commit.

**Pull request merged**
