### PR TITLE
Add eval node as a beta node

### PR DESCRIPTION
**Pull request by taxpon**
# Eval Node
## Appearance
image

## Function
This node enable users to user 'eval' function in python. This node is so powerful when you handle data structure :)

### CODE REVIEW

**Comment by enzyme69** [comment]
Is this similar to Dealga node ... a while back ago?

On Sunday, 6 September 2015, Takuro Wada <notifications@github.com> wrote:

> Eval Node Appearance
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1885971/9702349/b95e12f2-5493-11e5-977d-6ee68eccfdfd.png>
> Function
>
> This node enable users to user 'eval' function in python. This node is so
> powerful when you handle data structure :)
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/nortikin/sverchok/pull/705
> Commit Summary
>
>    - Add eval node as a beta node
>
> File Changes
>
>    - *M* .gitignore
>    <https://github.com/nortikin/sverchok/pull/705/files#diff-0> (3)
>    - *M* menu.py
>    <https://github.com/nortikin/sverchok/pull/705/files#diff-1> (3)
>    - *M* nodes/__init__.py
>    <https://github.com/nortikin/sverchok/pull/705/files#diff-2> (3)
>    - *A* nodes/basic_data/eval.py
>    <https://github.com/nortikin/sverchok/pull/705/files#diff-3> (46)
>
> Patch Links:
>
>    - https://github.com/nortikin/sverchok/pull/705.patch
>    - https://github.com/nortikin/sverchok/pull/705.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nortikin/sverchok/pull/705>.
>


-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by ly29** [comment]
Please provide an example of how you would use this.

**Comment by taxpon** [comment]
@ly29 
Thanks for quick response.

I am currently making network client node to communicate with other programs and I am using this eval node to parse messages from another program as follows.

image

**Comment by ly29** [comment]
Wow. Just wow.
Also @zeffii

**Comment by zeffii** [comment]
i'm OK with that being added.. we had something similar a while back called [' EvalKnieval '(https://github.com/nortikin/sverchok/issues/257)
 but realize you can do this with the scripted nodes already -- I think they are a little more convenient to be very honest.

**Comment by zeffii** [comment]
i'm not positive that we have solved the issue of preventing execution of unscreened eval/exec upon loading blends from other people. Obviously, when we are the ones writing the code and setting up our node networks, this is no issue at all. --- but the use of such a node without restrictions is a a definite point of concern.

**Comment by ly29** [comment]
I would have the text processing in the network node, I guess, but for testing purposes it kind of makes sense.

**Comment by ly29** [comment]
@zeffii 
We solved finding them and stopping something them from executing, then we never really did anything with it.

**Comment by taxpon** [comment]
OK I see. In fact, I did not know that you've already discussed this 'eval' issue. I am sorry for taking up your time. I'll use Scripted Node. Thanks.

**Comment by zeffii** [comment]
@taxpon we welcome new ideas  /  approaches. no need to be sorry here. I just imagine that you might find the scripted node sufficient for most of this. I might be wrong...

**Comment by taxpon** [comment]
:+1:

**Comment by nortikin** [comment]
:smiley_cat:

**Comment by taxpon** [comment]
Finally, I used scripted node and it works well! Thanks :)
image

**Comment by nortikin** [comment]
what do you parsing?

**Comment by taxpon** [comment]
In this node, I am parsing simple CSV string data sent form another program and convert it to list of number.

**Comment by enzyme69** [comment]
Which another program? Maya or Houdini, maybe? Do you blog it? Just curious
:]



------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by taxpon** [comment]
I am currently using [MaxMSP](https://cycling74.com/products/max/) to analyze sound data played in iTunes. I have not write article yet, but my presentation document is on Speaker Deck [Here](https://speakerdeck.com/taxpon/blender-x-pythondemoderingu-and-3dpurinto-3) (Sorry for only Japanese).

**Comment by nortikin** [comment]
Cool, my freand is fan of such a things, but not programmer. JHe wants to create architecture from music, but not axactly know how

**Comment by taxpon** [comment]
OK. I will write blog post soon. By the way, I will attend Blender Conference 2015 and have my presentation including these things. If you guys come there, let's talk :)

**Comment by nortikin** [comment]
sadly i will not go. maybe others...

**Pull request closed without merging**
