### PR TITLE
3dview center align tool

### PR DESCRIPTION
**Pull request by zeffii**
this is both 
- a nodeview operator, that works on an active node.. 
- a node operator that is added directly to the viewer interface (where it makes sense )

image

### CODE REVIEW

**Comment by enzyme69** [comment]
So this thing will exist as a button click under Viewer draw? Or more like Macro as well?

**Comment by zeffii** [comment]
re-read the first post on the top.

**Comment by zeffii** [comment]
it's not currently a default macro but i might make it one...  i was thinking of `kw: zm` if I do.  but a button on the Viewer UI seems like the most convenient.

**Comment by zeffii** [comment]
current implementation only jumps to first item in matrices, or vectors*matrices

**Pull request merged**
