### PR TITLE
Wider FreeCAD support - NURBS Solids

### PR DESCRIPTION
**Pull request by portnov**
The plan is to add:

* [x] Support of FreeCAD's implementation of Nurbs curves and surfaces
* Update existing nodes:
  * [x] "Solid Edges" and "Solid Faces" output NURBS curves / surfaces
  * [x] "Solid Faces" node has additional "TrimCurves" output - outer edges of each face in U/V coordinate space of that surface, for use as trimming curve
* Face creation nodes:
  * [x] "Polygon Face" - make a Face from a polygon defined by usual Sverchok's Vertices and Faces; the polygon must be flat.
  * [x] "Face from Curves" : build a flat face with curvy edges, by making a face from one or several Curves, representing face's outer edges;
  * [x] "Cut Surface to make a Face":  build a curve face from a trimmed Surface; the only way I know to trim a Surface in FreeCAD API is to take a Curve somewhere in 3D space, and then project it onto surface (two methods of projection are available: parallel - along a vector, and perspective - from a point). **Better name for this node is welcome**.
* Solid creation nodes:
  * [x] "Extrude Face (Solid)" node (extrude face along vector, UI for `face.extrude` method)
  * [x] "Solidify Face (Solid)" node (make a solid by offsetting the face, UI for `face.makeOffsetShape` method) - **feel free to offer a better name**
  * [x] "Revolve Face (Solid)" node (make a solid of revolution from a face, UI for `face.revolve` method)
  * [x] "Sweep Face (Solid)" node (sweep a face along a curve, UI for `Part.BRepOffsetAPI.MakePipeShell`)
  * [x] "Solid from two Faces" node: given two Faces ("floor" and "ceil"), make a Solid by connecting edges of these faces by ruled surfaces ("walls"). This works only when two faces have exactly the same number of edges. Moved to Alpha nodes, because gives weird results too frequently, and in company with Booleans causes crashes :/
* [x] "Split Solid by Face" node: take a Solid and cut it into two (or more) parts with a Face.
* [x] "Project Curve on Surface (NURBS)" node.
* [x] "Helix" node

Only NURBS and NURBS-like curves and surfaces are supported (at least for now).

I had the following  options:

a) for all three solid-making nodes, support a switch which would allow different modes of how to provide a Face;
b) add a new socket class for Solid Face, and three additional nodes to make Faces.
c) add additional nodes to make Faces; use SvSurfaceSocket for faces, with SvSolidFaceSurface class

At the moment I like c) the most.

@vicdoval @zeffii  your opinion?

Screenshot_20200831_215050
Screenshot_20200831_215213

NURBS interpolation + Coons Surface + Extrude Face + Solid Boolean:
Screenshot_20200831_221918

Make a Ruled Surface from two interpolated curves, cut a Face from it by perspective projection of some Circle, then solidify this face, then cut holes with boolean:
Screenshot_20200902_004509

Cut a Cone by some surface ("split solid by face"), take a central part and make a hole in it with Boolean:
Screenshot_20200903_203804

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by vicdoval** [comment]
My opinion is that this is super cool, 🥳 
I think by the moment the best option is to stick to the SvSolidFaceSurface class, maybe if one day FreeCAD and Blender use the same python version we could tart thinking about implementing new sockets (Wire, Face, Shell..)

Maybe "Solid from Surface" would be a good name for "Cut Surface to make a Face" using the full surface if no curve is supplied and a trimmed version otherwise.

**Comment by portnov** [comment]
In FreeCAD's API terms I believe that's `Part.makeShell` + `Part.makeSolid`. That's what "Solid from two Faces" is using. I experienced several crashes when tried to combine it with Boolean, so.. idk.
To prepare a list of surfaces which form exactly a solid form (i.e. edges should precisely coincide everywhere) in Sverchok IMHO is too complex in most non-trivial cases...

**Comment by portnov** [comment]
Screenshot_20200903_220222

**Comment by portnov** [comment]
Screenshot_20200905_122510

**Comment by zeffii** [comment]
these are brilliant! any user who hardcore wants/needs these things will figure out how to install the dependencies.

my mother is in hospital again, it's difficult to concentrate on these^ things atm.

**Comment by nortikin** [comment]
> these are brilliant! any user who hardcore wants/needs these things will figure out how to install the dependencies.
> 
> my mother is in hospital again, it's difficult to concentrate on these^ things atm.

Pity.
Hope she will be ok. Send her to be healthy.

**Comment by portnov** [comment]
Screenshot_20200905_174733
Screenshot_20200905_175850

**Comment by portnov** [comment]
Screenshot_20200905_181925

**Comment by portnov** [comment]
Screenshot_20200905_203707

**Comment by fewerjunk** [comment]
I've tried on Mac and on Linux to install the dependencies and establish a path for FreeCAD to work.  Followed the recommended conda configuration for MAC and the Linux install for Ubuntu.  Everything seemed to be successful with the exception that, not only could I not pull up any of the nodes, but, the install broke sverchok.  Before I was getting the tabs, including "Extra Nodes" by which the success of not only the configuration of FreeCAD nodes, but also the other dependencies can be monitored / upgraded.

As I speak, I'm running 2.83.x, 2.90.1, even 2.79.  It's running currently, properly on 2.90.1 and 2.79, but 2.83.x is broken.

An older file with sverchok nodes no longer loads them on the broken blender.

Trying to add FreeCAD broke sverchok.

sverchok_broke_JPG

**Comment by portnov** [comment]
._.
To "fix" sverchok, you'll have to remove file `.../Blender/2.83/python/lib/python3.7/site-packages/freecad_path.pth`.
About how to enable FreeCAD on OSX, you'll have to ask other OSX users... see https://github.com/nortikin/sverchok/issues?q=is%3Aopen+is%3Aissue+label%3AOSX

**Comment by fewerjunk** [comment]
I downloaded the latest 2.83.x version (7).  Backed up the old version.  Started the new version to the default settings.
reinstalled Sverchok, and the Extra Nodes via the tab.  For extra measure I tried reinstalling / upgrading the programs via Terminal:

python -m pip install --upgrade scipy
python -m pip install --upgrade scikit-image
python -m pip install --upgrade geomdl
python -m pip install --upgrade numpy
python -m pip install --upgrade circlify
python -m pip install --upgrade ladybug
python -m pip install --upgrade PyMCubes

Once all that was done I installed sverchok-extra

I then restored all my addons (except sverchok and sverchok-extra) from backup as well as presets, datafiles and config.

Essential for also restoring "Quick Favorites".

**Pull request merged**
