### PR TITLE
Add new SuperEllipsoid generator node (WIP)

### PR DESCRIPTION
**Pull request by DolphinDream**
SuperEllipsoid node generates various 3D shapes (among which sphere, cylinder, cube, octahedron are special cases). Some other notable shapes are a rounded cube and rounded cylinder.

Based on super-ellipsoid formula: https://en.wikipedia.org/wiki/Superellipsoid

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

sv-superellipsoid-ui1

A sample chart with the parallel & meridian exponents varied from 0 to 4.

sv-superellipsoid-gallery1

### CODE REVIEW

**Comment by DolphinDream** [comment]
And a prettier gallery example:

sv-superellipsoid-gallery2

**Comment by DolphinDream** [comment]
And a few animated demos:

[](http://www.youtube.com/watch?v=zHINGFUEc6Y "SV SuperEllipsoid Node - Demo1")

[](http://www.youtube.com/watch?v=8B45WLid2ng "SV SuperEllipsoid Node - Demo2")

**Comment by DolphinDream** [comment]
> Huh. Next are the following by wikipedia links? :)

what do you mean, @portnov ?

**Comment by portnov** [comment]
@DolphinDream 
https://en.wikipedia.org/wiki/Superellipse
https://en.wikipedia.org/wiki/Superquadrics
https://en.wikipedia.org/wiki/Supertoroid
:)

**Comment by DolphinDream** [comment]
@portnov Ah :) I wasn't planning for it... but if there is interest in these shapes as well I guess it would be straight forward to add new formulas.

**Comment by portnov** [comment]
https://en.wikipedia.org/wiki/Superformula

**Comment by DolphinDream** [comment]
@portnov You mean this **SuperToroid**? :) (easy extension to the torus node, btw)

sv-torusmk2-exampl1

**Pull request merged**
