### PR TITLE
Bevel only edges

### PR DESCRIPTION
**Pull request by vicdoval**
## Addressed problem description

Bevel node does not work just with edges. The node does not update if there are no input polygons linked

I added (open) this feature.

This opens nice posibilities
beveledges

## Solution description

 When edges are inputed but not edges the propriety "Vertex only" is overwritten to True in order to work .

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x ] Code changes complete.
- [x ] Code documentation complete.
- [ x] Documentation for users complete (or not required, if user never sees these changes).
- [x ] Manual testing done. 
- [x ] Unit-tests implemented. Can you point me where to learn about this topic?
- [ ] Ready for merge.

### CODE REVIEW

**Comment by zeffii** [comment]
ideally it would have a mode that took:
 
- verts+edges+vertmask+constant_radius
- verts+edges+vertmask+variable_radii

**Comment by vicdoval** [comment]
I agree with you, 
For me it could be approachable to make the first option ( verts+edges+vertmask+constant_radius).
Right now if you input multiple radius you get multiple geometries
The implementation of variable radius in one mesh seems more complex with the actual bmesh.ops.bevel.  but i would be open to suggestions :)

**Comment by zeffii** [comment]
yeah the variable radius would probably require rolling our own algorithm.. there's a few older script node examples where we use zmj1000's (or whatever his nickname was) algorithm to fillet corners.

vertmask+constant_radius would already allow a lot of cool stuff.

**Comment by vicdoval** [comment]
screen
1- I've created the node, so the old "vertexOnly" propriety  (boolean) changes by and "mode" (enumpropiety), this may break old setups based on this node... 
    should i try to keep it somehow ?
    or should i create and mk2 ?
    or should i ignore this ?(the user may just have to change one button to make it work again)

2- Another question is that now I have BevelEdges and VerticesMask.
I think it would be more coherent to have EdgesMask and VerticesMask but this would make a bigger difference with the actual node (pushing more to the mk2..)
Any ideas on this?

**Comment by vicdoval** [comment]
I twist it  again ... I will create a new clean pull request.
Thanks!
beveledges1

**Comment by nortikin** [comment]
hilbert-bevel

**Pull request closed without merging**
