### PR TITLE
Menu restructuration change-make-sanitize

### PR DESCRIPTION
**Pull request by vicdoval**
Restructuring Add Menu based in #2523 and thoughts in #2522
Avoiding double-depth menus
Three categories:
Change: modifies current geometry
change
Make: creates new geometry from existing one
make
Sanitate: Reduces  or simplifies existing geometry
sanitate

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by vicdoval** [comment]
sanitize

**Comment by portnov** [comment]
I have yet another suggestion: to use YAML file instead of custom-parsed MD. For example,

`menu.yaml`:

```
- category: Generator
  description: Mesh generation nodes
  icon: OBJECT_DATAMODE
  nodes:
    - SvLineNodeMK3
    - SvPlaneNodeMK2
    - SvNGonNode
    - SvBoxNode
    - SvCircleNode
    - CylinderNode
    - SvCylinderNodeMK2
    - SphereNode
    - SvIcosphereNode
    - SvTorusNode
    - SvSuzanneNode
    - ---
    - BasicSplineNode
    - svBasicArcNode
    - RandomVectorNodeMK2
    - SvScriptNodeLite
    - SvSNFunctor
    - SvSNFunctorB
    - ImageNode
  children:
    - category: Extended
      description: More complex mesh generation nodes
      icon: PLUGIN
      nodes:
        - SvBoxRoundedNode
        - SvBricksNode
        - SvPolygonGridNode
        - HilbertNode
        - Hilbert3dNode
        - HilbertImageNode
        - SvProfileNodeMK2
        - SvProfileNodeMK3
        - SvMeshEvalNode
        - SvGenerativeArtNode
        - SvImageComponentsNode
        - SvTorusKnotNode
        - SvRingNode
        - SvEllipseNode
        - SvSuperEllipsoidNode
        - SvRegularSolid
- category: Analyzers
  description: Mesh analysis nodes
  icon: VIEWZOOM
  nodes:
    - SvBBoxNode
    - SvDiameterNode
    - SvVolumeNode
    - SvAreaNode
    - DistancePPNode
    - SvDistancePointLineNode
    - SvDistancePointPlaneNode
...
```

This would allow us:
* get rid of custom MD file parser
* Incorporate category names, icons, description in one file
* Declare the structure of menu decoratively.

I'd suggest to have a convention that in panels we would show top-level menus only (merging all sub-categories into their parent categories), but in menus show sub-categories as sub-menus. 
Another possible convention is to get rid of sub-categories at all, and thus get rid of sub-sub-menus. But in such a case it may appear that we have too many categories and too long menu.

@zeffii  @vicdoval  your thoughts on this?

**Comment by zeffii** [comment]
i'm not ready for that :) -- I'm first leaning towards making all node directories correspond `1-1` with the menus.

i don't know yet how i feel about relying on yaml.  but i'm not against it.

**Comment by vicdoval** [comment]
I started this PR thinking more in the "What" more that the "How" but i didn't find a clear path of acceptation for such a big change.
I could keep on trying to organise the menu to avoid double-depth menus for after pairing the menu with the folder structure but i'm not sure if that is everyone's desire

**Comment by zeffii** [comment]
I think we all agree that the menus/categories are a mess, but we're finding it difficult to state exactly what is wrong with them, and even more murky about what would be better.

this is a classic problem with Nodesystems that have many Nodes. In Jeskola Buzz ( a modulR tracker software for music ) people can script their own "index". This means that people could drop a tonne of nodes they don't like from their menu experience, and even rename the menu labels.

it's why i started LiteMenu, but haven't managed to get around to finishing it. I think it will make sense once you use it.

**Comment by portnov** [comment]
In Blender 2.8, there is a "quick menu". You can add a node to the menu by right-clicking on it's icon or item in the menu and selecting "add to quick favorites". The menu is assigned to the Q key by default.

**Comment by vicdoval** [comment]
I like the idea of the custom menu but anyway we have to supply a basic menu even if it is not the perfect one

**Comment by zeffii** [comment]
in jeskola buzz, the community (thousands of users) eventually converged on the custom menu of a small set of users, and they would supplement/prune the custom menu to fit their exact need. 

once i've added dashed lines to vd experimental, i'll focus on the `menu / directory structure`.

**Comment by Durman** [comment]
The `merge mesh 2d` node should be in `CAD` menu or `modifiers`?

**Comment by zeffii** [comment]
i think CAD

**Comment by Durman** [comment]
Actually I don't understand how describe the CAD category and which functions can be categorized to this category. 😕

**Comment by Durman** [comment]
And should be new folder with name `CAD` be created in nodes folder?

**Comment by zeffii** [comment]
i find the "modifier" category also unsatisfactory, it's too vague.  So is CAD.

**Comment by zeffii** [comment]
@Durman  for the time being place the node in the category that seems most appropriate to you .

**Comment by zeffii** [comment]
can we close this, sverchok has drifted a lot since the PR was made.   it's not a solved problem yet though :)

**Comment by zeffii** [comment]
although short menus using 1..5 hotkey does solve the problem of ever increasing "big menu" size - big menu is an artifact, not a solution. The more we can convince people to use extrasearch and short menus the better their experience will be.

**Pull request closed without merging**
