### PR TITLE
console node

### PR DESCRIPTION
**Pull request by zeffii**
super secret project, with several use cases.
- [x] prepare bitmap
- [x] prepare tri-grid
- [x] prepare `render_text()`
- [ ] prepare glyph color multiply for theme

image

### CODE REVIEW

**Comment by zeffii** [comment]
once this works i'll write a dedicated `tri_grid` generator to simplify the node

**Comment by zeffii** [comment]
hmmm
https://www.opengl-tutorial.org/beginners-tutorials/tutorial-5-a-textured-cube/

**Comment by zeffii** [comment]
what a surprise..
```python
shader = gpu.shader.from_builtin('2D_IMAGE')
batch = batch_for_shader(
    shader, 'TRIS',
    {
        "pos": (
            (100, 100), (200, 100), (200, 200), 
            (100, 100), (200, 200), (100, 200)
        ),
        "texCoord": (
            (0, 0), (1, 0), (1, 1),
            (0, 0), (1, 1), (0, 1))
    }
)
```

**Comment by zeffii** [comment]
i've not been this happy to see a bug, for a long time.. : ) 
image

**Comment by zeffii** [comment]
rawrr!  
image

i think this could be used for annotations as well as displaying code in-situ

**Comment by zeffii** [comment]
The current implementation uses the Blender supplied `2D_IMAGE` shader/batch, which is useful for testing the "pipeline" of getting from a multi-line string of text to a 2d list of vertices and uv_indices.
But the interesting thing for me is to allow per character color multiplication, this would allow
    - basic syntax highlighting (it's not a code editor... basic differentiation of characters and punctuation/syntax would be cool already.)
A hand coded fragmentshader would allow for this..by passing an index along with each uv, the fragment shader would perfom a lookup and multiply with colour assign to the index.

i'm not sure how to do this yet ;)

**Comment by Durman** [comment]
I think annotations are quite important. I write errors into console about what is wrong with input data or whatever but I think few users new about console and error messages there.

**Comment by zeffii** [comment]
i better continue this before i forget stuff

**Comment by zeffii** [comment]
image

OK :) now we're talking

**Comment by zeffii** [comment]
this tokenizes the current file..
```python
def syntax_highlight_basic(text):
    """
    example comment
    """
    import tokenize
    import io
    # buffer = io.StringIO()
    # buffer.write(text)

    try:
        tokens = tokenize.generate_tokens(text.readline)
        for token in tokens:
            print(token)
    except Exception as err:
        print(err)
        
    

file_path = __file__
with open(file_path) as f:
    syntax_highlight_basic(f)

```
resulting in
<details>
```
TokenInfo(type=1 (NAME), string='def', start=(1, 0), end=(1, 3), line='def syntax_highlight_basic(text):\n')
TokenInfo(type=1 (NAME), string='syntax_highlight_basic', start=(1, 4), end=(1, 26), line='def syntax_highlight_basic(text):\n')
TokenInfo(type=53 (OP), string='(', start=(1, 26), end=(1, 27), line='def syntax_highlight_basic(text):\n')
TokenInfo(type=1 (NAME), string='text', start=(1, 27), end=(1, 31), line='def syntax_highlight_basic(text):\n')
TokenInfo(type=53 (OP), string=')', start=(1, 31), end=(1, 32), line='def syntax_highlight_basic(text):\n')
TokenInfo(type=53 (OP), string=':', start=(1, 32), end=(1, 33), line='def syntax_highlight_basic(text):\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(1, 33), end=(1, 34), line='def syntax_highlight_basic(text):\n')
TokenInfo(type=5 (INDENT), string='    ', start=(2, 0), end=(2, 4), line='    """\n')
TokenInfo(type=3 (STRING), string='"""\n    example comment\n    """', start=(2, 4), end=(4, 7), line='    """\n    example comment\n    """\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(4, 7), end=(4, 8), line='    """\n')
TokenInfo(type=1 (NAME), string='import', start=(5, 4), end=(5, 10), line='    import tokenize\n')
TokenInfo(type=1 (NAME), string='tokenize', start=(5, 11), end=(5, 19), line='    import tokenize\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(5, 19), end=(5, 20), line='    import tokenize\n')
TokenInfo(type=1 (NAME), string='import', start=(6, 4), end=(6, 10), line='    import io\n')
TokenInfo(type=1 (NAME), string='io', start=(6, 11), end=(6, 13), line='    import io\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(6, 13), end=(6, 14), line='    import io\n')
TokenInfo(type=55 (COMMENT), string='# buffer = io.StringIO()', start=(7, 4), end=(7, 28), line='    # buffer = io.StringIO()\n')
TokenInfo(type=56 (NL), string='\n', start=(7, 28), end=(7, 29), line='    # buffer = io.StringIO()\n')
TokenInfo(type=55 (COMMENT), string='# buffer.write(text)', start=(8, 4), end=(8, 24), line='    # buffer.write(text)\n')
TokenInfo(type=56 (NL), string='\n', start=(8, 24), end=(8, 25), line='    # buffer.write(text)\n')
TokenInfo(type=56 (NL), string='\n', start=(9, 0), end=(9, 1), line='\n')
TokenInfo(type=1 (NAME), string='try', start=(10, 4), end=(10, 7), line='    try:\n')
TokenInfo(type=53 (OP), string=':', start=(10, 7), end=(10, 8), line='    try:\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(10, 8), end=(10, 9), line='    try:\n')
TokenInfo(type=5 (INDENT), string='        ', start=(11, 0), end=(11, 8), line='        tokens = tokenize.generate_tokens(text.readline)\n')
TokenInfo(type=1 (NAME), string='tokens', start=(11, 8), end=(11, 14), line='        tokens = tokenize.generate_tokens(text.readline)\n')
TokenInfo(type=53 (OP), string='=', start=(11, 15), end=(11, 16), line='        tokens = tokenize.generate_tokens(text.readline)\n')
TokenInfo(type=1 (NAME), string='tokenize', start=(11, 17), end=(11, 25), line='        tokens = tokenize.generate_tokens(text.readline)\n')
TokenInfo(type=53 (OP), string='.', start=(11, 25), end=(11, 26), line='        tokens = tokenize.generate_tokens(text.readline)\n')
TokenInfo(type=1 (NAME), string='generate_tokens', start=(11, 26), end=(11, 41), line='        tokens = tokenize.generate_tokens(text.readline)\n')
TokenInfo(type=53 (OP), string='(', start=(11, 41), end=(11, 42), line='        tokens = tokenize.generate_tokens(text.readline)\n')
TokenInfo(type=1 (NAME), string='text', start=(11, 42), end=(11, 46), line='        tokens = tokenize.generate_tokens(text.readline)\n')
TokenInfo(type=53 (OP), string='.', start=(11, 46), end=(11, 47), line='        tokens = tokenize.generate_tokens(text.readline)\n')
TokenInfo(type=1 (NAME), string='readline', start=(11, 47), end=(11, 55), line='        tokens = tokenize.generate_tokens(text.readline)\n')
TokenInfo(type=53 (OP), string=')', start=(11, 55), end=(11, 56), line='        tokens = tokenize.generate_tokens(text.readline)\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(11, 56), end=(11, 57), line='        tokens = tokenize.generate_tokens(text.readline)\n')
TokenInfo(type=1 (NAME), string='for', start=(12, 8), end=(12, 11), line='        for token in tokens:\n')
TokenInfo(type=1 (NAME), string='token', start=(12, 12), end=(12, 17), line='        for token in tokens:\n')
TokenInfo(type=1 (NAME), string='in', start=(12, 18), end=(12, 20), line='        for token in tokens:\n')
TokenInfo(type=1 (NAME), string='tokens', start=(12, 21), end=(12, 27), line='        for token in tokens:\n')
TokenInfo(type=53 (OP), string=':', start=(12, 27), end=(12, 28), line='        for token in tokens:\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(12, 28), end=(12, 29), line='        for token in tokens:\n')
TokenInfo(type=5 (INDENT), string='            ', start=(13, 0), end=(13, 12), line='            print(token)\n')
TokenInfo(type=1 (NAME), string='print', start=(13, 12), end=(13, 17), line='            print(token)\n')
TokenInfo(type=53 (OP), string='(', start=(13, 17), end=(13, 18), line='            print(token)\n')
TokenInfo(type=1 (NAME), string='token', start=(13, 18), end=(13, 23), line='            print(token)\n')
TokenInfo(type=53 (OP), string=')', start=(13, 23), end=(13, 24), line='            print(token)\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(13, 24), end=(13, 25), line='            print(token)\n')
TokenInfo(type=6 (DEDENT), string='', start=(14, 4), end=(14, 4), line='    except Exception as err:\n')
TokenInfo(type=6 (DEDENT), string='', start=(14, 4), end=(14, 4), line='    except Exception as err:\n')
TokenInfo(type=1 (NAME), string='except', start=(14, 4), end=(14, 10), line='    except Exception as err:\n')
TokenInfo(type=1 (NAME), string='Exception', start=(14, 11), end=(14, 20), line='    except Exception as err:\n')
TokenInfo(type=1 (NAME), string='as', start=(14, 21), end=(14, 23), line='    except Exception as err:\n')
TokenInfo(type=1 (NAME), string='err', start=(14, 24), end=(14, 27), line='    except Exception as err:\n')
TokenInfo(type=53 (OP), string=':', start=(14, 27), end=(14, 28), line='    except Exception as err:\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(14, 28), end=(14, 29), line='    except Exception as err:\n')
TokenInfo(type=5 (INDENT), string='        ', start=(15, 0), end=(15, 8), line='        print(err)\n')
TokenInfo(type=1 (NAME), string='print', start=(15, 8), end=(15, 13), line='        print(err)\n')
TokenInfo(type=53 (OP), string='(', start=(15, 13), end=(15, 14), line='        print(err)\n')
TokenInfo(type=1 (NAME), string='err', start=(15, 14), end=(15, 17), line='        print(err)\n')
TokenInfo(type=53 (OP), string=')', start=(15, 17), end=(15, 18), line='        print(err)\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(15, 18), end=(15, 19), line='        print(err)\n')
TokenInfo(type=56 (NL), string='\n', start=(16, 8), end=(16, 9), line='        \n')
TokenInfo(type=56 (NL), string='\n', start=(17, 4), end=(17, 5), line='    \n')
TokenInfo(type=56 (NL), string='\n', start=(18, 0), end=(18, 1), line='\n')
TokenInfo(type=6 (DEDENT), string='', start=(19, 0), end=(19, 0), line='file_path = __file__\n')
TokenInfo(type=6 (DEDENT), string='', start=(19, 0), end=(19, 0), line='file_path = __file__\n')
TokenInfo(type=1 (NAME), string='file_path', start=(19, 0), end=(19, 9), line='file_path = __file__\n')
TokenInfo(type=53 (OP), string='=', start=(19, 10), end=(19, 11), line='file_path = __file__\n')
TokenInfo(type=1 (NAME), string='__file__', start=(19, 12), end=(19, 20), line='file_path = __file__\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(19, 20), end=(19, 21), line='file_path = __file__\n')
TokenInfo(type=1 (NAME), string='with', start=(20, 0), end=(20, 4), line='with open(file_path) as f:\n')
TokenInfo(type=1 (NAME), string='open', start=(20, 5), end=(20, 9), line='with open(file_path) as f:\n')
TokenInfo(type=53 (OP), string='(', start=(20, 9), end=(20, 10), line='with open(file_path) as f:\n')
TokenInfo(type=1 (NAME), string='file_path', start=(20, 10), end=(20, 19), line='with open(file_path) as f:\n')
TokenInfo(type=53 (OP), string=')', start=(20, 19), end=(20, 20), line='with open(file_path) as f:\n')
TokenInfo(type=1 (NAME), string='as', start=(20, 21), end=(20, 23), line='with open(file_path) as f:\n')
TokenInfo(type=1 (NAME), string='f', start=(20, 24), end=(20, 25), line='with open(file_path) as f:\n')
TokenInfo(type=53 (OP), string=':', start=(20, 25), end=(20, 26), line='with open(file_path) as f:\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(20, 26), end=(20, 27), line='with open(file_path) as f:\n')
TokenInfo(type=5 (INDENT), string='    ', start=(21, 0), end=(21, 4), line='    syntax_highlight_basic(f)\n')
TokenInfo(type=1 (NAME), string='syntax_highlight_basic', start=(21, 4), end=(21, 26), line='    syntax_highlight_basic(f)\n')
TokenInfo(type=53 (OP), string='(', start=(21, 26), end=(21, 27), line='    syntax_highlight_basic(f)\n')
TokenInfo(type=1 (NAME), string='f', start=(21, 27), end=(21, 28), line='    syntax_highlight_basic(f)\n')
TokenInfo(type=53 (OP), string=')', start=(21, 28), end=(21, 29), line='    syntax_highlight_basic(f)\n')
TokenInfo(type=4 (NEWLINE), string='\n', start=(21, 29), end=(21, 30), line='    syntax_highlight_basic(f)\n')
TokenInfo(type=56 (NL), string='\n', start=(22, 0), end=(22, 1), line='\n')
TokenInfo(type=6 (DEDENT), string='', start=(23, 0), end=(23, 0), line='')
TokenInfo(type=0 (ENDMARKER), string='', start=(23, 0), end=(23, 0), line='')
```
</details>

**Comment by zeffii** [comment]
so..
```python
import tokenize
import io

def syntax_highlight_basic(text):
    """
    example comment
    """
    # buffer = io.StringIO()  # buffer = io.StringIO(text)
    # buffer.write(text)

    try:
        tokens = tokenize.generate_tokens(text.readline)
        for token in tokens:
            print(token)
    except Exception as err:
        print(err)
        
multi_line = """\
def syntax_highlight_basic(text):
    '''
    example comment
    '''
    import tokenize
    import io
    # buffer = io.StringIO()  # buffer = io.StringIO(text)
    # buffer.write(text)

    try:
        tokens = tokenize.generate_tokens(text.readline)
        for token in tokens:
            print(token)
    except Exception as err:
        print(err)
        
"""

with io.StringIO(multi_line) as f:
    syntax_highlight_basic(f)
```

**Comment by zeffii** [comment]
and 
```python
import tokenize
import io
import inspect

def syntax_highlight_basic(text):
    """
    example comment
    """

    try:
        tokens = tokenize.generate_tokens(text.readline)
        for token in tokens:
            print(token)
    except Exception as err:
        print(err)
        
multi_line = inspect.getsource(syntax_highlight_basic)

with io.StringIO(multi_line) as f:
    syntax_highlight_basic(f)
```

**Pull request closed without merging**
