### PR TITLE
Smoothing node

### PR DESCRIPTION
**Pull request by portnov**
This is actually an interface for bmesh.ops.smooth_vert and smooth_laplacian_vert.

### CODE REVIEW

**Comment by portnov** [comment]
box_xy
extruded_box
suzanne
extruded_box_2

**Comment by portnov** [comment]
Combining Subdivide and Smooth, you can get...

extruded_box_3

**Comment by nortikin** [comment]
мержай

**Comment by kalwalt** [comment]
Super!

**Comment by portnov** [comment]
https://gist.github.com/7179097023324db66fb5994a46b60eaa

ico-virus

**Comment by nortikin** [comment]
крутотень

**Pull request merged**
