### PR TITLE
"Rounded rectangle" node

### PR DESCRIPTION
**Pull request by portnov**
This node generates a Curve object, representing a rectangle with rounded corners.

Screenshot_20200510_235429

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by vicdoval** [comment]
I'm not sure if it should be an option in "evaluate curve" or it could be automatic depending on the curve class, you may know, but wouldn't be nice that in the case of cyclic curves the "evaluate curve" node could remove the repeated vertex?

**Comment by zeffii** [comment]
@portnov  is the samples setting something like intrange- in interpolation node?
image

**Comment by portnov** [comment]
@vicdoval yeah, probably you're right, each curve could know if it is closed, and bring this information to Evaluate Curve node. A point to think about.

@zeffii the resulting curve is composed out of 8 segments: 4 arcs and 4 line segments. Arc segments have domain of `[0; pi/2]`, line segments have domain of `[0; L]`, where L is the length of that segment. So the whole domain of the curve is something like `[0; pi/2] + [pi/2; pi/2 + L1] + [pi/2 + L1; pi/2 + L1 + pi/2] + ...`. What "Evaluate Curve" does is simple: it takes the whole domain and splits it into N equal segments, that's all. Since domains of different segments have different length, we see different density of points on the curve.
There is an "Even Domains" switch on this particular node, which rescales domains of all segments into `[0;1]` - then each arc and each straight segment will have equal number of points after "Evaluate Curve", but that does not mean they will be distributed evenly in space - distribution of points in space will still depend on sizes of rectangle and radius of arcs.
To make points actually evenly spaced, you'll have to either use "Curve Length Parameter" node instead of "Evaluate Curve", or "Naturally Paramertized Curve". These nodes do non-trivial calculation to figure out how the curve domain is to be split (into non-even parts) so that corresponding segments of the curve would have even lengths.

**Comment by zeffii** [comment]
@portnov understood.  I'm looking forward to taking this stuff for a ride :)  i'd like to stay blissfully ignorant of the code for as long as possible :)

**Pull request merged**
