### PR TITLE
Implementation of `Objects along edge' node

### PR DESCRIPTION
**Pull request by portnov**
See portnov#6 for some description.
Please review and test :).

### CODE REVIEW

**Comment by zeffii** [comment]
```python
def get_axis_idx(self):
    return 'XYZ'.index(self.orient_axis_)
```

maybe it's just me but I prefer to see stuff indented as far to the left as possible.
```python
    orient_axis_ = EnumProperty(name = "Orientation axis",
                        description = "Which axis of donor objects to align with recipient edge",
                        default = "X",
                        items = axes, update=orient_axis_change)

# vs


    orient_axis_ = EnumProperty(
        name="Orientation axis",
        description = "Which axis of donor objects to align with recipient edge",
        default="X",
        items=axes, 
        update=orient_axis_change)

```
else it's just artificially indenting so far

**Comment by zeffii** [comment]
i'm a fan of all the other stuff tho, but that indentation seems a bit jarring

**Comment by portnov** [comment]
I fixed formatting.
And also I added a parameter "padding" to left ends of recipient edge free - this can be useful to put something at vertices, or just to avoid intersections between generated objects.

**Comment by zeffii** [comment]
coool! let's make some neat renders to show this off, or find out to break it :)

**Comment by portnov** [comment]
I did some minor fix in UI.
See last screens in portnov#6 :)

**Pull request merged**
