### PR TITLE
Import inputSwitch node from 2.79 to 2.80

### PR DESCRIPTION
**Pull request by DolphinDream**
The port seem to work except the macro connections or auto connection to VD node. I'm not sure if there is something missing a the socket / node_tree level, or whether there is something not quite working with the VD node.

The anomalous behavior I notice:
1. right click to connect to VD creates the VD node but it doesn't connect the sockets to it
2. the sw macros work except the connection to the VD node (e.g. sw123 only connects V and E but not P socket).
3. once connecting the outputs of the switch node to the vD node the viewport doesn't draw anyting unless i change the frame.

- [ ] Code changes complete.
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [ ] Manual testing done. 
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by DolphinDream** [comment]
It seems that the VD node does not draw vertices unless the edges and/or faces inputs are also connected.

**Comment by zeffii** [comment]
your macro must assume the socket names are different for the VD node in 2.8

**Comment by DolphinDream** [comment]
@zeffii there seems to be an issue with the VD node. Try connecting a box generator to the VD node one socket at a time.. if you connect just the vertices it draws nothing until you also connect either the edges and/or the faces. 

The VEP colors could be better chosen I think. The current edge color is almost invisible on the gray background. I always think the VD doens't draw the edges..until I realize they are hidden in plain sight :)

**Comment by DolphinDream** [comment]
@zeffii Here's an issue with (apparently) socket data not being updated properly. As I connect the output of the switch node to the VD nothing happens.. until I change the frame. Note how the labels of the output sockets of the switch node don't have the data count numbers next to the label (Data 1 .. vs Data 1.1) . These numbers appear once the frame changes. I'm not sure if this is a switch node issue or is caused by some other changes in SV b28 at a lower level/infrastructure. 

SV-InputSwitchNode-B28-demo1

**Comment by zeffii** [comment]
the issue with the VD node is that I didn't entirely fix the input logic, it's nothing overly complicated - i just didn't get around to it.

it's almost weekend and rainy, i might have more time for this in the next few days.

**Comment by zeffii** [comment]
the best way to test the switch node conversion in b.28 is possibly by using the DebugPrint node, which accepts multiple inputs.     it's possible that the use of the `macro` causes the tree (and all nodes involved) to be updated less times than needed.  There's all kinds of update limiting going on  the update system/event handler, and it is different substantially than 2.79 in that respect.

**Comment by zeffii** [comment]
remember i implemented custom defaults for nodes some time ago. check the issue tracker for how to set defaults for example the VD node.  I happen to use a bright background

**Comment by zeffii** [comment]
btw, using the arrow keys up/down is how i update the frame when stuff like this happens. Naturally one should not have to do any of this, but it's a faster ui trick.

**Comment by DolphinDream** [comment]
> btw, using the arrow keys up/down is how i update the frame when stuff like this happens. Naturally one should not have to do any of this, but it's a faster ui trick.

Thanks for the tip. Yes, this is what I normally do for chaning the frame, though for the purpose of the gif capturing I chose to click on the timeline to capture the frame change action since left/right keys are not going to show the frame is changed.

**Comment by DolphinDream** [comment]
Also, the default color features is nice to have. thanks for reminding me about it. However, IMO for the new users we should probably come up with a default colors that look best on blender's default theme.

**Comment by DolphinDream** [comment]
I imported this node to 2.8 but I can't figure out why the updates don't work correctly, until changing the frame a couple of times. If anyone wants to take a hit at it, be my guest. I kind of lost hope.

For what is worth.. here's another wierd behavior... initiating a socket connect and drop it before connecting it changes the inputs to the other sockets (apparently, if that even makes sense).

SV-InputSwitchNode-B28-demo2

InputSwitchNode-B28-Issue

**Comment by zeffii** [comment]
weird, i'll have a look later.

**Comment by zeffii** [comment]
there's a few things going on there, none of which I have a satisfactory fix for at the moment. i'm not sure where there's a `cache-miss` as a result of some non-event.

i'm merging so it's easier to check.

**Comment by zeffii** [comment]
i'm slowly rewriting this node @DolphinDream -- to the best of my ability, with less superficial features.. just in an attempt to see if a completely alternative approach lets us identify the problem.

**Comment by DolphinDream** [comment]
@zeffii the MOD version of the InputSwitch node seems to have some issues:
* Once new set is created it doesn’t get removed if the input sockets are disconnected.
* The switch macros do not work since the label_of_set method (used to figure out the next set to connect the input nodes to) does no longer exist.

**Comment by zeffii** [comment]
1. yep, there's no automatic removal if last visible set is unconnected 
    - (or last two sets is what you probably mean, would be the criterion. If last two sets visible are unconnected, then hide last set )
   - i think this would be acceptable to do at the top of the process function, either automated ..but simpler is an operator to "prune" socket sets.

2. of course switch macros is useless on the modified version, first things first .

my goal was really to see if this would be acceptable / useful / helpful as an example / alternative approach.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/commit/8760419e48b497845095a3774087cd2f425b5dbe
pushed a working version (at least 123 works ) of the macro.

this is not massively tested yet, i make no claims of its stability. I also don't know how the node behaves in iojson :) haha probably not great

**Pull request merged**
