### PR TITLE
add string to vector conversion

### PR DESCRIPTION
**Pull request by Durman**
What about adding "string to vector" conversion ? I think it would let to rid out of extra `vector in` nodes in many layouts.

string to vector

### CODE REVIEW

**Comment by portnov** [comment]
It's not obvious how should it work :/
Should it map X -> (X, X, X), or X -> (X, 0, 0), or X -> (0, 0, X), or whatever? So It seems to me the layout with explicit conversion node will be easier to understand.

**Comment by Durman** [comment]
The idea has come from animation node. They have special node which convert value to vector. The mapping is always (x, x, x).

image
https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/vector/vector_from_value.html

Since I was aware of this little feature I started to notice more and more cases where it is really convenient to use.

If we will add this convention there is even no need in adding the node I guess.

**Comment by portnov** [comment]
With #3312 it will be possible to add a drop-down menu to inputs to select between different conversion logics...

**Comment by nortikin** [comment]
all auto conversion are great

**Pull request merged**
