### PR TITLE
adds sv_custom_exception

### PR DESCRIPTION
**Pull request by zeffii**
## Addressed problem description

addresses the minor usability issue of letting users know they need to connect more sockets for the node to be useful. https://github.com/nortikin/sverchok/issues/1986

## Solution description

This adds a new exception subclass to be `raise`d as soon as the node enters the process function, but doesn't have enough sockets to generate data from.

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete. (well.. @portnov will have some comments I hope )
- [ ] Code documentation complete.
- [ ] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. (works for my needs)
- [ ] Unit-tests implemented.
- [ ] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
At a first glance the code looks good; I have an intention to test it this week.

**Comment by portnov** [comment]
Okay, this works good.

Maybe we should have specific node color for this exception, like that we have for SvNoDataError?

**Comment by zeffii** [comment]
yes, a unique color.  i'm all for it.

**Comment by zeffii** [comment]
id like to start using it

**Comment by nortikin** [comment]
bright green color for node?

**Pull request merged**
