### PR TITLE
shift + ]  menu

### PR DESCRIPTION
**Pull request by zeffii**
image

### Usage

- `shift+]` will trigger a new search bar.  
- The search database is loaded with 
    - All nodes (shows Node Name (bl_label) and Description
    - Several default macros ( shown by `>` )
    - optionally User Driven Macros ( shown by `<` )
        These need to be created by the user in `/datafiles/sverchok/user_macros/macros.py` . See an example of such a file here

### Implementation details

- [x] implement macro searching
     - ( i can not control the width of the window.. unless there's a trick somewhere...)
- [x] select / place node
- [x] implement default macros
    - [x] `obj vd`   (single object to vdmk2)
    - [x] `objs vd`   (multi object to vdmk2)
    - [x] `sn petal`  (auto loads petalsine in snlite)
    - [x] `zen` (the zen of sverchok, shows [my tumblr post about the zen of it all](http://blenderpython.tumblr.com/post/91951323209/zen-of-sverchok))
    /- [ ] swap viewer  (hot swap viewer nodes  vdmk3 <-->  bmeshview )
- [x] Auto Line splitting on `///` for description
- [x] `>` will indicate the result is a macro
- [x] `<` will indicate the result is a user macro
- [x] Auto Line wrapping for description
- [x] implement user driven macro definitions.
- [x] pass mouse location.

### CODE REVIEW

**Comment by zeffii** [comment]
I don't know about you guys, but i've noticed the regular search feature is slow ( i type in text and it takes several hundred milliseconds to appear). I don't know how long it's been that slow, but it's happening in an area i've not interfered with (and am puzzled why it's so slow...)

I present a faster search, and one that we can customize to some extent.

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
@nortikin  this will finally show the docstring of a node beside the node label (which default search doesn't..) -- This also means we should probably go through all nodes and give them a suitable short doscstring that can help the user pick from the searchbox.

I think `>`  will indicate that a result is a macro:

image

**Comment by zeffii** [comment]
Debug Print is an example of a docstring we should change.. and probably many others.
```python
class SvDebugPrintNode(bpy.types.Node, SverchCustomTreeNode):
    ''' SvDebugPrintNode '''  <----
    bl_idname = 'SvDebugPrintNode'
    bl_label = 'Debug print'
    bl_icon = 'OUTLINER_OB_EMPTY'
```

**Comment by zeffii** [comment]
unfortunately the invoke_search_popup doesn't do linewrapping automatically.. so, i'll probably have to split at 20 chars or something stupid..

image

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
so ..svProfile is candadate for docstring revision.. or some kind of docstring interpretter..
```python
class SvProfileNode(bpy.types.Node, SverchCustomTreeNode):
    '''
    SvProfileNode generates one or more profiles / elevation segments using;
    assignments, variables, and a string descriptor similar to SVG.
    This node expects simple input, or vectorized input.
    - sockets with no input are automatically 0, not None
    - The longest input array will be used to extend the shorter ones, using last value repeat.
    '''
    bl_idname = 'SvProfileNode'
    bl_label = 'Profile Parametric'
    bl_icon = 'OUTLINER_OB_EMPTY'
```

**Comment by zeffii** [comment]
image

```python
class SvProfileNode(bpy.types.Node, SverchCustomTreeNode):
    '''
    svg-like 2d profiles ///

    SvProfileNode generates one or more profiles / elevation segments using;
    assignments, variables, and a string descriptor similar to SVG.

    This node expects simple input, or vectorized input.
    - sockets with no input are automatically 0, not None
    - The longest input array will be used to extend the shorter ones, using last value repeat.
    

    '''
    bl_idname = 'SvProfileNode'
    bl_label = 'Profile Parametric'
    bl_icon = 'OUTLINER_OB_EMPTY'
```
using the `///` as a separator

**Comment by zeffii** [comment]
image
you get the idea

**Comment by portnov** [comment]
Consider also macros that can do something with selected nodes.
For example:
* Have nodes like Sphere -> Move -> Viewer, select the Move node
* Hit magic button
* Now you will have Sphere -> List Mask Out -> Move -> List Mask In -> Viewer, connected so that only selected vertices will be moved.

**Comment by zeffii** [comment]
@portnov 
- pick a nice trigger _term_
- you can write the code in this form, and i'll plug it in.. 

```python
        cls.ensure_nodetree(operator, context)

        tree = context.space_data.edit_tree
        nodes, links = tree.nodes, tree.links

        # this form for now..
        if term == 'obj vd':
            obj_in_node = nodes.new('SvObjInLite')
            obj_in_node.dget()
            vd_node = nodes.new('ViewerNode2')
            vd_node.location = obj_in_node.location.x + 180, obj_in_node.location.y
            
            links.new(obj_in_node.outputs[0], vd_node.inputs[0])
            links.new(obj_in_node.outputs[2], vd_node.inputs[1])
            links.new(obj_in_node.outputs[3], vd_node.inputs[2])        

```
and `nodes.active` will return the active node reference.


or wait till i've added user defined macro definitions (next step...)

**Comment by zeffii** [comment]
@portnov   can you include a screenshot of the proposed setup?  or a gist (before and after) lets see if it can be automated even more lazily.

**Comment by zeffii** [comment]
image

**Comment by portnov** [comment]
@zeffii 
yeah, something like that... only I think mask generation (random generator here) and specific node parameters (vector in here) should be present before invoking the macro. Macro only adds Mask In/Out nodes and links them.

**Comment by zeffii** [comment]
perhaps it should spawn a monad.

@portnov  you touch on an interesting point , and there's lots to take into account -- therefor what might become the way we work on this is.. you write a snippet that transforms `input set of nodes` to a `resulting set of nodes with desired connections` , and suggest a useful shorthand identifier/trigger. then I or we add it to the defaults... but if it's too specific then we'll probably say " add that to your `/datafiles/sverchok/macros.fx` file .

**Comment by zeffii** [comment]
maybe set up a separate repository for user defined macros, minimizing the chance you lose your hard work..

**Comment by zeffii** [comment]
##### objs vd

umdaagif

**Comment by zeffii** [comment]
i'm thinking of .. 

> replace (vdmk2<->bmview)

**Comment by zeffii** [comment]
image

**Comment by portnov** [comment]
Couple of points more...

* Related to #1526: Templates could become macros.
* One promising application for macros is "add Script node + select specific script in it".
* List of macros for adding Templates and Script nodes could be automatically added to main Shift-A menu or maybe to separate menu or toolbar.

**Comment by zeffii** [comment]
I think Shift-A is fully populated at this point. It would be nice to start a new menu..

**Comment by zeffii** [comment]
added default `> sn petal`

consider this an example..

```python
        elif term == 'sn petal':
            snlite = nodes.new('SvScriptNodeLite')
            # set location of snlite based on mouse?

            sv_path = os.path.dirname(sv_get_local_path()[0])
            snlite_template_path = os.path.join(sv_path, 'node_scripts', 'SNLite_templates')
            fullpath = os.path.join(snlite_template_path, 'petal_sine.py')
            
            txt = bpy.data.texts.load(fullpath)
            snlite.script_name = os.path.basename(txt.name)
            snlite.load()
```

**Comment by zeffii** [comment]
i'll meditate on how to implement user-defined-macros (UDM henceforth).

This what I think i want.. before doing the implementation

- they will be located in `../datafiles/sverchok/user/macros.py`
- the content of `user` can be `folders` or `files` allowing you to import scripts / functions local to it.

so i think
```text
.../datafiles/sverchok/user/macros.py
                            /some_macro_folder/some_other_util.py
                            /some_macro_util.py
```
and in macros.py
```
import bpy

from .some_marco_util import add, set_var


```

**Comment by zeffii** [comment]
cool. progress..
```python
import importlib.util
import os

ddir = lambda content: [n for n in dir(content) if not n.startswith('__')]



def function_iterator(foo):
    for name in ddir(foo):
        obj = getattr(foo, name)
        if callable(obj):
            yield name, obj.__doc__


def fx_extend(idx, datastorage, filepath):
    # shall be dynamic
    datafiles = r'C:\Users\zeffi\AppData\Roaming\Blender Foundation\Blender\2.78' 

    fullpath = os.path.join(datafiles, filepath)
    if os.path.exists(fullpath):
        spec = importlib.util.spec_from_file_location("macro_module.name", fullpath)
        foo = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(foo)
        for func_name, func_descriptor in function_iterator(foo):
            fx.append((func_name, func_descriptor, '', idx))
            idx +=1
    else:
        print('nope')


fx = []
idx = 20
fx_extend(idx, fx, 'datafiles/sverchok/user_macros/macros.py')

print(fx)
```

**Comment by zeffii** [comment]
image

not sure exactly the next step..

**Comment by zeffii** [comment]
now user macros are implemented, sadly there's no easy way to trigger them with parameters that you might want to decide at runtime.. (which blows...)

**Comment by zeffii** [comment]
for example `C:\Users\zeffi\AppData\Roaming\Blender Foundation\Blender\2.78\datafiles\sverchok\user_macros\macros.py`

```
"""

blablabla

"""

def domo_esta(self, context):
    """ info about domo esta /// will ignore this"""
    active_node = context.active_node
    if active_node:
        print(active_node.name)
        print(active_node.location)
        print(active_node.bl_idname)


def domo_esta4(a=10, b=140):
    """ info about domo esta4 """
    print(a, b)
```

**Comment by zeffii** [comment]
i'll pass mouse location too.

**Comment by zeffii** [comment]
i'm ready to commit this.

**Comment by kalwalt** [comment]
the macro feature works for me:

```c
** Sverchok loaded with 231 nodes **
added keyboard items to Text Editor.
** version:  (0, 5, 9, 6)  **
** Have a nice day with sverchok  **

 ______ _    _ _______  ______ _______ _     _  _____  _     _
/______  \  /  |______ |_____/ |       |_____| |     | |____/
______/   \/   |______ |    \_ |_____  |     | |_____| |    \_
initialized.
Sverchok is reloaded, press update
SvRx reloading
/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/svrx/util/transforms.py:1899: UserWarning: failed to import module _transformations
  warnings.warn("failed to import module %s" % name)
SvRx is reloaded, press update
Registered Animation Nodes with 409 modules.
Registered Code Autocomplete with 38 modules.
2017-04-18 13:14:28,033     INFO manuelbastionilab_logger Looking for the database in the folder [Trunked]..2.78/scripts/addons_contrib/manuelbastionilab/data...
2017-04-18 13:14:28,033     INFO manuelbastionilab_logger Loading characters definition from [Trunked]..ons_contrib/manuelbastionilab/data/characters.json
gc.collect() -> 17153
Time: 0.00004 - fps : 22727.27 - Function: update
Time: 0.00020 - fps : 5025.13 - Function: updateEverything
Time: 0.00010 - fps : 10204.08 - Function: update
Time: 0.00038 - fps : 2617.80 - Function: updateEverything
[]
[]
[('domo_esta', ' info about domo esta /// will ignore this', '', 20), ('domo_esta4', ' info about domo esta4 ', '', 21)]

```
followed your instructions @zeffii above

**Pull request merged**
