### PR TITLE
Panel 3d - refactoring

### PR DESCRIPTION
**Pull request by Durman**
List of all nodes which can have properties on 3D panel,
And new location of 3D panel on N panel:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [x] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
It looks there is no need always show limits in 3D panel for `A number` node.
n panel a number

**Comment by Durman** [comment]
`Hasattr` is most curious function in Python
```Python
class A:
    def prop(self):
        A.asdfasd
        return True
   
>>> hasattr(A(), 'prop')
False
```

**Comment by Durman** [comment]
After this PR if someone would like to have UI on 3d panel for a node all what should be done is to add one special method and one special property to a node, like this:
```Python
class SvMyNode:
    my_prop: bpy.props.IntigerProperty()
    draw_3dpanel: bpy.props.BoolProperty()

    def draw_buttons_3dpanel(self, layout):
        layout.prop(self, 'my_prop')
```
Property can be dynamic:
```Python
class SvMyNode:
    my_prop: bpy.props.IntigerProperty()

    @property
    def draw_3dpanel(self):
        return True if self.outputs[0].is_linked else False

    def draw_buttons_3dpanel(self, layout):
        layout.prop(self, 'my_prop')
```
@zeffii Can you make a suggestion where this logic could be documented? If there is no objection of such approach.

**Comment by zeffii** [comment]
@Durman 
```
class A():

    def __init__(self):
        ...

    def prop(self):
        return True

a = A()
print(hasattr(a, 'prop'))
>>> True
```

i have no objections to making it easier for nodes to display properties in the other panels, be aware that there is already a property-check in place for when a node is deleted, to clean up the propertygroup used to show the properties.

https://github.com/nortikin/sverchok/blob/a92cea484c3a90dd908bcc1884467e1a6c2b448b/node_tree.py#L533-L544

**Comment by Durman** [comment]
With class A example I only try to point that debugging process can be painful. If you try to get some non existed attribute inside method and try to check whether the method exists you can be surprised that the method does not exist from point of Python.

> be aware that there is already a property-check in place for when a node is deleted, to clean up the propertygroup used to show the properties.

I will check but it looks that this contradicts with 3d panel code:

https://github.com/nortikin/sverchok/blob/a92cea484c3a90dd908bcc1884467e1a6c2b448b/ui/sv_panels.py#L196-L206

**Comment by Durman** [comment]
There are no even one node with `has_3dview_props` attribute. I think it worth to reimplement this part of code. This code is probably outdated or it is just a declaration of functionality without any real job.

**Comment by Durman** [comment]
But probably it worth to discuss how to handle deleting of a node represented in 3D panel. Now it does not removed from 3D panel automatically, but there is warning message about this.

From my point of view it is quite good approach. You can delete a node casually without noticing but then you can see the hint on 3D panel that the node was deleted. Any thoughts?

**Comment by zeffii** [comment]
i don't have a strong opinions about this, i can't help with this at the moment.

**Pull request merged**
