### PR TITLE
Line Node MK2

### PR DESCRIPTION
**Pull request by DolphinDream**
- cleanup the code
- optimize the calculation
- sanitize the inputs
- and new X,Y,Z direction option to create line along X,Y or Z (no need to do rewire just to swich directions)

linenodemk2-example2

linenodemk2-demo1

linenodemk2-demo3

### CODE REVIEW

**Comment by zeffii** [comment]
I did something similar.. https://github.com/nortikin/sverchok/issues/1147  but the orientation was a socket

**Comment by enzyme69** [comment]
This Line MK2 thing has some kind of "Ratio" happening? Ask Nikitron about
it. He has a thing with LINE node. It can do some SV magic underneath, that
not many people know.

**Comment by DolphinDream** [comment]
@enzyme69 the new LineMK2 is identical in behavior with the current Line node.. except I added the X/Y/Z orientation .. and cleaned up the code. What “ratio” are you referring to ?

**Comment by DolphinDream** [comment]
Trying out some new ideas.
One thing I think i miss in the line node is the ability to define the size of the line. Adjusting the number of vertices and steps always grows the line in an unpredictable way. I added a normalize (just to check it out) option to allow the line to use the same inputs as before but normalize the length to a given size. 

linenodemk2-demo3

**Comment by portnov** [comment]
Maybe add modes similar to RangeFloat node?
Line can be defined by:
a) number of vertices and step
b) line length and number of vertices

**Comment by enzyme69** [comment]
screen shot 2017-03-08 at 21 14 30

**Comment by enzyme69** [comment]
screen shot 2017-03-08 at 21 19 17
screen shot 2017-03-08 at 21 19 08

Line somewhat has accumulate function built in.

**Comment by DolphinDream** [comment]
yeah, I see that. But it’s not accumulation.. it’s a different way of vectorizing (i guess). It seems that if you split the “step” list into separate lists, each list in the list of lists creates a separate mesh (line) which is what you see when you replicate this with the other line along Y. The first line is the one having the step equal to the START value in the range of float.. while the last replicated line (if you match the replications with the number of elements in the range of floats) you’ll get a line with the step equal to the STOP value of the range of floats.  So the line node knows how to vectorize this way when it gets a lists of lists. It’s a bit of a non conventional way of using the generators  based on what I know so far about SV, but maybe this is what the generators were intended to do from the very beginning? @nortikin may testify to that. 

Sure, I can make the Line MK2 handle the list of lists the same way.

**Comment by DolphinDream** [comment]
Original Line node vectorization added to Line MK2 .. side by side comparison.

Note: the Normalization/Size is not yet implemented for this version. Besides, the normalization/size only makes sense for a single line as it can keep a variable steps/verts line within a given size. With split list vectorization each line is generated with one N and one S (equal size step) thus normalization would invalidate the step size, while the number of verts per line will still vary, thus resulting in equal size lines with different numbers of verts. 

linenodemk2-demo4

**Comment by DolphinDream** [comment]
Now.. to take @nortikin vectorization madness a step further :) we could feed the step input a list of list of lists which will allow each replicated line to have a variable step division. :)

And that could spiral fast into a mind boggling philosophical question  :)

“There was a young man who said though, it seems that I know that I know, but what I would like to see is the I that knows me when I know that I know that I know.”
― Alan W. Watts

**Comment by DolphinDream** [comment]
And with normalization (fixed size, variable verts per replication):

linenodemk2-demo5

**Comment by DolphinDream** [comment]
Having fun with some RingLine replication :) 

https://gist.github.com/af5a5f607e80a68c604e7602b046801b

linenodemk2-ringlinereplication

**Comment by enzyme69** [comment]
That's neat, I just remember there is this new RING node! Cool :) Great
addition!

**Comment by DolphinDream** [comment]
With the updated, more compact UI:

linenodemk2-demo7

**Comment by zeffii** [comment]
please resolve conflict and indentation and let's merge this sucker.

**Comment by DolphinDream** [comment]
Will do shortly. I was already working on it 🤓

**Comment by DolphinDream** [comment]
@zeffii resolved. ready for merge.

**Pull request merged**
