### PR TITLE
Vector In: get 3D cursor location

### PR DESCRIPTION
**Pull request by portnov**
This adds a button to Vector In node, which assigns current location of 3D Cursor to X,Y, Z parameters of node. This button is available only when no inputs are connected.

### CODE REVIEW

**Comment by zeffii** [comment]
why not hijack the XYZ node instead?

**Comment by zeffii** [comment]
@portnov 

how about a dedicated 3d cursor node, that can also store a number of locations?

**Comment by enzyme69** [comment]
@zeffii @portnov "A number of locations" you mean multiple 3D Cursor Node? Like Empty? I remember having Sverchok reading 3D cursor and we can sort of have interactive setup like objects moving into 3D cursor position. Or maybe I was dreaming.

**Comment by enzyme69** [comment]
@portnov Can this "button" have an option to continuously updating and tracking when Frame Updates so that objects can fly into this 3D cursor position?

**Comment by zeffii** [comment]
A separate Node, just for 3d cursor. makes more sense than to add these extra features to the Vector In node.

**Comment by enzyme69** [comment]
@zeffii @portnov Ah, yeah, I thought about that too hijacking "XYZ node" might keep "Vector In" cleaner. 

When a user plugging Range Float to Vector In, the might be surprise on why the button disappear, but it's all optional, I guess. I leave it to you guys~

**Comment by zeffii** [comment]
but the reason i retracted the offer to use XYZ instead, is because the XYZ node is really just for _axis_.

**Comment by nortikin** [comment]
agree, idea is good deserve separate node with additional functions for cursor.

**Comment by portnov** [comment]
And what should it do?

**Comment by nortikin** [comment]
personally i agree zeffii, separate to new cursor node. leave vector node as it was before

**Comment by nortikin** [comment]
new cursor node can have input position and output position also

**Comment by zeffii** [comment]
we can even add a nice bgl drawing into 3d view of stored 3d locations.

**Comment by zeffii** [comment]
with custom colours per 3d reference..

**Comment by enzyme69** [comment]
And custom option where it can be triggered when:
- frame updated
- cursor position changed
- other
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by enzyme69** [comment]
screen shot 2017-04-04 at 15 25 42

Gotta admit that sometimes this button to get 3D Cursor position can be handy, in this case for me getting the pivot for the spider legs.

**Pull request merged**
