### PR TITLE
Add fillet to smoothline

### PR DESCRIPTION
**Pull request by zeffii**
image

adds arc :)  - the image shows a slight artificial offset for illustration purposes only, the node doesn't produce the offset.

### CODE REVIEW

**Comment by nortikin** [comment]
faces + laplacian smooth crashes blender with no debug output
[smooth.zip](https://github.com/nortikin/sverchok/files/2538743/smooth.zip)

**Comment by zeffii** [comment]
this is not intended for faces...  but it should not crash

**Comment by zeffii** [comment]
that's a different node @nortikin    ,  "smooth vertices"

**Comment by zeffii** [comment]
image

regarding the smooth vertices, it might be that input vertices that all have the same 0.0 for z, might make the algorithm slow if it's smoothing out x y and z, when only x and y make sense.

**Comment by nortikin** [comment]
smooth

**Pull request merged**
