### PR TITLE
Set Properties to COLOR_GAMMA Instaed of COLOR

### PR DESCRIPTION
**Pull request by mifth**
For settings.py I set color properties to COLOR_GAMMA to set them to the same color.

Before:
image

After:
image

### CODE REVIEW

**Review by Durman — APPROVED** [review]

**Comment by Durman** [comment]
I guess you can merge this yourself. )

**Comment by mifth** [comment]
Sorry, I don't have the Merge button. Probably I have no rights to do it. I can only close the Pull Request.

**Comment by nortikin** [comment]
added to collaborators.
Maybe someone waiting to be added?

**Comment by mifth** [comment]
Thank you! It's pleasure for me.

**Pull request merged**
