### PR TITLE
Fix typos carthesian->cartesian 

### PR DESCRIPTION
**Pull request by luzpaz**
Fixes both source code and source comment

### CODE REVIEW

**Comment by zeffii** [comment]
can we merge this already? seems good.

**Comment by luzpaz** [comment]
Question here is about backward compatibility though, right?

**Comment by zeffii** [comment]
so far i don't see anything in the PR that would break existing .blends / .jsons , in the enum lists ( in math module, the modes lists) only the first element is stored in the .blend

**Comment by luzpaz** [comment]
alrighty then :)

**Review by portnov — APPROVED** [review]
LGTM

**Pull request merged**
