### PR TITLE
Adaptive polygons: Frame / Fan mode

### PR DESCRIPTION
**Pull request by portnov**
This adds an option to "Adaptive Polygons mk2" node to work in "Frame" / "Fan" mode (similar to Tissue addon). 

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
Screenshot_20191109_175107
Screenshot_20191109_175226

**Comment by portnov** [comment]
Screenshot_20191109_180330
Screenshot_20191109_180628

**Comment by vicdoval** [comment]
Wouldnt you like to add a optional call to remove doubles inside the node?
https://github.com/nortikin/sverchok/blob/03b09b88f9e218d5c2534dc53e170dacd0255e22/nodes/generators_extended/triangle.py#L199

**Comment by portnov** [comment]
Probably...

**Pull request merged**
