### PR TITLE
New Distance Point Line Node

### PR DESCRIPTION
**Pull request by vicdoval**
Basic and super useful distance point-line node.

screen
screen2

screen1
screen1

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by Durman** [comment]
Something similar to this: #2376 ?

**Comment by vicdoval** [comment]
Similar but simpler.
The line is defined by 2 vertices. (first and last) I think it can be useful in many  parametric/mathemaical definitions.
#2376 would be more "project point on edges"

**Comment by nortikin** [comment]
will do video for this one.
cool node

**Comment by Durman** [comment]
@nortikin I'll switch attention to this node but still can't say how long does it take.

**Comment by Durman** [comment]
I'm slightly confuse. What does line mean? 
As I thought Line is shape that consists from several edges. But also there is boundless line, probably straight line.

**Comment by nortikin** [comment]
@Durman Good question. there is straight line. Not curved or segmented one. Would be great to deal both. straight for simple cases and yours for complex.

**Comment by portnov** [comment]
Any reason why this is not merged yet?

**Comment by vicdoval** [comment]
@Durman this node refers with Line to the endless straight line, it also gives some info about the relationship with the supplied segment.

@portnov i had some minor details i wanted to change. Now it is done.

More details in the docs file 😄

**Comment by Durman** [comment]
> I'm slightly confuse. What does line mean?
> As I thought Line is shape that consists from several edges. But also there is boundless line, probably straight line


I found evidence that line is something consisted with several segments according Blender API.))

**Pull request merged**
