### PR TITLE
adds wad reader

### PR DESCRIPTION
**Pull request by zeffii**
adds a Basic Authorization storage/reader for gist uploads

### CODE REVIEW

**Comment by nortikin** [comment]
nice. it will be benefit for sure. To store own collection.

**Comment by zeffii** [comment]
ok if time later today will inspect and push

**Comment by zeffii** [comment]
and add a gray-out for the upload button, when sverchok doesn't detect local wad file

**Comment by zeffii** [comment]
internally sverchok will query the following code, and decide whether to show the `gist upload` button on the UI or not

```python
>>> sverchok.utils.sv_git_connection.login_found
True
```

**Comment by zeffii** [comment]
ok this will work as follows; for basic authentication.

1. you need a github account, if yes - proceed to 2.  if no. byebye for now
2. you must convert your username:pw with a base64 encoder and obtains a string

    ```python
    import base64
    arp = '%s:%s' % ("your username", "your password")
    b43 = base64.b64encode(arp.encode()).decode('utf-8')
    print(b43)
    ```
    in this case

   > eW91ciB1c2VybmFtZTp5b3VyIHBhc3N3b3Jk

3. you store the string in a file called `sv_fx.wad` at this location on your HD `.../2.7x/datafiles/sv_fx.wad`
4. if blender was running, restart it and it will find a token and display the upload button again.

**Comment by zeffii** [comment]
if people can confirm that they can figure out how to do this, then i'll maybe also add support for f8 (to avoid the restart)

**Comment by portnov** [comment]
Any problems that prevent us from implementing that code (for creating a wad storage) in sverchok?

**Comment by zeffii** [comment]
not really,  but i legitimately feel uncomfortable storing that b64-encoded string.

but of course. we could offer a popup windows with two text fields, and have "OK" generate the `.wad`, in the correct place.  .... but that's not really the point, and certainly isn't why i've avoided doing that.

**Comment by zeffii** [comment]
if Sverchok could obtain a `secret` from github while generating the token, that would be cool.

**Comment by portnov** [comment]
You mean you feel uncomfortable about storing non-encrypted passwords?... Well, I believe some other addons should of work with the same problem already...

**Comment by zeffii** [comment]
i welcome proposals.

**Comment by portnov** [comment]
It seems that "the correct way" of doing this is to ask users to generate github API access token manually (i think there is no way to generate it automatically from username/password, and should not be from security point of view), and enter that token in sverchok preferences.

**Comment by zeffii** [comment]
if someone wants to make that happen / do a write up for users / cool

**Pull request merged**
