### PR TITLE
Metaball out vectorized (WIP)

### PR DESCRIPTION
**Pull request by portnov**
The goal is to be able to create several META objects. For that, the Metaball Out node should be able to consume a list of lists of matrices: one list of matrices per Meta object. Or it in consume just a list of matrices (compatibility mode) and produce single object.

### CODE REVIEW

**Comment by Durman** [comment]
@portnov How are you going to generate list of lists of matrices? I have received the same question from zeffi here: #1728 ))

**Comment by Durman** [comment]
Can you give your example with monad node? I don't manage to create this.

**Comment by portnov** [comment]
Well, I did not try yet :)

**Comment by zeffii** [comment]
i'll port this version over to 2.8 today i think :)

**Comment by zeffii** [comment]
i've ported this to sv 4 2.80

**Pull request closed without merging**
