### PR TITLE
Skinviewer update tplex

### PR DESCRIPTION
**Pull request by zeffii**
image

### CODE REVIEW

**Comment by zeffii** [comment]
This node has had major bypass surgery, i will keep it in Beta for observation for the time being.

@nortikin  you made a change some time ago, i've modified that code but the behaviour should be no-different.

**Comment by zeffii** [comment]
@enzyme69  you'll want to update.. sv skin viewer is now at MK1, still beta, but behaves a bit more like the other viewers.

- still not separate x/y radius . don't ask.

**Comment by enzyme69** [comment]
Thanks @zeffii I tested just now, looks great! Will try all sort of things. Love this feature~!

**Comment by zeffii** [comment]
@enzyme69 no, remove doubles code not yet pushed to master, but will be testing it shortly from a branch

**Pull request merged**
