### PR TITLE
Implementation of `Apply matrix to mesh` node

### PR DESCRIPTION
**Pull request by portnov**
refs #563

### CODE REVIEW

**Comment by zeffii** [comment]
but
```python
        result_edges = edges * n
        result_faces = faces * n

        self.outputs['Vertices'].sv_set(result_vertices)
        if self.outputs['Edges'].is_linked:
            self.outputs['Edges'].sv_set(result_edges)
        if self.outputs['Faces'].is_linked:
            self.outputs['Faces'].sv_set(result_faces)
```
Performs `edges*n` and `faces*n` even if no sockets are connected. Though I expect this is not much processing really..

Also I wonder about the Vector_Degenerate if it would not be simpler (or even faster) to
```python
    def apply(self, vecs, mats):
        out = []
        lengthve = len(vecs)-1
        for i, m in enumerate(mats):
            out_ = []
            k = i
            if k > lengthve:
                k = lengthve
            out_ = [(m*v)[:] for v in vecs[k]]  # vector direct to tuple
            out.append(out_)
        return out
```
and ditch the vector_degenerate step?

**Comment by zeffii** [comment]
I don't quite understand, the _Join_ part is not implemented merely the _Repeat_ part?

**Comment by portnov** [comment]
Yes, atm it in fact outputs N whole meshes, to be joined by Mesh Join. Do you think it should also do the work of Mesh Join?

**Comment by zeffii** [comment]
Optionally, yes. Else it might be a misnomer to include _Join_ in the name of the node. My preference is that it could do Join but implemented as a module in `utils/sv_mesh_utils.py` so both a separate Join node and this Apply node could reuse the same code.

The node is handy without the feature though, but then I would call it something like _ApplyAndRepeat_.

**Comment by portnov** [comment]
Ok, will try to implement that

**Comment by zeffii** [comment]
The current code also has a limiting assumption that if there are several nested vert lists, that they all have the same edges/faces, which they might not.

**Comment by portnov** [comment]
From my point of view, usage of Vector_degenerate once at last moment produces much cleaner code than [[:]] mumbo-jumbo :) And I don't think this will do any noticable difference in performance.

I pushed some refactorings; please review.

**Comment by zeffii** [comment]
https://github.com/portnov/sverchok/blob/master/data_structure.py#L392-L393
under the hood the mumbo jumbo is the same, almost.

**Comment by portnov** [comment]
Yep, but it's under the hood, that's whole point :)

**Comment by zeffii** [comment]
I was speculating, which it still is unless someone speedtests.

**Comment by portnov** [comment]
@zeffii sorry, i found a bug introduced while refactoring. I pushed a fix.

**Comment by portnov** [comment]
Btw, currently when Join option is used, the node outputs unwrapped output. Just list of vertices and so on. Should it do wrapping of outputs for Join mode?

**Comment by zeffii** [comment]
maybe @nortikin or @ly29 have opinion about that, I don't at the moment

**Comment by zeffii** [comment]
pick one, if it turns out to be better to have the other, we switch.

**Comment by portnov** [comment]
Ok, then let's wait for other opinions.

**Comment by nortikin** [comment]
from my practic i see wrapping has to be option and not by default. by default it need to be unwrapped as usual.

**Pull request merged**
