### PR TITLE
Framework (carcass / ferme) node

### PR DESCRIPTION
**Pull request by portnov**
This PR adds a new "framework" (construction carcass) node. The framework is generated by extruding vertices of some "profile mesh" to generate lengthwise crossbars, and then connecting the resulting vertices by traverse edges. The traverse edges can intersect in some cases.

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [ ] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
Screenshot_20191201_205125
Screenshot_20191201_212559
Screenshot_20191201_214141

**Comment by portnov** [comment]
https://gist.github.com/7fa317b132e4a811e672e82ef35df568

Screenshot_20191201_222753

**Comment by portnov** [comment]
https://gist.github.com/d666af0faf28bad9a34f0384fe4d48a4

framework_adaptive_1

**Comment by portnov** [comment]
https://gist.github.com/2ea5c06978610da3451ac3edf161e6ba

Screenshot_20191202_220551

**Comment by nortikin** [comment]
ухты, фермогенератор!

**Comment by nortikin** [comment]
framework4
framework3
framework2
framework1
framework

**Pull request merged**
