### PR TITLE
Obj sockets

### PR DESCRIPTION
**Pull request by Kosvor**

### CODE REVIEW

**Comment by ly29** [comment]
This needs some serious checking before merging but the sooner the better.
The changes to script node one should

**Comment by zeffii** [comment]
@ly29 Agreed, SN MK1 should be on lockdown completely except for superficial changes. My apologies for this KO, SN progres is to be made in MK2

**Comment by ly29** [comment]
Well that is my fault, I did it a long time ago.

**Comment by Kosvor** [comment]
can't delete second post
Cant do almost everything except updating files.

**Comment by zeffii** [comment]
KO, it might be an idea to make a branch/clone of master call it (KO-master) and try to merge the obj_sockets branch into that, that should give you some idea of how to resolve the conflicts - if you are interested.

**Comment by portnov** [comment]
it is usually better to use "git rebase --interactive origin/master" in such cases. You will have to resolve conflicts during rebase, but after it you will have "clean" branch which can be easily merged to master.

**Comment by Kosvor** [comment]
I think I'll just leave it all here until I find a way to restore full access to github

**Comment by ly29** [comment]
I Will try to find some time to do this...

**Pull request closed without merging**
