### PR TITLE
Bezier curve nodes

### PR DESCRIPTION
**Pull request by portnov**
This PR contains:

* Classes for Bezier curves - of arbitrary order, and a specialized class for most common cubic Bezier curves.
* "Bezier Spline" node, to generate a Bezier curve with several ways to define it - quadratic curve, cubic curve, generic curve of arbitrary order.
* "Tangents Curve" node, to generate a curve that passes through the specified points and has the specified tangent vectors at these points. The curve is generated with Bezier curves.
* "Blend Curves" node, to smoothly connect (blend) two or more curves - end of the first curve to the beginning of the second, and so on. Connections are made with Bezier curves too.

Screenshot_20200524_234248

Screenshot_20200525_011016

Screenshot_20200525_003017

Screenshot_20200524_195340

## Preflight checklist

Put an x letter in each brackets when you're done this item:

- [x] Code changes complete.
- [x] Code documentation complete.
- [x] Documentation for users complete (or not required, if user never sees these changes).
- [x] Manual testing done. 
- [x] Unit-tests implemented.
- [x] Ready for merge.

### CODE REVIEW

**Comment by portnov** [comment]
https://gist.github.com/f490e8c15fc6c1197bd07a39d767e301

Screenshot_20200525_013336

**Comment by portnov** [comment]
Well, I managed to do this simpler, but this list manipulation is still a lot of magic for me... :/

https://gist.github.com/d67c2a2a463b213c1782afdb5088e9c4

Screenshot_20200525_015742

**Comment by nortikin** [comment]
> Well, I managed to do this simpler, but this list manipulation is still a lot of magic for me... :/
> 
> https://gist.github.com/d67c2a2a463b213c1782afdb5088e9c4
> 
> Screenshot_20200525_015742

we need to fix zip and flip nodes. it is matrix calculations. can be made with numpy if orthodox lists.
problem of zip and flip (transpose) are - not working on some levels of data

**Comment by vicdoval** [comment]
@nortikin List flip already uses numpy if feeded with Numpy Arrays

**Comment by nortikin** [comment]
> @nortikin List flip already uses numpy if feeded with Numpy Arrays

but level of flip is sometimes wrong

**Pull request merged**
