### PR TITLE
Calculation of used sites for node "Voronoi on Mesh". 

### PR DESCRIPTION
**Pull request by satabol**
#4979 

Inspired by https://www.youtube.com/watch?v=Ip6JI6Qiiwg but more precise.

Some issue is in this video-tutorial - all emitted points has to be applied to source mesh. If no then result will have glitches.
Not all source sites converts to Voronoi cells. This Pull Request take capability to get only used sites:

image

Voronoi Tower 001
[Voronoi Tower.001.blend.zip](https://github.com/nortikin/sverchok/files/12332957/Voronoi.Tower.001.blend.zip)

**Is it sense to add Mask or Indices of used sites?**

### CODE REVIEW

**Comment by portnov** [comment]
1. I'd say it is more usual for Sverchok nodes to output masks, rather than subsets of vertices.
2. What if node already exists in the scene, but does not yet have this new output? maybe this is not a problem since the new version of the node was introduced very recently.

**Comment by satabol** [comment]
1. I'll do indices
2. Code to check new output socket exists in the "process" function. But I think a new version is better. )

**Comment by satabol** [comment]
@portnov this is new version of file for tests: [Voronoi Tower.003.blend.zip](https://github.com/nortikin/sverchok/files/12339718/Voronoi.Tower.003.blend.zip) (press play for animation)

image

**Comment by portnov** [comment]
Sites_idx should be a SvStringSocket then?

**Comment by satabol** [comment]
What do you think about property to switch type socket to a vector or an index for Site_idx? With rename socket to “Site” and show this additional property in “N-panel”.

**Comment by satabol** [comment]
Fix socket type to SvStringsSocket:
image

**Comment by portnov** [comment]
ok with me.

**Pull request merged**
