### PR TITLE
fix for bug in Texture viz

### PR DESCRIPTION
**Pull request by kalwalt**
It seems that the changes i made fix the bug, please test it and tell me your opinion.
Thanks,
Walter

### CODE REVIEW

**Comment by Kosvor2** [comment]
a bug? how to reproduce it?

**Comment by kalwalt** [comment]
@Kosvor2 was about weird glitch at the interface of Blender and sometimes the texture became black or change color, and flickering effect. did you ever experienced this?

**Comment by enzyme69** [comment]
@kalwalt I did experience it time to time. I have not touched the Texture Viewer yet so far, maybe I should use GIT PULL request. Will do soon.

**Comment by kalwalt** [comment]
>@kalwalt I did experience it time to time. I have not touched the Texture Viewer yet so far, maybe I should use GIT PULL request. Will do soon.

@enzyme69 git pull not needed this time, you can try it, it is in master now @zeffii merged it.

**Pull request merged**
