### PR TITLE
"Proportional edit falloff" node

### PR DESCRIPTION
**Pull request by portnov**
This node converts vertex selection mask into selection coefficients, with falloff modes similar to usual Blender's "proportional edit" mode. For vertices selected by mask coefficient will be 1.0; for vertices which are too far coefficient will be 0.0.

So usual usage is:
1. select something manually or by "Select mesh elements" node
2. Pass selection to "proportional edit" node
3. Pass coefficients to Move, or to Extrude, or whatever else.

Documentation is pending.

### CODE REVIEW

**Comment by portnov** [comment]
smooth
const
scale
extrude

**Comment by portnov** [comment]
cube-scale-proportional

**Comment by portnov** [comment]
Added the documentation. Please review.

**Comment by enzyme69** [comment]
@portnov Checking this node now. The documentation is offline only for now? Reading and studying it.

**Comment by enzyme69** [comment]
proportional_001

@portnov Is there any tips to prevent this red error halting the process?

**Comment by portnov** [comment]
@enzyme69 
About documentation: you can always find documentation in readable form near https://github.com/nortikin/sverchok/blob/master/docs/nodes/analyzers/proportional.rst (just click the link).

About error: could you please provide error message from console.

**Comment by nortikin** [comment]
will make docs asap. have no time enough

**Pull request merged**
