### PR TITLE
Recalc normals

### PR DESCRIPTION
**Pull request by ly29**
No really ready for merge perhaps but makes polygon adaptive better in certain scenarios and introduces the new ```bmesh_from_pydata``` interface #1152 

Please test.

### CODE REVIEW

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/recalc_normals/nodes/modifier_make/solidify.py#L39  can be removed :)

I was thinking **(but totally not planning to do it myself, or expecting you to)**  but there's a point to be made to also offer to mode of normal calculation for bmesh_from_pydata, in the same call.

```
   def bmesh_from_pydata(verts, edges, faces, normals='', mode=''):
       # where   mode options are 'fast' / 'correct'
```

**Comment by zeffii** [comment]
according to x https://twitter.com/raymondh/status/822296239156920321
```python
bmesh_from_pydata(verts=[], edges=[], faces=[], normals=""):
```
we should be writing

```python
    bmesh_from_pydata(verts=None, edges=None, faces=None, normals=""):
```

**Comment by ly29** [comment]
The same for normal or it is okay since string isn't mutable?

**Comment by zeffii** [comment]
yeah, that's ok i think.. but will dig around.

**Comment by zeffii** [comment]
i don't know about `normals=''` , the language some of these guys use to discuss what _is_ or what _is not_ allowed is a little presumptive regarding the scope of my vocabulary.

**Comment by zeffii** [comment]
but this kind of suggests we ought to avoid it too.  https://pythonconquerstheuniverse.wordpress.com/2012/02/15/mutable-default-arguments/

**Comment by ly29** [comment]
Ok, that is something that we do in many places actually.  Oops

**Comment by zeffii** [comment]
mutable types not ok, immutable types fine :)

**Comment by zeffii** [comment]
not allowing a string as default param would be a crippling python feature. : )

**Comment by ly29** [comment]
Not my favourite python feature... This can lead to so many bugs...

```python
>>> def f(d={}):
...     print(d)
...     d['a']=True
...     
>>> f()
{}

>>> f()
{'a': True}
```

**Comment by ly29** [comment]
Also I guess verts shouldn't have a default argument since it is needed...

**Pull request merged**
