### PR TITLE
Add a couple of examples.

### PR DESCRIPTION
**Pull request by portnov**
Technical PR to run Travis on it.

### CODE REVIEW

**Comment by portnov** [comment]
Wtf. What does it need with Donut example...

**Comment by zeffii** [comment]
looks like the .blend being used to try all these .jsons , isn't being object wiped between imports.
so if there was a Curve Viewer node or something creating an object called Alpha, and then next json import is a BMeshViewer ,creating a mesh object also called Alpha..   I think this might happen

**Comment by zeffii** [comment]
we can add something in sv_obj_helper to 
 - tell the user that the node is picking up some other node's data

if this is the problem i'll think about it for a bit.

**Comment by zeffii** [comment]
i think we should also add a "whipe object and bpy.data.mesh/curve/... prior to eacc json import tests

**Comment by zeffii** [comment]
something like this:
```python
def blend_cleanup_remove_obj_and_data(context):

    collection = bpy.context.scene.collection
    objects = bpy.data.objects
    
    meshes = bpy.data.meshes
    curves = bpy.data.curves
    metas = bpy.data.metaballs

    # first remove all the objects
    for obj in objects:
        collection.objects.unlink(obj)
        objects.remove(obj)

    # then remove their data
    for data_kind in [meshes, curves, metas]:
        for data in data_kind:
            data_kind.remove(data)
```

**Comment by enzyme69** [comment]
🤟One suggestion: with EXAMPLES from Help can we make it as zipped blend with node tree or JSON?

**Comment by zeffii** [comment]
relevant. https://blender.stackexchange.com/questions/46990/how-to-completely-remove-all-loaded-data-from-blender?noredirect=1&lq=1

**Comment by zeffii** [comment]
i renamed the `basedata_name` to `RV_Alpha` , but there's a few nodes with `SvEx+` bl_idnames.

**Pull request merged**
